### ISSUE TITLE
Buff Farming

### ISSUE THREAD

**Issue by djonmla** [PiweeX/HogRealms#10]
Pecanje je isplatljivije od skupljanja pšenice.
Predlažem da se cena pšenice poveća jer je za nju potrebno uložiti sate kako bi napravili farmu, potrebni su traktori i gorivo za traktore.
Dok je za pecanje potreban samo štap

**Comment by buducidzelat** [comment]
> Pecanje je isplatljivije od skupljanja pšenice. Predlažem da se cena pšenice poveća jer je za nju potrebno uložiti sate kako bi napravili farmu, potrebni su traktori i gorivo za traktore. Dok je za pecanje potreban samo štap

ali rp zanimljivije je kad vise ulazes u njega

**Comment by akipaki293** [comment]
Bilo bi dobro povecati prodaju wheata bar na 50$

**Comment by PiweeX** [comment]
Slažem se da u RP treba uložiti više truda, dakle ne može sve odma već kroz neko vreme. Pogotovo to što se mapa ne resetuje, mora da bude zanimljivo uvek i da se ceni to što se ostvari inače igrači neće igrati, to je bar dosadašnje iskustvo sa serverima iz predhodnih godina od 2017.

što se tiče prodajne cene pšenice, videćemo šta ostali igrači budu rekli ali svakako uskoro će moći da se prodaju i drva i doćiće možda još neki načini za zaradu koji bi poboljšali RP

što se tiče pecanja, kad je tek ubačeno da se ribe mogu prodavati pre par meseci cena je bila mnogo veća od ove, sad je dosta nerfovano i sad je ok, možda se još bude smanjila kad dođu još neki načini zarade, po meni pecanje je najzanimljivije i dosta utiče na aktivnost četa

**Comment by djonmla** [comment]
Da ali ako je pecanje najisplatljivije onda ubija poentu ovoga da treba uložiti više truda za pare,
Najbolje je pojačati pšenicu ili smanjiti pecanje
Isto bi bilo dobro da se baš pojača pšenica, a da traktor može da se puni samo ugljem što bi odma podiglo i ekonomiju rudarenja

**Comment by akipaki293** [comment]
Sto se tiče toga po meni trebalo bi ostati sve kao što i jeste samo izbaciti semena za gorivo, jeste da je to kao bio masa ali idalje...

**Comment by djonmla** [comment]
Izbaciti sve kao gorivo osim uglja i pojačati pšenicu

**Comment by dzelat** [comment]
> Izbaciti sve kao gorivo osim uglja i pojačati pšenicu

**ni slučajno**

**Comment by djonmla** [comment]
> > Izbaciti sve kao gorivo osim uglja i pojačati pšenicu
> 
> **ni slučajno**

Zašto?

**Comment by dimitrije231** [comment]
Predlažem za poboljšanje ribolova(veće šanse za legy ili epic) i veća cena pšenice(45) i ribe za 24$

**Comment by PiweeX** [comment]
> ![image](https://user-images.githubusercontent.com/107082292/172711364-7fab1d35-7483-4e23-b232-0b1be536108e.png)
> 
> Nepovezano ali ovo da se izbaci, prvo ne vidi se scoreboard i ova žuta boja iritira. Isti problem kada je hladno

ovo je odlična stvar, samo da ne traje predugo

**Comment by PiweeX** [comment]
Cena pecanja će se od sutra od 7h promeniti i verovatno skroz smanjiti, trebaće neko vreme dok se balansira

**Comment by Darislaw** [comment]
Evo ovk za sad sta je najbolje: 
20 pšenice za 45$ (umesto sadasnjih 18 za 38$) 
Pecanje da se ne promeni 
Traktor da moze da se puni samo sa ugalj i drveni ugalj na primer 1 ugalj da daje 1% meni je to fer i perfekt, znaci 64 uglja odnosno 64 coal za 64% 
Ko se slaze za ovaj predlog?

**Comment by Darislaw** [comment]
> Evo ovk za sad sta je najbolje: 20 pšenice za 45(umestosadasnjih18za38) Pecanje da se ne promeni Traktor da moze da se puni samo sa ugalj i drveni ugalj na primer 1 ugalj da daje 1% meni je to fer i perfekt, znaci 64 uglja odnosno 64 coal za 64% Ko se slaze za ovaj predlog?

U zagradi sam napisao: umesto sadasnjih 18 za 38$

**Comment by Darislaw** [comment]
Ja sam od pocetka razgledao situaciju kako i sta funkcionise i planiram da otvorim nov issue za neki dan gde cu sva svoja misljenja da izjasnim i gde bi trebalo najveca debata da se vodi sto se tice RP ekonomije i kretanju ka boljeg balansa igre. Do tad pozdrav

**Comment by HyperTwo29394** [comment]
Najbolje je povećati cijenu pšenice na 45$-43$ jer 50$ je već malo previše.što se mene tiče,nebi volio da samo ugalj bude način za punjenje rezervoara taktora ili bilo koje mašine jer realno onda bi baš potražnja uglja porasla.I ovo što Piweeex i pojedini ljudi kažu da je pecanje zanivljivo,ja stvarno ne znam šta da kažem na to...bukvalno mi je zanivljivije da se vozam traktorom po njivi,nego stojati u mjestu i pecati,a i kad pecaš,sve se bazira na sreću a kad žanješ pšenicu,tu barem znaš da te čeka dobra plata

**Comment by djonmla** [comment]
> Najbolje je povećati cijenu pšenice na 45−43 jer 50$ je već malo previše.što se mene tiče,nebi volio da samo ugalj bude način za punjenje rezervoara taktora ili bilo koje mašine jer realno onda bi baš potražnja uglja porasla.I ovo što Piweeex i pojedini ljudi kažu da je pecanje zanivljivo,ja stvarno ne znam šta da kažem na to...bukvalno mi je zanivljivije da se vozam traktorom po njivi,nego stojati u mjestu i pecati,a i kad pecaš,sve se bazira na sreću a kad žanješ pšenicu,tu barem znaš da te čeka dobra plata

Ni jedna ruda na serveru nema korist, moraju se malo ubaciti u ugru...
Naravno da kažu da je pecanje "zanimljivije" kad su platili plugin, ali platili su i traktore tako da ne razumem zašto im je pecanje toliko vaznije

**Comment by PiweeX** [comment]
Upravo reseno :)

**Comment by PiweeX** [comment]
(pecanje je nerfovano odavno ali upravo je resen drugi slican issue predlog da se traktori mogu puniti samo coalom i charcoalom)
