### ISSUE TITLE
mobovi

### ISSUE THREAD

**Issue by PsihoKing** [PiweeX/HogRealms#100]
Mobovi se jako retko spawnuju na SMP pa ako moze da se poveca

**Comment by Lenna672** [comment]
> Mobovi se jako retko spawnuju na SMP pa ako moze da se poveca 

Na kojoj planeti je tako psiho

**Comment by bogoljub1234** [comment]
Sta kazete da dodate zebre, lavove i slona?

**Comment by bogoljub1234** [comment]
U, pitanje oce lagat ak ce biti custom mobova
Sta kazes?

**Comment by DzingisKan** [comment]
> U, pitanje oce lagat ak ce biti custom mobova Sta kazes?
Bit ce ih koliko i onih vodenih naga. Znaci jako retke

**Comment by PiweeX** [comment]
rešeno u novoj sezoni SMPa za 2023. gde je PSIHO vlasnik
