### ISSUE TITLE
Eternity Life

### ISSUE THREAD

**Issue by PiweeX** [PiweeX/HogRealms#101]

**Comment by ConeBe** [comment]
Močvara 👍🏼

**Comment by buducidzelat** [comment]
microsft edge 💀

**Comment by PiweeX** [comment]
![download](https://user-images.githubusercontent.com/33425430/176543178-02a1a8ce-79c0-47c6-8230-878c44d0be19.png)

izgradnja ostrva započeta

**Comment by PiweeX** [comment]
![download](https://user-images.githubusercontent.com/33425430/176543797-1ea1ff80-c462-457b-bb39-4826424f0865.png)

**Comment by PiweeX** [comment]
![download](https://user-images.githubusercontent.com/33425430/176544440-87f26a2f-6a2f-4a0c-bf5c-494e7128ce3c.png)

**Comment by PiweeX** [comment]
iz visa 

https://prnt.sc/xcz7sGBA1vay

**Comment by PiweeX** [comment]
![download](https://user-images.githubusercontent.com/33425430/176546466-e6551e4b-d135-494d-92bd-ed4acd7b4a27.png)

**Comment by IvanBela** [comment]
Brate spawn ce da puca a server jos vise 🔥🔥🔥🔥💪💪💪

**Comment by PiweeX** [comment]
![download](https://user-images.githubusercontent.com/33425430/176550738-6254d327-59a4-4cf0-9b71-b5ffd7040625.png)

**Comment by PiweeX** [comment]
spawn će možda biti na foru piratskog, modern i zgrade ne idu uz to jer je ipak ostrvo, više ide neki mediveal uz priču tako da je pirate odlična opcija

**Comment by PiweeX** [comment]
![Uploading 2022-06-30_00.00.00.png…]()
![Uploading 2022-06-30_00.00.00.png…]()
![Uploading 2022-06-30_00.00.00.png…]()
![Uploading 2022-06-30_00.00.00.png…]()

**Comment by PiweeX** [comment]
![Uploading 2022-06-30_00.00.00.png…]()

**Comment by PiweeX** [comment]
![Uploading 2022-06-30_00.05.30.png…]()

**Comment by Featherica** [comment]
![2022-06-30_01 35 46](https://user-images.githubusercontent.com/71612070/176563272-c414e748-491b-4b83-8f89-0a0b9bd831f7.png)
![2022-06-30_01 17 21](https://user-images.githubusercontent.com/71612070/176563275-c3ec6ef6-ad29-46c9-9a60-493f1bef006f.png)
![2022-06-30_01 32 24](https://user-images.githubusercontent.com/71612070/176563279-4b965d65-cfac-46f5-8840-966813f10286.png)
![2022-06-30_01 32 28](https://user-images.githubusercontent.com/71612070/176563285-a84258bc-509c-4a8c-ad6d-fd1ea9c6c965.png)

**Comment by Featherica** [comment]
> ![2022-06-30_01 35 46](https://user-images.githubusercontent.com/71612070/176563272-c414e748-491b-4b83-8f89-0a0b9bd831f7.png) ![2022-06-30_01 17 21](https://user-images.githubusercontent.com/71612070/176563275-c3ec6ef6-ad29-46c9-9a60-493f1bef006f.png) ![2022-06-30_01 32 24](https://user-images.githubusercontent.com/71612070/176563279-4b965d65-cfac-46f5-8840-966813f10286.png) ![2022-06-30_01 32 28](https://user-images.githubusercontent.com/71612070/176563285-a84258bc-509c-4a8c-ad6d-fd1ea9c6c965.png)

Oblik Jail-a.

**Comment by Featherica** [comment]
Oblik Jaila.

**Comment by Featherica** [comment]
![2022-06-30_02 08 30](https://user-images.githubusercontent.com/71612070/176566016-7297f981-aee1-4bc2-9560-7dd9d546ad44.png)

**Comment by Featherica** [comment]
![2022-06-30_02 36 16](https://user-images.githubusercontent.com/71612070/176568354-e6fbbf3d-a42a-48ca-b01f-896ee850c91c.png)
![2022-06-30_02 35 43](https://user-images.githubusercontent.com/71612070/176568362-f0fc5e93-8c07-4697-9940-cc1a749eefc5.png)
![2022-06-30_02 36 10](https://user-images.githubusercontent.com/71612070/176568366-68f37510-0721-4939-9018-cf0dd6508262.png)

Jednostavno sam morao jednom slikati sa šejderima.

**Comment by Featherica** [comment]
![2022-07-02_17 27 49](https://user-images.githubusercontent.com/71612070/177006995-e63ab5bb-40d5-4ab3-a939-92e927018e1d.png)
![2022-07-02_17 27 54](https://user-images.githubusercontent.com/71612070/177006999-1c866a67-79c0-4b65-91cf-9cdc58773d58.png)
![2022-07-02_17 27 58](https://user-images.githubusercontent.com/71612070/177007004-54c6cf77-13ab-4795-b817-bc423248cd2a.png)
![2022-07-02_17 28 03](https://user-images.githubusercontent.com/71612070/177007005-61f9ffa0-ab05-4c1b-9d81-9f9b1447441f.png)
![2022-07-02_17 28 11](https://user-images.githubusercontent.com/71612070/177007008-b21a34af-064c-45be-8657-2880a3a8f2b6.png)
![2022-07-02_17 28 23](https://user-images.githubusercontent.com/71612070/177007012-480d58af-48df-4636-a250-3aa6d94f4de6.png)
![2022-07-02_17 28 30](https://user-images.githubusercontent.com/71612070/177007015-143f3584-defe-48f8-8779-67e9dfaf363b.png)

Ceo spawn još wild ostao.

**Comment by PiweeX** [comment]
![download](https://user-images.githubusercontent.com/33425430/177016087-578567e2-2242-4035-9e64-9a5aac38ff42.png)

jako je ispalo

**Comment by VukIcrnogorskii** [comment]
Pixili pixili, da neces vidjet 🗞 na hog

**Comment by PiweeX** [comment]
gledam, sto?

**Comment by VukIcrnogorskii** [comment]
Nista nista, samo radi svoj posao

**Comment by VukIcrnogorskii** [comment]
> gledam, sto?

Juce si mutova sve koji napisu *glup si* frazu

**Comment by PiweeX** [comment]
Ja radim tehničku stranu, dželati su ti koji kazne, ako treba ja kaznim isto pošto oni nisu imali dozvole na discordu juče.

Što se tiče toga da li je neko nepravedno kažnjen, nek otvori tiket i može da zatraži obrazloženje, ukoliko ga ne dobije dobiće novčanu nadoknadu od 50k i javno izvinjenje u ime svih nas od strane mene
