### ISSUE TITLE
Problemi s teritorijom. (Mapa, politicka karta...)

### ISSUE THREAD

**Issue by DzingisKan** [PiweeX/HogRealms#102]
Kao sto svi znate postoji vise problema s politickom mapom i s teritorijama opcenito. Prije nego sta udjem u samu tematiku ovog odmah cu otvoreno i direktno da kazem posto nisam politicar da lazem, a ako jesam ocu da buden onaj pravedni. Ovu temu sam zapoceo prvobitno zbog vlastitih problema u drzavi, tako da nije tajna da u SMP smisljaju zakon na moj predlog jer meni prete neki problemi po pitanju teritorije. Medjutim u nastavku teksta vidit cete kako i druge drzave pate od istih problema. i moji i vasi predlozi nek budu u korist onog sto je pravedno i u korist celog servera, vise nego licne koristi.

1. Problem vlasnistva drzave.
1.1. U vreme politicke karte bilo je poznato kako ono sta je ucrtano pripadalo jednom vodji te svi claimovi koji su bili napravljeni pripadaju tom vodji.
1.1.1. Nakon ukidanja politicke karte i uvodjena PiweeeXovog sistema claim = vlasnik , u serveru je nastalo preko 30 slucajeva pobuna u drzavama od kojih su 2 u Mongoliji, 5 u Japanu i 2 u Koreji i ostatak u ostalim zemljama
1.1.2. Po PiweeeXovom sistemu netko je mogao otici svega jedan claim koji je izvan zida Britanije i tu napraviti claim i reci da je to njegovo
1.1.3. Po PiweeeXovom sistemu netko je mogao otici i claimati dio zida koji je Britanija napravila ali nije claimala i opet bi dobio slucaj i zakljucilo bi se da to pripada njemu
1.1.4. Po PiweeeXovom sistemu teritorija kao sto su Bardonija, Mongolija i Africka Republika koje su ogromne ali od pocetka iste i aktivno djeluju (Iznimke one koje su u medjuvremenu propale ili smanjile aktivnost) koje imaju preko 200 000 chunkova velicine trebaju claimat svu tu teritoriju
1.1.4.a. Posotji limit na chunkove sta ogranicava te zemlje da to urade
1.1.4.b Jos nije uvedena Nations komanda u kojoj cemo pricati kasnije u tekstu te ti landovi imaju jedan claim sta stvara problem za gradove 

MOJ PREDLOG (ovo je prvi predlog koji je predstavljen SMPu i na njega ce glasati, napisite ispod svoje predloge i za njih ce se jednako glasati)
1.1.4.b. - do dolaska nations komande mora se uvesti politicka karta koja ce prikazati sve moralne granice i claimane granice drzave ali ta karta nece se koristit za claimanje drzave
1.1.4.b, 1.1.4.a - drzave koje od pocetka svog postojanja vrse aktivnost na nekoj teritoriji moraju imati pravo da na politickim kartama imaju ucrtano tu teritoriju (Primjer Pustinje Gobi do Himalaje u Mongoliji) 
1.1.3., 1.1.2. Politicka karta koju ce raditi MBS zabraniti ce scenarije opisane pod 1.1.3.  i 1.1.2. jer to i zadnje dve mozdane celije mogu da zakljuce da je pravedno
1.1.1. Sve sta je na politickoj karti pripada jednom vodji ili jasno pre toga ima odredeno kome pripada zasebni dio teritorije, dakle claim nije drzava i ne znaci da pripada tom igracu vec drzavi
1.1.1. Ako je netko sagradio ceo grad u ime svoje drzave taj teritorij nakon odlaska tog igraca iz drzave ostaje toj drzavi
1.1.1. Ako je netko sagradio ceo grad ali od pocetka te gradnje trazi nezavisnost vlasti te da taj grad ne bude dio roleplaya i te drzave (Primjer Brumilde i Zlatne Horde) ta osoba ima pravo sazvati sud na kojem ce se odrediti prema ovom zakonu kako ima pravo na feudalni posjed (pogledaj ispod) 

1.1. Za sve probleme oko vlasnistva teritorije i svih problema navedenih u tekstu, POSTOJE SUDSKI PROCESI U UNu KOJI EFEKTIVNO RIJESAVAJU OVE PROBLEME, uvek mozete da se javite i resit ce se

FEUDALNI POSED - Feudalni posed poznat je pojam u Realmsu iz vremena politcke karte, to je teritorija koja nije ucrtana u politicku kartu, moze biti ucrtana kao deo politicke karte bilo koje drzave, ali ono sta je pod njenim claimom ima potpunu kontrolu vlasnika claima

Napisite ispod predloge za ovu problematiku. Osobno cu prepisati sve probleme direktno u kanal DAO da  brze vide predloge i brze presude

**Comment by akipaki293** [comment]
Ima neograničeno chunkova za claim...

**Comment by akipaki293** [comment]
Da se vrati politicka mapa je ok, ali pošto ima mnogo novih ljudi koji ne vide politicku mapu oni će claimati negde i posle će nastati problem, kao što je bio problem sa UKA.

**Comment by DzingisKan** [comment]
> Da se vrati politicka mapa je ok, ali pošto ima mnogo novih ljudi koji ne vide politicku mapu oni će claimati negde i posle će nastati problem, kao što je bio problem sa UKA.

bilo je takvih problema i pre, to smo resavali sudskim procesima ili jednostavniim dogovorima. I takvi slucajevi bili su poznati i u drugim serverima

**Comment by akipaki293** [comment]
> 

Staćeš, ja sam novinar ja moram imati :)

**Comment by DzingisKan** [comment]
Upravo se odvija sud i predlozi su prihvaceni. S obzirom da sastnak i dalje traje sad napisite predloge i instant ce se glasat

**Comment by akipaki293** [comment]
I Sa Obzirom da sam se ja popravio u rađenu mapa po meni ja bih voleo raditi je

**Comment by Lenna672** [comment]
sto bi moj dragi prijatelj rekao . NEMAS ARGUMENTE

**Comment by akipaki293** [comment]
> sto bi moj dragi prijatelj rekao . NEMAS ARGUMENTE

Ako se usvoji politička i moj predlog gore pravim vam kanale na MBS za to

**Comment by DzingisKan** [comment]
> Ako se vrati politička, da DAO i par dobrih ljudi glasa koja će teritorija ići, a koja ne, i ako ta nova teritorija zauzima deo neke koja je već na karti da dobije samo ono što nije zauzeto ili da pošalje slike sa pregovorima i dogovorima

Predlog prihvacem. DAO i Dzelati ce pregledavat aktivnost na teritoriji, i gledat ce da se ne uzme teritoija koja ne pripada toj drzavi i da nije uzeta teritorija na kojoj se kasnije nista nije radilo

**Comment by akipaki293** [comment]
> > Ako se vrati politička, da DAO i par dobrih ljudi glasa koja će teritorija ići, a koja ne, i ako ta nova teritorija zauzima deo neke koja je već na karti da dobije samo ono što nije zauzeto ili da pošalje slike sa pregovorima i dogovorima
> 
> Predlog prihvacem. DAO i Dzelati ce pregledavat aktivnost na teritoriji, i gledat ce da se ne uzme teritoija koja ne pripada toj drzavi i da nije uzeta teritorija na kojoj se kasnije nista nije radilo

Je l će je Aki raditi?

**Comment by Lenna672** [comment]
> > sto bi moj dragi prijatelj rekao . NEMAS ARGUMENTE
> 
> Ako se usvoji politička i moj predlog gore pravim vam kanale na MBS za to

zapratite me na instagramu uwu

**Comment by dzelat** [comment]
Upravo smo se dogovrili mi u Juznoj Americi da napravimo vlastitu kartu koju cemo postovati medjusobno, dok se ne viid sta cemo sa kartom svijeta

**Comment by DzingisKan** [comment]
> > > Ako se vrati politička, da DAO i par dobrih ljudi glasa koja će teritorija ići, a koja ne, i ako ta nova teritorija zauzima deo neke koja je već na karti da dobije samo ono što nije zauzeto ili da pošalje slike sa pregovorima i dogovorima
> > 
> > 
> > Predlog prihvacem. DAO i Dzelati ce pregledavat aktivnost na teritoriji, i gledat ce da se ne uzme teritoija koja ne pripada toj drzavi i da nije uzeta teritorija na kojoj se kasnije nista nije radilo
> 
> Je l će je Aki raditi?

MBS radi kartu uz pomoc naroda i dzelata

**Comment by akipaki293** [comment]
> > > > Ako se vrati politička, da DAO i par dobrih ljudi glasa koja će teritorija ići, a koja ne, i ako ta nova teritorija zauzima deo neke koja je već na karti da dobije samo ono što nije zauzeto ili da pošalje slike sa pregovorima i dogovorima
> > > 
> > > 
> > > Predlog prihvacem. DAO i Dzelati ce pregledavat aktivnost na teritoriji, i gledat ce da se ne uzme teritoija koja ne pripada toj drzavi i da nije uzeta teritorija na kojoj se kasnije nista nije radilo
> > 
> > 
> > Je l će je Aki raditi?
> 
> MBS radi kartu uz pomoc naroda i dzelata

Ok

**Comment by Lenna672** [comment]
> > > > sto bi moj dragi prijatelj rekao . NEMAS ARGUMENTE
> > > 
> > > 
> > > Ako se usvoji politička i moj predlog gore pravim vam kanale na MBS za to
> > 
> > 
> > zapratite me na instagramu uwu
> 
> Kako se zoves prijateljice

@helenakojicc

**Comment by DzingisKan** [comment]
> Upravo smo se dogovrili mi u Juznoj Americi da napravimo vlastitu kartu koju cemo postovati medjusobno, dok se ne viid sta cemo sa kartom svijeta

1.1.1. pogledaj, setio sam se i te situacije.

**Comment by dzelat** [comment]
> > > > Ako se vrati politička, da DAO i par dobrih ljudi glasa koja će teritorija ići, a koja ne, i ako ta nova teritorija zauzima deo neke koja je već na karti da dobije samo ono što nije zauzeto ili da pošalje slike sa pregovorima i dogovorima
> > > 
> > > 
> > > Predlog prihvacem. DAO i Dzelati ce pregledavat aktivnost na teritoriji, i gledat ce da se ne uzme teritoija koja ne pripada toj drzavi i da nije uzeta teritorija na kojoj se kasnije nista nije radilo
> > 
> > 
> > Je l će je Aki raditi?
> 
> MBS radi kartu uz pomoc naroda i dzelata

Fropik pravi odlicnu kartu sto bi to radio MBS lol

**Comment by dzelat** [comment]
Cuo sam ko ce da radi kartu, bojim se

**Comment by NemanjaRusija** [comment]
> Kao sto svi znate postoji vise problema s politickom mapom i s teritorijama opcenito. Prije nego sta udjem u samu tematiku ovog odmah cu otvoreno i direktno da kazem posto nisam politicar da lazem, a ako jesam ocu da buden onaj pravedni. Ovu temu sam zapoceo prvobitno zbog vlastitih problema u drzavi, tako da nije tajna da u SMP smisljaju zakon na moj predlog jer meni prete neki problemi po pitanju teritorije. Medjutim u nastavku teksta vidit cete kako i druge drzave pate od istih problema. i moji i vasi predlozi nek budu u korist onog sto je pravedno i u korist celog servera, vise nego licne koristi.
> 
> 1. Problem vlasnistva drzave.
>    1.1. U vreme politicke karte bilo je poznato kako ono sta je ucrtano pripadalo jednom vodji te svi claimovi koji su bili napravljeni pripadaju tom vodji.
>    1.1.1. Nakon ukidanja politicke karte i uvodjena PiweeeXovog sistema claim = vlasnik , u serveru je nastalo preko 30 slucajeva pobuna u drzavama od kojih su 2 u Mongoliji, 5 u Japanu i 2 u Koreji i ostatak u ostalim zemljama
>    1.1.2. Po PiweeeXovom sistemu netko je mogao otici svega jedan claim koji je izvan zida Britanije i tu napraviti claim i reci da je to njegovo
>    1.1.3. Po PiweeeXovom sistemu netko je mogao otici i claimati dio zida koji je Britanija napravila ali nije claimala i opet bi dobio slucaj i zakljucilo bi se da to pripada njemu
>    1.1.4. Po PiweeeXovom sistemu teritorija kao sto su Bardonija, Mongolija i Africka Republika koje su ogromne ali od pocetka iste i aktivno djeluju (Iznimke one koje su u medjuvremenu propale ili smanjile aktivnost) koje imaju preko 200 000 chunkova velicine trebaju claimat svu tu teritoriju
>    1.1.4.a. Posotji limit na chunkove sta ogranicava te zemlje da to urade
>    1.1.4.b Jos nije uvedena Nations komanda u kojoj cemo pricati kasnije u tekstu te ti landovi imaju jedan claim sta stvara problem za gradove
> 
> MOJ PREDLOG (ovo je prvi predlog koji je predstavljen SMPu i na njega ce glasati, napisite ispod svoje predloge i za njih ce se jednako glasati) 1.1.4.b. - do dolaska nations komande mora se uvesti politicka karta koja ce prikazati sve moralne granice i claimane granice drzave ali ta karta nece se koristit za claimanje drzave 1.1.4.b, 1.1.4.a - drzave koje od pocetka svog postojanja vrse aktivnost na nekoj teritoriji moraju imati pravo da na politickim kartama imaju ucrtano tu teritoriju (Primjer Pustinje Gobi do Himalaje u Mongoliji) 1.1.3., 1.1.2. Politicka karta koju ce raditi MBS zabraniti ce scenarije opisane pod 1.1.3. i 1.1.2. jer to i zadnje dve mozdane celije mogu da zakljuce da je pravedno 1.1.1. Sve sta je na politickoj karti pripada jednom vodji ili jasno pre toga ima odredeno kome pripada zasebni dio teritorije, dakle claim nije drzava i ne znaci da pripada tom igracu vec drzavi 1.1.1. Ako je netko sagradio ceo grad u ime svoje drzave taj teritorij nakon odlaska tog igraca iz drzave ostaje toj drzavi 1.1.1. Ako je netko sagradio ceo grad ali od pocetka te gradnje trazi nezavisnost vlasti te da taj grad ne bude dio roleplaya i te drzave (Primjer Brumilde i Zlatne Horde) ta osoba ima pravo sazvati sud na kojem ce se odrediti prema ovom zakonu kako ima pravo na feudalni posjed (pogledaj ispod)
> 
> 1.1. Za sve probleme oko vlasnistva teritorije i svih problema navedenih u tekstu, POSTOJE SUDSKI PROCESI U UNu KOJI EFEKTIVNO RIJESAVAJU OVE PROBLEME, uvek mozete da se javite i resit ce se
> 
> FEUDALNI POSED - Feudalni posed poznat je pojam u Realmsu iz vremena politcke karte, to je teritorija koja nije ucrtana u politicku kartu, moze biti ucrtana kao deo politicke karte bilo koje drzave, ali ono sta je pod njenim claimom ima potpunu kontrolu vlasnika claima
> 
> Napisite ispod predloge za ovu problematiku. Osobno cu prepisati sve probleme direktno u kanal DAO da brze vide predloge i brze presude

Ja mislim da imaš ti veliku slobodu govora

**Comment by akipaki293** [comment]
> Cuo sam ko ce da radi kartu, bojim se

Hahahaha
