### ISSUE TITLE
Ko ovdje koga jebe?

### ISSUE THREAD

**Issue by dzelat** [PiweeX/HogRealms#103]
Znači od kako sam staff tj 4 mjeseca uvijek je bilo jedino pravilo nema perma bana, sada kada sam uradio ono što je zajednica htjela dobio sam ban zauvijek. Pa eto ako može komentar...

**Comment by buducidzelat** [comment]
UPRAVA NAPOLJE ZLAJA DA PUSI KURACC

**Comment by DzingisKan** [comment]
svaka vam cast, pokazali ste da ste vi trebali bit ti koji vodite server. Imate pravi stav i prave kvalifikacije.

**Comment by dzelat** [comment]
> svaka vam cast, pokazali ste da ste vi trebali bit ti koji vodite server. Imate pravi stav i prave kvalifikacije.

Od tebe sigurno komentar trazio nisam

**Comment by buducidzelat** [comment]
> svaka vam cast, pokazali ste da ste vi trebali bit ti koji vodite server. Imate pravi stav i prave kvalifikacije.

KO TI jebe mater

**Comment by konfix** [comment]
https://user-images.githubusercontent.com/66477781/176796316-69063677-9497-4ff0-9884-b67043a69af4.mp4

**Comment by dzelat** [comment]
> nemojte.mp4

hahahahaha

**Comment by Coplek** [comment]
> svaka vam cast, pokazali ste da ste vi trebali bit ti koji vodite server. Imate pravi stav i prave kvalifikacije.

zlajo kako se glasa u dao? Zasto glasas protiv?,  Cijeli smp ce glasat za, pa? zasto da se banuje coplek zasto sto si ga vrijedjo

**Comment by NemanjaRusija** [comment]
> svaka vam cast, pokazali ste da ste vi trebali bit ti koji vodite server. Imate pravi stav i prave kvalifikacije.

Tvoj odgovor mi ne znači ništa

**Comment by NemanjaRusija** [comment]
Ovaj DAO sistem je glup a čovek koji ga vodi je još gluplji

**Comment by Cetnik1918** [comment]
Ajmo svi koji nisu banovani na ulice hoga kao sto je bilo kod nas 2003. ZLAJA NAPOLJE ZLAJA NAPOLJE

**Comment by buducidzelat** [comment]
UPRAVA NAPOLJEEE ZLAJOO PEDERU

**Comment by buducidzelat** [comment]
https://imgur.com/Mg4N484

**Comment by PiweeX** [comment]
izjasnio sam se o svemu na dozahoga instagramu, pogledajte sve storije, ko ima oči nek vidi

drugo ne može govoriti neko o petom oktobru ko nije ni bio u planu tad, molim vas lečite se

**Comment by buducidzelat** [comment]
> izjasnio sam se o svemu na dozahoga instagramu, pogledajte sve storije, ko ima oči nek vidi
> 
> drugo ne može govoriti neko o petom oktobru ko nije ni bio u planu tad, molim vas lečite se

UPRAVA NAPOLJEEE

**Comment by buducidzelat** [comment]
> > htio bih pitat šta je ovo pre svega. PX evo ovde ću, za taj vaš jučerašnji problem sa onom rečenicom o Zlaji, ja i nemam pojma da se dogodilo dok nijesam video slike. Tad sam čak šta više i zaspao xd. No vidim da sam banovan zbog "izvršena kazne od sinoć" verovatno se mislim na to sa Zlajom tako da, eto mogu u samoodbranu reći da to nisam rekao, ako postoji drugi razlog mjuta, htio bi skrinšot, da se uverim. Doviđenja prijatno
> 
> Zlaja piše mutove svima

![Screenshot_74](https://user-images.githubusercontent.com/107114906/176945016-847885d0-87bc-4b30-8a9c-a58376e4756d.png)
lagano cemo sa zlajom

**Comment by VukIcrnogorskii** [comment]
Mozda mogu na dc da nas mutuju, al na git hub nikad URAAA! XD

**Comment by NemanjaRusija** [comment]
> 

Nemoj ti nas engleze da diraš
