### ISSUE TITLE
Ujedinjene nacije

### ISSUE THREAD

**Issue by spahomir** [PiweeX/HogRealms#104]
Vidio sam da je pola HogRealmsa banovano sa UNa, e sad kako mi da čitamo zakone i kazne. Mislim da bi svi trebali imati pristup supportu u svakom momentu

**Comment by DzelatDjovani** [comment]
Svi su unbanovani

**Comment by PiweeX** [comment]
Primetio sam ovaj propust i odmah unbanovao sve iako ih nije bilo puno

obrisan je i kanal #ban gde su pisali banovi

da u svakom momentu svako može da piše na UN i da otvara tikete, na UN jedina kazna što može da postoji je timeout ili mute, ban nebi smeo zbog otvaranja tiketa i sličnog
