### ISSUE TITLE
Ulazenje i pravljenje landova

### ISSUE THREAD

**Issue by akipaki293** [PiweeX/HogRealms#105]
Kao sto svi znaju, od prebacivanja na novu mašinu desio se bug da novi igrači mogu ući u samo 1 land, što pravi mnoge probleme. Novi igrači sve više dolaze, a ako ne mogu ulaziti u više landova tolko brzo će i otići. Predlazem da prioritet rešavanja tehničkih problema budu landovi. I moli se px da svaku novu urađenu stvar objavi ovde

**Comment by DzingisKan** [comment]
Pravi primjer GitHuba kakvog zajednica trazi

**Comment by vukstrale** [comment]
Slažem se Aki

**Comment by PiweeX** [comment]
ovo će biti rešeno u najkraćem mogućem roku, diskutovali smo o tome i nadam se da ću uskoro uspeti da rešim

**Comment by PiweeX** [comment]
reseno!
