### ISSUE TITLE
Dungeons

### ISSUE THREAD

**Issue by PiweeX** [PiweeX/HogRealms#109]

**Comment by R1derPN** [comment]
ako je to moguce u vezi dungeons bi reseto bi podzemni dio chankova, stavio mobove i dodo bi custom dungeone i bosove .Dal su to custom ili sa modova.

**Comment by PiweeX** [comment]
> ako je to moguce u vezi dungeons bi reseto bi podzemni dio chankova, stavio mobove i dodo bi custom dungeone i bosove .Dal su to custom ili sa modova.

ovo je za drugi projekat, u sklopu firme, a to za custom bosseve ispod zemlje to će itekako biti ali na podzemni svet se treba fokusirati tek na kraju pošto ipak nemamo mobove na vrhu sem nage

**Comment by PiweeX** [comment]
the world will be created when the server 2 is enabled (should be during the day)

build won't be in a flat world

**Comment by PiweeX** [comment]
![seed](https://user-images.githubusercontent.com/33425430/177332431-6b91d86b-b48d-4bd0-920e-953cb1ed62eb.png)

**Comment by PiweeX** [comment]
![download](https://user-images.githubusercontent.com/33425430/177332639-2b1bb1f9-99f1-4e65-b48a-c7c9cff85c29.png)

**Comment by PiweeX** [comment]
![download](https://user-images.githubusercontent.com/33425430/178148585-389cf63b-fe39-4190-85e5-abe3ead72218.png)

**Comment by PiweeX** [comment]
path
![download](https://user-images.githubusercontent.com/33425430/178148620-a4c9dfa7-a9af-4d5e-9b6b-128d13927cac.png)

**Comment by PiweeX** [comment]
spawn-monsters=false

**Comment by PiweeX** [comment]
backup created

**Comment by PiweeX** [comment]
![download](https://user-images.githubusercontent.com/33425430/178151660-3bd1aff3-a44f-4488-86d9-741c717287cc.png)
added water

**Comment by PiweeX** [comment]
![download](https://user-images.githubusercontent.com/33425430/178556292-d8b5d967-1a15-471d-8a28-7f8483400e20.png)

builder zZzZVUCNIK

**Comment by R1derPN** [comment]
Kad je u pitanju dungeons.Jel cete ubrajati custom mobove ili mobove iz Modova.(Bosove takodjer)

**Comment by PiweeX** [comment]
> Kad je u pitanju dungeons.Jel cete ubrajati custom mobove ili mobove iz Modova.(Bosove takodjer)

ovo je za nešto drugo, ne za Decentraland podserver

**Comment by PiweeX** [comment]
![3](https://user-images.githubusercontent.com/33425430/178723288-588d3aa9-2bac-4329-a108-8f15bdc7afe2.png)

**Comment by PiweeX** [comment]
![4](https://user-images.githubusercontent.com/33425430/178723310-1c4e0826-3735-4fc4-b0d1-dd828650e8b8.png)

**Comment by PiweeX** [comment]
Bio je sagrađen novi build obzirom da se predhodni nije svideo, issue zatvaram ovim
