### ISSUE TITLE
Stvari hakera do novih igrača

### ISSUE THREAD

**Issue by PiweeX** [PiweeX/HogRealms#110]
Danas je 3 zajednička igrača kažnjeno na 4 meseca zatvora i oduzimanje stvari zbog hakovanja,

Želeli smo da kao i u predhodnim slučajima delimo stvari koje zaplenimo a koje mormao da zaplenimo jer su nepravedno stečene (xray)

u predhodnom slučaju pre mesec dana delili smo igračima sa zanimljivim RPom, kvalitetnim državama sa dobrim buildom i igračima koji igraju RP i koji ne prave probleme

otvoren je predlog u DAO da se te stvari spaljuju ali za ovako nešto je potreban Issue kako bi svi mogli da glasaju jer nema veze sa toksičnim igračima već sa nečim što je za veće mase ljudi i to kako bi igrači mislili da je ok

po meni ovo balansira ekonomiju, uvek treba podspešiti kvalitetne države, svakako što se tiče netherite armora neće imati toliku ulogu kad dođu tunic armori koji će poboljšati RP i koji će se dobijati na vote i na rewards

takođe ovo se jako dobro raspodeli, ne da se nikad jednom igraču ili državi

glasajte i napišite šta mislite

**Comment by akipaki293** [comment]
Ja mislim da aki ne pravi probleme i da se njemu treba nesto dati :)
