### ISSUE TITLE
Nepotrebni claim-ovi

### ISSUE THREAD

**Issue by aaaaaaaaaaaaaadddddddddddddddaaaaaaaa** [PiweeX/HogRealms#113]
Na Hogu ima previse claim-ova koji jako smetaju igracima. Ti claim-ovi jako smetaju ako neko oce da siri drzavu ne moze od claim-ova koji su neaktivni ili nemaju nista u sebi. Po mom misljenju svi claimovi koji su neaktivni ili smetaju. Voleo bih da svako ko ima neke claim-ove oko svog land-a moze negde da se posalje i sa glasom vise od troje ljudi to da se ukloni.
Znaci za ovo bi mogla da se napravi skala
-ispod 10 chunkova nedelju dana neaktivnosti-brisanje landa
-ispod 50 chunkova dve nedelje neaktivnosti-brisanje landa 
-ispod 100 chunkova mesec neaktivnosti-brisanje landa
-preko 100 chunkova 2 meseca neaktivnosti-brisanje landa
Primeri:
-na Hogu imaju claim-ovi koji su jako mali nemaju bildove i nepotrebni su.
-jedan igrac(necu da ga imenujem)oce da napravi jedan veliki claim i ima problem zato sto ima jedan claim od 2 chunka i smeta
-neko ne moze da zauzme celu Spaniju zato sto imaju 2 neaktivna claim-a

**Comment by stipefire** [comment]
Slazem se  neke drzave se zele prosiriti i jednostavno nemogu zbog nekog sinise koji je prije 3 mjeseca samo uso i tu claimo 5 chunkova ovakav sistem bi to sprijecio i ostavio samo aktivne claimove

**Comment by R1derPN** [comment]
Slazem se takodje u vezi tik drzave koje kbkruzuju jedniom linijom oko landa necijem da bi sprecili sirenje drzave kao na primer Treci rajh (koji se treba mac) kod Danske

**Comment by akipaki293** [comment]
Claimovi koji vam smetaju su mozda feudalni posedi, a ljudi nisu aktivni jer imaju obaveza, po tvom sistemu ja koji imam preko 2k claima u koj sam ulozio preko 500k bice izbrisano za 2 meseca, mozda tokom skole gde ne mogu igrati i onda kad dodjem za raspust vidim nema mi claima i propade mi sav trud i sva motivacija za igranjem, a vec mi se desilo da mi deo claima nestao

**Comment by JedemJaja** [comment]
> Claimovi koji vam smetaju su mozda feudalni posedi, a ljudi nisu aktivni jer imaju obaveza, po tvom sistemu ja koji imam preko 2k claima u koj sam ulozio preko 500k bice izbrisano za 2 meseca, mozda tokom skole gde ne mogu igrati i onda kad dodjem za raspust vidim nema mi claima i propade mi sav trud i sva motivacija za igranjem, a vec mi se desilo da mi deo claima nestao

Dobro, mozda da javis dao ili otvoris issue da ces biti neaktivan, uglavnom ovo je samo ideja, ali dobra ideja

**Comment by ratkomraleu** [comment]
> Na Hogu ima previse claim-ova koji jako smetaju igracima. Ti claim-ovi jako smetaju ako neko oce da siri drzavu ne moze od claim-ova koji su neaktivni ili nemaju nista u sebi. Po mom misljenju svi claimovi koji su neaktivni ili smetaju. Voleo bih da svako ko ima neke claim-ove oko svog land-a moze negde da se posalje i sa glasom vise od troje ljudi to da se ukloni. Znaci za ovo bi mogla da se napravi skala -ispod 10 chunkova nedelju dana neaktivnosti-brisanje landa -ispod 50 chunkova dve nedelje neaktivnosti-brisanje landa -ispod 100 chunkova mesec neaktivnosti-brisanje landa -preko 100 chunkova 2 meseca neaktivnosti-brisanje landa Primeri: -na Hogu imaju claim-ovi koji su jako mali nemaju bildove i nepotrebni su. -jedan igrac(necu da ga imenujem)oce da napravi jedan veliki claim i ima problem zato sto ima jedan claim od 2 chunka i smeta -neko ne moze da zauzme celu Spaniju zato sto imaju 2 neaktivna claim-a

Ne, jer neki prisutni su banovani na 5 meseci a imaju ogromne claimove ;)

**Comment by PiweeX** [comment]
da javim samo da je ovo reseno tako sto je upravo malo pre smanjeno sa 80 dana neaktivnosti na 50 dana kako bi nepotrebni claimovi nestali i kako bi se kvalitetni roleplayovi stvarali :)
