### ISSUE TITLE
skidanje Red-u nadleznost za toxic i vredjanje

### ISSUE THREAD

**Issue by aaaaaaaaaaaaaadddddddddddddddaaaaaaaa** [PiweeX/HogRealms#116]
od kada je napravljena grupa HogShield kojoj je vlasnik Red niko nista ne sme da kaze. On na svaku pskovku ili sl trazi mute ili nesto slicno,sa tim se ulizuje dzelatima zato sto on sam oce da postane. Ja predlazem da se skine nadleznost Reda i da se ta grupa skloni ili da neko razumniji dodje da bude glavni. Kao sto je MRKnedla ili DjoVani

**Comment by aaaaaaaaaaaaaadddddddddddddddaaaaaaaa** [comment]
psovku*

**Comment by Siu804** [comment]
Dzaba ti je to skinut si kao clan HogShield-a napravljena je grupa od strane mene i svaki igrac koji dobije mute je zasluzeno kažnjen takodje ne odlucujem samo ja,svaki put kad neko vredja,psuje ili slicno prolazi kroz tiket u UN...Tako da ne moras da se brines za mene odobrena je od strane px-a i sluzi u dobre svrhe servera ne dobija svako mute cim nesto Kaze ili opsuje vec dobija prvo upozorenje za mute ako opet ponavlja vredja i slicno onda tek dobija mute...Npr sada Frop1k treba da dobije mute koji je sam napisao u ticket u HogShield-u "Knedlo jedi govna"pa mi reci da li sada gresim da treba da dobije mute? Ne naravno da ne to takodje razmatraju i dzelati!Hvala,ne moras da se brines.Zelim da postanem dzelat kazes?I jel imas neki problem svako moze da postane ako se trudi nema tu zabrane mogu da se trudim koliko hocu ali to necu odredjivati ja.

**Comment by bogoljub1234** [comment]
Od tok red njegova poruka uvijek dzelat

**Comment by NemanjaRusija** [comment]
Ja se slažem da se hog info ukine to je glupost. Ako ima UN šta će onda Hog Info? Ne kontam? Neka hog info bude za novine a ne za novi UN.

**Comment by PiweeX** [comment]
Hog info server od Reda nema nikakve veze sa kažnjavanjem niti sam ja insistirao da se to napravi

on je napravio taj server kako bi pomogao dželatima u praćenju ko pravi probleme, screenshotuje i pošalje na UN i kazni se PO ZAKONU, ništa više

**Comment by PiweeX** [comment]
ne znam šta vam nije jasno

**Comment by Siu804** [comment]
Ne stvarno sta tu nije jasno?Kao sto je rekao PiweeX da to ide na UN ticket,i opet govoris da "dobiju mute za jednu psovku" ne odlucujem ja dal ce neko dobiti kaznu vec dzelati kao sto rekoh sve prolazi kroz UN ticket...
