### ISSUE TITLE
MHN Community 

### ISSUE THREAD

**Issue by akipaki293** [PiweeX/HogRealms#117]
- Kao što svi znaju **MHN Novine** su nastale nakon _raspada_ **MBS-a**. 
 ![преузимање](https://user-images.githubusercontent.com/107085831/177831279-569ea09b-86b9-4337-9db8-3e81d65f9707.png)

- Danas  **MHN** sebe naziva _Community_ jer obuhvata **MHN Novine, Hogo Psihijatriju, Hogo Dizajners, MHN Events i HIS ili MHN IS**. 

- Na ovom issues-u će dolaziti svi _Updetovi_ u **MHN-u** kao i na discordu u kanalu #🎖︲dostignuća.

- `[MHN Community ]`(https://discord.gg/85NK5gqjyb)

**Comment by Featherica** [comment]
Čekamo da se raspadne pa da dodje MTS 🥳

**Comment by dihack111** [comment]
Tesko da cemo se raspasti tako lako ; )

**Comment by Featherica** [comment]
> Tesko da cemo se raspasti tako lako ; )

Neće biti prvi put, šteta ako se raspadne jer aki dobija ogromnu podršku ostalih ljudi sa hoga, a da tako lako preda nekom ko ne zna ni šta je to nije baš lepo.

**Comment by akipaki293** [comment]
> > Tesko da cemo se raspasti tako lako ; )
> 
> Neće biti prvi put, šteta ako se raspadne jer aki dobija ogromnu podršku ostalih ljudi sa hoga, a da tako lako preda nekom ko ne zna ni šta je to nije baš lepo.

To se nece desiti, ownership necu dati nikom, a server vodimo zajedno ja i dihack i ako ja odem on je tu da drzi

**Comment by akipaki293** [comment]
> > Tesko da cemo se raspasti tako lako ; )
> 
> Neće biti prvi put, šteta ako se raspadne jer aki dobija ogromnu podršku ostalih ljudi sa hoga, a da tako lako preda nekom ko ne zna ni šta je to nije baš lepo.

**Comment by VukIcrnogorskii** [comment]
> > Tesko da cemo se raspasti tako lako ; )
> 
> Svi znamo da Wolf voli da vređa al dotice me toliko koliko me napala crna gora u Age of History

Kakve veze ja imam i sa čim ođe

**Comment by akipaki293** [comment]
MHN Community

Organizacija koja je zvanični Hog Decentraland server. Imamo dozvolu od PX-a za korištenje imena "Hogo" u sledećim i sadašnjim projektima.

Šta smo mi?

Mi smo grupa ljudi, odnosno MHN Team koji pišu Novine, drže Psihijatriju, rade političku kartu i još dosta toga.

Ako smo Hog Decentraland organizacija što imamo u imenu Community?

Mi našu organizaciju nazivamo Community jer obuhvatamo više stvari, 2 glavne su MHN Novine i Hogo Dizajners, a ostale, ali ne tako zapostavljene su HIS ili MHN IS (MHN Informativna Stranka), Hogo Psihijatrija i MHN Events.

Šta su MHN Novine?

Mi u ovom delu zajednice objavljujemo Novosti servera, država i organizacija. Postati novinar je moguće u kanalu #🧨︲prijave-za-novinare, a postupci su sledeći: Prijava za Novinare
Stupnjevi - 1 [najlakši], 2 [polutežak], 3 [težak]

1. Stupanj popuniti prijavnicu:
Vaše ime u igri:
Da li imate iskustva?:
Da li ste ovo radili pre?:
Zašto bas novinar?:

2. Stupanj, ako prođete prvi dobijate zadatak da @NGeneralni Sekretar u DM napišete nešto [da izgleda na novine] o nekom događaju najstarije pre 7 dana. @NGeneralni Sekretar odlučuje ko prolazi u 3. Stupanj. 

3. Stupanj, da intervjuišete nekoga, napišete ono što su vam oni rekli, vi to prepravite i pošaljete @NGeneralni Sekretar u DM prepravljeni i neprepravljeni deo. @MHN Team odlučuje ko prolazi.

Šta su Hogo Dizajners?

Naši Dizajneri trenutno rade političku mapu sveta, ali u planu su nam izrađivanje zastava i grbova država i organizacija. Te izrada logotipa. 

Kako radi Hogo Psihijatrija?

Radi na način što vi u #🌊︲psihijatrija odaberete šta želite, i onda u #💸︲zakazivanje-termina tagujete psihijatra i napišete koju ponudu želite.

MHN Events i HIS?

MHN Events rade na poentu da MHN Team organizuje neki Event, i pobednik tog Eventa dobije nagradu uz dogovor sa Hog Stafom. HIS odnosno MHN Is - Hogo Informativna Stranka ili MHN Informativna Stranka, članovi ove stranke pomažu novim igračima u snalaženju na serveru.

Kako se prijaviti za Dizajnera, Psihijatra i Člana HIS-a?

Prijave su trenutno u izradi, ali biće do kraja 7. Meseca.

![преузимање](https://user-images.githubusercontent.com/107085831/178618914-8c82c4f7-4ffb-45d9-a51f-be0dd83286e2.png)
