### ISSUE TITLE
Claim

### ISSUE THREAD

**Issue by JaSamIgor** [PiweeX/HogRealms#119]
Zbog dodavanja političke karte, a i da rp postane bolji,mislim da bi se na mainnet trebala povećati cjena prvog claima. To bi smanjilo claimovanje po teritorijama država na političkoj karti, i verovatno ne bi bilo država sa glupim imenima po Africi i drugim kontinentima. Dok igrači skupe pare za claim već će znati kako rp funkcioniše.

**Comment by PiweeX** [comment]
rešeno pred mainnet, inače objavio sam malo pre da je mainnet umesto Maja pomren za April!
