### ISSUE TITLE
Igrač denzavkk da ga poštedite smrtne kazne i vratite u server.

### ISSUE THREAD

**Issue by Featherica** [PiweeX/HogRealms#12]
Poštovani, 

Denza je napravio dosta grešaka tokom njegove karijere, meni je jasno da je morao dobiti ban, ali ovom prilikom zamolio bih dzelate da mu pokažu milost i da ga puste na slobodu, ili da mu smanju kaznu barem na mesec dana. Ja možda nisam Denzel, ali verujem da neće više praviti gluposti kao što je pre pravio.

Srdačan pozdrav!

**Comment by akipaki293** [comment]
Takodjw

**Comment by PiweeX** [comment]
ja sam za to da on dobije unban ili da  mu se makar da trajnost banu, ranije sam pisao o ovoj temi u privatnom četu pa neću sad ponovo ali u suštini razumete

**Comment by buducidzelat** [comment]
> ja sam za to da on dobije unban ili da mu se makar da trajnost banu, ranije sam pisao o ovoj temi u privatnom četu pa neću sad ponovo ali u suštini razumete

i ja sam zato unbanuj
![Screenshot_2061](https://user-images.githubusercontent.com/107114906/173239068-c12cd3ba-168c-4673-9fa7-8a5ced33e706.png)

**Comment by akipaki293** [comment]
Ovo treba da se zatvori, denzel je unbanan

**Comment by bogoljub1234** [comment]
Lijepo
