### ISSUE TITLE
Ne primajte ove igrace u drzave! SCAM

### ISSUE THREAD

**Issue by T1GAR** [PiweeX/HogRealms#120]
1. Sinisa
Dosao je kao i svi normalni, ali bio je malo sketchy. Vidio sam uz /invsee da uzima velik proj sedla i ostalih materijala za građenje i pitao sam ga zasto je to uzeo. rekao je da uzima kako bi si napravio kucu, uz to da sam mu napisao da nista ne uzima i da samo pogleda kako grad izgleda do sutra je evo bilo je 3 ujutro. To ga je cak malo i prepalo ali svejedno samo dobio ovo:
![image](https://user-images.githubusercontent.com/107375896/178128423-9fc737d6-8d20-4a0e-b797-a895d926116a.png)
Jos jedan od razloga zasto je vazno imat privatne chestove, a u ovom slucaju sve vazne stvari su u njima tako da nije bilo nista posebno za ukrast uopce. Nakon toga naravno tu ide i discord ban jer se nas Sinisa prepao i nestao je. Pitaj Boga ako ce uopce opet uc na server. Ako vas ista pita samo prijavite nekome jer SCAM je.

2. Milorad
On je skoro pa i u istu minutu usao na server kao i Sinisa. Duo SCAMERI su. On pak niti nije usao u drzavu nego napravio ovo.
![image](https://user-images.githubusercontent.com/107375896/178128478-1f17d54d-10c7-4986-840d-a70f146191b1.png)
"poglup si za moje standarde" kaze neko ko ide krast od ljudi koji se trude nesto postic i to  on zove "standard". Necu niti komentirat koliko je to maloumno ali ajde.

3. jos neki ss-ovi
![image](https://user-images.githubusercontent.com/107375896/178128519-8afa06ec-cc14-4c8b-9fbe-10cbb1f29a7e.png)

naravno i banao me na discordu klasika
![image](https://user-images.githubusercontent.com/107375896/178128532-ffed330d-74ad-4cde-aba0-dd543e71824c.png)

dokaz da je uopce bio u zemlji ako netko i to pita
![image](https://user-images.githubusercontent.com/107375896/178128558-5f9f0d11-30d7-460a-9a37-720f20f0adf1.png)

Mislim da dalje ne trebam. Posalo sam i u UN i u HogShield ticket jer niti ja ne znam vise koje radi koje ne koje je za sto koje za nesto trideseto u oboje sam posalo i netko ce vidjet. 
Nadam se da ce oboje dobit ono sto zaslužuju!

1.1. Svako neodobreno uzimanje itema smatra se krađom- Sinisa je uzeo stvari uz to da sam mu i napomenuo da ne dira nista

1.3. Itemi koji su na području neke teritorije pripadaju vlasniku te države- Krao je i iz chestova na centru grada barem onih koji nisu privatni gdje ima dosta materijala za gradnju i pripadaju vlasniku države kao i ostalim građanima

1.4.1 Osoba koja je ukrala iteme stavlja se u jail do stupanja kontakta, nakon čega je osoba dužna donijeti stvari. Nakon što su stvari vraćene osoba ispunjava kaznu u periodu propisanom u paragrafu 2.1. počevši od trenutka kada su stvari vraćene- nadam se da se vratiti stvari

1.5. Ako je osoba napustila državu itemi koji su dobiveni od države pripadaju državi osim ako u pitanju nije trajni poklon ili enchantovi na itemima- Sve sto je uzeo je pripadalo ostalim građanima i državi i uzeo je uz napomenu da nista ne dira

3.1. Toksičnim ponašanjem smatra se svaka vrsta interakcije koja je uvrijedljiva drugom subjektu- ss-ovi objasnjavaju ovo

3.2. Toksično ponašanje strogo je zabranjeno u javnim chatovima- isto tako ss-ovi objasnjavaju ovo

3.4. Psovanje je zabranjeno u javnim chatovima- isto tako ss-ovi objasnjavaju ovo

oprostite na gramatici pola 5 ujutro je

**Comment by VukIcrnogorskii** [comment]
> 1. Sinisa
>    Dosao je kao i svi normalni, ali bio je malo sketchy. Vidio sam uz /invsee da uzima velik proj sedla i ostalih materijala za građenje i pitao sam ga zasto je to uzeo. rekao je da uzima kako bi si napravio kucu, uz to da sam mu napisao da nista ne uzima i da samo pogleda kako grad izgleda do sutra je evo bilo je 3 ujutro. To ga je cak malo i prepalo ali svejedno samo dobio ovo:
>    ![image](https://user-images.githubusercontent.com/107375896/178128423-9fc737d6-8d20-4a0e-b797-a895d926116a.png)
>    Jos jedan od razloga zasto je vazno imat privatne chestove, a u ovom slucaju sve vazne stvari su u njima tako da nije bilo nista posebno za ukrast uopce. Nakon toga naravno tu ide i discord ban jer se nas Sinisa prepao i nestao je. Pitaj Boga ako ce uopce opet uc na server. Ako vas ista pita samo prijavite nekome jer SCAM je.
> 2. Milorad
>    On je skoro pa i u istu minutu usao na server kao i Sinisa. Duo SCAMERI su. On pak niti nije usao u drzavu nego napravio ovo.
>    ![image](https://user-images.githubusercontent.com/107375896/178128478-1f17d54d-10c7-4986-840d-a70f146191b1.png)
>    "poglup si za moje standarde" kaze neko ko ide krast od ljudi koji se trude nesto postic i to  on zove "standard". Necu niti komentirat koliko je to maloumno ali ajde.
> 3. jos neki ss-ovi
>    ![image](https://user-images.githubusercontent.com/107375896/178128519-8afa06ec-cc14-4c8b-9fbe-10cbb1f29a7e.png)
> 
> naravno i banao me na discordu klasika ![image](https://user-images.githubusercontent.com/107375896/178128532-ffed330d-74ad-4cde-aba0-dd543e71824c.png)
> 
> dokaz da je uopce bio u zemlji ako netko i to pita ![image](https://user-images.githubusercontent.com/107375896/178128558-5f9f0d11-30d7-460a-9a37-720f20f0adf1.png)
> 
> Mislim da dalje ne trebam. Posalo sam i u UN i u HogShield ticket jer niti ja ne znam vise koje radi koje ne koje je za sto koje za nesto trideseto u oboje sam posalo i netko ce vidjet. Nadam se da ce oboje dobit ono sto zaslužuju!
> 
> 1.1. Svako neodobreno uzimanje itema smatra se krađom- Sinisa je uzeo stvari uz to da sam mu i napomenuo da ne dira nista
> 
> 1.3. Itemi koji su na području neke teritorije pripadaju vlasniku te države- Krao je i iz chestova na centru grada barem onih koji nisu privatni gdje ima dosta materijala za gradnju i pripadaju vlasniku države kao i ostalim građanima
> 
> 1.4.1 Osoba koja je ukrala iteme stavlja se u jail do stupanja kontakta, nakon čega je osoba dužna donijeti stvari. Nakon što su stvari vraćene osoba ispunjava kaznu u periodu propisanom u paragrafu 2.1. počevši od trenutka kada su stvari vraćene- nadam se da se vratiti stvari
> 
> 1.5. Ako je osoba napustila državu itemi koji su dobiveni od države pripadaju državi osim ako u pitanju nije trajni poklon ili enchantovi na itemima- Sve sto je uzeo je pripadalo ostalim građanima i državi i uzeo je uz napomenu da nista ne dira
> 
> 3.1. Toksičnim ponašanjem smatra se svaka vrsta interakcije koja je uvrijedljiva drugom subjektu- ss-ovi objasnjavaju ovo
> 
> 3.2. Toksično ponašanje strogo je zabranjeno u javnim chatovima- isto tako ss-ovi objasnjavaju ovo
> 
> 3.4. Psovanje je zabranjeno u javnim chatovima- isto tako ss-ovi objasnjavaju ovo
> 
> oprostite na gramatici pola 5 ujutro je

Posto si bardonijanac vjerovatno ce te samo seenovati, kao i vecinu ostalih igraca koji nijesu dio sistema

**Comment by T1GAR** [comment]
> > 1. Sinisa
> >    Dosao je kao i svi normalni, ali bio je malo sketchy. Vidio sam uz /invsee da uzima velik proj sedla i ostalih materijala za građenje i pitao sam ga zasto je to uzeo. rekao je da uzima kako bi si napravio kucu, uz to da sam mu napisao da nista ne uzima i da samo pogleda kako grad izgleda do sutra je evo bilo je 3 ujutro. To ga je cak malo i prepalo ali svejedno samo dobio ovo:
> >    ![image](https://user-images.githubusercontent.com/107375896/178128423-9fc737d6-8d20-4a0e-b797-a895d926116a.png)
> >    Jos jedan od razloga zasto je vazno imat privatne chestove, a u ovom slucaju sve vazne stvari su u njima tako da nije bilo nista posebno za ukrast uopce. Nakon toga naravno tu ide i discord ban jer se nas Sinisa prepao i nestao je. Pitaj Boga ako ce uopce opet uc na server. Ako vas ista pita samo prijavite nekome jer SCAM je.
> > 2. Milorad
> >    On je skoro pa i u istu minutu usao na server kao i Sinisa. Duo SCAMERI su. On pak niti nije usao u drzavu nego napravio ovo.
> >    ![image](https://user-images.githubusercontent.com/107375896/178128478-1f17d54d-10c7-4986-840d-a70f146191b1.png)
> >    "poglup si za moje standarde" kaze neko ko ide krast od ljudi koji se trude nesto postic i to  on zove "standard". Necu niti komentirat koliko je to maloumno ali ajde.
> > 3. jos neki ss-ovi
> >    ![image](https://user-images.githubusercontent.com/107375896/178128519-8afa06ec-cc14-4c8b-9fbe-10cbb1f29a7e.png)
> > 
> > naravno i banao me na discordu klasika ![image](https://user-images.githubusercontent.com/107375896/178128532-ffed330d-74ad-4cde-aba0-dd543e71824c.png)
> > dokaz da je uopce bio u zemlji ako netko i to pita ![image](https://user-images.githubusercontent.com/107375896/178128558-5f9f0d11-30d7-460a-9a37-720f20f0adf1.png)
> > Mislim da dalje ne trebam. Posalo sam i u UN i u HogShield ticket jer niti ja ne znam vise koje radi koje ne koje je za sto koje za nesto trideseto u oboje sam posalo i netko ce vidjet. Nadam se da ce oboje dobit ono sto zaslužuju!
> > 1.1. Svako neodobreno uzimanje itema smatra se krađom- Sinisa je uzeo stvari uz to da sam mu i napomenuo da ne dira nista
> > 1.3. Itemi koji su na području neke teritorije pripadaju vlasniku te države- Krao je i iz chestova na centru grada barem onih koji nisu privatni gdje ima dosta materijala za gradnju i pripadaju vlasniku države kao i ostalim građanima
> > 1.4.1 Osoba koja je ukrala iteme stavlja se u jail do stupanja kontakta, nakon čega je osoba dužna donijeti stvari. Nakon što su stvari vraćene osoba ispunjava kaznu u periodu propisanom u paragrafu 2.1. počevši od trenutka kada su stvari vraćene- nadam se da se vratiti stvari
> > 1.5. Ako je osoba napustila državu itemi koji su dobiveni od države pripadaju državi osim ako u pitanju nije trajni poklon ili enchantovi na itemima- Sve sto je uzeo je pripadalo ostalim građanima i državi i uzeo je uz napomenu da nista ne dira
> > 3.1. Toksičnim ponašanjem smatra se svaka vrsta interakcije koja je uvrijedljiva drugom subjektu- ss-ovi objasnjavaju ovo
> > 3.2. Toksično ponašanje strogo je zabranjeno u javnim chatovima- isto tako ss-ovi objasnjavaju ovo
> > 3.4. Psovanje je zabranjeno u javnim chatovima- isto tako ss-ovi objasnjavaju ovo
> > oprostite na gramatici pola 5 ujutro je
> 
> Posto si bardonijanac vjerovatno ce te samo seenovati, kao i vecinu ostalih igraca koji nijesu dio sistema

Prekrasnan je to sistem moram rec.

**Comment by PiweeX** [comment]
Zatvaram ovaj issue jer je dosta star, služio je dovoljno 👌🏻
