### ISSUE TITLE
Pecanje 

### ISSUE THREAD

**Issue by akipaki293** [PiweeX/HogRealms#124]
Pecanje je postalo jako dosadno, sezona ribolova ima jako Lose nagrade... Preporucujem da se doda novi sistem ribolova npr da se napravi custom textura za vece ribe i da izgledaju kao traktor samo manje, da riba moze da pobegne itd, a sto se tiče sezone ribolova, da se nameste bolje nagrade i da ako je sezona ribolova sansa za bolju ribu je npr +20%
...

**Comment by akipaki293** [comment]
Sad tek ovo nece biti pogledano kad sam dobio dosije

**Comment by muvstp** [comment]
Ok

**Comment by PiweeX** [comment]
Pecanje trenutno ima errora u konzoli i to velikih od kako se memorija zeznula, radimo na tome da rešimo, zatvoriću ovaj issue jer je odavno tu, što se tiče tekstura za ribe to nije moguće
