### ISSUE TITLE
nether wart,soul sand i nether brick

### ISSUE THREAD

**Issue by Major1312** [PiweeX/HogRealms#126]
treba da se doda u shopu ili Nether wart,Soul sand i Nether brick!!!!
pod hitno!!!

**Comment by Hanci007** [comment]
da

**Comment by Steva1890** [comment]
Da

**Comment by RIx4er** [comment]
> treba da se doda u shopu ili Nether wart,Soul sand i Nether brick!!!! pod hitno!!!

Da

**Comment by RIx4er** [comment]
> 

Da

**Comment by RIx4er** [comment]
Da

**Comment by muvstp** [comment]
Da nego kako ćeš mi dati tih 5k kad dobijem unban ili nekome drugom

**Comment by muvstp** [comment]
Da

**Comment by vojin007** [comment]
Ja mislim da bi Ili na spawn-u da se kupuje meter wart blaze rod itd Ili da se u juznoj africi u cave nade.

**Comment by JedemJaja** [comment]
> Ja mislim da bi Ili na spawn-u da se kupuje meter wart blaze rod itd Ili da se u juznoj africi u cave nade.

Zasto bas u juznoj africi krtico pohlepna

**Comment by PiweeX** [comment]
Biće dodato u black shop koji se otvara uskoro, Djomla i Djovani su ga izgradili i ostalo je još doraditi questove i još neke stvari
