### ISSUE TITLE
Mediveal world

### ISSUE THREAD

**Issue by PiweeX** [PiweeX/HogRealms#127]
https://user-images.githubusercontent.com/33425430/181618872-d1bf1f94-35de-4992-bf53-26a82db440ca.mp4

**Comment by PiweeX** [comment]
![stadhuis-Leiden](https://user-images.githubusercontent.com/33425430/181618106-4e087a7a-399e-4fe5-b7a2-b83e2c59aed7.jpg)

**Comment by PiweeX** [comment]
![2022-07-28_19 46 38](https://user-images.githubusercontent.com/33425430/181618595-1ab83642-7790-4efd-ada0-3c64353b9145.png)
![2022-07-28_19 45 05](https://user-images.githubusercontent.com/33425430/181618711-c3b7783a-58b4-420d-b96e-9c3def6a6560.png)
![2022-07-28_19 47 29](https://user-images.githubusercontent.com/33425430/181618763-b98465db-2108-4f0c-abe0-88e45ee15adb.png)

**Comment by PiweeX** [comment]
![stadhuis-Leiden](https://user-images.githubusercontent.com/33425430/181619107-1944ea7c-ac75-41a4-a9de-ad61fad4bbdc.jpg)

![Wroclaw-ratusz-archiwalne-z-1800r](https://user-images.githubusercontent.com/33425430/181619129-3223ccdb-087b-4c76-9072-424b5b0de597.jpg)

**Comment by PiweeX** [comment]
![2022-07-31_01 37 14](https://user-images.githubusercontent.com/33425430/182024073-50d5278c-d25a-4522-a67e-4708fe22f5ee.png)
![2022-07-31_01 37 18](https://user-images.githubusercontent.com/33425430/182024078-7c5445d6-2aff-4d47-a8d4-f53466cbe770.png)
![2022-07-31_01 37 10](https://user-images.githubusercontent.com/33425430/182024083-0f1fc171-0d1d-4329-9b50-616c6d2338c5.png)

**Comment by PiweeX** [comment]
![2022-07-31_13 19 16](https://user-images.githubusercontent.com/33425430/182024101-66cbf60e-d3ea-46e9-8959-a5b0e9784d56.png)


rebuilded
![2022-07-31_12 01 40](https://user-images.githubusercontent.com/33425430/182024104-f4163a9b-3834-46e5-b92a-575b919535f0.png)
![2022-07-31_12 01 44](https://user-images.githubusercontent.com/33425430/182024106-fd39e831-4792-4ad3-a9f1-ff4fb6991907.png)

**Comment by PiweeX** [comment]
The third time it's being built because the sound hasn't been recorded in the OBS

**Comment by PiweeX** [comment]
![download](https://user-images.githubusercontent.com/33425430/182028772-d8d046a6-4a4d-4fe3-a107-45a41d29d8e9.png)

**Comment by PiweeX** [comment]
za radio na Hogoflow discordu svaki NPM je instaliran posebno po restartu ali idalje ne radi, docker image će biti smanjen sa 17 na 16

**Comment by PiweeX** [comment]
idalje ne radi

discord.js, @discordjs/voice, @discordjs/opus, sodium, distube, discord-api-types, @discordjs/rest

dodato u dodatne node packageove na panelu

**Comment by PiweeX** [comment]
> idalje ne radi
> 
> discord.js, @discordjs/voice, @discordjs/opus, sodium, distube, discord-api-types, @discordjs/rest
> 
> dodato u dodatne node packageove na panelu

opet je isto, stavljena je arm verzija 16

**Comment by PiweeX** [comment]
Extracting [==================================================>]  4.089kB/4.089kB
Pull complete 
Extracting [>                                                  ]  360.4kB/34.22MB
Extracting [====>                                              ]  2.884MB/34.22MB
Extracting [=======>                                           ]  5.407MB/34.22MB
Extracting [============>                                      ]   8.29MB/34.22MB
Extracting [================>                                  ]  11.53MB/34.22MB
Extracting [====================>                              ]  14.06MB/34.22MB
Extracting [=========================>                         ]   17.3MB/34.22MB
Extracting [============================>                      ]  19.82MB/34.22MB
Extracting [=================================>                 ]  22.71MB/34.22MB
Extracting [=====================================>             ]  25.95MB/34.22MB
Extracting [==========================================>        ]  28.84MB/34.22MB
Extracting [=============================================>     ]     31MB/34.22MB
Extracting [==============================================>    ]  31.72MB/34.22MB
Extracting [===============================================>   ]   32.8MB/34.22MB
Extracting [=================================================> ]  33.88MB/34.22MB
Extracting [==================================================>]  34.22MB/34.22MB
Pull complete 
Extracting [>                                                  ]  32.77kB/2.286MB
Extracting [===================================>               ]  1.638MB/2.286MB
Extracting [==================================================>]  2.286MB/2.286MB
Extracting [==================================================>]  2.286MB/2.286MB
Pull complete 
Extracting [==================================================>]     453B/453B
Extracting [==================================================>]     453B/453B
Pull complete 
Extracting [>                                                  ]  557.1kB/105.9MB
Extracting [==>                                                ]  5.571MB/105.9MB
Extracting [====>                                              ]  8.913MB/105.9MB
Extracting [=====>                                             ]   11.7MB/105.9MB
Extracting [======>                                            ]  14.48MB/105.9MB
Extracting [========>                                          ]  17.27MB/105.9MB
Extracting [=========>                                         ]  20.05MB/105.9MB
Extracting [===========>                                       ]   23.4MB/105.9MB
Extracting [============>                                      ]  26.74MB/105.9MB
Extracting [==============>                                    ]  30.08MB/105.9MB
Extracting [===============>                                   ]  32.87MB/105.9MB
Extracting [================>                                  ]  35.09MB/105.9MB
Extracting [==================>                                ]  38.44MB/105.9MB
Extracting [===================>                               ]  41.78MB/105.9MB
Extracting [=====================>                             ]  45.12MB/105.9MB
Extracting [======================>                            ]  47.91MB/105.9MB
Extracting [========================>                          ]  51.25MB/105.9MB
Extracting [==========================>                        ]  55.15MB/105.9MB
Extracting [===========================>                       ]  59.05MB/105.9MB
Extracting [=============================>                     ]   63.5MB/105.9MB
Extracting [===============================>                   ]  66.85MB/105.9MB
Extracting [=================================>                 ]  70.19MB/105.9MB
Extracting [==================================>                ]  72.97MB/105.9MB
Extracting [====================================>              ]  76.32MB/105.9MB
Extracting [====================================>              ]  77.43MB/105.9MB
Extracting [=====================================>             ]   79.1MB/105.9MB
Extracting [======================================>            ]  82.44MB/105.9MB
Extracting [=======================================>           ]  84.67MB/105.9MB
Extracting [==========================================>        ]  90.24MB/105.9MB
Extracting [============================================>      ]   94.7MB/105.9MB
Extracting [==============================================>    ]   98.6MB/105.9MB
Extracting [================================================>  ]  102.5MB/105.9MB
Extracting [=================================================> ]  105.8MB/105.9MB
Extracting [==================================================>]  105.9MB/105.9MB
Pull complete 
Extracting [==================================================>]      32B/32B
Extracting [==================================================>]      32B/32B
Pull complete 
Extracting [==================================================>]     466B/466B
Extracting [==================================================>]     466B/466B
Pull complete 
Digest: sha256:893722c5641f31cbad1e066805fd456a0a265a7b9djzd23b 
Status: Downloaded newer image for ghcr.io/software-noob/arm64:nodejs_16 
[Pterodactyl Daemon]: Finished pulling Docker container image

ARM instaliran

**Comment by PiweeX** [comment]
posle nekog vremena se desio i kreš a bota nije ubacilo

Status: Downloaded newer image for ghcr.io/software-noob/arm64:nodejs_16 
[Pterodactyl Daemon]: Finished pulling Docker container image
container@pterodactyl~ Server marked as offline...
standard_init_linux.go:228: exec user process caused: exec format error
[Pterodactyl Daemon]: ---------- Detected server process in a crashed state! ----------
[Pterodactyl Daemon]: Exit code: 1
[Pterodactyl Daemon]: Out of memory: false
[Pterodactyl Daemon]: Updating process configuration files...
[Pterodactyl Daemon]: Ensuring file permissions are set correctly, this could take a few seconds...
container@pterodactyl~ Server marked as starting...
[Pterodactyl Daemon]: Pulling Docker container image, this could take a few minutes to complete...

**Comment by PiweeX** [comment]
Opet su provereni tokeni i idevi i drugačiji su, sad krešuje ali ovako

standard_init_linux.go:228: exec user process caused: exec format error
container@pterodactyl~ Server marked as offline...
[Pterodactyl Daemon]: ---------- Detected server process in a crashed state! ----------
[Pterodactyl Daemon]: Exit code: 1
[Pterodactyl Daemon]: Out of memory: false
[Pterodactyl Daemon]: Updating process configuration files...
[Pterodactyl Daemon]: Ensuring file permissions are set correctly, this could take a few seconds...
container@pterodactyl~ Server marked as starting...
[Pterodactyl Daemon]: Pulling Docker container image, this could take a few minutes to complete...
Pulling from software-noob/arm64 
Status: Image is up to date for ghcr.io/software-noob/arm64:nodejs_16 
Digest: sha256:89rc308929casxAWRXbad1e066805fd123a0265a7bd23b 
[Pterodactyl Daemon]: Finished pulling Docker container image
standard_init_linux.go:228: exec user process caused: exec format error
container@pterodactyl~ Server marked as offline...
[Pterodactyl Daemon]: ---------- Detected server process in a crashed state! ----------
[Pterodactyl Daemon]: Exit code: 1
[Pterodactyl Daemon]: Out of memory: false
[Pterodactyl Daemon]: Aborting automatic restart, last crash occurred less than 60 seconds ago.

biće vraćen 16 java version bez ARM

**Comment by PiweeX** [comment]
sad opet prikazuje stariji error

deo errora je

  rawError: { message: 'Missing Access', code: 50001 },
  
  možda bot nema dovoljne permisije

**Comment by PiweeX** [comment]
bot ima sve permisije, setane su mu opet ali svakako je imao administratora, možda na discord developer portalu fali nešto

**Comment by PiweeX** [comment]
files: undefined,
    json: [ [Object], [Object], [Object], [Object], [Object], [Object] ]
  }
}
Bot is Online!
/home/container/node_modules/distube/dist/index.js:2201
      throw new DisTubeError("INVALID_TYPE", "BaseGuildVoiceChannel", voiceChannel, "voiceChannel");
            ^
DisTubeError [INVALID_TYPE]: Expected 'BaseGuildVoiceChannel' for 'voiceChannel', but got undefined (undefined)
    at DisTube.play (/home/container/node_modules/distube/dist/index.js:2201:13)
    at Client.<anonymous> (/home/container/index.js:106:20)
    at Client.emit (node:events:527:28)
    at WebSocketManager.triggerClientReady (/home/container/node_modules/discord.js/src/client/websocket/WebSocketManager.js:385:17)
    at WebSocketManager.checkShardsReady (/home/container/node_modules/discord.js/src/client/websocket/WebSocketManager.js:368:10)
    at WebSocketShard.<anonymous> (/home/container/node_modules/discord.js/src/client/websocket/WebSocketManager.js:194:14)
    at WebSocketShard.emit (node:events:527:28)
    at WebSocketShard.checkReady (/home/container/node_modules/discord.js/src/client/websocket/WebSocketShard.js:512:12)
    at WebSocketShard.onPacket (/home/container/node_modules/discord.js/src/client/websocket/WebSocketShard.js:484:16)
    at WebSocketShard.onMessage (/home/container/node_modules/discord.js/src/client/websocket/WebSocketShard.js:321:10) {
  errorCode: 'INVALID_TYPE'
}

dakle startuje ga i odmah ugasi jer mu nešto fali oko setupa konfiguracije

**Comment by PiweeX** [comment]
na pogrešno mesto pisano..

**Comment by Featherica** [comment]
Well, it is going pretty well for the third time, i checked videos, and now video has sounds, so when it is going to be published it won't be monotone
![2022-07-31_18 32 07](https://user-images.githubusercontent.com/71612070/182036292-ee2d25a4-74f0-4905-99b6-6e6354ecbca9.png)
.

**Comment by Featherica** [comment]
> Well, it is going pretty well for the third time, i checked videos, and now video has sounds, so when it is going to be published it won't be monotone ![2022-07-31_18 32 07](https://user-images.githubusercontent.com/71612070/182036292-ee2d25a4-74f0-4905-99b6-6e6354ecbca9.png) .

**Comment by Featherica** [comment]
I am trying to get the look of old design, but with some more detail
![2022-07-31_18 44 17](https://user-images.githubusercontent.com/71612070/182036695-9ffd8208-3d69-447d-a35b-aa1a09024fa1.png)
s

**Comment by Featherica** [comment]
Allright at this moment, i finally did it
![2022-07-31_21 16 58](https://user-images.githubusercontent.com/71612070/182042069-d9a4fd18-47d2-4ffd-ad91-5b9c101b5a54.png)
![2022-07-31_21 19 59](https://user-images.githubusercontent.com/71612070/182042071-34675bd2-dbd3-4844-989b-264bfb757979.png)
![2022-07-31_21 26 09](https://user-images.githubusercontent.com/71612070/182042073-dc544d75-741a-4b6a-bf24-41437ca6d4b3.png)
![2022-07-31_21 16 54](https://user-images.githubusercontent.com/71612070/182042075-98682234-75ff-4a8f-840f-a05072bd97f9.png)
!

**Comment by PiweeX** [comment]
done
