### ISSUE TITLE
TV Studio

### ISSUE THREAD

**Issue by PiweeX** [PiweeX/HogRealms#129]
TV Studio for sveproductions

**Comment by Featherica** [comment]
![2022-08-03_04 10 09](https://user-images.githubusercontent.com/71612070/182509113-c104f361-ae72-49ca-aa30-477d8bb68b9e.png)
I made this world using world painter app, i am starting late but i will finish this on time.

**Comment by Featherica** [comment]
![2022-08-03_04 22 25](https://user-images.githubusercontent.com/71612070/182510478-2b720d0d-d86c-4d49-b8a7-4f0173ed28a5.png)
![2022-08-03_04 21 43](https://user-images.githubusercontent.com/71612070/182510480-f78ea6ec-3cfa-415b-92a2-f1b1fa275fb6.png)
Made something like mountain from below, but on top something that can only aliens create 😵
