### ISSUE TITLE
Rewards Predlog

### ISSUE THREAD

**Issue by Mikikikirik** [PiweeX/HogRealms#130]
malo je kada neko dobije podmornicu da se rewards zavrsi. Bilo bi mnogo bolje kada bi postojala druga i mozda treca strana. Na drugoj strani da budu netherite armori i netherite pickaxe a na trecoj strani da budu custom item
Da li se slazete?

**Comment by JedemJaja** [comment]
Netherite je tako jednostavno naci da se prodaje po 10k, nemq potrebe da na drugoj strani bude bilo sto netherite

**Comment by PiweeX** [comment]
> malo je kada neko dobije podmornicu da se rewards zavrsi. Bilo bi mnogo bolje kada bi postojala druga i mozda treca strana. Na drugoj strani da budu netherite armori i netherite pickaxe a na trecoj strani da budu custom item Da li se slazete?

bice! :)

**Comment by PiweeX** [comment]
Rewardsovi dobijaju svoje preuređenje kad sredimo i optimizujemo svoj Fokus RankUp plugin!

**Comment by PiweeX** [comment]
uskoro

**Comment by PiweeX** [comment]
Da obavestim ovde u starom issue-u predloga za rewards da smo pre par dana počeli na realizaciji ovoga.

Uz to kako bi netherite armori bili retki kao što su pre jer igrači to žele dodaćemo više strana u rewards polje koje će imati nivoe po kojima se dobija različiti tip armora tako da netherite neće biti toliko tražen jer će se dobijati prvo tunic armori verovatno a onda ruby i ostali

**Comment by PiweeX** [comment]
Ps

Podmornica je izbačena, vidim da je ovde pisalo to. I da, boje su izbačene apsolutno nakon predomišljanja da li da se doda i ljibičasta i crna od predloga iz 4. meseca mog ali prosto nije to to, želimo da svi budu isti po tome a da sami stvaraju svoj karakter tj. rp priču a ne da ih server ograničava ugabuga "Razbojnik" itd po meni je to debilno

**Comment by PiweeX** [comment]
> Ps
> 
> Podmornica je izbačena, vidim da je ovde pisalo to. I da, boje su izbačene apsolutno nakon predomišljanja da li da se doda i ljibičasta i crna od predloga iz 4. meseca mog ali prosto nije to to, želimo da svi budu isti po tome a da sami stvaraju svoj karakter tj. rp priču a ne da ih server ograničava ugabuga "Razbojnik" itd po meni je to debilno

poslednje izmene na ovom predlogu bile su pre 4 meseca

imamo u planu da dodamo drugu stranu rewardsa do čak 60d u momentu kad u sredini Maja (ovog meseca) dodamo tunic armore. Puno toga će biti preuređeno i na prvoj strani jer će se pomeriti dosta, više o tome sam pisao igračima pa da ne ponavljam ovde

**Comment by PiweeX** [comment]
> malo je kada neko dobije podmornicu da se rewards zavrsi. Bilo bi mnogo bolje kada bi postojala druga i mozda treca strana. Na drugoj strani da budu netherite armori i netherite pickaxe a na trecoj strani da budu custom item Da li se slazete?

ovo je issue koji je potrajao skoro godinu dana, nedavno smo rešili ovaj problem. Prvobitno je podmornica uklonjena kao i boja na 7 dana igre a sad je i totalno preuređena prva strana rewardsa gde su usput i blokirane sve netherite i diamond stvari i + se ne dobijaju u prvih 20d igre što im stvara ogromnu vrednost iako ih sad ima puno od mnogih

plan je da se doda još puno stranica, to će sve stići u narednom periodu kroz issue za custom stvari


issue je zvanično zatvoren. Hvala na čekanju, strpljenje se isplati

**Comment by DaniloU08** [comment]
Slažem se u potpunosti
