### ISSUE TITLE
© HogMaps

### ISSUE THREAD

**Issue by TheFrontView** [PiweeX/HogRealms#131]
Od samog starta smo krenuli da radimo mape tako da zbog čega da ne nastavimo kada imamo priliku.

HogRealms igrač TheFrontView i galileo_g su originalno smislili ideju. Nažalost kada je @PiweeX isključio političku mapu morali smo da zaustavimo proizvodnju. Poslednja mapa je bila kreirana 20.04.2022. Vratila se u skorije vreme tako da nemamo razloga da kažemo ne da nastavimo.

Dizajn koj ćemo koristiti je HW. 
- Dizajn radi na 3d Renderu mape.
- Poslednji put pravljena izgledala je:

![MapaHW_1](https://user-images.githubusercontent.com/71612070/183229127-90aaa518-0fdf-4f72-9bf6-1ae91beebd1d.png)

Ovaj stil ćemo idalje da koristimo, samo naravno sa novim teritorijama. 

Kako da ubacim teritoriju na mapu?

Treba te ući na originalni HogMaps discord server.
- https://discord.gg/ugRvgEUp8b
- Uđe te u kanal #nova-teritorija zatim otvorite tiket i pokažete vašu teritoriju.

Mi ćemo vas dodati na mapi. Hvala, Srdačan pozdrav!

**Comment by TheFrontView** [comment]
Mapa odrađena 8/15/22. Dizajn Attack
![AttackEuropa](https://user-images.githubusercontent.com/71612070/185209512-cb239e23-44c1-41d2-94a0-bc099f0f67be.png)
![image](https://user-images.githubusercontent.com/71612070/185209887-0a5b37fb-039b-4ac9-8630-0391924d8250.png)

**Comment by PiweeX** [comment]
vrh

**Comment by galileoba** [comment]
Spojilo se sve jos koje izdanje da izadje i necemo kontinente imat nikako

**Comment by PiweeX** [comment]
Ovaj issue ćemo ugasiti jer će se HOGMAPS discord kroz par dana skroz prebaciti na Roleplay Ligu zbog preglednosti a taj projekat već ima svoj issue
