### ISSUE TITLE
TNT

### ISSUE THREAD

**Issue by Attack36** [PiweeX/HogRealms#134]
Htio bi dati prijedlog da se TNT omoguči u smislu da se omoguči da eksplodira ali da ne uništava blockove. Ovo bi doniejlo novu dinamiku u ratove, tipa omogučilo artiljeriju koje ne uništava trud igrača ali knockback i damage može biti korišten kako bi strateški poziciju otežali onima koji brane i dodalo novu dinamiku u izazov za redstone igrače. Uz to TNT je rijeđi na decentralandu jer je teže skupiti velike količine gunpowdera!

**Comment by NemanjaRusija2** [comment]
> Htio bi dati prijedlog da se TNT omoguči u smislu da se omoguči da eksplodira ali da ne uništava blockove. Ovo bi doniejlo novu dinamiku u ratove, tipa omogučilo artiljeriju koje ne uništava trud igrača ali knockback i damage može biti korišten kako bi strateški poziciju otežali onima koji brane i dodalo novu dinamiku u izazov za redstone igrače. Uz to TNT je rijeđi na decentralandu jer je teže skupiti velike količine gunpowdera!

Nije loša ideja

**Comment by vukstrale** [comment]
Zapravo gunpowder je prelako naći samo kopaš gravel. Ne svidja mi se iskr

**Comment by Attack36** [comment]
> Zapravo gunpowder je prelako naći samo kopaš gravel. Ne svidja mi se iskr

Mislim da ali ga teško sakupiš u velikim količinama jel ne dropa se često. Za pravi TNT top koji šta vrijedi treba mase i mase TNTa. Uz to pored toga TNT topovi bi idalje imali dobru svrhu na bojištu. Dopustili bi konjici da bude još važnija jer sada moraš taktički napraviti da izoliraš topove da možeš ubiti ljude koje upravljaju njima kako bi zaustavio paljbu. Uz to ne uništava blokove pa nije problem za greif

**Comment by vukstrale** [comment]
Tnt ide bum bum ne možeš to kontrolisati ima da razneseš i svoje i tudje.

**Comment by Attack36** [comment]
> Tnt ide bum bum ne možeš to kontrolisati ima da razneseš i svoje i tudje.

Nije istina, pogledaji barem jedan TNT top tutorijal i vidit ces da mogu biti vrlo precizni. Ako ti ne možeš taktički napraviti da ti topovi ne pucaju na trupe, nemoj ih koristiti. Ti ne pucaš po neprijatelju kad si več ušao u PvP već kada se iz daljine gađate ili na zidine, ili na dijelove gdje je lakše pogoditi neprijatelja a ne svoje. Trebaš znati se koristiti sa njima i to dodaje dodatan skill na hogu koji će zainteresirati igrače!

**Comment by JaSamIgor** [comment]
Bolje da se skroz tnt omogući u ratovima.

**Comment by Attack36** [comment]
> Bolje da se skroz tnt omogući u ratovima. Ustvari ovo je bolje

Ne jer uništavanje ubija trud igrača i dopušta totalni greif svega, ako netko napravi top koji ištrca TNT po tvom gradu sve ti ode. Ovako je samo za PvP svrhe i ne uništava volju za igru.

**Comment by PiweeX** [comment]
ovo za sad nije moguce, jedino da nam osoba koja pravi plugine napravi neku skriptu ili manji plugin za ovo sto ce nam biti trosak ali nek issue ostane svakako jer mozda izdvojimo novac za to

**Comment by PiweeX** [comment]
Rešeno
