### ISSUE TITLE
Px pls dodaj blaze rodove u shop na spawnu sto prije mozes

### ISSUE THREAD

**Issue by T1GAR** [PiweeX/HogRealms#136]
Naslov sve govori

**Comment by GitPurker** [comment]
Dodaj i Dragon breath u shop.

**Comment by PiweeX** [comment]
moramo osmisliti kako ce se dobijati nether stvari

**Comment by GitPurker** [comment]
A dragon breath?

**Comment by PiweeX** [comment]
Mislim da je sad u black shopu dodat

**Comment by PiweeX** [comment]
Blaze rodovi su stvar na koju nam se žali puno igrača, neki imaju a neki ne što stvara to da server nije uramnotežen sa te strane, uskoro će biti dodato u black shop

**Comment by PiweeX** [comment]
Dodati su pre neki dan

međutim preključe su dosmanlije rejdovale laputu i black shop, laputu smo uspeli da rollbackamo ali black market ne..

Svakako igrači su dosta zadovoljni iako je cena bila skupa tako da ćemo na spawn u najkraćem mogućem roku dodati to verovatno kod lidla ili na drugom prikladnom mestu, zatvoriću ovaj issue sad
