### ISSUE TITLE
Napredak servera

### ISSUE THREAD

**Issue by DzingisKan738** [PiweeX/HogRealms#137]
Teže krađe na serveru, landovi na tuđoj teritoriji, dupliciranje itema koje iste prodaje dželat, Srbenda i Gothia se vratili, podjebatori su u svakoj poruci, svaka čast serveru na ovako dobrom napretku. Svakom bi preporučio.

**Comment by spahomir** [comment]
> Teže krađe na serveru, landovi na tuđoj teritoriji, dupliciranje itema koje iste prodaje dželat, Srbenda i Gothia se vratili, podjebatori su u svakoj poruci, svaka čast serveru na ovako dobrom napretku. Svakom bi preporučio.

Priznaj da je bolje bilo sa mnom

**Comment by spahomir** [comment]
> Teže krađe na serveru, landovi na tuđoj teritoriji, dupliciranje itema koje iste prodaje dželat, Srbenda i Gothia se vratili, podjebatori su u svakoj poruci, svaka čast serveru na ovako dobrom napretku. Svakom bi preporučio.

btw druga strana medalje

**Comment by PiweeX** [comment]
evo ga, gringosi su bolji ali sa hoga ne izlazimo i hog ne vadimo iz usta

**Comment by spahomir** [comment]
> evo ga, gringosi su bolji ali sa hoga ne izlazimo i hog ne vadimo iz usta

ništa nije slagao

**Comment by PiweeX** [comment]
evo ga još veći stručnjak

**Comment by spahomir** [comment]
> evo ga još veći stručnjak

da, hvala na komplimentima

**Comment by spahomir** [comment]
![ezgif com-gif-maker (1)](https://user-images.githubusercontent.com/107082292/187046267-17a1899e-e9af-42f5-96e4-126acc291bf9.gif)

**Comment by spahomir** [comment]
moramo priznati da je unikatan server

**Comment by PiweeX** [comment]
> 

do jaja! kako su gringosi samo dobar server matori. svi presli pa tako i ja! Ziveo atlas! ziveli gringosi! ziveo wolf!

**Comment by spahomir** [comment]
> > 
> 
> do jaja! kako su gringosi samo dobar server matori. svi presli pa tako i ja! Ziveo atlas! ziveli gringosi! ziveo wolf!

AMIN

**Comment by PiweeX** [comment]
zene i deca ba

**Comment by vukstrale** [comment]
> Teže krađe na serveru, landovi na tuđoj teritoriji, dupliciranje itema koje iste prodaje dželat, Srbenda i Gothia se vratili, podjebatori su u svakoj poruci, svaka čast serveru na ovako dobrom napretku. Svakom bi preporučio.

Najgore o serveru govori činjenica da još nisi banovan zbog piweeexovih čeličnih živaca. AKO TI SE NE SVIDJA IDI BRATE. Putuj igumane što bi rekao piweeex. Koliko puta si "prešao" na gringose pa eto te opet od jutra igraš! Koliko puta vredjaš server, pa moram pitam, ZAMOLIM Piweeexa da mi dozvoli da te mutam jer KRŠIŠ PRAVILA KOJA SI SAM PISAO. A ti galileo ti si kul brate. Nemam šta da kažem loše o Spahu jbg. Ugledaj se na njega Zlajo, Spaho je dobar čovek.

**Comment by spahomir** [comment]
> > Teže krađe na serveru, landovi na tuđoj teritoriji, dupliciranje itema koje iste prodaje dželat, Srbenda i Gothia se vratili, podjebatori su u svakoj poruci, svaka čast serveru na ovako dobrom napretku. Svakom bi preporučio.
> 
> Najgore o serveru govori činjenica da još nisi banovan zbog piweeexovih čeličnih živaca. AKO TI SE NE SVIDJA IDI BRATE. Putuj igumane što bi rekao piweeex. Koliko puta si "prešao" na gringose pa eto te opet od jutra igraš! Koliko puta vredjaš server, pa moram da pitam, ZAMOLIM Piweeexa da mi dozvoli da te mutam jer KRŠIŠ PRAVILA KOJA SI SAM PISAO. A ti galileo ti si kul brate. Nemam šta da kažem loše o Spahu jbg. Ugledaj se na njega Zlajo, Spaho je dobar čovek.

tako je slava mi!

**Comment by NemanjaRusija2** [comment]
Ja ovdje nisam spomenut tako da neću ni odgovarat. Zlajo kad su već tu može unban sa gringosa igra mi se.

**Comment by NemanjaRusija2** [comment]
Ja ovdje nisam spomenut tako da neću ni odgovar

**Comment by spahomir** [comment]
> Ja ovdje nisam spomenut tako da neću ni odgovarat. Zlajo kad su već tu može unban sa gringosa igra mi se.

i meni brate brutalno je, si vidio kako vojnik roka kokija

**Comment by NemanjaRusija2** [comment]
Neću odgovarati jer nisam spomenut ili da me uvredio. Može li unban sa gringosa zlajo igra mi se

**Comment by spahomir** [comment]
> Neću odgovarati jer nisam spomenut ili da me uvredio. Može li unban sa gringosa zlajo igra mi se

brt nemanja ko ti sipo piće u drogu

**Comment by NemanjaRusija2** [comment]
> > Neću odgovarati jer nisam spomenut ili da me uvredio. Može li unban sa gringosa zlajo igra mi se
> 
> brt nemanja ko ti sipo piće u drogu

Ne znam možda neko

**Comment by NemanjaRusija2** [comment]
Dušmani

**Comment by buducidzelat** [comment]
ziveli gringosi

**Comment by PiweeX** [comment]
Nemojte molim vas da pričate o serveru vi kojima su serveri trajali limit 2 ipo meseca. I vi koji ste od istih tih s kojima ste izdali izdani, pozdrav
