### ISSUE TITLE
Ne aktivne drzave

### ISSUE THREAD

**Issue by GitPurker** [PiweeX/HogRealms#138]
Dodato je da se claim brise posle 50 dana ne atvinnosti, da li to znaci da ce se obrisati ako vlasnik claima nije aktivan 50 dana? Takodje da li moze da se smanji na 30 dana.

**Comment by PiweeX** [comment]
ne vlasnik claima, ako je celokupan claim neaktivan 50 dana, jer ima puno claimova koji su stvoreni tek tako i koji stoje a serveru trebaju kvalitetne drzave zar ne, moguce da ce se i smanjiti na 30 ili 35 ali tek kad krene mainnet

**Comment by GitPurker** [comment]
sta znaci ceo claim, jel to znaci ako se ne prosiruje claim?

**Comment by PiweeX** [comment]
> sta znaci ceo claim, jel to znaci ako se ne prosiruje claim?

ne proširenje, striktno ako nisu aktivni toliko dana da nisu ulazili, plaćali porez državi itd

**Comment by PiweeX** [comment]
reseno
