### ISSUE TITLE
Pokemon Stadium from Smash Bros Ultimate

### ISSUE THREAD

**Issue by PiweeX** [PiweeX/HogRealms#139]
Builder TheFrontView

**Comment by PiweeX** [comment]
There were problems with worldedit this morning, but the build is complete and the client is happy


![2022-09-04_14 42 46](https://user-images.githubusercontent.com/33425430/188317753-43c3a045-b7e3-4763-9b91-59e153c3dd47.png)

**Comment by TheFrontView** [comment]
![2022-09-04_16 23 00](https://user-images.githubusercontent.com/71612070/188318427-de57d919-a5da-4135-b528-fcc141938e4f.png)
![2022-09-04_16 22 10](https://user-images.githubusercontent.com/71612070/188318431-8d36b07e-252f-414b-a8db-8a43fb632d0c.png)
![2022-09-04_16 22 18](https://user-images.githubusercontent.com/71612070/188318432-e40cd3b8-48e2-42d7-be9c-26957fe882b7.png)
![2022-09-04_16 22 31](https://user-images.githubusercontent.com/71612070/188318434-96629c35-f4f9-46f4-a88f-022d8fc3aacf.png)
