### ISSUE TITLE
KOLONIJE

### ISSUE THREAD

**Issue by akipaki293** [PiweeX/HogRealms#16]
U RL Kolonije su bile ključan deo svetskih sila, a neke države i dan danas imaju koloniju. Ako se odobre kolonije, da bude max claim u koloniji 150 chunkova i 1 claim po jednom kontinentu to bi bio bolji rp ipak je rp simulacija stvarnog života

**Comment by JaSamIgor** [comment]
Slažem se za kolonije, neodobravanje kolonija je ograničavanje roleplaya.

**Comment by PiweeX** [comment]
Kolonije nemaju smisla na serveru u kom je dobar % mesta ne popunjeno, vrlo lako bi moglo da se iskorišćava i da jednostavno smeta novim državama, ali svakako jednom će biti dozvoljene zakonom a to će biti sigurno kad krene mainnet i kad na server dođe veći priliv igrača!

**Comment by akipaki293** [comment]
> Kolonije nemaju smisla na serveru u kom je dobar % mesta ne popunjeno, vrlo lako bi moglo da se iskorišćava i da jednostavno smeta novim državama, ali svakako jednom će biti dozvoljene zakonom a to će biti sigurno kad krene mainnet i kad na server dođe veći priliv igrača!

Pa i zabavnije je da imaju kolonije i da se ceo svet claima i onda ce novi morati ici u novu drzavu a ne claimate negde random
