### ISSUE TITLE
UN Bot

### ISSUE THREAD

**Issue by PiweeX** [PiweeX/HogRealms#18]
UN bot se stopira kad neko zatvori tiket

**Comment by PiweeX** [comment]
Probali smo da rešimo problem preko komande za ponovno kreiranje databaze svih membera servera,
 
 nije se uspelo rešiti pa je upravo pokrenuto pravljenje backupa kako bi radovi mogli da se obave

**Comment by dzelat** [comment]
Nemojte otvarati tikete ili koristiti bilo koju od radnji koje vam bot nudi dok se radovi ne završe.
Sve dok ova obavijest stoji u kanalu #⛑│support bot neće raditi

![image](https://user-images.githubusercontent.com/107082292/173067878-779e413a-70b6-497a-a85a-389d9fc47fae.png)

**Comment by PiweeX** [comment]
Otoliko bolje, aaaah tačka zarez povlaka

NOVI RED

**Comment by PiweeX** [comment]
UN bot trenutno radi bez problema.
