### ISSUE TITLE
Oduzeti Zlaji komandu za mute.

### ISSUE THREAD

**Issue by Ratko7** [PiweeX/HogRealms#20]
Pozdrav svim igračima hog realmsa. Kao što ste verovatno svi primetili da zlaja abjuza sve što može i stigne tako i mute komandu. Mislim da je vreme da stanemo protiv toga i da tražimo skidanje te iste komande Zlaji! Ostanimo ujedinjeni.

**Comment by akipaki293** [comment]
jeste da ne volim kad me mute bez razloga ali je ipak admin a kakav je to admin bez mute komande?

**Comment by Ratko7** [comment]
> jeste da ne volim kad me mute bez razloga ali je ipak admin a kakav je to admin bez mute komande?

Ukoliko se admin ne dokaže da pravosudno određuje kazne, on mora biti sankcionisan

**Comment by buducidzelat** [comment]
Predlazem da Cetniku oduzme svako pravo glasa na ovom serveru
Sportski Pozdrav <3 Madjar
![Screenshot_2061](https://user-images.githubusercontent.com/107114906/173540420-04b95bf9-9ac3-4ad2-8b5e-fec7663c6c9d.png)

**Comment by Coplek** [comment]
> Ja bih da se njemu skine admin zato sto bez razloga banuje i u dosije kanalu pise da je banovao nekog lika iz "uzitka".

Ovako tradicija ovog servera je pljuvanje po zlaji a dal se iko zapita tko je zlaja? zlaja je dosao na srw 2020, a planiranje roleplaya je krenulo 2020 zlaja je tu tokom cijelog planiranja te je jedan od planera roleplay-a zlaju ne mozete ukloniti i on dobro radi svoj posao, na serveru nam ne treba kocijaski rijecnik "Jebem ti mamu" "Pusi Kurac" itd na serveru igracu djeca od 11-12 godina i kakav im to uzor daje+ polako krecu dolaziti streameri smatram da zlaja radi posao odlicno jer drzi autoritet sto svaki admin mora zlaji nije problem uci u voice i pricati s vama, ali ne voli toxic ponasanje

**Comment by frop1k** [comment]
Zlaja ne zna da rpa. Kraj priče. Nek izabere da rpa Il da bude admin. U više navrata, iznova i iznova je zloupotrebio položaj koji ima, tako da je za očekivati da će to ponovo uraditi, odnosno da to radi, svaki bogovetni dan.

**Comment by VukIcrnogorskii** [comment]
Čopleče ne budi kontradiktoran
![Uploading Screenshot_20220615-182526_Instagram.jpg…]()

**Comment by Coplek** [comment]
Ja ti kazem sagledaj malo stvari da si ti admin, sto bi napravio? slazem se myb da ne postupa uvijek pravilno, al cekaj malo na drugim serverima ti bi pokupio ban i nebi bilo ove konverzacije  a ti si vuce dobio hag vec ne znam ni ja koliko puta pa si ipak izasao iako si odlezao prije si raidovo bardoniju tko prema fropiku za ocekivati je da ces ponovo to napraviti, a za zlaju dajte konkretne dokaze gdje je abuseao, posaljite screenove, poruke, iteme sto je abuse pa da sagledamo argumentirano raspravljajte

**Comment by VukIcrnogorskii** [comment]
Aj mi prevedi ovaj dio sa fropikom, i to nije abuse nego rp, a drugo ima tona sceva dje zlaja abusa, mislim da smo toga svjesni i ti i ja i cijeli server!

**Comment by Coplek** [comment]
pa posalji

**Comment by VukIcrnogorskii** [comment]
Imas tonu na tvccg i na ccg discord servere
