### ISSUE TITLE
1.19 smp

### ISSUE THREAD

**Issue by PsihoKing** [PiweeX/HogRealms#24]
Ubaciti 1.19 na smp posto je izasao i prosiriti border na 5k i dovuci igrace posto je nova verzija hvala.

**Comment by konfix** [comment]
> Ubaciti 1.19 na smp posto je izasao i prosiriti border na 5k i dovuci igrace posto je nova verzija hvala.

Ne još uvek, beta verzija je izašla tek pre 2-3 dana, treba bar mesec dva dok svi plugini ne budu ažurirani na 1.19

**Comment by PiweeX** [comment]
Dodat je ViaVersion na Velocity

ovo znači da će na Lobby moći da uđu svi od dosta starijih verzija pa do danas, ali to ne znači da će moći da igraju na svakom podserveru na istoj verziji

Recimo SMP možemo da aržuriramo odmah, ali Decentraland podserver će trebati sigurno bar 2 meseca da se prebaci na 1.19 najviše zbog tekstura, zbog tekstura možda i potraje više od toga pa ćemo jednom na silu prebaciti te mnoge teksture neće raditi

ovo je zato što je većina tekstura spajano iz više njih, iz više tekstura, modela i sličnog

**Comment by PiweeX** [comment]
svakako ne radi se o 1.13 verziji kao 2018. u trećoj sezoni SMP podservera kada je ceo koncept igre promenjen i kada smo najveće plugine poput Worldeita čekali neverovatnih 6 meseci a mnogi nikad nisu ni aržurirani od 1.13 ili im je trebalo godinu ipo dana

ovo prebacivanje nebi trebalo da potraje!

**Comment by PiweeX** [comment]
> Dodat je ViaVersion na Velocity
> 
> ovo znači da će na Lobby moći da uđu svi od dosta starijih verzija pa do danas, ali to ne znači da će moći da igraju na svakom podserveru na istoj verziji
> 
> Recimo SMP možemo da aržuriramo odmah, ali Decentraland podserver će trebati sigurno bar 2 meseca da se prebaci na 1.19 najviše zbog tekstura, zbog tekstura možda i potraje više od toga pa ćemo jednom na silu prebaciti te mnoge teksture neće raditi
> 
> ovo je zato što je većina tekstura spajano iz više njih, iz više tekstura, modela i sličnog

od sutra posle jutarnjeg restarta Velocity-a lobby će verovatno biti dostupan i na 1.19 ali i na starijim verzijama 

- [ ] 

- [ ]

**Comment by PiweeX** [comment]
ViaVersion je jutros stvarao probleme te je privremeno uklonjen iz jar fajla

**Comment by PiweeX** [comment]
Ovo će odložiti radove prebacivanja SMP-a do kraja meseca
