### ISSUE TITLE
Prijedlog za Ban - Skleper

### ISSUE THREAD

**Issue by dzelat** [PiweeX/HogRealms#25]
U posljednjih nekoliko dana dobio sam dosta prijava na igrača Sklepera uz te prijave dobio sam dokaze o tome kako je ulazio na server sa VPN-om i sl. Sve navedeno je sam izjavio u chatovima sa igračima. Nekim njegovim prijestupima sam i sam svjedocio i zato mislim da zaslužuje temp ban na 200 dana. 

_Jedan od dokaza je ispod kako se ne biste pričali da lupetamo._

![image](https://user-images.githubusercontent.com/107082292/173873735-37d5c7d2-0538-4f63-a271-643970fd5e9d.png)

**Comment by frop1k** [comment]
Slažem se u potpunosti.

**Comment by dzelat** [comment]
> On voli da sere ali valjda bi nadlezni videli na panelu ip adresu ulaska pa ono proverite tu

Imam još dosta njeogovih chatova ne vjerujem da su sve izmišljotine

**Comment by buducidzelat** [comment]
> > On voli da sere ali valjda bi nadlezni videli na panelu ip adresu ulaska pa ono proverite tu
> 
> Imam još dosta njeogovih chatova ne vjerujem da su sve izmišljotine

al kazem da sve jedno px zlaja ili konfix provere mozda se lik zajebava

**Comment by VukIcrnogorskii** [comment]
Slazem se!

**Comment by dzelat** [comment]
> > > On voli da sere ali valjda bi nadlezni videli na panelu ip adresu ulaska pa ono proverite tu
> > 
> > 
> > Imam još dosta njeogovih chatova ne vjerujem da su sve izmišljotine
> 
> al kazem da sve jedno px zlaja ili konfix provere mozda se lik zajebava

VPN nije jedini okidač za taj ban, na to utiče još mnogo faktora... njegovo ponašanje i sl.

**Comment by buducidzelat** [comment]
> Samo koristenje VPN-A bi trebalo rezultirat ban, a ponasanje je faktor za koji bi se trebao dati hag, tako da je izmjesano

ban na godinu dana resava problem

**Comment by buducidzelat** [comment]
> > Samo koristenje VPN-A bi trebalo rezultirat ban, a ponasanje je faktor za koji bi se trebao dati hag, tako da je izmjesano
> 
> Mi nismo roboti i mislim da ne bismo trebali kaznjavati po nekim pravilima nego onako kako mi mislimo da bi za ovu zajednicu bilo najbolje, po mom mišljenju ban je više nego potreban

mac sa 2 ostrice

**Comment by dzelat** [comment]
Svi mi znamo zasto je ovaj issue otvoren, i zbog cega, molim savjesne igrace da citaju i glasaju, HVALA

**Comment by buducidzelat** [comment]
ne samo ti kazem neka px ili konfix provere na panelu za vpn pa preko toga odlucite vremenski koliko ce igrac biti banovan.
HVALA

**Comment by buducidzelat** [comment]
opet ce se naci neka budala da se buni

**Comment by dzelat** [comment]
Ma neka se bune, prije svega neka se nauce kako stvari ovdje funkcionisu

**Comment by Coplek** [comment]
Na nekom drugom serveru nebi bilo ove diskusije admin bi banovao i .
Nek se bune imaju pravo, ali nek onda daju argumente a ne seljacku bunu

**Comment by R1derPN** [comment]
Ja se ne slazem.

**Comment by dzelat** [comment]
> Ja se ne slazem.

reaguj gore

**Comment by akipaki293** [comment]
Slazem se

**Comment by dzelat** [comment]
> Ja se ne slazem.

imas ove emojie da se izjasnis

**Comment by akipaki293** [comment]
> > Ja se ne slazem.
> 
> imas ove emojie da se izjasnis

Ok

**Comment by ConeBe** [comment]
Ne ali gledajte, Liverpul je izgubio ligu šampiona tako da jebiga

**Comment by dzelat** [comment]
> Ne ali gledajte, Liverpul je izgubio ligu šampiona tako da jebiga

izjasni se emojiem

**Comment by HyperTwo29394** [comment]
Ja se ne slažem jer bilo je gorih ljudi od njega pa eno ih igraju i dan danas...

**Comment by R1derPN** [comment]
takodje se ne slazem za ponasanje ima gorih ljudi na serveru sa ponasanjem i od njih da skleper dobije ban

**Comment by buducidzelat** [comment]
jedan od njih je
ratko

**Comment by tejdja** [comment]
Ne slazem se.

**Comment by dzelat** [comment]
aj ne glupirajte se ovdje

**Comment by KriptoEtnoRomAleksa** [comment]
Ja sam neutralan

**Comment by KriptoEtnoRomAleksa** [comment]
Jesam

**Comment by KriptoEtnoRomAleksa** [comment]
Cekaj ko glasa,ko?

**Comment by ZlajaCelendzGej** [comment]
ja sam ti za za

**Comment by dzelat** [comment]
@buducidzelat  traži bolji dokaz

![image](https://user-images.githubusercontent.com/107082292/173914946-e098244c-d259-4e83-88f1-b397f7b323a4.png)

**Comment by JaSamIgor** [comment]
ako se abjuzeri banuju zašto sklepera preskočiti

**Comment by dzelat** [comment]
> ako se abjuzeri banuju zašto sklepera preskočiti

upravo

**Comment by bogoljub1234** [comment]
Preporučujem ako px treba pomoc oko neceg uvijek smo tu za njega, jos sta nam znaci dzelat ako i onako pomazem drugim igracima

**Comment by ConeBe** [comment]
Bara veče

**Comment by ConeBe** [comment]
Zlaja Izazov

**Comment by bogoljub1234** [comment]
Ne banati sklepera

**Comment by DrogiraniGremlin** [comment]
BANUJ SKLEPERA BOGOLJUBE KO TE JEBE

**Comment by markeccc998** [comment]
B A N

**Comment by markeccc998** [comment]
BEZ RAZMIŠLJANJA

**Comment by bogoljub1234** [comment]
Drogirani ko si ti?


Ne banati skleper

**Comment by buducidzelat** [comment]
bogoljub je 2009to

**Comment by markeccc998** [comment]
bogoljube nemoj srati sta si se napalio ovde si 2 meseca ne znas nista

**Comment by buducidzelat** [comment]
> > bogoljub je 2009to
> 
> 2010

jos gore

**Comment by bogoljub1234** [comment]
I sta onda buraz moj pomogao sam puno ljudi i ne trazim dzelata

Ako ce te banati skleper onda i mene

**Comment by ConeBe** [comment]
Što vam smeta Bogoljubče

**Comment by buducidzelat** [comment]
> ### **[bogoljub1234](/bogoljub1234) ** commented [14 seconds ago](#issuecomment-1156876850)

ok

**Comment by markeccc998** [comment]
> > ### **[bogoljub1234](/bogoljub1234) ** commented [14 seconds ago](#issuecomment-1156876850)
> 
> ok

buducidzelat commented in 1 minute

**Comment by ConeBe** [comment]
A

**Comment by markeccc998** [comment]
> A

hoiyeahhh

**Comment by dzelat** [comment]
> I sta onda buraz moj pomogao sam puno ljudi i ne trazim dzelata
> 
> Ako ce te banati skleper onda i mene

![image](https://user-images.githubusercontent.com/107082292/173917621-fbfd5ace-337c-4390-9773-e9f3d61695fc.png)

**Comment by ConeBe** [comment]
AHAHAHAHHAHAHAHAHA

**Comment by buducidzelat** [comment]
> > I sta onda buraz moj pomogao sam puno ljudi i ne trazim dzelata
> > Ako ce te banati skleper onda i mene
> 
> ![image](https://user-images.githubusercontent.com/107082292/173917621-fbfd5ace-337c-4390-9773-e9f3d61695fc.png)

AHAHAHAHAHAHA

**Comment by bogoljub1234** [comment]
Sta se ti smijes

**Comment by buducidzelat** [comment]
> Sta se ti smijes

izvinite gospodine bogoljube

**Comment by buducidzelat** [comment]
nemoj me tuces samo

**Comment by ConeBe** [comment]
> Sta se ti smijes

Bole dobar čovek

**Comment by bogoljub1234** [comment]
Necu, nisam nasilnik

**Comment by NemanjaRusija** [comment]
Bogoljube smiri se

**Comment by bogoljub1234** [comment]
Smiren sam

**Comment by NemanjaRusija** [comment]
Još bolje

**Comment by NemanjaRusija** [comment]
> I sta onda buraz moj pomogao sam puno ljudi i ne trazim dzelata
> 
> Ako ce te banati skleper onda i mene

Bogoljube ovaj server ima dvije strane jednu lošu i jednu dobru stranu. Ali skleper je uradio to šta je uradio ti sad njega braniš jer misliš da je dobar. Ali život zna da prevari. Tako da Bogoljube nemoj se miješati u ovo.

**Comment by bogoljub1234** [comment]
Kad mi je trebala pomoc on je bio uz mene

**Comment by dzelat** [comment]
Glasanje zavrseno 22:19 je rezultan skleper banovan na 50 dana

**Comment by bogoljub1234** [comment]
Unban skleper

**Comment by dzelat** [comment]
![image](https://user-images.githubusercontent.com/107082292/173929093-d1cb2292-b6de-493a-a774-a8130d9e3ffe.png)

**Comment by DrogiraniGremlin** [comment]
IDE GAAAAS VOZIM CRNI BMW

**Comment by JedemJaja** [comment]
> Glasanje zavrseno 22:19 je rezultat skleper banovan na 50 dana zbog abjuza i krsenja drugih pravila servera!
Samo 50?

**Comment by Lava1-7** [comment]
Iskreno mislim da je 200 dana ban previse, ako mora ban onda na nekih 90-100 dana
