### ISSUE TITLE
Vracanje teritorija Japanu

### ISSUE THREAD

**Issue by buducidzelat** [PiweeX/HogRealms#26]
S obzirom da se TheFrontView oglasio na podelu Japana ne vidim vise razlog zasto bi pojedinci uzimali tu teritoriju lol

**Comment by VukIcrnogorskii** [comment]
Momak je otisao pa se vratio, po tvojoj logici to znači da ja mogu da uzmem opet cijeli "stari" CCG jer sam vratio i negirao nove feudalce te oasti

**Comment by buducidzelat** [comment]
on nigde nije otisao to sto nije bio na diskordu 2 dana ne znaci da je otisao lol

**Comment by VukIcrnogorskii** [comment]
Looool pogledaj bolje druze madjare!

**Comment by buducidzelat** [comment]
Denza je proglasio kako njih dvojica idu iza Frontovih ledja.To je kao da je kazem da ti ja sada napustamo server i to znaci da bilo kod moze doci i claimovati Crnu Goru

**Comment by VukIcrnogorskii** [comment]
Nmg prepametan si ti za ovakve stvari, takvoj bistrini se ne moze objasniti

**Comment by buducidzelat** [comment]
nemas sta da mi objasnjavas
bukvalno bi tako bilo

**Comment by buducidzelat** [comment]
vrati se u misiju rupu

**Comment by VukIcrnogorskii** [comment]
Opak si igrač, baš si me zajebao sad

**Comment by buducidzelat** [comment]
a i to sto Vuk i ostali rade su takodje kolonije sto tehnicki gledano ne bi smeli raditi.Tako da oni nemaju pravo to da pripoje svojim drzavama

**Comment by Coplek** [comment]
Sa tim se slazem nemaju pravo to pripojiti, ali front je bio svjestan kad je denzi davo shoguna zato je vodja drzave uvijek jedan front se sam zajebo

**Comment by buducidzelat** [comment]
ali mislim da oni to nebi smeli da rade zato je issue i otvoren

**Comment by dzelat** [comment]
Ja ovdje samo vidim nepostivanje roleplay-a.

**Comment by dzelat** [comment]
Izmišljanje nekih priča je dosta providno, Front čim je vidio da je Japan podijeljen   rekao da on nikada nije ni otišao. Ovo nije prvi put da radi istu stvar...

**Comment by Coplek** [comment]
buducidzelat mozes, otici i claimati politicka mapa je iskljucena nitko ti ne brani, ali sam sebi kvaris roleplay, mali je problem sto srw nema roleplay pravila kao MG,NONRP, RP2WIN itd ali ok i stavi neke argumente jer ja sam ti naveo argumente dok ti odgovaras jednom recenicom uvijek iznova ponavljas da nije otisao ne mora on otic, ali denzel je predao japan

**Comment by akipaki293** [comment]
Brate ne mozes ti sad kvariti rp koj se desio, desilo se i desili nadji ili napravi novu drzavu i caos

**Comment by VukIcrnogorskii** [comment]
Ja sam pravio sranja i ne poricem to, ali kada sam prvi put raspustio carevinu, i vidio da su odma dosli da claimaju, ja se nijesam vratio i oplakivao kako je to moje

**Comment by Coplek** [comment]
I isto tako kako su oni mogli uzeti claim frontova greska sto claim nije pod njim, nema se tu sta vracat ako je njegov claim on moze radit sta hoce, ako preda nekome claim snosi odgovornost a vuk njegovim sranjima nema premca on je zasro sta je stigao al je opet podigao ccg iznova

**Comment by buducidzelat** [comment]
> I isto tako kako su oni mogli uzeti claim frontova greska sto claim nije pod njim, nema se tu sta vracat ako je njegov claim on moze radit sta hoce, ako preda nekome claim snosi odgovornost a vuk njegovim sranjima nema premca on je zasro sta je stigao al je opet podigao ccg iznova

ne menja cinjenicu za kolonije.I Zlaja koji je jedan od glavnih na hogu se slozio sa tim da oni jednostavno ne mogu claimovati Japan kao koloniju.Moraju je ostaviti ili novim igracima ili da se ovi vrate na tu teritoriju.

**Comment by VukIcrnogorskii** [comment]
Opet ti aludiram da bolje procitas prvo zlajinu, pa onda moju poruku!

**Comment by buducidzelat** [comment]
ta tvoja poruka ne menja nista Zlaja je to izjavio

**Comment by VukIcrnogorskii** [comment]
E vidis to bi bio abuse, jer je ovo nase sve u skladu sa pravilima!

**Comment by buducidzelat** [comment]
u skladu sa pravilima su kolonije?

**Comment by VukIcrnogorskii** [comment]
Ne citas poruke! Procitaj moju poruku ja ti opet kazem

**Comment by buducidzelat** [comment]
-tražim da sve države koje nisu vezane za matičnu državu budu sklonjene ili reformirane u feudalni posjed (Baza koja ne pripada ni jednoj državi, već individualnom igraču te nije ucrtana u političku mapu, primjer takvog postojećeg posjeda je claim Zlatna Horda u Mongoliji)
-tražim da članovi država koji imaju vlast imaju zabranu obavljanja administrativnih dužnosti u drugim državama. Primjer Nemanja Rusija ne može upravljat gradom u Japanu jer je u Engleskoj jedan od vođa

**Comment by Coplek** [comment]
Kolonije su zabranjene te im treba maknut kolonije, ali teritoriju vratiti frontu se ne moze i ne treba

**Comment by buducidzelat** [comment]
> Kolonije su zabranjene te im treba maknut kolonije, ali teritoriju vratiti frontu se ne moze i ne treba

evo sada kazem nek im se sklone uzecu ja japan kao njegov naslednik

KRAJ

**Comment by VukIcrnogorskii** [comment]
Ja ponavljam nas posjed nije kolonija!

**Comment by ConeBe** [comment]
I Real Madrid je rekao kraj Liverpulu

**Comment by VukIcrnogorskii** [comment]
Trebam li da aplaudiram?

**Comment by VukIcrnogorskii** [comment]
Ja sam car a ne ti

**Comment by ConeBe** [comment]
Možemo vuče ako želiš

**Comment by ConeBe** [comment]
xd

**Comment by buducidzelat** [comment]
ti si retard ne car

**Comment by ConeBe** [comment]
Rekao su mi

**Comment by ConeBe** [comment]
Volite li više burek sa mesom ili sirnicu

**Comment by VukIcrnogorskii** [comment]
MESO FOR LIFE!

**Comment by ConeBe** [comment]
MOJ ČOVEK.

**Comment by frop1k** [comment]
Misliš burek sa sirom

**Comment by vukstrale** [comment]
Sve je moje. Ja i Skleper smo Šoguni. Ako neko ima nešto protiv, neka viče. Mislim piše.

**Comment by ConeBe** [comment]
Izvini Šogunu

**Comment by VukIcrnogorskii** [comment]
Nijesmo ga prepoznali

**Comment by ConeBe** [comment]
Šo gusan

**Comment by ConeBe** [comment]
Guzan pardon

**Comment by vukstrale** [comment]
Puna titula je Antartički Imperator Šogun Khanov Unuk Princ Ruskog Carstva Zakoniti Prestolonaslednik Gondara mamoje... Vuk Veliki

**Comment by frop1k** [comment]
> Sve je moje. Ja i Skleper smo Šoguni. Ako neko ima nešto protiv, neka viče. Mislim piše.

Kakav ti, ti si sirotinja teška.

**Comment by vukstrale** [comment]
Ne, sami smo otišli, pa onda napravili državni udar. Pročitaj wiki nekad

**Comment by ConeBe** [comment]
Princ Ruskog Carstva
Hohoho no.

**Comment by VukIcrnogorskii** [comment]
On je serdar crnogorski, veca titula nego sve te tvoje nagomilane i izmisljene zajedno!

**Comment by vukstrale** [comment]
> > Ne, sami smo otišli, pa onda napravili državni udar. Pročitaj wiki nekad
> 
> otisli ili vas je denzel izbacio?

Denzel nije ni znao da smo otišli dok mu nisam rekao

**Comment by buducidzelat** [comment]
> > > Ne, sami smo otišli, pa onda napravili državni udar. Pročitaj wiki nekad
> > 
> > 
> > otisli ili vas je denzel izbacio?
> 
> Denzel nije ni znao da smo otišli dok mu nisam rekao

po njegovim poruka se cini da je on vas oterao

**Comment by vukstrale** [comment]
> On je serdar crnogorski, veca titula nego sve te tvoje nagomilane i izmisljene zajedno!
kul

**Comment by ConeBe** [comment]
Princ Ruskog Carstva nije, sin Lizarda jeste i dalje, koliko se ja pouzdano razumem, prestao si biti princ od kad si napustio antartičku imperiju i otišao u šogun ili šta si već uradio

**Comment by buducidzelat** [comment]
> > > > > Ne, sami smo otišli, pa onda napravili državni udar. Pročitaj wiki nekad
> > > > 
> > > > 
> > > > otisli ili vas je denzel izbacio?
> > > 
> > > 
> > > Denzel nije ni znao da smo otišli dok mu nisam rekao
> > 
> > 
> > po njegovim poruka se cini da je on vas oterao
> 
> I?

n

> > ali ako je tako prepustam claimanje japana vama dvojici
> 
> već jesam lol

e sad daj trust i gotovo

**Comment by vukstrale** [comment]
> > > > > > Ne, sami smo otišli, pa onda napravili državni udar. Pročitaj wiki nekad
> > > > > 
> > > > > 
> > > > > otisli ili vas je denzel izbacio?
> > > > 
> > > > 
> > > > Denzel nije ni znao da smo otišli dok mu nisam rekao
> > > 
> > > 
> > > po njegovim poruka se cini da je on vas oterao
> > 
> > 
> > I?
> 
> n
> 
> > > ali ako je tako prepustam claimanje japana vama dvojici
> > 
> > 
> > već jesam lol
> 
> e sad daj trust i gotovo

ko si ti?

**Comment by buducidzelat** [comment]
ja sam cuveni

**Comment by buducidzelat** [comment]
najcuveniji

**Comment by ConeBe** [comment]
Princ nisi kod nas, to znam sigurno, tako da ove druge titule što imaš to se ja ne razumem

**Comment by buducidzelat** [comment]
owner traktorsmpa

**Comment by vukstrale** [comment]
Dobro cone napisao sam iz swaga malo efekat dramatični oladi

**Comment by ConeBe** [comment]
Fan Liverpula

**Comment by vukstrale** [comment]
> owner traktorsmpa

dobićeš trust kad ja dobijem trust u Samarkand

**Comment by ConeBe** [comment]
U redu vukstrale.

**Comment by vukstrale** [comment]
> Deste

oooooo

**Comment by ConeBe** [comment]
Pomaže Bog Nemanja

**Comment by vukstrale** [comment]
> U redu vukstrale.

Ovo mi acc od pre hrista boga ima 4 godine

**Comment by NemanjaRusija** [comment]
Bog vam pomogao

**Comment by NemanjaRusija** [comment]
Šta reći kupio amazon prime ne znam zašto ahahha

**Comment by buducidzelat** [comment]
> > > > owner traktorsmpa
> > > 
> > > 
> > > dobićeš trust kad ja dobijem trust u Samarkand
> > 
> > 
> > mislim da se skeeleper nece sloziti sa tim
> 
> Oš se kladimo?

u perma ded

**Comment by ConeBe** [comment]
Bolje preći na discord, ovo je više sajt za rasprave i saglasnost

**Comment by vukstrale** [comment]
Slažem se cone, mare, ajmo da nastavimo u #vip
