### ISSUE TITLE
DZELATI

### ISSUE THREAD

**Issue by akipaki293** [PiweeX/HogRealms#27]
> Da se napravi neki rp za dželate, npr negde naprave kao policijsku postaju i tu dolaze ljudi da prijave i kad ih upute sta gde oni otvore ticket na un npr: Aki: Zdravo, gde mogu da prijavim slučaj? Spaho: Dobar dan, Vaš slučaj prijavljujete na Vašem telefonu, uđete na aplikaciju discord i onda nađete server Ujedinjene Nacije i prijavite Vaš slučaj i u roku od par dana slučaj će biti pregledan. Aki: Hvala. To bi mnogo mnogo poboljšalo RP.

> Nalaženje novih dželata. da nove dželate tražite po tome da su odgovorni, imaju mikrofone, znaju da budu ozbiljni, ali da znaju i da se zabavljaju, da ne budu ljudi sa već postojećim dosijeom... I kada nađete osobu u dželatskoj postavi (un) glasaju svi delovi policije (staffa) i da ako bude izjednačeno da vođa organizacije (PX) glasa za svoje ili odluči.

> Kažnjavanje ljudi. Da se napišu sve kazne koje postoje da dželati nebi kažnjavali sve kako hoće nego da imaju neka pravila za koje se mora i sam vođa pridržavati.

> Zakonik. Znam da je Spaho na aplikaciji (discordu) počeo pisati zakonik u pomoć ljudi iz policije, ali trebalo bi da se otvori u policijskoj stanici mesto gde će ljudi predlagali zakone (issues), a svaki prekršen zakon da se kažnjava kaznama koje su posle njega napisane.

> Prijave. Da prijave ljudi gledaju drugi ljudi (support) i oni posle to prijave inspektorima (dželatima)  i inspektori (dželati) to istražuju.

> Imena. Da se imena uloga promeni npr supporter -> Policajac (njegova uloga da gleda tickete i prijavljuje dželatima) dželat -> inspektor, admini -> Vođa IP-a (Inspektora/Policajaca), Vođa (PX) -> Načelnik

> Ustavi. U zakonik koji se i ako se bude završio da se doda da ustavi država budu obavezni i da bude razraćena kazna ko to nema, i da Inspektori poštuju zabranjene stvari ustavom u državi.

(Ovo je sve moj predlog, i moje mišljenje, ne mora da se ustavi ali bi pomoglo rpu. Mole se ljudi da ne komentiraju gluposti na ovaj issues samo ako imaju predlog i dželati/admini oko ovoga što sam napisao)

**Comment by Coplek** [comment]
Ovo tu oko policije je bespotrebno a zakon o kaznjavanju se pise

**Comment by akipaki293** [comment]
> Ovo tu oko policije je bespotrebno a zakon o kaznjavanju se pise

Jeste bespotrebno ali bolje je za rp a ovo je RP a ne neki tamo obican mc srw

**Comment by Coplek** [comment]
zato i jesu dzelati dzelat je onaj koji izvrsava smrtne kazne
