### ISSUE TITLE
Spahu skinuti đelata;)

### ISSUE THREAD

**Issue by Skleper5** [PiweeX/HogRealms#28]
Spaho je tako dobar đelat da je ljudima kao što sam ja Hypertwo i još par njih nije hteo role back Iteme koji su ukradeni.Npr Hypertwo su ukradeni 7 Beacona on mu je vratio 3 a ostala 4 je rekao da ne može , dok Srbendi ili nekima poznatiji kao Thunder vraćao po par double chestova svaki put kad mu nestane po nešto plus ga slepo brani i ako svi znamo da je Srbenda ubacivao deci xray i hakove na kompove i davao im krampove da kopaju nerherite za njega i kad se sazna da su ratkove stvari Ratko ne najebe još mu se vrati pikeks i da mu se sav Netherite koji su ovi Kopali.
![Screenshot_20220517-074947](https://user-images.githubusercontent.com/107573030/173888856-08328bfb-49a4-406f-97e2-bad1671df40c.png)

**Comment by akipaki293** [comment]
ni meni gala nije vratio 200k nego 150k i ne bunim se jer znam da se ne moze videti preko komanda i konzole kolko je stvarno nestalo claimova, ili jer je bio bug ili jer je bilo davno

**Comment by Coplek** [comment]
Umm jel ti kontas ako bi rollbackao iteme da bi to bilo dupliranje itema taj koji je uzeo iteme mora ih i vratiti

**Comment by dzelat** [comment]
Eh da, ono sto je ukradeno hopperima smije se vratiti ukoliko nisi upoznat s necim ne bi trebao komentarisati. Isto tako nemoj brate slati nudes u dm nemo si gej

**Comment by dzelat** [comment]
Dalje ratku je oduzet sav netherite koji je imao, a Gothii je licno piwex vratio pick

**Comment by dzelat** [comment]
Za beacone je istina vratio sam 3 beacona hyperubjer lik nije bio aktivan, zao mi je kad nekome nestanu vrijedne stvari to nisam uradio jer mi je hyper platio, mogao sam samo reci ako dodje nek vrati i otici, da na kraju opet sam najgori pucate kao i na zlaju jadno i to mnogo, ja ne bih ulazio u nesto bez dokaza. Dodjes ovdje i gubiš se iskreno.... sto jos da ti kazem od sad ne vracam nikom ni dirt

**Comment by ratkomraleu** [comment]
> Spaho je tako dobar đelat da je ljudima kao što sam ja Hypertwo i još par njih nije hteo role back Iteme koji su ukradeni.Npr Hypertwo su ukradeni 7 Beacona on mu je vratio 3 a ostala 4 je rekao da ne može , dok Srbendi ili nekima poznatiji kao Thunder vraćao po par double chestova svaki put kad mu nestane po nešto plus ga slepo brani i ako svi znamo da je Srbenda ubacivao deci xray i hakove na kompove i davao im krampove da kopaju nerherite za njega i kad se sazna da su ratkove stvari Ratko ne najebe još mu se vrati pikeks i da mu se sav Netherite koji su ovi Kopali. ![Screenshot_20220517-074947](https://user-images.githubusercontent.com/107573030/173888856-08328bfb-49a4-406f-97e2-bad1671df40c.png)

Bukvalno ako ne znas o cemu pricas nemoj pricati, Za to je pre rollbackovanja obavesten px i on je dozvolio rollback

**Comment by dzelat** [comment]
Jos da dodam da nije đelat no je dželat

**Comment by ConeBe** [comment]
Ajde bre ljudi idemo na neko janje, imam kod Mileta koljača sine hrskavo janje, dušu dalo

**Comment by markeccc998** [comment]
> Ajde bre ljudi idemo na neko janje, imam kod Mileta koljača sine hrskavo janje, dušu dalo

Može

**Comment by KriptoEtnoRomAleksa** [comment]
Brate Galileo dogovori se sa pxom i sa zlajom
