### ISSUE TITLE
Stanje Servera, predlog za dalje. 

### ISSUE THREAD

**Issue by DzingisKan** [PiweeX/HogRealms#29]
U zadnjih nekoliko dana dešava se potpuni raspad sistema među igračima i državama na Hogu.
Želim ukratko obuhvatiti sve temeljne podjele i dati predlog. 

Dželati - ni jedan Dželat kojeg imamo nema čist dosije. Galileo pa i Djovani svi imaju nekog doticaja s kriminalom. Zbog tog razloga bolje je bilo kada je postojao Vrhovni sud gdje je PiweeeX i gdje sam ja mogao apelirati na način pomaganja drugima. Dželati nebi trebali cijeli sistem prijava nositi na sebi. 

Piweeex ne želi da admini budu sustav koji kažnjava iz razloga što onda ljudi prosto seru po adminima. Međutim tako smo živjeli do sada i anketa od sinoć pokazala je da su ti koji laju najčešće ti koji su krivi. NEK SE VRATI SUD U UN I PODJELA NA VRHOVNI I KRIVIČNI SUD.

Igrači kao što su Skleper, Spaho, Ratko, Gothia, Denzavkk, Wolf, koje se asocira s kriminalom do te mjere kada se njihovo ime spomene uvek netko postavi pitanje "al oni nisu banani", njih treba gledati individualno. Postavite sebi pitanje 1. Kome štete? 2. Pridonose li zajednici? 3. Mogu li takvu osobu staviti za Dželata i zašto ne? 

Hog je jedini server koji je otišao ovoliko daleko po pitanju opraštanja. Sa Rebirtha i Gringosa perma banalo bi me nakon druge greške. POTREBNO JE UVESTI PERMA BAN I PRIDRŽAVATI GA SE. Neki igrači jednostavno ne pripadaju na Realms.

Obiđite servere država i HogRealmsove kanale. Primjetit cete kako su kanali svugdje ispunjeni uvredama, ucjenama, kategorizacije i zavjera. Moj predlog je da se uvede bot koji brise poruke s kljucnim rečima. Te reči bile bi psovke i neki toksični epiteti. Tako da osoba može nakon dugog dana sjest za računalo i uživat u igri.

1 land 1 Država.
Vjerovali ili ne ograničenje jednog landa bilo je uvedeno kako bi se ograničilo osobe da budu u više država. To se nije pokazalo praktično jer su neke države imale više claimova. Moj predlog je da osoba po roleplayu može biti samo u jednoj državi. Ako želi zaposjesti teritorij druge države potrebno je da su ta dva teritorija susjedna, a ne jedan u npr SAD a drugi u S. Europi. Drugi tip baze je feudalni posjed koji pripada individualnoj osobi i ne ucrtava se u politicku kartu vec je claim njegova granica i ne smije služiti kao roleplay destinacija za neku državu. 

Za jednak i pravedan server, ZSS - Zlajina Seljačka Stranka!

**Comment by vukstrale** [comment]
Fuj, volim krimose da mi govore šta da radim, i  Akija čija se država proteže na svim kontinentima, i igrači koji kupuju unban, a najviše od svega volim ZSS! Heil Džingis!

**Comment by vukstrale** [comment]
> a ja nisam dzelat mene se ne spominje :( plaky

Nemaš kriminalni dosije Hhahahahahhahahaha ne mogu ozbiljno to reći lollll xD

**Comment by dzelat** [comment]
jedini moj kriminal je sto sam tebi rekao da nesto radim iz provokacijenemoj mene tako daleko gurat

**Comment by Coplek** [comment]
> Nemaš kriminalni dosije Hhahahahahhahahaha ne mogu ozbiljno to reći lollll xD

Imam u beti sam ukrao spahi 3 krumpira

**Comment by vukstrale** [comment]
> jedini moj kriminal je sto sam tebi rekao da nesto radim iz provokacijenemoj mene tako daleko gurat

ja to nogom

**Comment by vukstrale** [comment]
> > Nemaš kriminalni dosije Hhahahahahhahahaha ne mogu ozbiljno to reći lollll xD
> 
> Imam u beti sam ukrao spahi 3 krumpira

I OVO NAM JE DŽELAT

**Comment by ConeBe** [comment]
Pita sa višnjama

**Comment by buducidzelat** [comment]
ja imam dosije mogu ja dzelata?

**Comment by ConeBe** [comment]
Hvala na srcu markec i ja tebe volim

**Comment by vukstrale** [comment]
no


> Cone za dželata šta reći

**Comment by bogoljub1234** [comment]
Bogoljub za dzelata dobar covjek pomazem

Ali glub

**Comment by vukstrale** [comment]
> Cone za dželata šta reći

Zapravo ajde, otvori issue. Glasamo za svi

**Comment by buducidzelat** [comment]
> Cone za dželata šta reći

ja sam bolji

**Comment by ConeBe** [comment]
Jebi ga nije lako igrati 2-3 meseca i odma imati full Netherite Vuče

**Comment by bogoljub1234** [comment]
Ja

**Comment by Coplek** [comment]
Zlajin prijedlog mi se svidja ali je mac sa dvije ostrice

**Comment by ConeBe** [comment]
Šta je Zlaja reka

**Comment by markeccc998** [comment]
Cono za želata

**Comment by vukstrale** [comment]
> Jebi ga nije lako igrati 2-3 meseca i odma imati full Netherite Vuče

i dve katane, vlašku knjigu, borbenu sekiru, imam dva seta nemoj me vredjati, dobro sad nemam imao sam pre. Oh da i imam trust u Samarkand

**Comment by ConeBe** [comment]
Igram pola godine Bože moj

**Comment by bogoljub1234** [comment]
Igor za dzelata

**Comment by vukstrale** [comment]
> Igram pola godine Bože moj

That's kinda cringe innit bruv?

**Comment by dzelat** [comment]
![image](https://user-images.githubusercontent.com/107082292/173910299-0a94099c-6bd5-44af-9c2a-096d31c3bb0d.png)

**Comment by ConeBe** [comment]
Brat na razgovoru gde svi pišemo srpsko-hrvatski dođe piše mi tu na engleskom

**Comment by Coplek** [comment]
Realno dzelati su oni koji su doprinjeli serveru, dugo na serveru i u koje px ima povjerenje

**Comment by vukstrale** [comment]
> ![image](https://user-images.githubusercontent.com/107082292/173910299-0a94099c-6bd5-44af-9c2a-096d31c3bb0d.png)

wtf

**Comment by ConeBe** [comment]
To ti kažem Čopleče

**Comment by dzelat** [comment]
> Realno dzelati su oni koji su doprinjeli serveru, dugo na serveru i u koje px ima povjerenje

covjek me stavio u istu recenicu s ovom grupom 
voli lupit ko niko

**Comment by ConeBe** [comment]
Ma Zlajica moj tatica

**Comment by buducidzelat** [comment]
> Realno dzelati su oni koji su doprinjeli serveru, dugo na serveru i u koje px ima povjerenje

hmm

**Comment by markeccc998** [comment]
A maćkice

**Comment by JaSamIgor** [comment]
> ![image](https://user-images.githubusercontent.com/107082292/173910299-0a94099c-6bd5-44af-9c2a-096d31c3bb0d.png)

prijavio si Carigrad za glupost i meni si rekao da se zbog žaljenja na gluposti stavlja u hag tako da ne vidim problem

**Comment by Ratko7** [comment]
Vi ako izglasate za ovo da je on u vrhu vlasti na hogu, vi potpisujete smrt vaše države i roleplaya zato što zlaja će to iskoristiti i svi će biti u državi mongoliji

**Comment by markeccc998** [comment]
![IMG _20220612-225222_Chrome](https://user-images.githubusercontent.com/107552341/173912031-c56e6471-d9e1-487c-a759-dcc5bb3f5af8.jpg)
Kruh👍

**Comment by vukstrale** [comment]
![image](https://user-images.githubusercontent.com/77744362/173912427-c1e44d1a-3dd1-432c-b5e7-74a5dd6efbff.png)

lebac

**Comment by buducidzelat** [comment]
> Vi ako izglasate za ovo da je on u vrhu vlasti na hogu, vi potpisujete smrt vaše države i roleplaya zato što zlaja će to iskoristiti i svi će biti u državi mongoliji

ratko uvalice ti mare glatko

**Comment by buducidzelat** [comment]
> > > Realno dzelati su oni koji su doprinjeli serveru, dugo na serveru i u koje px ima povjerenje
> > 
> > 
> > hmm
> 
> pod dugo na serveru mislim od rp alphe ili od 2019 kao npr zlaja, spaho, djovani, ja

od 2019 sam tu xd

**Comment by ConeBe** [comment]
Vidimo da ti treba Dželat mare, mnogo se nešto ti tu ulizuješ

**Comment by buducidzelat** [comment]
> Vidimo da ti treba Dželat mare, mnogo se nešto ti tu ulizuješ

bas jako

**Comment by buducidzelat** [comment]
inace zlajo os ti ispusim za dzelata?

**Comment by ConeBe** [comment]
Pa mora, Liverpul on the top

**Comment by bogoljub1234** [comment]
Dovoljna su 3dzelata i px zna ko nije toxic i  ko. pomaze novim igracima

**Comment by buducidzelat** [comment]
> 

i ja number 4 taman

**Comment by bogoljub1234** [comment]
Zlaja je 4

**Comment by ConeBe** [comment]
Piwexu da toliko treba dželat, on bi pozvao nekog odavno

**Comment by ConeBe** [comment]
Dželat ne menja nikakav stil igranja bruh

**Comment by buducidzelat** [comment]
> ConeBe

no ja se zajebavam ovde nemoj da me shvatas ozbiljno

**Comment by JaSamIgor** [comment]
> U zadnjih nekoliko dana dešava se potpuni raspad sistema među igračima i državama na Hogu. Želim ukratko obuhvatiti sve temeljne podjele i dati predlog.
> 
> Dželati - ni jedan Dželat kojeg imamo nema čist dosije. Galileo pa i Djovani svi imaju nekog doticaja s kriminalom. Zbog tog razloga bolje je bilo kada je postojao Vrhovni sud gdje je PiweeeX i gdje sam ja mogao apelirati na način pomaganja drugima. Dželati nebi trebali cijeli sistem prijava nositi na sebi.
> 
> Piweeex ne želi da admini budu sustav koji kažnjava iz razloga što onda ljudi prosto seru po adminima. Međutim tako smo živjeli do sada i anketa od sinoć pokazala je da su ti koji laju najčešće ti koji su krivi. NEK SE VRATI SUD U UN I PODJELA NA VRHOVNI I KRIVIČNI SUD.
> 
> Igrači kao što su Skleper, Spaho, Ratko, Gothia, Denzavkk, Wolf, koje se asocira s kriminalom do te mjere kada se njihovo ime spomene uvek netko postavi pitanje "al oni nisu banani", njih treba gledati individualno. Postavite sebi pitanje 1. Kome štete? 2. Pridonose li zajednici? 3. Mogu li takvu osobu staviti za Dželata i zašto ne?
> 
> Hog je jedini server koji je otišao ovoliko daleko po pitanju opraštanja. Sa Rebirtha i Gringosa perma banalo bi me nakon druge greške. POTREBNO JE UVESTI PERMA BAN I PRIDRŽAVATI GA SE. Neki igrači jednostavno ne pripadaju na Realms.
> 
> Obiđite servere država i HogRealmsove kanale. Primjetit cete kako su kanali svugdje ispunjeni uvredama, ucjenama, kategorizacije i zavjera. Moj predlog je da se uvede bot koji brise poruke s kljucnim rečima. Te reči bile bi psovke i neki toksični epiteti. Tako da osoba može nakon dugog dana sjest za računalo i uživat u igri.
> 
> 1 land 1 Država. Vjerovali ili ne ograničenje jednog landa bilo je uvedeno kako bi se ograničilo osobe da budu u više država. To se nije pokazalo praktično jer su neke države imale više claimova. Moj predlog je da osoba po roleplayu može biti samo u jednoj državi. Ako želi zaposjesti teritorij druge države potrebno je da su ta dva teritorija susjedna, a ne jedan u npr SAD a drugi u S. Europi. Drugi tip baze je feudalni posjed koji pripada individualnoj osobi i ne ucrtava se u politicku kartu vec je claim njegova granica i ne smije služiti kao roleplay destinacija za neku državu.
> 
> Za jednak i pravedan server, ZSS - Zlajina Seljačka Stranka!

 1 land 1 država = propast

**Comment by DzingisKan** [comment]
> jedini moj kriminal je sto sam tebi rekao da nesto radim iz provokacijenemoj mene tako daleko gurat

Poštovani, vi ste spomenuti zbog afere s srbendinim abjuzanim stvarima za koje je potvrđeno da ste znali. Također je danas u toku dana još jedan od igrača stvorio issue prozivajući vas. U mojoj objavi nije rečeno da tražimo sankcije za vas, već da se na vaš slučaj gleda individualno.

**Comment by buducidzelat** [comment]
sad ga smenjuj

**Comment by DzingisKan** [comment]
> Zlajin prijedlog mi se svidja ali je mac sa dvije ostrice

Kako to mislite?

**Comment by DzingisKan** [comment]
> Realno dzelati su oni koji su doprinjeli serveru, dugo na serveru i u koje px ima povjerenje

Postovani, u vašu izjavu nema sumnje. Sama ideja Dželata stigla je kad Vrhovni sud nije imao vremena pa je krivični sud riješio svih 40+ problema. Problem je što se sada vidi i potreba za višim sudom. Jer Dželati riješavaju probleme, ali ne donose zakon i odluke kao što smo tada uvodili kako bi održali mir.

**Comment by VukIcrnogorskii** [comment]
Da oprostis posto mene stalno pljujes i nije ni cudo da nekad neko pita zar nijesam banovan, sta se pita kad tebe neko spominje a?

**Comment by VukIcrnogorskii** [comment]
Trebam li da nabrajam pa da se uporedi nasa i tvoja toksicnost

**Comment by VukIcrnogorskii** [comment]
Djeliminicno se slazem sa tim, ali moramo svi da svatimo da je ovo rp i da su takve stvari normalne na ovakvim serverima, a ne toksicne

**Comment by buducidzelat** [comment]
zasto si onda bio u savezu sa rimom ako smo tako losi?

**Comment by VukIcrnogorskii** [comment]
Zato sto cast crnogorska tako nalaze, i mi nikad ne bi smo izdali prijatelja kao sto to radis ti i novi tvoj gang! Odrzavao si se na Apenine samo zbog mene, jer su se Imperiuma plasili!

**Comment by PiweeX** [comment]
Dželati su samo viši vid igrača, tačnije oni igrači koji izvršavaju naredbe po tome kako je zajednica izglasala ili po zdravom razumu ukoliko dođe do raida, prijave ili sličnog.

Ne vidim ništa sporno da su dželati ranije imali kriminalnu prošlost, ja gledam šta je pozitivno u ljudima i šta trenutno dobro rade, gledam da se ne vraćam i da ne baziram svoje mišljenje o njima na osnovu toga šta su rekli ili šta su uradili pre u nekoj situaciji.

Što se tiče galilea, on tu definitivno najbolje radi ovaj posao, Čoplek i Djovani su od nedavno dželati kako nebi bilo da je samo on i jer mu realno treba pomoć kako server raste pred mainnet

Što se tiče Čopleka pokazao je svoje diplomatske sposobnosti kad je uspeo da pozove Sky posle toliko naših pokušaja, to je velika stvar a pored toga i dosta toga je radio za community, od toga da je lepio Hog Decentraland flajere po svom gradu do mnogih drugih stvari

Djovani radi i modele, takođe vrhunski, za sad se nije toliko izkazao kao dželat ili makar nisam primetio ali svakako sam srećan što imamo te tri osobe na serveru


kao što rekoh, ne možemo naći idealne ljude, možemo najbolje moguće a oni su najbolji

**Comment by PiweeX** [comment]
Što se tiče perma banova, već sam pisao o tome ali to jednostavno ništa ne rešava, kod ovakvog tipa otvorenog servera svud je isto, banujete IP igrača zauvek, upali VPN, napravi novi acc na TLauncheru free i uđe jer server nije samo premium već svako može ući sa bilo kog nicka

inati se i pravi zijane po serveru, jer što nebi. Ovo da banujemo po 150 dana je idealna stvar, olade se i nauče, ukoliko se opet ponovi nema veze, ban na 250d i da vidimo ko je uporniji

ja ovo govorim iz iskustva i jednostavno ovo je realna situacija

**Comment by akipaki293** [comment]
> Fuj, volim krimose da mi govore šta da radim, i Akija čija se država proteže na svim kontinentima, i igrači koji kupuju unban, a najviše od svega volim ZSS! Heil Džingis!

Ne pruza se svuda samo po ostrvima okeanije i azije :)

**Comment by Vedran069** [comment]
Ja verujem da se treba maknuti Zlaja ili malo da prekine da smara.

Živelo Rimsko Carstvo

**Comment by buducidzelat** [comment]
> Ja verujem da se treba maknuti Zlaja ili malo da prekine da smara.
> 
> Živelo Rimsko Carstvo

hvala na podrzavanju moje stare drzave ali ne mogu se sloziti sa ovim drugim

**Comment by Vedran069** [comment]
> > Ja verujem da se treba maknuti Zlaja ili malo da prekine da smara.
> > Živelo Rimsko Carstvo
> 
> hvala na podrzavanju moje stare drzave ali ne mogu se sloziti sa ovim drugim

Rimsko carstvo je moja nova zemlja ne vidim u čemu je problem

**Comment by DzingisKan** [comment]
> Što se tiče perma banova, već sam pisao o tome ali to jednostavno ništa ne rešava, kod ovakvog tipa otvorenog servera svud je isto, banujete IP igrača zauvek, upali VPN, napravi novi acc na TLauncheru free i uđe jer server nije samo premium već svako može ući sa bilo kog nicka
> 
> inati se i pravi zijane po serveru, jer što nebi. Ovo da banujemo po 150 dana je idealna stvar, olade se i nauče, ukoliko se opet ponovi nema veze, ban na 250d i da vidimo ko je uporniji
> 
> ja ovo govorim iz iskustva i jednostavno ovo je realna situacija

poštovani, iz iskustva vidim kako nakon tih 150 dana, kada ponovo pokušamo dati hag ili ban odjednom nemamo privilegiju za to već nas se redirektira na Dželate i ulazi se u proces da dižemo cijeli server na noge nebi li banovali toksične igrače i abjuzere. Uvedemo li natrag Vrhovni sud puno lakše ćemo se nositi s abjuzerima. Čak ako nije perma ban biti ćemo u stanju hagovati ih, ovako gubimo vreme a i oduzima nam se konzola kad želimo djelovat.

ZSS - Zlajina Seljačka Stranka. Za ravnopravan server!

**Comment by akipaki293** [comment]
> > Što se tiče perma banova, već sam pisao o tome ali to jednostavno ništa ne rešava, kod ovakvog tipa otvorenog servera svud je isto, banujete IP igrača zauvek, upali VPN, napravi novi acc na TLauncheru free i uđe jer server nije samo premium već svako može ući sa bilo kog nicka
> > inati se i pravi zijane po serveru, jer što nebi. Ovo da banujemo po 150 dana je idealna stvar, olade se i nauče, ukoliko se opet ponovi nema veze, ban na 250d i da vidimo ko je uporniji
> > ja ovo govorim iz iskustva i jednostavno ovo je realna situacija
> 
> poštovani, iz iskustva vidim kako nakon tih 150 dana, kada ponovo pokušamo dati hag ili ban odjednom nemamo privilegiju za to već nas se redirektira na Dželate i ulazi se u proces da dižemo cijeli server na noge nebi li banovali toksične igrače i abjuzere. Uvedemo li natrag Vrhovni sud puno lakše ćemo se nositi s abjuzerima. Čak ako nije perma ban biti ćemo u stanju hagovati ih, ovako gubimo vreme a i oduzima nam se konzola kad želimo djelovat.
> 
> ZSS - Zlajina Seljačka Stranka. Za ravnopravan server!

Ja mislim da ako igraci upravljaju serverom da oni glasaju da l da se vrati ili ne a posle clanovi da se biraju ljudima iz policije (staffa)

**Comment by DzingisKan** [comment]
> > > Što se tiče perma banova, već sam pisao o tome ali to jednostavno ništa ne rešava, kod ovakvog tipa otvorenog servera svud je isto, banujete IP igrača zauvek, upali VPN, napravi novi acc na TLauncheru free i uđe jer server nije samo premium već svako može ući sa bilo kog nicka
> > > inati se i pravi zijane po serveru, jer što nebi. Ovo da banujemo po 150 dana je idealna stvar, olade se i nauče, ukoliko se opet ponovi nema veze, ban na 250d i da vidimo ko je uporniji
> > > ja ovo govorim iz iskustva i jednostavno ovo je realna situacija
> > 
> > 
> > poštovani, iz iskustva vidim kako nakon tih 150 dana, kada ponovo pokušamo dati hag ili ban odjednom nemamo privilegiju za to već nas se redirektira na Dželate i ulazi se u proces da dižemo cijeli server na noge nebi li banovali toksične igrače i abjuzere. Uvedemo li natrag Vrhovni sud puno lakše ćemo se nositi s abjuzerima. Čak ako nije perma ban biti ćemo u stanju hagovati ih, ovako gubimo vreme a i oduzima nam se konzola kad želimo djelovat.
> > ZSS - Zlajina Seljačka Stranka. Za ravnopravan server!
> 
> Ja mislim da ako igraci upravljaju serverom da oni glasaju da l da se vrati ili ne a posle clanovi da se biraju ljudima iz policije (staffa)

Poštovani, ukazao bi vam na već poznati problem kada osobe koje abjuzaju, abjuzanje stvari davaju svom narodu, tako osiguravaju podršku na ovakvim mjestima gdje se gleda svačiji glas. Vrlo jednostavno je potplatitit nekog. Smatram kako bi to trebala biti odluka osobe koja ima neki viziju servera i koja radi na njemu. Primjer PiweeeX

**Comment by akipaki293** [comment]
> > > > Što se tiče perma banova, već sam pisao o tome ali to jednostavno ništa ne rešava, kod ovakvog tipa otvorenog servera svud je isto, banujete IP igrača zauvek, upali VPN, napravi novi acc na TLauncheru free i uđe jer server nije samo premium već svako može ući sa bilo kog nicka
> > > > inati se i pravi zijane po serveru, jer što nebi. Ovo da banujemo po 150 dana je idealna stvar, olade se i nauče, ukoliko se opet ponovi nema veze, ban na 250d i da vidimo ko je uporniji
> > > > ja ovo govorim iz iskustva i jednostavno ovo je realna situacija
> > > 
> > > 
> > > poštovani, iz iskustva vidim kako nakon tih 150 dana, kada ponovo pokušamo dati hag ili ban odjednom nemamo privilegiju za to već nas se redirektira na Dželate i ulazi se u proces da dižemo cijeli server na noge nebi li banovali toksične igrače i abjuzere. Uvedemo li natrag Vrhovni sud puno lakše ćemo se nositi s abjuzerima. Čak ako nije perma ban biti ćemo u stanju hagovati ih, ovako gubimo vreme a i oduzima nam se konzola kad želimo djelovat.
> > > ZSS - Zlajina Seljačka Stranka. Za ravnopravan server!
> > 
> > 
> > Ja mislim da ako igraci upravljaju serverom da oni glasaju da l da se vrati ili ne a posle clanovi da se biraju ljudima iz policije (staffa)
> 
> Poštovani, ukazao bi vam na već poznati problem kada osobe koje abjuzaju, abjuzanje stvari davaju svom narodu, tako osiguravaju podršku na ovakvim mjestima gdje se gleda svačiji glas. Vrlo jednostavno je potplatitit nekog. Smatram kako bi to trebala biti odluka osobe koja ima neki viziju servera i koja radi na njemu. Primjer PiweeeX

Ok, i sam sam uveren u te stvari, necu da dajem primer jer ga i vi znate, ali najbolje da o tome on odluci osoba o kojoj sam hteo pricati su Skleper i Stipe ali to je za neki drugi put

**Comment by DzingisKan** [comment]
> > > > > Što se tiče perma banova, već sam pisao o tome ali to jednostavno ništa ne rešava, kod ovakvog tipa otvorenog servera svud je isto, banujete IP igrača zauvek, upali VPN, napravi novi acc na TLauncheru free i uđe jer server nije samo premium već svako može ući sa bilo kog nicka
> > > > > inati se i pravi zijane po serveru, jer što nebi. Ovo da banujemo po 150 dana je idealna stvar, olade se i nauče, ukoliko se opet ponovi nema veze, ban na 250d i da vidimo ko je uporniji
> > > > > ja ovo govorim iz iskustva i jednostavno ovo je realna situacija
> > > > 
> > > > 
> > > > poštovani, iz iskustva vidim kako nakon tih 150 dana, kada ponovo pokušamo dati hag ili ban odjednom nemamo privilegiju za to već nas se redirektira na Dželate i ulazi se u proces da dižemo cijeli server na noge nebi li banovali toksične igrače i abjuzere. Uvedemo li natrag Vrhovni sud puno lakše ćemo se nositi s abjuzerima. Čak ako nije perma ban biti ćemo u stanju hagovati ih, ovako gubimo vreme a i oduzima nam se konzola kad želimo djelovat.
> > > > ZSS - Zlajina Seljačka Stranka. Za ravnopravan server!
> > > 
> > > 
> > > Ja mislim da ako igraci upravljaju serverom da oni glasaju da l da se vrati ili ne a posle clanovi da se biraju ljudima iz policije (staffa)
> > 
> > 
> > Poštovani, ukazao bi vam na već poznati problem kada osobe koje abjuzaju, abjuzanje stvari davaju svom narodu, tako osiguravaju podršku na ovakvim mjestima gdje se gleda svačiji glas. Vrlo jednostavno je potplatitit nekog. Smatram kako bi to trebala biti odluka osobe koja ima neki viziju servera i koja radi na njemu. Primjer PiweeeX
> 
> Ok, i sam sam uveren u te stvari, necu da dajem primer jer ga i vi znate, ali najbolje da o tome on odluci osoba o kojoj sam hteo pricati su Skleper i Stipe ali to je za neki drugi put

javite nam se na discordu ZSS

**Comment by Vedran069** [comment]
> > Što se tiče perma banova, već sam pisao o tome ali to jednostavno ništa ne rešava, kod ovakvog tipa otvorenog servera svud je isto, banujete IP igrača zauvek, upali VPN, napravi novi acc na TLauncheru free i uđe jer server nije samo premium već svako može ući sa bilo kog nicka
> > inati se i pravi zijane po serveru, jer što nebi. Ovo da banujemo po 150 dana je idealna stvar, olade se i nauče, ukoliko se opet ponovi nema veze, ban na 250d i da vidimo ko je uporniji
> > ja ovo govorim iz iskustva i jednostavno ovo je realna situacija
> 
> poštovani, iz iskustva vidim kako nakon tih 150 dana, kada ponovo pokušamo dati hag ili ban odjednom nemamo privilegiju za to već nas se redirektira na Dželate i ulazi se u proces da dižemo cijeli server na noge nebi li banovali toksične igrače i abjuzere. Uvedemo li natrag Vrhovni sud puno lakše ćemo se nositi s abjuzerima. Čak ako nije perma ban biti ćemo u stanju hagovati ih, ovako gubimo vreme a i oduzima nam se konzola kad želimo djelovat.
> 
> ZSS - Zlajina Seljačka Stranka. Za ravnopravan server!

Kakve ovo veze ima sa Rimskim carstvom.

Živelo Rimsko Carstvo

**Comment by Vedran069** [comment]
Inače, Zlajo, ovo ZSS zvuči poznato. Nemoj da zovem čika Punišu Račića.
![250px-Punisa_Racic](https://user-images.githubusercontent.com/107585534/173967367-5173b58f-2d3c-4a6e-9b61-7381247c9f0d.jpg)


A za tebe bi nam dobro došao i Blagoje Jovović.
![Uploading Blagoje_Jovović.jpg…]()
