### ISSUE TITLE
Republika Singahara na Decentralandu

### ISSUE THREAD

**Issue by akipaki293** [PiweeX/HogRealms#30]
5-10 Jul biće održano otvaranje Trgovnisko-Poljoprivrednog centra u Ostrvskoj Uniji, a vašar zakazan za 30 Jun, održaće se najranije između 5 i 10 Jula.

Zanatski centar će biti otvoren najkasnije 15 odnosno 20 Avgusta.

**Comment by akipaki293** [comment]
@PiweeX Trebaće mi jedna molba ako ne i usluga, da mi prihvatis dm al neću ti spamati. Hvala

**Comment by akipaki293** [comment]
> 5-10 Jul biće održano otvaranje Trgovnisko-Poljoprivrednog centra u Ostrvskoj Uniji, a vašar zakazan za 30 Jun, održaće se najranije između 5 i 10 Jula.
> 
> Zanatski centar će biti otvoren najkasnije 15 odnosno 20 Avgusta.

Ovo su očekivani datumi, ako online mapa proradi do tada.

**Comment by akipaki293** [comment]
Srpski: Novi igrač Fifour je iz Rusije, ja i on uskoro počinjemo školu Ruskog u istom gradu gde će biti trgovina i poljoprivreda

English: The new Fifour player is from Russia, and he and I will soon start a Russian school in the same city where there will be trade and agriculture

**Comment by PiweeX** [comment]
može al pisi na insta hogrealms pošto da bi dao konstruktivan odgovor treba mi vremena a za to treba i koncentracije tako da kad stignem odgovoriću, isto je dal mi napišeš u dm na discord ili na insta, na discordu mi smetaju notifikacije pa gledam da ne prihvatam ljude jer ne želim da imam toliku dozu dodatnog stresa

**Comment by akipaki293** [comment]
> može al pisi na insta hogrealms pošto da bi dao konstruktivan odgovor treba mi vremena a za to treba i koncentracije tako da kad stignem odgovoriću, isto je dal mi napišeš u dm na discord ili na insta, na discordu mi smetaju notifikacije pa gledam da ne prihvatam ljude jer ne želim da imam toliku dozu dodatnog stresa

Ja sam zaboravio šta sam hteo da te pitam haha

**Comment by akipaki293** [comment]
Nakon dužih pregovora osvojena teritorija u Australiji gde će biti građen grad Aterton, u Atertonu će biti Kulturni, Trgovinski i Poljoprivredni centar Ostrvske Unije.

**Comment by akipaki293** [comment]
![Screenshot_106](https://user-images.githubusercontent.com/107085831/174042155-e03cc512-88e1-4574-a0b5-ce836a9ff5ee.png)

**Comment by akipaki293** [comment]
Srpski: Claimanje je završeno, potrošeno je 50000$ na claimove i claimano 200 chunkova. Trenutni budžet Ostrvske Unije je 43406.70$. Uskoro kreće gradnja.

English: Claiming was completed, $ 50,000 was spent on claiming and 200 chunks were claimed. The current budget of the Island Union is $ 43406.70. Construction is about to begin.

**Comment by akipaki293** [comment]
Zbog nedostatka materijala radovi na Marketima kreće sutra.

**Comment by akipaki293** [comment]
Plan gradnje Atertona:
1. Marketi (Pijaca )
2. Super Market
3. Trg
4. Škola
5. Kafić
6. Restoran
7. Farma






Ostrvska Unija planira skloniti Japanski jezik i pismo iz svoje države zbog ukaljanog Japanskog imena. Glavne vlasti će odlučiti da li ćemo koristiti Engleski ili Indonežanski jezik i pismo.

**Comment by akipaki293** [comment]
Ako Aterton bude išao po planu  biće najveći grad u državi s tim i glavni.

**Comment by akipaki293** [comment]
Radovi na Atertonu se odlažu, jer se pišu stvari za drugi projekat

**Comment by akipaki293** [comment]
Nakon uređivanja discorda za Ostrvsku Uniju i još stvati kreće skupljanje materijala za Aterton

**Comment by akipaki293** [comment]
Materijali Za Markete skupljeni, a Busan uređen.

**Comment by Cetnik1918** [comment]
> Materijali Za Markete skupljeni, a Busan uređen.

Ne diraj busan

**Comment by akipaki293** [comment]
Koreja je sada slobodna zemlja, njome upravlja Cetnin1918. Koreja je trebala da bude Ujedinjena ili u Savezu sa Ostrvskom Unijom, ali Četnik1918 poznatiji kao A-L-E-K-S-A je pokvario odnose.

**Comment by Cetnik1918** [comment]
> Koreja je sada slobodna zemlja, njome upravlja Cetnin1918. Koreja je trebala da bude Ujedinjena ili u Savezu sa Ostrvskom Unijom, ali Četnik1918 poznatiji kao A-L-E-K-S-A je pokvario odnose.

Ja , denzai razux je upravljamo i glasajda ako smo posebna drzavq kao i sto jesmo

**Comment by akipaki293** [comment]
Clamovi:

> Claimana veća teritorija Atertona, i manja teritorija Tasmanije

Materijali:

> Materijali su skupljeni i pripremljeni, ostala je još gradnja.

Trgovina:

> Spremljeno je preko 5 double chesta jaja, par stekova drveta, i 6 konja za prodaju.

Cene:

> 16 Jaja - 250$
   64 Wood - 750$
    1 Konj - 1000$-20000$ (Zavisi od brzine i skoka)

**Comment by akipaki293** [comment]
Završena gradnja Marketa (Pijace) u Atertonu, vašar treba da se održi između 30.6 i 5.7

**Comment by akipaki293** [comment]
![Uploading unknown.png…]()

**Comment by akipaki293** [comment]
`. `

**Comment by akipaki293** [comment]
Izglasano menjanje državnog uređenja u Republiku, promene na discordu kreću sutra.

**Comment by akipaki293** [comment]
Ostrvska Unija je zvanično promenila uređenje u Republiku i ime u Singaharu. Discord server je updatean, a kada se završi projekat "Hogo Psihijatrija " krecemo sa gradnjom

**Comment by akipaki293** [comment]
Clamovi:

Claimana veća teritorija Atertona, i manja teritorija Tasmanije
Materijali:

Materijali su skupljeni i pripremljeni, ostala je još gradnja.
Trgovina:

Spremljeno je preko 5 double chesta jaja, par stekova drveta, i 6 konja za prodaju.
Cene:

16 Jaja - 250$

64 Wood - 750$

1 Konj - 1000-20000$ (Zavisi od brzine i skoka)

Plan gradnje Atertona:

Marketi (Pijaca ) +
Super Market
Trg +-
Škola
Kafić
Restoran
Farma

Vašar 30.6-5.7 Otvaranje Atertona u Fullu 10.7
