### ISSUE TITLE
Trajni ban za Ratka (Thunderrr, Srbenda1389)

### ISSUE THREAD

**Issue by DzingisKan** [PiweeX/HogRealms#31]
ZSS stranka prilaže zahtjev da se trajno bana igrač Ratko.

Ratka ZSS tereti za:
-Višestruki abjuz (oko 20 i više slučajeva)
-Korištenje pada plugina 
-Prodaja abjuzanih stvari tako narušavajući ekonomiju servera i dovođenje ostalih igrača u neprijatne situacije.
-Konstantno toksično ponašanje prema ostalim igračima
-SPAManje u HogRelams discordu
-Vređanje admina
-Ometanje roleplaya

ZSS kao stranka smatra kako Ratko ne pripada na serveru te je nepopravljiv. Smatramo kako bi trebao biti zauvek uklonjen kako bi ostali igrači mogli igrati u miru.

**Comment by Vedran069** [comment]
Rimsko carstvo traži da Zlaja prekine sa ustaškim referencama.

Ozbiljna je tema da bi se tako zajebavali.

**Comment by DzingisKan** [comment]
> Rimsko carstvo traži da Zlaja prekine sa ustaškim referencama.
> 
> Ozbiljna je tema da bi se tako zajebavali.

ustaške reference su?

**Comment by FarisSpaha** [comment]
> 

Pusti vedrana

**Comment by dzelat** [comment]
> > ZSS stranka prilaže zahtjev da se trajno bana igrač Ratko.
> > Ratka ZSS tereti za: -Višestruki abjuz (oko 20 i više slučajeva) -Korištenje pada plugina -Prodaja abjuzanih stvari tako narušavajući ekonomiju servera i dovođenje ostalih igrača u neprijatne situacije. -Konstantno toksično ponašanje prema ostalim igračima -SPAManje u HogRelams discordu -Vređanje admina -Ometanje roleplaya
> > ZSS kao stranka smatra kako Ratko ne pripada na serveru te je nepopravljiv. Smatramo kako bi trebao biti zauvek uklonjen kako bi ostali igrači mogli igrati u miru.
> 
> Moj prijatelj Zlaja uvek pravi posao poštenim 😍

naravno 😊

**Comment by vukstrale** [comment]
Podržavam ZSS sve više od kad je krenuo da se bavi realnim problemima koji muče zajednicu već duže vreme!

**Comment by dzelat** [comment]
mogli ste i mene ubacit tamo
da vidim cime se bavite

**Comment by markeccc998** [comment]
> 

No

**Comment by markeccc998** [comment]
> ZSS stranka prilaže zahtjev da se trajno bana igrač Ratko.
> 
> Ratka ZSS tereti za: -Višestruki abjuz (oko 20 i više slučajeva) -Korištenje pada plugina -Prodaja abjuzanih stvari tako narušavajući ekonomiju servera i dovođenje ostalih igrača u neprijatne situacije. -Konstantno toksično ponašanje prema ostalim igračima -SPAManje u HogRelams discordu -Vređanje admina -Ometanje roleplaya
> 
> ZSS kao stranka smatra kako Ratko ne pripada na serveru te je nepopravljiv. Smatramo kako bi trebao biti zauvek uklonjen kako bi ostali igrači mogli igrati u miru.

No

**Comment by markeccc998** [comment]
Zlaja sad želi skloniti svu konkurenciju

**Comment by dzelat** [comment]
> Svetskom dominacijom, očigledno. Prvi korak je banovanje svih neprijatelja i neistomišljenika. Politička čistka ako mogu tako reći

da da autokratija, totalitarizam, u jednoj rijeci nacizam

**Comment by ConeBe** [comment]
Bruh Zlajo imam predlog

**Comment by ConeBe** [comment]
Hajde da banujemo sve igrače sa servera osim tebe i Px i nekih admina i svi ostali u hag ili ban

**Comment by ConeBe** [comment]
Mislim da onda ne bi imao konkurenciju

**Comment by markeccc998** [comment]
Onda bi išao na px-a

**Comment by ConeBe** [comment]
a da viđam vraćen ti je

**Comment by markeccc998** [comment]
Nažalost

**Comment by PiweeX** [comment]
Mislim da Thunderrr nije nepopravljiv jer vi kad dobijete ban na 150d pa onda uradite nešto loše pa na 250 razmislićete da li ćete sledeći put napraviti neku zijanu. Dakle, ako mu je stalo do servera i sačeka da dobije unban paziće na svoje postupke



Što se tiče trajnih banova rećiću opet oni nemaju smisla jer na taj način podstičete da ljudi prave altove i da se zajebavaju (grifuju..) a ne da igraju jer što bi igrali na nekom random nicku gde ih niko ne zna

po tom osnovu, trajni banovi nemaju smisla ali da treba povećati banove za određene osobe definitivno da.



Ratko bi trebao da dobije veću kaznu jer su se pojavili snimci da i posle onog bana od 150 dana radio nešto novo loše (kad je random liku skidao xray i davao mu da igra i da mu kopa u debris claimu)

umesto toga, dobio je kaznu od 30 dana i oduzet mu je određen broj debrisa, ja sam za to da se većina njegovog bogatstva preusmeri na skroz nove igrače

to da je ovo pokrenuto da on dobije ban pa da Zlaja nema konkurenciju nema smisla jer on stvarno kvari igru u mnogim slučajevima

**Comment by dzelat** [comment]
https://discord.gg/TxyGxCu9

Od danas mi širimo demokraciju i brišemo nacizam sa servera

**Comment by ConeBe** [comment]
Bar dan Piwexu

**Comment by DzingisKan** [comment]
> Svetskom dominacijom, očigledno. Prvi korak je banovanje svih neprijatelja i neistomišljenika. Politička čistka ako mogu tako reći

poštovani, mojoj državi ne postavlja prijetnju nijedna država ni svjetska vođa. Također ne opravdavate ništa s tom rečenicom. Ratko je i dalje počinio i nastavlja činiti sve navedeno, a sramota je da ima ljudi koji ga brane.

**Comment by dzelat** [comment]
> Bar dan Piwexu

![image](https://user-images.githubusercontent.com/107082292/174077994-95dc7c34-293e-4232-ae4f-86dea23249e2.png)

**Comment by Skleper5** [comment]
> mogli ste i mene ubacit tamo da vidim cime se bavite

Os inv

**Comment by dzelat** [comment]
> > mogli ste i mene ubacit tamo da vidim cime se bavite
> 
> Os inv

an serveru sam al ne vidim da ista pisete

**Comment by DzingisKan** [comment]
> Mislim da Thunderrr nije nepopravljiv jer vi kad dobijete ban na 150d pa onda uradite nešto loše pa na 250 razmislićete da li ćete sledeći put napraviti neku zijanu. Dakle, ako mu je stalo do servera i sačeka da dobije unban paziće na svoje postupke
> 
> Što se tiče trajnih banova rećiću opet oni nemaju smisla jer na taj način podstičete da ljudi prave altove i da se zajebavaju (grifuju..) a ne da igraju jer što bi igrali na nekom random nicku gde ih niko ne zna
> 
> po tom osnovu, trajni banovi nemaju smisla ali da treba povećati banove za određene osobe definitivno da.
> 
> Ratko bi trebao da dobije veću kaznu jer su se pojavili snimci da i posle onog bana od 150 dana radio nešto novo loše (kad je random liku skidao xray i davao mu da igra i da mu kopa u debris claimu)
> 
> umesto toga, dobio je kaznu od 30 dana i oduzet mu je određen broj debrisa, ja sam za to da se većina njegovog bogatstva preusmeri na skroz nove igrače
> 
> to da je ovo pokrenuto da on dobije ban pa da Zlaja nema konkurenciju nema smisla jer on stvarno kvari igru u mnogim slučajevima

Poštovani, kao što ste i sami naveli, nakon isteka 150 dana jaila Ratko je opet počinio zločin. Napominjem kako je ratko imao preko 10 jailova i nakon svakog bili oni kraći ili duži opet je činio isto. Također govorimo o igraču koji nikada nije imao roleplay priču. Njegova bogatstva nikako nebi trebalo dati ikom drugom, ti itemi stvoreni su abjuzom te bi tako narušili ekonomiju. Što se tiče altova i griefa. Grief uvek možemo popraviti, altove uvijek možemo banati. Sklanjanjem ratka imate mir u serveru, a ako ratko i napravi alt i mi to ne znamo jer nije napravio nered, znaci da smo postigli ono što vi neuspješno pokušavate sa jailom već mjesecima.

**Comment by ConeBe** [comment]
Pita sa sirom ALE ALE

**Comment by PiweeX** [comment]
Što se tiče abjzovanih itema u momentu kad je to bilo moguće i dok build mod nije ukinut ti itemi su spaljeni, postoje priče od raznih igrača da on ima tajne stekove ali više puta je gledano i nikad ništa nije nađeno..

U ostalom, da još uvek ima abjuzovanih stvari u njegovim stekovima širom sveta kako se priča, nebi davao drugarima iz RL da mu kopaju sa hakovima



ne znam šta da kažem, ti itemi će svakako biti ili zakopani u hagu ili dati skroz novim igračima kako bi se ekonomija i moć u svetu još balansirala

da, dobio je ban i posle nešto manje od 150d se vratio, dobio još veći ban i da li će sledeći put praviti probleme? Razmisliće 2 puta pre nego što krene da spama ili slično.

**Comment by ConeBe** [comment]
9000 milja ispod mora

**Comment by denzavkk** [comment]
Banovi glavne konkurencije Genghis-Khana su sve česti i česti, mi se zalažemo za novu eru te da krenemo malo dalje s vremenom u povijesti, bio sam Mongol i imao sam sve dok sam bio Mongol, imunitet od bana, poštovanje svih igrača , duplicirane iteme, dosta je bilo natezanja, no Mongolsko Carstvo po povijesti treba pasti da bi se razvile nove price i države na tome području , Mongolija je problematična zemlja puna problematičnih ljudi kojih sam bio sam dio. Rado bih volio diskutirati o ovome cijeli dan i doći do zaključka ali mislim da si previše uzimaš za pravo Dino i da previše stavljaš Realms kao svoje nešto. Ostalo sto budem pričao će biti u klipu. Hvala na pozornosti i svima ugodan dan želim

**Comment by vukstrale** [comment]
Ne znam, čoek je samo izneo glasanje. Iznesi ti glasanje da se Zlaji skine co-owner. Ah da, već je bilo. I ljudi su glasali za ono što su hteli. Zato ne volim demokratiju.

**Comment by vukstrale** [comment]
https://github.com/PiweeX/HogRealms/issues/20

**Comment by dzelat** [comment]
da i 7 njih je bilo za

**Comment by DzingisKan** [comment]
> Banovi glavne konkurencije Genghis-Khana su sve česti i česti, mi se zalažemo za novu eru te da krenemo malo dalje s vremenom u povijesti, bio sam Mongol i imao sam sve dok sam bio Mongol, imunitet od bana, poštovanje svih igrača , duplicirane iteme, dosta je bilo natezanja, no Mongolsko Carstvo po povijesti treba pasti da bi se razvile nove price i države na tome području , Mongolija je problematična zemlja puna problematičnih ljudi kojih sam bio sam dio. Rado bih volio diskutirati o ovome cijeli dan i doći do zaključka ali mislim da si previše uzimaš za pravo Dino i da previše stavljaš Realms kao svoje nešto. Ostalo sto budem pričao će biti u klipu. Hvala na pozornosti i svima ugodan dan želim

Poštovani, molimo navedite mi imena ljudi i razloge zašto smatrate da su problematični. Server nije u eri mongolije, imamo Četničko carstvo, Vikinge, Rimsko Carstvo i Spartance. Molim vas proučite ere tih roleplaya. Na teritoriju Mongolije trenutno imamo oko 7 različitih država i različitih roleplaya sve u sklopu jedne teritorije. Smatram kako vi i vaša malenkost spadate u skupinu ljudi koja radi probleme na serveru. No za to će u budučnosti otvarati glasanje ako pređe određenu granicu.

**Comment by dzelat** [comment]
> to da neko trajno bude cancelovan i banovan sa servera nema smisla, to ni fariseji nisu radili
> 
> ako neko baš napravi problem može da dobije ban od 8 meseci, to je i suviše dovoljno, ako je dovoljno veliki kreten da posle 8 meseci onemogućene normalne igre napravi veći problem koji bi rezultirao narednim kažnjavanjem on treba da se zatvori stvarno na više od godinu dana.
> 
> čak sam i razmišljao da se umesto bana uvede zatvor u istoj trajnosti plus mute
> 
> na taj način, imaćete osobu kojoj je onemogućena igra i komunikacija a on će imati pristup svom nalogu, na taj način apsolutno NEĆEMO imati problema sa stvaranjem alt naloga i VPN servisima, jednostavno u praksi se tako pokazalo.
> 
> ne znate koliki nam problem i sa tehničke strane stvaraju VPN servisi i igrači koji prave više naloga. Ne može se gledati samo 1 strana slike, trajni ban je apsolutno loš....

apsolutno se slazem, no kad bi mogao doc na server da nesto pogledas

**Comment by DzingisKan** [comment]
> to da neko trajno bude cancelovan i banovan sa servera nema smisla, to ni fariseji nisu radili
> 
> ako neko baš napravi problem može da dobije ban od 8 meseci, to je i suviše dovoljno, ako je dovoljno veliki kreten da posle 8 meseci onemogućene normalne igre napravi veći problem koji bi rezultirao narednim kažnjavanjem on treba da se zatvori stvarno na više od godinu dana.
> 
> čak sam i razmišljao da se umesto bana uvede zatvor u istoj trajnosti plus mute
> 
> na taj način, imaćete osobu kojoj je onemogućena igra i komunikacija a on će imati pristup svom nalogu, na taj način apsolutno NEĆEMO imati problema sa stvaranjem alt naloga i VPN servisima, jednostavno u praksi se tako pokazalo.
> 
> ne znate koliki nam problem i sa tehničke strane stvaraju VPN servisi i igrači koji prave više naloga. Ne može se gledati samo 1 strana slike, trajni ban je apsolutno loš....

Poštovani nadam se kako će se onda bez ustručavanja banovati ratko na rok od 250+ dana jednom kada rezultati glasanja izađu.

**Comment by vukstrale** [comment]
> > to da neko trajno bude cancelovan i banovan sa servera nema smisla, to ni fariseji nisu radili
> > ako neko baš napravi problem može da dobije ban od 8 meseci, to je i suviše dovoljno, ako je dovoljno veliki kreten da posle 8 meseci onemogućene normalne igre napravi veći problem koji bi rezultirao narednim kažnjavanjem on treba da se zatvori stvarno na više od godinu dana.
> > čak sam i razmišljao da se umesto bana uvede zatvor u istoj trajnosti plus mute
> > na taj način, imaćete osobu kojoj je onemogućena igra i komunikacija a on će imati pristup svom nalogu, na taj način apsolutno NEĆEMO imati problema sa stvaranjem alt naloga i VPN servisima, jednostavno u praksi se tako pokazalo.
> > ne znate koliki nam problem i sa tehničke strane stvaraju VPN servisi i igrači koji prave više naloga. Ne može se gledati samo 1 strana slike, trajni ban je apsolutno loš....
> 
> Poštovani nadam se kako će se onda bez ustručavanja banovati ratko na rok od 250+ dana jednom kada rezultati glasanja izađu.

Ako je Skleper banovan na 50, jedino pošteno bi bilo da lika koji pravi 10 puta veće probleme bude banovan u tom rasponu dana

**Comment by DzingisKan** [comment]
> > > Banovi glavne konkurencije Genghis-Khana su sve česti i česti, mi se zalažemo za novu eru te da krenemo malo dalje s vremenom u povijesti, bio sam Mongol i imao sam sve dok sam bio Mongol, imunitet od bana, poštovanje svih igrača , duplicirane iteme, dosta je bilo natezanja, no Mongolsko Carstvo po povijesti treba pasti da bi se razvile nove price i države na tome području , Mongolija je problematična zemlja puna problematičnih ljudi kojih sam bio sam dio. Rado bih volio diskutirati o ovome cijeli dan i doći do zaključka ali mislim da si previše uzimaš za pravo Dino i da previše stavljaš Realms kao svoje nešto. Ostalo sto budem pričao će biti u klipu. Hvala na pozornosti i svima ugodan dan želim
> > 
> > 
> > Poštovani, molimo navedite mi imena ljudi i razloge zašto smatrate da su problematični. Server nije u eri mongolije, imamo Četničko carstvo, Vikinge, Rimsko Carstvo i Spartance. Molim vas proučite ere tih roleplaya. Na teritoriju Mongolije trenutno imamo oko 7 različitih država i različitih roleplaya sve u sklopu jedne teritorije. Smatram kako vi i vaša malenkost spadate u skupinu ljudi koja radi probleme na serveru. No za to će u budučnosti otvarati glasanje ako pređe određenu granicu.
> 
> ja ne kontam, ti stvarno mislis da si nepogresiv ili?

Poštovani dzelate. Denzavkk nije imao znatnije prijestupe u serveru osim toksičnosti. Međutim toksičnost prelazi granice po pitanju zahtjeva koje denzavk uručuje. Denzavkku trenutno ne prijeti ban niti ikakve sankcije.

**Comment by VukIcrnogorskii** [comment]
Dajte ljudi molim vas edukujte se nije četničko carstvo, nego četnička provincija u sklopu Imperium Montenegrinuma

**Comment by vukstrale** [comment]
> Dajte ljudi molim vas edukujte se nije četničko carstvo, nego četnička provincija u sklopu Imperium Montenegrinuma

Oprostite velepoštovani. Zavisna Četnička Provincija Kao Sastavni Deo Svetog Crnogorskog Carstva

**Comment by VukIcrnogorskii** [comment]
To je vec bolje al mi ne prozivamo nas svetinjama i bogovima!

**Comment by vukstrale** [comment]
You know what they say about big feet hehe

**Comment by VukIcrnogorskii** [comment]
Bog je jedan pravoslavni!

**Comment by VukIcrnogorskii** [comment]
A od nasih svestenih lica jos niko umro da bi bio svetac!

**Comment by ConeBe** [comment]
![image](https://user-images.githubusercontent.com/107082648/174086951-3666e39b-8a7c-4157-baa4-1589dfad7246.png)

**Comment by vukstrale** [comment]
Gorgeus

**Comment by markeccc998** [comment]
No

**Comment by akipaki293** [comment]
Da li ZSS ima svoj discord i ako ima posaljite mi ga hvala

**Comment by bogoljub1234** [comment]
Ima

**Comment by SaracYT** [comment]
> 

Sa njim nije moguce pricati. Konstantno ulazi u svadje i vredja igrace. Zasluzuje perma ban.

**Comment by IamJoseMourinho** [comment]
> ZSS stranka prilaže zahtjev da se trajno bana igrač Ratko.
> 
> Ratka ZSS tereti za: -Višestruki abjuz (oko 20 i više slučajeva) -Korištenje pada plugina -Prodaja abjuzanih stvari tako narušavajući ekonomiju servera i dovođenje ostalih igrača u neprijatne situacije. -Konstantno toksično ponašanje prema ostalim igračima -SPAManje u HogRelams discordu -Vređanje admina -Ometanje roleplaya
> 
> ZSS kao stranka smatra kako Ratko ne pripada na serveru te je nepopravljiv. Smatramo kako bi trebao biti zauvek uklonjen kako bi ostali igrači mogli igrati u miru.

Ratko, Thunderrr, Srbenda1389, kako god hocete, ali samo pravite budalu od sebe, posebno ovaj Kan Zlaja... 
Tvrdi kako je abjuzovao iteme dok je Zlaja mesecima podmetao te iteme po Karakorumu te je Srbenda sve to nalazio i uzimao.. Cak je Zlaja i shulkere iz creativa stavljao po Mongoliji, znam to jer sam bio tamo kad se dogodilo. On uopste nije los po vredjanju drugih igraca na serveru, samo im vraca ono sto je on dobio od njih. A sto se tice vredjanja admina, to nije mnozina, to je dzingis kan. Stavljao ga je u Hag i mutovao bez razloga, cak je i sam to rekao u #dosije. Zlaja se jeste ponasao veoma bezobrazno prema njemu. Ti abjuzovi ne postoje uopste, to je sve podmetanje stvari od strane admina Zlaje da ga banaju jer ga ne voli.. Sada ce biti komentar od tog dzingisa i naravno da ce da brani svoj stav, ali svkako ce slagati, jer eto, to je nas admin roleplaya.....

**Comment by IamJoseMourinho** [comment]
> > 
> 
> Sa njim nije moguce pricati. Konstantno ulazi u svadje i vredja igrace. Zasluzuje perma ban.

Normalno da ce biti nemoguce kad ga napadate sa svih strana cim krene konverzacija, treba s njim popricati neko ko je dobar sa njim, poput jednog poznatog igraca

**Comment by SaracYT** [comment]
> > > 
> > 
> > 
> > Sa njim nije moguce pricati. Konstantno ulazi u svadje i vredja igrace. Zasluzuje perma ban.
> 
> Normalno da ce biti nemoguce kad ga napadate sa svih strana cim krene konverzacija, treba s njim popricati neko ko je dobar sa njim, poput jednog poznatog igraca

Promasio si poentu. Nije cilj da sa jednim igracem moze pricati, nego da eventualno sa jednim ne moze, a da mu svi ostali ne smetaju. Ako je tolika cvecka kako je prvi put dobio ban? Jednostavno je zasluzio, odbija nove igrace od servera.

**Comment by denzavkk** [comment]
Ja sam se kačio s Srbendom non-stop to svi znaju u Decentralandu jer ima dozu nacionalizma koju vise ne pokazuje prema meni barem , da je mirniji prema par igrača jeste, mrzitelj sam nacionalizma i rasizma te je to bio jedini razlog sto san se kačio s Srbendom, a kad smo kad nacionalnosti molio bih gospodina Zlaju Challengea da ne glumi Srbina kad je Hrvat jer je pomalo cringe i nikog ne osvaja svojim lažnim tonalitetima. Jesi iz Kaštela? Jesi rođen Hrvat ? Ne glumi ono sto nisi nego sto jesi.

**Comment by Lava1-7** [comment]
Slazem se, Srbendu treba banovati.

**Comment by ConeBe** [comment]
@DzingisKan  nešto pobedio Ratko u glasovima protiv banovanja? Ili mi se čini.

**Comment by IamJoseMourinho** [comment]
> > > > 
> > > 
> > > 
> > > Sa njim nije moguce pricati. Konstantno ulazi u svadje i vredja igrace. Zasluzuje perma ban.
> > 
> > 
> > Normalno da ce biti nemoguce kad ga napadate sa svih strana cim krene konverzacija, treba s njim popricati neko ko je dobar sa njim, poput jednog poznatog igraca
> 
> Promasio si poentu. Nije cilj da sa jednim igracem moze pricati, nego da eventualno sa jednim ne moze, a da mu svi ostali ne smetaju. Ako je tolika cvecka kako je prvi put dobio ban? Jednostavno je zasluzio, odbija nove igrace od servera.

> > > > 
> > > 
> > > 
> > > Sa njim nije moguce pricati. Konstantno ulazi u svadje i vredja igrace. Zasluzuje perma ban.
> > 
> > 
> > Normalno da ce biti nemoguce kad ga napadate sa svih strana cim krene konverzacija, treba s njim popricati neko ko je dobar sa njim, poput jednog poznatog igraca
> 
> Promasio si poentu. Nije cilj da sa jednim igracem moze pricati, nego da eventualno sa jednim ne moze, a da mu svi ostali ne smetaju. Ako je tolika cvecka kako je prvi put dobio ban? Jednostavno je zasluzio, odbija nove igrace od servera.

Dobro si to rekao, ali svakako obicni ljudi koji nisu vise od 5 meseci na decentralandu ne vide kakav je zapravo Zlaja čelendž, te potvrdjuju sta god on da kaze jer eto, zasto da ne kad je admin

**Comment by Henoyx** [comment]
@DzingisKan  Tvoji mongoli su nadjačani demokratskom voljom naroda.

**Comment by Henoyx** [comment]
Sto se mene tice Ratko je pobedio

**Comment by DzingisKan** [comment]
> > > > > 
> > > > 
> > > > 
> > > > Sa njim nije moguce pricati. Konstantno ulazi u svadje i vredja igrace. Zasluzuje perma ban.
> > > 
> > > 
> > > Normalno da ce biti nemoguce kad ga napadate sa svih strana cim krene konverzacija, treba s njim popricati neko ko je dobar sa njim, poput jednog poznatog igraca
> > 
> > 
> > Promasio si poentu. Nije cilj da sa jednim igracem moze pricati, nego da eventualno sa jednim ne moze, a da mu svi ostali ne smetaju. Ako je tolika cvecka kako je prvi put dobio ban? Jednostavno je zasluzio, odbija nove igrace od servera.
> 
> > > > > 
> > > > 
> > > > 
> > > > Sa njim nije moguce pricati. Konstantno ulazi u svadje i vredja igrace. Zasluzuje perma ban.
> > > 
> > > 
> > > Normalno da ce biti nemoguce kad ga napadate sa svih strana cim krene konverzacija, treba s njim popricati neko ko je dobar sa njim, poput jednog poznatog igraca
> > 
> > 
> > Promasio si poentu. Nije cilj da sa jednim igracem moze pricati, nego da eventualno sa jednim ne moze, a da mu svi ostali ne smetaju. Ako je tolika cvecka kako je prvi put dobio ban? Jednostavno je zasluzio, odbija nove igrace od servera.
> 
> Dobro si to rekao, ali svakako obicni ljudi koji nisu vise od 5 meseci na decentralandu ne vide kakav je zapravo Zlaja čelendž, te potvrdjuju sta god on da kaze jer eto, zasto da ne kad je admin

Poštovani ja sam u svojoj karijeri okružen samo ljudima koji se protive mojim stavovima

**Comment by Ratko7** [comment]
Mislim da je očigledno da sam ja pobedio

**Comment by BaatarovaKrv** [comment]
Rešio si

**Comment by darixonn** [comment]
Ban za ratkom nema potrebe ako ste mu dali drugu sansu dajte mu drugu sansu i neznam sto uracunavate stare stvari u danasnje pustite ratka na miru i pustite ga da igra

**Comment by Henoyx** [comment]
Zlajo mislim da si puko ovaj vote?
