### ISSUE TITLE
Mobovi na Decentralandu

### ISSUE THREAD

**Issue by PiweeX** [PiweeX/HogRealms#32]
Svi smo svesni situacije da server nema mobova, razlog tome je što u serveru sa pravom mapom sveta nema smisla da postoje kriperi i ostala čudovišta

u momentu kad mobovi poput mrava budu ubačeni, Hog će biti potpun u smislu interakcije igrača sa igrom, u prevodu biće zanimljiva igra i uvek će biti nešto da se radi čak i kad nema nikog i kad je dosadno i kad je sve u datom momentu završeno na bazama itd.
 
ovo nije jednostavno napraviti i puno košta, svakako to je next level i to će nam zasigurno dati prvo mesto na Balkanu i staviti nas u prednost naspram ostalih servera do momenta kad i oni kao i za sve ne iskopiraju i to, ali do tad ćemo već smisliti neki next level za Minecraft servere.

ovde ćemo obaveštavati šta je tim za modele uspeo da napravi i koliko je novca utrošeno na pravljenje tih custom tekstura.

**Comment by PiweeX** [comment]
što se tiče interakcije sa igrom i onog momenta tišine svih dok su u callu, pecanje je dosta doprinelo da se to suzbije, taj momenat koji postoji na svim Minecraft serverima, tačnije na 90% njih izuzev ovih što su minigames.

taj efekat se stvara iz razloga što dođe momenat kad ljudi sve urade što su zamislili i nemaju više ideja a ustvari im je potrebno samo da se podstaknu na igru i smisliće vrlo lako

međutim ukoliko je monotono u callovima i ako je interakcija igrača sa igrom na serveru dosatna server polako ali sigurno umire

to je baš ono što muči 90% novih servera, a uzmimo da mi ne radimo global reset nikada, ostali serveri to rade na 3 meseca i onda ni ne znate šta igrate..

zato kažem, poradiće se na tome, gledam lajvove i pratim kako ljudi pričaju i šta rade na serveru dok igraju i zaključio sam to, u suštini SMRT za server je M O N O T O N I J A

**Comment by PiweeX** [comment]
dalje, što se tiče situacije sa monotonijom na Hogu, minimalna je ali jednostavno postoje momenti i ciklusi, što se tiče toga kako sam ja osmislio koncept igre da server nikada ne bude dosadan a da nema ni 1 global reset tu je odrađen sjajan posao, svakako ima prostora za poboljšanje!

kako sve funkcioniše po ciklusima tako i server, nekad je aktivniji nekad aktivnost padne za 60%, jednostavno zavisi od puno faktora kao naprimer sad ovo za maturu, završetak školske godine, praznike i slično ali bitno je da se sa tehničke strane odradi najbitniji deo, posle toga sve ide lako što se tiče igre ali za takve procese su potrebne godine da se zaključi kako se pravi igriv server i par meseci do godinu da se uvede u praksu.

**Comment by PiweeX** [comment]
Što se tiče bezbednosti mape, ova slika vam govori dosta toga

Server se svakog petka backupa na privatan disk na google drive gde stalno postoje trenutno 2 aktivna backupa nakon čega se jedan briše, ovo važi i za SMP podserver

![Screenshot_2022-06-16-14-57-55-728_com google android apps docs](https://user-images.githubusercontent.com/33425430/174074918-72c81746-2457-496c-9429-0dbad1aa56a2.jpg)

Tako da, ocenio bih sigurnost servera 3.5 od 5 jer uvek može bolje ali svakako server je dosta siguran od potencijalnog "raida" sa unutrašnje strane

**Comment by vukstrale** [comment]
Samo cepaj pixi

**Comment by buducidzelat** [comment]
zelimo ptice

**Comment by R1derPN** [comment]
Px slazem se sa svim tvojim misljenjem.Ja bih umesto default mobova doda neke mobove kao sto je sad poznata Zaga(zmija).Kao i sto su passivne.Za RL dodo bi veci broj zivotinja i neke random strukture da igraci imaju zabavu dok idu kroz te dungeone.

**Comment by PiweeX** [comment]
Zatvoriću ovaj issue jer iznad postoji 1 od igrača pa da ne bude 2 ista

Uglavnom uskoro će biti custom mobova koji će zameniti obične mobove, nadoknadiće
