### ISSUE TITLE
Godisnja doba na Decentralandu

### ISSUE THREAD

**Issue by Coplek** [PiweeX/HogRealms#33]
Ovako posto bi srw bio bolji rp i armor bi imao neku korist, te bi se igraci malo potrudili da se vrati kao sto je bilo u rp beti godisnja doba kad je vruce ne mozes hodat po pijesku jer ti se skida hp, i ne mozes koristiti armor isto tako kad je hladno moras koristiti armor itd. glasajte za ili protiv

**Comment by Coplek** [comment]
slucajno

**Comment by Coplek** [comment]
ne snalazim se

**Comment by VukIcrnogorskii** [comment]
Ja sam dva put od hladnoce lipsa u Kuoplo kad sam bio hahahahahaha

**Comment by VukIcrnogorskii** [comment]
Iako je jun

**Comment by ConeBe** [comment]
> Ja sam dva put od hladnoce lipsa u Kuoplo kad sam bio hahahahahaha

💀

**Comment by vukstrale** [comment]
NEEEE NEEEEEEE NEEEEEE JESI NORMALAN ŽIVIM NA ANTARTIKUUUU!!!! KOJI TI JE KURAC BRATE NEEEEEE

**Comment by VukIcrnogorskii** [comment]
Spremi skafander hahahahaha

**Comment by vukstrale** [comment]
_Vuk dok sedi na Antartiču čeka leto_

**Comment by Skleper5** [comment]
Ne

**Comment by vukstrale** [comment]
fuj

**Comment by bogoljub1234** [comment]
Px prijedlog: da dodas godišnja doba

**Comment by vukstrale** [comment]
no

**Comment by PiweeX** [comment]
Ko god je igrao u beti zna koje nam je probleme to stvaralo

godišnja doba kao doba su ok ali problem je što su igrači takođe kad pređu preko peska dobijali damage i onda je server optuživan da laguje a ustvari niko nije kapirao poentu, ili primera kad neko uđe u hladnu vodu


videćemo kako to bude moglo da se odradi sa tehničke strane a da bude ok, svakako biće!

**Comment by Coplek** [comment]
tototo realno ok je to preko pijeska

**Comment by Coplek** [comment]
jer armor bi se primjenjivao ne samo u ratovanju

**Comment by vukstrale** [comment]
NEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE

**Comment by PiweeX** [comment]
ovaj issue je izglasan, pre jedno 2 meseca sam radio na tome koliko se sećam ali sam odustao jer je previše komplikovano pogotovo za nove igrače, u svakom slučaju neću zatvarati issue jer možda pronađemo alternativu ili napravimo naš plugin za to koji bi rešio probleme koji je predhodni imao

**Comment by PiweeX** [comment]
moraćemo da napravimo naš plugin za ovo kako stvari stoje

**Comment by PiweeX** [comment]
Nešto slično će biti odrađeno do Oktobra

Hud oko svačijeg inv.

Zatvaram issue.
