### ISSUE TITLE
WP Teme Workspace - Changelog (Java Store - Hogo Studios LTD)

### ISSUE THREAD

**Issue by L0renaA** [PiweeX/HogRealms#35]
Počela se izrađivati prva Tebex tema koja će se prodavati
predlažit što biste dodali, maknuli, popravili...mišljenja...
![image](https://user-images.githubusercontent.com/107634534/174110233-1a7f6a1c-0da1-4d1f-a81b-96b2f30221e8.png)

**Comment by bogoljub1234** [comment]
Dodati tornado

**Comment by HesskyDev** [comment]
Pozdrav @L0renaA ,Ignorirajte kolegu @bogoljub1234 , ovo izgleda lijepo, ali mi se ne sviđa boja pozadine (tamno plava) promijenio bih ju u sivu boju koja je prozirna te bih predložio da se koristi drukčiji font.
Srdačan pozdrav!

**Comment by bogoljub1234** [comment]
Nisam ja birao pozadini samo je

**Comment by PiweeX** [comment]
> 

graidenti da, treba ih dodati. Takođe font za ovo sa strane da, a inače što se tiče stevea, njega treba ostaviti dok je onda vizuelno ovca nepotrebno i bilo bi lepše bez nje, u suštini jako dobar osnov to sam rekao i njoj

trebalo bi nekako zaoštriti linije ako me razumete, da ima senke u pozadini npr ovog dela gde se nalaze oblačići (deo gde je najveća svetlo plava boja), senke kao što su na stivu.

**Comment by PiweeX** [comment]
i da, ova opcija ima i na figmi. Predlog je da se pri privlačenju miša po npr ovome Top Customer, Forums, Home, Store, Vote itd doda neka mini animacija (ako je to moguće, nisam radio ranije toliko UI ali predpostavljam da može)

**Comment by akipaki293** [comment]
Imam pitanje sta je ovo i za sta je ovo

**Comment by bogoljub1234** [comment]
Teme

**Comment by PiweeX** [comment]
@bogoljub1234 možeš davati mišljenja šta da se izmeni kako bi bilo bolje, ona će uzeti predloge u obzir ukoliko joj se svidi a i znači nam mišljenje drugih ljudi pre objavljivanja zbog salesa

inače je ovo neka vizuelna zamisao (valjda ovo smem da podelim)
![unknown](https://user-images.githubusercontent.com/33425430/174118559-b63352cb-64b5-48d3-8dc3-ad415335fc0b.png)
a

**Comment by bogoljub1234** [comment]
Moze, ja sam se prijavio za dizajnera pa ako treba nes cu napravit

**Comment by PiweeX** [comment]
Trenutno testiram Tebex platformu kako bi video na koji način se custom tema ubacuje.

**Comment by PiweeX** [comment]
![download](https://user-images.githubusercontent.com/33425430/174348500-ae93d055-f37f-4b58-abae-023de457db63.png)

ubacio sam Tebex plugin za Bukkit na Dev server na Hogu i verifikovao se i mogu vam reći da default sajt izgleda ovako

**Comment by PiweeX** [comment]
![download](https://user-images.githubusercontent.com/33425430/174348984-37b6dd67-a25f-450c-8c81-c0de6f9e622a.png)

ovde takođe imamo sreće, stvari poput blog dela, foruma i ostalog se ne dobija u monthly pretplatama na Tebex platformi,

ovo znači da ljudi zaista puno kupuju Tebex teme jer, slabo ko želi default sajt, bukvalno svako će kupiti temu

**Comment by PiweeX** [comment]
tako da prijatno sam iznenađen da nešto nije krenulo po zlu


i što više gledam temu od gore to mi se više sviđa struktura sajta, tj dobro je osmišljen raspored :D


font na headeru (gde pišeHome, Forums, Vote, Staff po meni nikako ne treba menjati) a ostali font gde je Top Customer da

**Comment by buducidzelat** [comment]
i meni se svidja
inace mogao sam isto ovako ja da ti uradim na wordpressu

**Comment by PiweeX** [comment]
Ne radimo WP jer su ovo teme, Lorena radi dizajn a 1 lik završava frontend tj kod u pozadini koji čini da sajt radi na svakom delu

**Comment by L0renaA** [comment]
(Malecni) Update
![image](https://user-images.githubusercontent.com/107634534/174489306-5cd3bf3e-cc31-4b59-8328-d132bc3b64ef.png)

**Comment by L0renaA** [comment]
*slucajno closed

**Comment by PiweeX** [comment]
odlično! Mnogo je bolje sa senkama

**Comment by PiweeX** [comment]
Posle nekoliko meseci se javljam uoči otvaranja Java Store platforme i mogu reći da za sad Front i verovatno još 1 osoba uči webflow kako bi imali kvalitetnu platformu

**Comment by PiweeX** [comment]
Sajt kompanije postoji već jako dugo i generalno sam zadovoljan kako je ispao ali zbog promena oko Java Store platforme smo odlučili da napravimo sajt od 0 iznova,

obzirom da se Marketplace deo premestio na budući Java Store tačnije marketplace za kodove sajt kompanije više neće imati Marketplace deo kao što je do sad imao

![download](https://user-images.githubusercontent.com/33425430/213930261-d51e4f75-e4b6-4ab5-9d43-216b7a27f829.png)

već će to jelte biti na Java Store platformi kako bi bilo bolje organizovano.

Što se tiče sajta kompanije on će sadržati deo sa uslužnim radom iako smo pre 3 meseca totalno prekinuli sa uslužnim radom svakako nam je u budućnosti bio cilj uslužni rad za veće klijente što smo sad i u mogućnosti i prednosti jer kroz prototipe svih naših kodova možemo da radimo i kao agencija uslužno

Ovo je deo trenutnog sajta koji više uskoro neće biti u funkciji,
https://hogostudios.com/ 

![download](https://user-images.githubusercontent.com/33425430/213930098-52cc817e-999e-44ca-a226-2a5b71f1f11b.png)

 ovde ću obaveštavati i slati proces slike kako novi sajt bude napredovao
 (trenutni sajt neće biti isključivan dok novi ne bude pri kraju.)

**Comment by PiweeX** [comment]
slika sajta od gore je inače uveličana kako bi se ceo sajt video, dosta lep sajt ali nije funkcionalan za ono što nama treba u buduće

inače pre neki dan je 1 osoba primljena na obuku oko pravljenja sajtova, sutra će biti još 1 i tražio sam još 1 osobu iz DAO ali niko nema to znanje pa ćemo verovatno zaposliti Lorenu kao treću osobu jer je pre par meseci radila sajt od gore na kojem smo napravili veću pauzu iz drugih razloga

**Comment by PiweeX** [comment]
Sajtovi koji će u narednom periodu biti izrađeni iznova jer se prebacuju u worldpress

Glavni sajt [hogostudios.com](http://hogostudios.com/)
Sajt za plugin https://tradingflow.shop/
Sajt za plugin [autofakeplayers.com](http://fakeplayers.com/)

+ novi sajt Java Store

Templateovi za teme koje će biti napravljene za Java Store marketplace


Saas landing page tema 1
Digital agency tema 1
NFT marketplace tema 1
Hosting marketplace tema 1
Personal portfolio tema 1
Web hosting tema 1

(za svaku temu će biti 5 različitih varijanti)

**Comment by PiweeX** [comment]
Juče sam tokom dana još uređivao novi sajt kompanije, sutra ću pisati strukturu za njega kako bi se preuredio

**Comment by PiweeX** [comment]
Outra verovatno radimo na prvom webflow sajtu za 1 Minecraft server, pre 9 meseci u webflow-u sam radio za Hog ali mi se nije svideo

**Comment by PiweeX** [comment]
Alati

Spline - 3d dizajn alat

Icons8 - ilustracije ux

**Comment by PiweeX** [comment]
Od kraja meseca bi trebalo da se krene sa ovim

**Comment by PiweeX** [comment]
![PiweeeX_website_for_webflow_agency_1f3702ec-63ca-471d-99cc-6b14f0383b56](https://user-images.githubusercontent.com/33425430/218896402-af11c0e7-1d54-4255-be4a-7669d28de95e.png)
!
![PiweeeX_ui_ux_landing_page_for_game_server_c7db67e4-1ff8-454e-83d0-427685cc5a99](https://user-images.githubusercontent.com/33425430/218896420-303dc098-592b-441f-8948-2a50101e4c43.png)
![PiweeeX_Ui_layouts_for_a_landing_page_715578c3-94bb-45fc-9f82-e873f49dd49b](https://user-images.githubusercontent.com/33425430/218896426-76519675-d0bc-49c2-a09d-2130c2a83703.png)

Ttt

**Comment by PiweeX** [comment]
Figma to webflow opcija je stigla na Figmu što mi je dosta drago jer će to znatno olakšati posao pravljenja sajtova

**Comment by PiweeX** [comment]
U petak krećemo sa osmišljavanjem plana za ovo

**Comment by PiweeX** [comment]
Evo kako trenutno izgleda novi dizajn novog websajta Hogo kompanije

![Screenshot_2023-02-25-16-23-58-203_com brave browser](https://user-images.githubusercontent.com/33425430/221365246-519068f6-35d3-45c4-b6bd-96c84ad7abf2.jpg)

**Comment by PiweeX** [comment]
> (Malecni) Update ![image](https://user-images.githubusercontent.com/107634534/174489306-5cd3bf3e-cc31-4b59-8328-d132bc3b64ef.png)

iz ovoga u ovo. Ovo je samo nekoliko meseci napretka, issue je otvoren 16. Juna prošle godine a danas imamo profesionalne sajtove za naše softvere i plugine. Naravno tu ima još dosta da se radi, u svakom slučaju prejako izgleda za sad
