### ISSUE TITLE
Macke na Decentralandu

### ISSUE THREAD

**Issue by Skyakanebo** [PiweeX/HogRealms#37]
Macke na serveru su odlicna prilika da se doda jos mobova na HogRealms iako ne rade nista posebno, mogu da budu kucni ljubimci i pomazu u rp

**Comment by Skyakanebo** [comment]
Piwex mi je rekao da otvorim i svesna sam da imaju macke u mc, ali ne i na Hogu

**Comment by akipaki293** [comment]
> Piwex mi je rekao da otvorim i svesna sam da imaju macke u mc, ali ne i na Hogu

Ok, zar se ne spawnaju?

**Comment by akipaki293** [comment]
A joj da samo kod villigera se spawna zaboravio sam

**Comment by PiweeX** [comment]
Sviđa mi se zapažanje da na Hogu nema mačaka, nema jer se ne spawnuju a ne spawnuju se pošto seljaka nema

može, ukoliko se izglasa do dovoljnog broja glasova do ponedeljka 2 mačke će biti stvorene posebno za Sky što će dodatno poboljšati RP i ekonomiju prodaje

**Comment by akipaki293** [comment]
Sky ja kupujem 2 macke kad ih naparis

**Comment by Coplek** [comment]
> 



> Sviđa mi se zapažanje da na Hogu nema mačaka, nema jer se ne spawnuju a ne spawnuju se pošto seljaka nema
> 
> može, ukoliko se izglasa do dovoljnog broja glasova do ponedeljka 2 mačke će biti stvorene posebno za Sky što će dodatno poboljšati RP i ekonomiju prodaje

Jesi za da zatvorimo glasanje u 23:00?

**Comment by Coplek** [comment]
Macke su izglasane macke se ubacuju piweex daj joj

**Comment by PiweeX** [comment]
potrebno je još glasova, minimum 10 za ovako nešto

u ponedeljak jutru zatvaramo glasanje
