### ISSUE TITLE
Psi na Decentralandu

### ISSUE THREAD

**Issue by akipaki293** [PiweeX/HogRealms#38]
Pošto nema pasa na serveru, da li bih mogao dobiti 2 Psa da pokrenem biznis, posto moj grad u Ostrvskoj Uniji će biti centar trgovine u Okeaniji, voleo bih prodavati pse, konje i mačke, a pasa nema nigde.

**Comment by Coplek** [comment]
vec postoje

**Comment by NemanjaRusija** [comment]
> vec postoje

Valjda misli na one prave kao iz rl

**Comment by akipaki293** [comment]
..
