### ISSUE TITLE
Vote

### ISSUE THREAD

**Issue by PiweeX** [PiweeX/HogRealms#39]
Posle ban sistema za celokupan realms treba popraviti i konačno omogućiti vote i napraviti mu nagrade

već znam da će nagrade biti custom itemi manje vrednosti ali pišite šta mislite da bi bila ok nagrada za osobe koje svakog dana glasaju na /vote 

(nagrade idu automatski)

**Comment by JaSamIgor** [comment]
> Posle ban sistema za celokupan realms treba popraviti i konačno omogućiti vote i napraviti mu nagrade
> 
> već znam da će nagrade biti custom itemi manje vrednosti ali pišite šta mislite da bi bila ok nagrada za osobe koje svakog dana glasaju na /vote
> 
> (nagrade idu automatski)

Osim custom itema mislim da bi se trebali dobijati zupcanici (metalni, zlatni i dijamantski) i možda po neka enčentovana knjiga

**Comment by PiweeX** [comment]
hvala na ideji, ovo će biti totalno sam zaboravio na zlatne i dijamantske zupčanike. Enčentovane knjige neće biti jer je ipak čaranje zanimljivije i zahteva više truda a ovo je nepotrebno tek tako dobiti knjigu

**Comment by ConeBe** [comment]
Da se nađemo na pola puta

**Comment by ConeBe** [comment]
Pola ulice, i pola uzdaha

**Comment by PiweeX** [comment]
![Screenshot_2022-06-17-15-29-15-621_com android chrome](https://user-images.githubusercontent.com/33425430/174307920-db451d61-9b08-4e72-889c-c35e0051abd7.jpg)

**Comment by PiweeX** [comment]
![Uploading IMG_20220617_153208.jpg…]()

**Comment by PiweeX** [comment]
![Uploading IMG_20220617_153208.jpg…]()

**Comment by PiweeX** [comment]
Votingplugin ima problema sa time da Mysql ne prepoznaje vote na ip-u

**Comment by PiweeX** [comment]
![Uploading IMG_20220617_153723.jpg…]()

**Comment by PiweeX** [comment]
![Uploading IMG_20220617_153723.jpg…]()
