### ISSUE TITLE
Mrmidoni na Decentralandu

### ISSUE THREAD

**Issue by PiweeX** [PiweeX/HogRealms#40]
![download](https://user-images.githubusercontent.com/33425430/174153542-1b22edb6-5a02-4ffd-8965-5672478eee52.png)

Pošto je odrađen pokušaj da se na server dodaju kamile i još neke stvari vezane za sve pustinjske biome Mrmidoni su se zbagali nakon čega nikad nisu stvoreni na serveru, neki su ih videli a neki nikada

trenutno se gleda da se to reši
![download](https://user-images.githubusercontent.com/33425430/174153898-344b70d6-f8db-4bd5-b5cd-0efaf97e6ebf.png)

**Comment by PiweeX** [comment]
igrači će sutra posle podne moći da vide mrmidone na serveru

**Comment by ConeBe** [comment]
Šta je mrmidon

**Comment by ConeBe** [comment]
Konj-kamila

**Comment by PiweeX** [comment]
Mrmidoni i pevačice uspešno integrisane u server!
