### ISSUE TITLE
Mapa. predlog ZSSa (da Narod i PiweeeX budu zadovljni)

### ISSUE THREAD

**Issue by DzingisKan** [PiweeX/HogRealms#41]
UN je zapoceo kao roleplay ideja. Danas je osnovni sustav prijava i kažnjavanja na roleplayu.

Predstavljam ZSS ideju stvaranja rolaplaya GIS-a (Geografski Informacijski Sustav)

KAKO OZNAČITI TERITORIJ?
-Teritorij se smatra sve pod Claimom i moralni dio koji nije claiman, odnosno ako imamo grad claiman u državi, a ta država ima zaseban claim preko cele teritorije, razmak između claima grada i claima države spada na kartu.

-Šalje se skica teritorije Kartografu u zaseban kanal koji ćemo izraditi, a mogu ga preuzeti i već postojeći sustavi za karte

-Kartograf ima pristup TP komandi te odlazi i provjerava legitimitet skice koji je dobio te ga ucrtava u Kartu

ŠTO ONDA KARTA PRIKAZUJE?
-Karta prikazuje samo već zauteti dio teritorije na kojem se strogo odvija aktivnost neke države, odnosno imaju ceste, gradove ili slično. 

ŠTO JE ZABRANJENO?
-uzimanje teritorije na kojoj se ne izvršava roleplay
-uzimanje teritorije koja nije dio claima ili nije u moralnoj i neposrednoj blizini claima
-uzimanje teritorije u kojoj je aktivnost neke druge države koja još nije stigla claimati teritorij
-trgovanje i ratovanje za teritoriju

Ova ideja  karte podliježe PiweeeXovim uvjetima za kartu. Imati ćemo preglednu sliku svih teritorija.

ZSS - Za pravedan server

**Comment by BaatarovaKrv** [comment]
Mongolski način borbe protiv korupcije na serveru, na kraju svega videće se ko je bio u pravu... Hvala (•‿•)

**Comment by vukstrale** [comment]
Uhm, okej. Vreme je da pravim kuće po antartiku. Dirt Shack Speedrun

**Comment by PiweeX** [comment]
napomenuću da se nations komanda vraća na hog posle 6 meseci, dakle stvar je u tome da za ovo što je napisano gore da ako 1 država ima odvojene claimove to spadne u političku kartu će se realizovati ali na drugi način

dakle, nations komanda ima opciju da velike države stvore naciju u kojoj će biti više gradova (u nekom slučaju plemena u nekom slučaju naroda)

samim tim, oni imaju savršeni sistem gde svaki unapređeni igrač koji vodi 1 pleme u državi ima vođstvo nad određenim claimom a sve je to spojeno u JEDAN veliki claim


usput, običan claim za običan land idalje radi, to znači da bi i novi igrači mogli da prave svoja mesta, neko će sam neko sa društvom iz škole nevezano za ceo sistem odvojeno od svih, onda bi bilo dobro da možda lands claim ima ograničen broj chunkova a da nacije nemaju limit


svakako, nacije se moraju testirati kako bi se usavršile, kreiranje nacije se jednokratno plaća x sumu i sad npr u nacije bi spadale npr Engleska, u sklopu Engleske imaju lupam Kraljevina Engleska i ostale

ili bolji primer, Japan, sve je sklop Japana a tu ima više vlastelina tj više plemena i samim tim kultura, samim tim se RP mnoogo bolje razvija jer se plemena među sobom nadmeću što je next level
