### ISSUE TITLE
Da se hogrealms ukine na githubu

### ISSUE THREAD

**Issue by NemanjaRusija** [PiweeX/HogRealms#42]
Skoro svima nama je već github smorio. Zašto? Zato što igrači imaju preveliku slobodu da pišu i stavljaju šta hoće. Pravi primjer je za prijedlog da se ratko banuje. Ako se to desi onda će svako neko staviti membera hoga da se bana. Nisam se nikada bunio ali moram priznati da se PRETJERALO.

**Comment by PiweeX** [comment]
Pa, šta je tu loše

ako za nekog igrača postoji određena kritika u masi i ako zaista pravi probleme, ljudi će napraviti pobunu tj napraviće glasanje šta da se uvede na serveru ili ko da se banuje ukoliko je to potrebno

svakako, nevini ljudi neće biti banovani jer što bi onda svi glasali za da se kazne ako ništa nisu skrivili?

i da, ne može da vlada ono kolko je ljudi izglasalo, prvo se vidi ko su ti ljudi i zašto su to izglasali, dal je dovoljan broj ljudi izglasao

ne može da postoji hajka na nevine igrače bez razloga

**Comment by NemanjaRusija** [comment]
> Pa, šta je tu loše
> 
> ako za nekog igrača postoji određena kritika u masi i ako zaista pravi probleme, ljudi će napraviti pobunu tj napraviće glasanje šta da se uvede na serveru ili ko da se banuje ukoliko je to potrebno
> 
> svakako, nevini ljudi neće biti banovani jer što bi onda svi glasali za da se kazne ako ništa nisu skrivili?
> 
> i da, ne može da vlada ono kolko je ljudi izglasalo, prvo se vidi ko su ti ljudi i zašto su to izglasali, dal je dovoljan broj ljudi izglasao
> 
> ne može da postoji hajka na nevine igrače bez razloga

Ne kažem ali doći će neko dijete i optužiti nekoga pa će pozvati cijelu državu ili svoje drugove da glasaju. Pa će se početi po githubu svađali i itd... Po meni više bih volio da se na hog discord serveru otvori soba sa prijedlozi pa da napišu pa ti px i tvoj staff team odluče da li će taj prijedlog biti usvojen.

**Comment by DzingisKan** [comment]
> Skoro svima nama je već github smorio. Zašto? Zato što igrači imaju preveliku slobodu da pišu i stavljaju šta hoće. Pravi primjer je za prijedlog da se ratko banuje. Ako se to desi onda će svako neko staviti membera hoga da se bana. Nisam se nikada bunio ali moram priznati da se PRETJERALO.

ovu ideju podržat ću jedino ako se nađe način da se ljude koji su ugrozili server ukloni

**Comment by markeccc998** [comment]
> Skoro svima nama je već github smorio. Zašto? Zato što igrači imaju preveliku slobodu da pišu i stavljaju šta hoće. Pravi primjer je za prijedlog da se ratko banuje. Ako se to desi onda će svako neko staviti membera hoga da se bana. Nisam se nikada bunio ali moram priznati da se PRETJERALO.

Isk smorio github

**Comment by ConeBe** [comment]
Meni jedan frape sa mlekom

**Comment by dzelat** [comment]
Github nije los ako se pravilno koristi, ali eto imamo slucejve gdje se ovo iskoristava na glup nacin

**Comment by konfix** [comment]
> Skoro svima nama je već github smorio. Zašto? Zato što igrači imaju preveliku slobodu da pišu i stavljaju šta hoće. Pravi primjer je za prijedlog da se ratko banuje. Ako se to desi onda će svako neko staviti membera hoga da se bana. Nisam se nikada bunio ali moram priznati da se PRETJERALO.

Da, koliko god on pravio sranja na serveru opet postoje grupice koje teraju svakoga da glasa za/protiv po discord serverima. Glupo je da dovodimo bilo koga do bana ako glasanje nije iskreno već forsirano od strane nekog drugog. U teoriji bi onda svako mogao da bude banovan ako se skupi dovoljan broj ljudi koji bi radili sta im se kaže...

Iskreno mislim da sad svako ima previše slobode, staffu treba ostaviti da kažnjava, naravno sve to bi trebalo da bude javno i pravično, ne da se igrači kažnjavaju jer se nekome tako može.

**Comment by NemanjaRusija** [comment]
> > Skoro svima nama je već github smorio. Zašto? Zato što igrači imaju preveliku slobodu da pišu i stavljaju šta hoće. Pravi primjer je za prijedlog da se ratko banuje. Ako se to desi onda će svako neko staviti membera hoga da se bana. Nisam se nikada bunio ali moram priznati da se PRETJERALO.
> 
> Da, koliko god on pravio sranja na serveru opet postoje grupice koje teraju svakoga da glasa za/protiv po discord serverima. Glupo je da dovodimo bilo koga do bana ako glasanje nije iskreno već forsirano od strane nekog drugog. U teoriji bi onda svako mogao da bude banovan ako se skupi dovoljan broj ljudi koji bi radili sta im se kaže...
> 
> Iskreno mislim da sad svako ima previše slobode, staffu treba ostaviti da kažnjava, naravno sve to bi trebalo da bude javno i pravično, ne da se igrači kažnjavaju jer se nekome tako može.

Opet ću ponoviti. Ne kažem ali doći će neko dijete i optužiti nekoga pa će pozvati cijelu državu ili svoje drugove da glasaju. Pa će se početi po githubu svađali i itd... Po meni više bih volio da se na hog discord serveru otvori soba sa prijedlozima pa da napišu prijedlog pa px i njegov staff team odluče da li će taj prijedlog biti usvojen.

**Comment by VukIcrnogorskii** [comment]
> > Skoro svima nama je već github smorio. Zašto? Zato što igrači imaju preveliku slobodu da pišu i stavljaju šta hoće. Pravi primjer je za prijedlog da se ratko banuje. Ako se to desi onda će svako neko staviti membera hoga da se bana. Nisam se nikada bunio ali moram priznati da se PRETJERALO.
> 
> Da, koliko god on pravio sranja na serveru opet postoje grupice koje teraju svakoga da glasa za/protiv po discord serverima. Glupo je da dovodimo bilo koga do bana ako glasanje nije iskreno već forsirano od strane nekog drugog. U teoriji bi onda svako mogao da bude banovan ako se skupi dovoljan broj ljudi koji bi radili sta im se kaže...
> 
> Iskreno mislim da sad svako ima previše slobode, staffu treba ostaviti da kažnjava, naravno sve to bi trebalo da bude javno i pravično, ne da se igrači kažnjavaju jer se nekome tako može.

Slažem se,
Moj prijedlog je ako je već došlo vrijeme da možeš bilo koga kad god oćeš da prijaviš za ban, ukoliko rezultati zaista budu prevagnuli u korist bana da se onda organizuje javno suđenje i pravo suđenje đe bi se igrač branio, a dželat davao podatke za ban sakupljene od strane osoba koje su optužile tog igrača.

**Comment by konfix** [comment]
> > > Skoro svima nama je već github smorio. Zašto? Zato što igrači imaju preveliku slobodu da pišu i stavljaju šta hoće. Pravi primjer je za prijedlog da se ratko banuje. Ako se to desi onda će svako neko staviti membera hoga da se bana. Nisam se nikada bunio ali moram priznati da se PRETJERALO.
> > 
> > 
> > Da, koliko god on pravio sranja na serveru opet postoje grupice koje teraju svakoga da glasa za/protiv po discord serverima. Glupo je da dovodimo bilo koga do bana ako glasanje nije iskreno već forsirano od strane nekog drugog. U teoriji bi onda svako mogao da bude banovan ako se skupi dovoljan broj ljudi koji bi radili sta im se kaže...
> > Iskreno mislim da sad svako ima previše slobode, staffu treba ostaviti da kažnjava, naravno sve to bi trebalo da bude javno i pravično, ne da se igrači kažnjavaju jer se nekome tako može.
> 
> Slažem se, Moj prijedlog je ako je već došlo vrijeme da možeš bilo koga kad god oćeš da prijaviš za ban, ukoliko rezultati zaista budu prevagnuli u korist bana da se onda organizuje javno suđenje i pravo suđenje đe bi se igrač branio, a dželat davao podatke za ban sakupljene od strane osoba koje su optužile tog igrača.

previše je to, ne znam zašto vam je zanimljivo da mučite staff hahaha

**Comment by konfix** [comment]
> > > Skoro svima nama je već github smorio. Zašto? Zato što igrači imaju preveliku slobodu da pišu i stavljaju šta hoće. Pravi primjer je za prijedlog da se ratko banuje. Ako se to desi onda će svako neko staviti membera hoga da se bana. Nisam se nikada bunio ali moram priznati da se PRETJERALO.
> > 
> > 
> > Da, koliko god on pravio sranja na serveru opet postoje grupice koje teraju svakoga da glasa za/protiv po discord serverima. Glupo je da dovodimo bilo koga do bana ako glasanje nije iskreno već forsirano od strane nekog drugog. U teoriji bi onda svako mogao da bude banovan ako se skupi dovoljan broj ljudi koji bi radili sta im se kaže...
> > Iskreno mislim da sad svako ima previše slobode, staffu treba ostaviti da kažnjava, naravno sve to bi trebalo da bude javno i pravično, ne da se igrači kažnjavaju jer se nekome tako može.
> 
> Opet ću ponoviti. Ne kažem ali doći će neko dijete i optužiti nekoga pa će pozvati cijelu državu ili svoje drugove da glasaju. Pa će se početi po githubu svađali i itd... Po meni više bih volio da se na hog discord serveru otvori soba sa prijedlozima pa da napišu prijedlog pa px i njegov staff team odluče da li će taj prijedlog biti usvojen.

to se već dešava, video sam da na nekim discord serverima pozivaju ljude da glasaju za ban

**Comment by PiweeX** [comment]
Što se tiče konkretno banova, mislim da će to prestati kad se završe slučajevi za pojedince po put Srbende kao što je sad, tu je najzeznutije jer se stvori 2 grupe i to ničemu ne vodi a u drugim stvarima je lakše da svako ima neko svoje mišljenje kao npr šta treba da bude na vote nagradama ili slično
