### ISSUE TITLE
Koga bi ste još voleli videti kao dzelata?

### ISSUE THREAD

**Issue by BaatarovaKrv** [PiweeX/HogRealms#46]

**Comment by bogoljub1234** [comment]
Mene sigurno ne😔

**Comment by NemanjaRusija** [comment]
Mene hahaha

**Comment by bogoljub1234** [comment]
Nemanju*

**Comment by markeccc998** [comment]
Takodje nemanju i coneta i mene:)

**Comment by bogoljub1234** [comment]
Sta ti markec

**Comment by markeccc998** [comment]
> Sta ti markec

Bogoljube nr dipr

**Comment by bogoljub1234** [comment]
?

**Comment by NemanjaRusija** [comment]
Coneta imam potencijal za dželata

**Comment by ConeBe** [comment]
Pa gle, Px ako odluči da pita nekog za dželata, ono, svako će da se prijavi ako ćemo iskreno, naravno ja igram od početka januara možda čak i kraj decembra više i ne sećam, ali ako Px da, naravno da će svako biti srećan 👍🏼

**Comment by NemanjaRusija** [comment]
> Pa gle, Px ako odluči da pita nekog za dželata, ono, svako će da se prijavi ako ćemo iskreno, naravno ja igram od početka januara možda čak i kraj decembra više i ne sećam, ali ako Px da, naravno da će svako biti srećan 👍🏼

Isto smo krenuli hahahahah

**Comment by bogoljub1234** [comment]
Ako cone bude dzelat napravit cu party da se proslavi, kao i inace i nemanja

**Comment by ConeBe** [comment]
Oba dvojica se zovemo Nemanja...

**Comment by ConeBe** [comment]
Samo je on poznatiji Nemanja

**Comment by bogoljub1234** [comment]
Neka

**Comment by ConeBe** [comment]
AHAHAHAHHA šta ćeš braća po moždane ćelije

**Comment by NemanjaRusija** [comment]
> AHAHAHAHHA šta ćeš braća po moždane ćelije

Samo ne isti grad

**Comment by buducidzelat** [comment]
Mene normalno

Mare

**Comment by markeccc998** [comment]
> Mene normalno
> 
> Mare

Niko ne želi tebe vidit

**Comment by markeccc998** [comment]
Zezam se ne smem rizikovati da me izbaci iz coc klana

**Comment by bogoljub1234** [comment]
Sta se svađate px ce odabrati kad ce mu zatrebati

**Comment by buducidzelat** [comment]
> Zezam se ne smem rizikovati da me izbaci iz coc klana

upravo tako

**Comment by Coplek** [comment]
trenutno nam ne treba novi dzelat, mislim da ovako nitko nece dobiti dzelata, osobno ni jedan dzelat se nece sloziti
