### ISSUE TITLE
Samostalni predlog za novog dzelata (d_mch) *PREZENTACIJA*

### ISSUE THREAD

**Issue by BaatarovaKrv** [PiweeX/HogRealms#47]
-Na predlog koji je Gengish Khan trebao da predloži adminu servera, ja bi spadao u jedan od 5 igraca sa servera koji bi mogli da u skorijem periodu postanu dzelati

-Nisam ovde da govorim o drugima, već samo o sebi i zašto bi ja hteo i mislim da bi mogao da obavljam tu funkciju na serveru:

1. Nikad nisam bio osuđivan
2. Nemam dosije lošeg konteksta o radnjama na serveru
3. Na serveru sma počeo da igram 29. Novembra 2021. godine, jako sam dugo ovde, sa kraćim prekidima i pauzama, ali sam zato jako dobro upoznat da serverom
4.Poštovanje demokratije i donošenje normalnih i ispravnih odluka donetim u mogućim situacijama
5. Nadprosečna aktivnost na serveru u toku dana, a tek pogotovo u periodu sledećeg letnjeg raspusta
6. Lojalnost i vernost kako serveru tako i državi u kojoj sam sad....

-Od ovog određenog i preciznog vremena koliko sam već na serveru, bavio sam se raznim stvarima koje su bile jako usko vezane sa community-em na njemu i učestvovao koliko god sam mogao u razvoju kako servera tako i ljudi na njemu

1. Hog Competitions
2. Hog Media - YT kamp
3. Kvizovi
4. Wiki moderator

-Verujem, a cak mogu i da potvrdim da cu de jos dugo zadržati na serveru.... Sada kada se pojavila ta vunkcija koja se dodeljuje posebnim igračima koji su se u određenom periodu istakli na istom voleo bi i ja da pokušam isto... Imam želu da postanem dzelat radi svoje zabave ali ne u kontekstu na koji bi ste prvo pomislili, a drugi bi naravno bio u kratkim crtama suzbijanje osoba čije bi ponašanje svrstao u:

1. Širenje mržnje
2. Toxičnost
3. Nacionalizam
4. Abjuz
5. Krađa
6. Laganje
7. Scam

-Molim da pre svega razmišljate racionalno kad donosite bilo koju odluku koju bi ste iskazali ovde, samo budite iskreni... Hvala

                                                                              d_mch

**Comment by buducidzelat** [comment]
mislim da bih ja bio bolji hehe

**Comment by ConeBe** [comment]
Px će sam odlučit bruh, jebo više

**Comment by BaatarovaKrv** [comment]
> Px će sam odlučit bruh, jebo više

Legendo nebi ja ovo pravio da mi on nije rekao

**Comment by ConeBe** [comment]
Legendice ne kažem tebi

**Comment by Coplek** [comment]
Ovakvo prihvacanje dzelata nije moguce, mogu ja tako postaviti prijavu za ownera servera... dzelati i px odlucuju tko ce postati, a i trenutno nas je dovoljno lock

**Comment by dzelat** [comment]
Ovo je suludo, na ovakav nacin birati staff jednog kzbiljnkg servera mi je neprihvatljivo i **glupo***

**Comment by JaSamIgor** [comment]
Ovakav način biranja staffa je glupo a čovjek koji se prijavio za dželata je još gluplji

**Comment by dzelat** [comment]
> Ovakav način biranja staffa je glup a čovjek koji se prijavio za dželata je još gluplji

Gagagaga istina

**Comment by ConeBe** [comment]
> Ovakav način biranja staffa je glup a čovjek koji se prijavio za dželata je još gluplji

Mongol momenat Igore ☕

**Comment by JaSamIgor** [comment]
> > Ovakav način biranja staffa je glup a čovjek koji se prijavio za dželata je još gluplji
> 
> Mongol momenat Igore ☕

☕

**Comment by VukIcrnogorskii** [comment]
> > Ovakav način biranja staffa je glup a čovjek koji se prijavio za dželata je još gluplji
> 
> Mongol momenat Igore ☕

Inc ko je ovaj brat

**Comment by BaatarovaKrv** [comment]
> > > Ovakav način biranja staffa je glup a čovjek koji se prijavio za dželata je još gluplji
> > 
> > 
> > Mongol momenat Igore ☕
> 
> ☕

Sine moj ja sam 1l5 predlozenih, ako znas da citas onda ces skontati pocetak

**Comment by JaSamIgor** [comment]
> > > > Ovakav način biranja staffa je glup a čovjek koji se prijavio za dželata je još gluplji
> > > 
> > > 
> > > Mongol momenat Igore ☕
> > 
> > 
> > ☕
> 
> Sine moj ja sam 1l5 predlozenih, ako znas da citas onda ces skontati pocetak

☕

**Comment by VukIcrnogorskii** [comment]
Po ovim statistikama kazes od 2021 si, onda bi ja trebao bit prestolonasljednik servera,  a ne dzelat hahahahaha

**Comment by ConeBe** [comment]
> > > Ovakav način biranja staffa je glup a čovjek koji se prijavio za dželata je još gluplji
> > 
> > Mongol momenat Igore ☕
> 
> Inc ko je ovaj brat

ja sam Cone, a ovaj BaatarovaKrv je onaj Deutchi iz Mongolije

**Comment by BaatarovaKrv** [comment]
> Po ovim statistikama kazes od 2021 si, onda bi ja trebao bit prestolonasljednik servera, a ne dzelat hahahahaha

Ma ti si najjaci

**Comment by VukIcrnogorskii** [comment]
> > > > Ovakav način biranja staffa je glup a čovjek koji se prijavio za dželata je još gluplji
> > > 
> > > 
> > > Mongol momenat Igore ☕
> > 
> > 
> > Inc ko je ovaj brat
> 
> ja sam Cone, a ovaj BaatarovaKrv je onaj Deutchi iz Mongolije

Realno po svemu ovome bi ja trebao za dzelata ic (ako izuzmemo dio sa osudjivanjem) hahahahahhahahahahaha

**Comment by ConeBe** [comment]
pa ne kako kaže Čoplek, oni to jest Dželati i Admini odlučuju koga će staviti za novog dželata,tkd ne znam zašta ovo

**Comment by VukIcrnogorskii** [comment]
> pa ne kako kaže Čoplek, oni to jest Dželati i Admini odlučuju koga će staviti za novog dželata,tkd ne znam zašta ovo

Self promo

**Comment by Lenna672** [comment]
baatar je kul!

**Comment by dzelat** [comment]
> baatar je kul!

ne lijepo lagati ljude...

**Comment by Ratko7** [comment]
Bukvalno ni ne znam ko si a i puca mi ono dole, ne treba nam drugi zlaja

**Comment by BaatarovaKrv** [comment]
> Bukvalno ni ne znam ko si a i puca mi ono dole, ne treba nam drugi zlaja

Idi lečini negde drugde svoje komplekse

**Comment by BaatarovaKrv** [comment]
> > > > > Ovakav način biranja staffa je glup a čovjek koji se prijavio za dželata je još gluplji
> > > > 
> > > > 
> > > > Mongol momenat Igore ☕
> > > 
> > > 
> > > Inc ko je ovaj brat
> > 
> > 
> > ja sam Cone, a ovaj BaatarovaKrv je onaj Deutchi iz Mongolije
> 
> Realno po svemu ovome bi ja trebao za dzelata ic (ako izuzmemo dio sa osudjivanjem) hahahahahhahahahahaha

Realno nebi trebao

**Comment by BaatarovaKrv** [comment]
> > baatar je kul!
> 
> nije lijepo lagati ljude...

Proteran čovek iz mongolije došao da keči komolekse

**Comment by buducidzelat** [comment]
Damijane smiri se
