### ISSUE TITLE
Zlaja za Ownera

### ISSUE THREAD

**Issue by dzelat** [PiweeX/HogRealms#49]
Nema opisa-Zlaja za Ownera!

**Comment by konfix** [comment]
slazem se, zivela mongolija 🇲🇳🇲🇳🇲🇳🇲🇳🇲🇳

**Comment by ConeBe** [comment]
Zlaja pobeđuje u glasovima!!!

**Comment by buducidzelat** [comment]
maybe yes maybe not

**Comment by PsihoKing** [comment]
Bolje ne

**Comment by dzelat** [comment]
> Bolje ne

Znam, znam ovo je bilo ironicno
