### ISSUE TITLE
Predlažem sledeće: (ODGOVORENO)

### ISSUE THREAD

**Issue by XDrock** [PiweeX/HogRealms#493]
Da se namesti da kada se napiše nešto u chatu piše iz koje nacije je igrač
Da kada kucas, postojece komande ne budu crvene
Da se vrati dynamap za pc
Da marihuana ne smanjuje fps
Da smislite neku caku za dobijanje netherite i diamond armora (Moj predlog je da se sve stvari od diamonda mogu napraviti, ali to vi odlučite)
Da se pored /laputa, doda komanda /shop gde će se sve moći prodavati (ali ne igračima nego serveru) za novac

**Comment by PiweeX** [comment]
Da se namesti da kada se napiše nešto u chatu piše iz koje nacije je igrač


radimo na tome


Da kada kucas, postojece komande ne budu crvene
dobar predlog, ako mozes napravi poseban issue za ovo samo da imamo za kasnije kad budemo zavrsavali cet

Da se vrati dynamap za pc
nije moguce, postoji BlueStacks za ko ne zeli preko telefona

Da marihuana ne smanjuje fps
reseno zanaveka, marihuana i grozdje su od sutra posle restarta izbrisani sa servera

Da smislite neku caku za dobijanje netherite i diamond armora (Moj predlog je da se sve stvari od diamonda mogu napraviti, ali to vi odlučite)
videli ste preuredjenje rewardsa, to je samo deo, slede novi armori nadam se sto pre


Da se namesti da kada se napiše nešto u chatu piše iz koje nacije je igrač
Da kada kucas, postojece komande ne budu crvene
Da se vrati dynamap za pc
Da marihuana ne smanjuje fps
Da smislite neku caku za dobijanje netherite i diamond armora (Moj predlog je da se sve stvari od diamonda mogu napraviti, ali to vi odlučite)

Da se pored /laputa, doda komanda /shop gde će se sve moći prodavati (ali ne igračima nego serveru) za novac
tip servera je takav da nije pozeljno dodati to, to ce ipak biti samo na Iznad Lapute podserveru kad krene 7.7.

**Comment by PiweeX** [comment]
PiweeeX — Today at 12:10 AM
za takav shop gde se kuca /shop nije ok, imali smo ga pre 4 godine i veruj mi to samo ulenji igrace, mozda vam naizlged deuje ok ali nije tako dobro
a lapute komanda je ok nego nju preuredjujemo
