### ISSUE TITLE
Da se vrati mapa svijeta, imamo i dobrog kartografa sad

### ISSUE THREAD

**Issue by VukIcrnogorskii** [PiweeX/HogRealms#5]
Valjalo bi da se vrati karta svijeta, ipak je rp a ne factions server, s time ne samo što bi svijet izgledao urednije nego bi bilo i državama mnogo lakše da komuniciraju, sarađujuz prave saveze(ekonomske i vojne)...
Politička mapa svijeta je veliki faktor na rp serverima i ne bi trebalo da je zanemarujemo!

**Comment by dzelat** [comment]
Sada kada je velik priliv novih igrača mislim da je to neizvedivo, treba uzeti u obzir da ima dosta igrača koji jos nemaju 14 godina i teško je objasniti kako to funkcionise. Mapa se svkako nije poštovala i UN je bio pun tiketa. Uskoro je opet tu live mapa gdje ćemo vidjeti sve klejmove (3D) i mislim da će još jedna karta u ovom slučaju politička biti potpuno nepotrebna.

**Comment by VukIcrnogorskii** [comment]
> Sada kada je velik priliv novih igrača mislim da je to neizvedivo, treba uzeti u obzir da ima dosta igrača koji jos nemaju 14 godina i teško je objasniti kako to funkcionise. Mapa se svkako nije poštovala i UN je bio pun tiketa. Uskoro je opet tu live mapa gdje ćemo vidjeti sve klejmove (3D) i mislim da će još jedna karta u ovom slučaju politička biti potpuno nepotrebna.

Svakako da svi ozbiljni roleplay serveri imaju i mapu claimova i politicku mapu, mi ovdje pokusavamo da napravimo ozbiljan community, znam da nije lako nosit se sa mnogo tiketa al i za to postoji rešenje, a to se zove politička mapa

**Comment by dzelat** [comment]
> > Sada kada je velik priliv novih igrača mislim da je to neizvedivo, treba uzeti u obzir da ima dosta igrača koji jos nemaju 14 godina i teško je objasniti kako to funkcionise. Mapa se svkako nije poštovala i UN je bio pun tiketa. Uskoro je opet tu live mapa gdje ćemo vidjeti sve klejmove (3D) i mislim da će još jedna karta u ovom slučaju politička biti potpuno nepotrebna.
> 
> Svakako da svi ozbiljni roleplay serveri imaju i mapu claimova i politicku mapu, mi ovdje pokusavamo da napravimo ozbiljan community, znam da nije lako nosit se sa mnogo tiketa al i za to postoji rešenje, a to se zove politička mapa

Koji serveri?

Prvo kada otvore tiket protiv nekoga ko je zauzeo "njihovu teritoriju" a ti isti imaju 3 chunka klejmovana mi moramo natjerati nekoga da obriše claim i zatvoriti ga, isti taj koji je prijavio drzi pola kontinenta na političkoj karti a na live karti ima 3-4 chunka jednostavno nema smisla.

**Comment by VukIcrnogorskii** [comment]
Naravno tu je gigant StoneWorks koji je izuzetno uspješan i ovog ljeta pravi treći svijet sa istom politikom kao i za Rathnir i Eldham! 
Pored njega imamo i manje EarthPol, Sabrim i mnoge druge servere!
Za stvaranje država postoje dogovaranja, i stavranja prije i čak opena, a za neaktivnost igrača zaslužno su škola, treninzi, socijalni život i mnogi drugi životni faktori, nekima Hag ili nešto drugo pak su tako u nemogućnosti da prošire svoj claim. Takođe na navede pobude nadovezaću se da se na GIGANTIMA claimuju samo gradovi i ti claimovi su mnogo značajnini, a ne cijele države, jer iako claimujes cijelu "zemlju koju smatras svojom" uvjek neko može da claimuje chunkove unutar nje jer ti nemaš para da priuštiš toliki claim.
Ovo na šta ti aludiraš je Factions sa mapom, a na šta ja napominjem je RolePlay!

**Comment by dzelat** [comment]
> Naravno tu je gigant StoneWorks koji je izuzetno uspješan i ovog ljeta pravi treći svijet sa istom politikom kao i za Rathnir i Eldham! 
> Pored njega imamo i manje EarthPol, Sabrim i mnoge druge servere!
> Za stvaranje država postoje dogovaranja, i stavranja prije i čak opena, a za neaktivnost igrača zaslužno su škola, treninzi, socijalni život i mnogi drugi životni faktori, nekima Hag ili nešto drugo pak su tako u nemogućnosti da prošire svoj claim. Takođe na navede pobude nadovezaću se da se na GIGANTIMA claimuju samo gradovi i ti claimovi su mnogo značajnini, a ne cijele države, jer iako claimujes cijelu "zemlju koju smatras svojom" uvjek neko može da claimuje chunkove unutar nje jer ti nemaš para da priuštiš toliki claim.
> Ovo na šta ti aludiraš je Factions sa mapom, a na šta ja napominjem je RolePlay!

Planirano je da cijena klejmanja bude svedena na minimum  cak je bilo prica i uvodjenju nacija pa bi tako mogli praviti i gradove, jednostavno znamo kako je to bilo prije. Ko od igrača će doći i tražiti dozvolu da bapravi državu na mjestu gdje nema claima, niko! Pola njih ne želi ni da pregleda tutorijale od po 5 minuta koji su sami uvod u igru. Meni prvom je bilo nejasno na prvom ulasku zasto ne mogu napraviti državu na mjestu gdje nema nikakvo obilježije da je to tvoje, npr tada je to bio jug balkana, kada sam dosao tu nije bilo nikakve naznake da je to CCG koja je imala mali claim u grckoj ili Lješ nisam siguran ali mi je rečeno da je balkan zauzet. Kada krene mainnet to nece biti izvodivo.

**Comment by VukIcrnogorskii** [comment]
Carevina Crna Gora je bila jasno raspoređena i u svakoj oblasti je imala grad što mogu potvrditi i svi igrači, samo na Balkanu imali smo 3 grada, na bliskom istoku 1, u Francuskoj 1, na Pirineju 2 i u sjevernoj africi 1. Ako nije bilo tu naznačeno da je Carevina Crna Gora na tom mjestu onda ne znam. Po tvojoj logici ja sad mogu da odem na primjer po sred Šumadije u nekakvu šumu i jer nijesam vidio Bilbord đe piše Srbija ja se ne obavezujem da poštujem državni integritet nego ću da posadim državu đe zgodno mjesto nađem!
Ukoliko neko dijete od 9 godina ne želi da poštuje pravila servera, kako si ti rekao ni tutorijal da pogleda, onda se svi možemo složiti da nam on ni ne treba. Ovo je ozbiljan community, sa ozbiljnim igračima i ozbiljnim roleplayom!

**Comment by PiweeX** [comment]
slažem se sa obojicom, obe opcije su mač sa dve oštrice

donekle razumem na koji način StoneWorks funkcioniše ali me zanima na koji način si mislio da mi to odradimo?


npr. uzmimo zemlju kao što je Mongolija, ta zemlja je predobro organizovana i početa da se gradi ali setite se dok je bila raspodeljena na gradove tačnije dok je svaki vođa grada u Mongoliji imao svoj claim, claim pod svojim vlasništvom, došlo je do svađe i Lizard se odvojio od Zlaje, to su situacije u kojima dželati dobiju nervne slomove jer ko će te gluposti da trpi..


E sad, kad Zlaji pripada čitav claim u Mongoliji tu ipak postoji neki red, nema više svađa i cepljenja, ako neko hoće da napusti jer se posvađao sa nekim iz države on se jednostavno preseli u drugu državu, preseli se jer ne može da proglasi nezavisnost jer tu ipak stoji claim


moj predlog je onda da se u 1 momentu od trenutnih većih država poput Bardonije, Japana, Engleske, Britanije itd formiraju statične države koje se neće pomerati i onda, nebitno je ko im je vođa u datom momentu jer jednom će biti jedan jednom drugi a igrači će ostati isti ili će dolaziti novi i biće priliv starih

ovo bi bilo dobro iz razloga što onda dobijamo nešto što se zove vezivanje za nešto, isto kao što se neko veže za Partizan ili Zvezdu, tako bi i recimo igrači Hoga za određene države, ideologije, ljude u njima itd a sve radi zabave.. Sve to utiče na to da Hog zadrži bukvalno svakog igrača koji igra, jer evo neće živeti u državi od 8godišnjaka koji se posvađao sa nekim i izbrisao claim, srušio sve i popljuvao server već u da se tako izrazim brendiranoj državi kao npr CCG koju predhodno nije statički formirao server već osoba koja je sposobna za tako nešto da osmisli napravi i vodi državu mesecima. To je pozitivno i zbog toga što bi se onda vrlo lako organizovali eventi u pojedinačnim državama, zamislite da Engleska ima 50 membera od tih da uzmemo da je minimum 20 aktivno dnevno i da rade na zajedničkim projektima u Engleskoj, a onda kad je recimo rat svih 50 državljana dođu i tako puta još 10 velikih država, mnogo utiče na brending i na to prepiranje i stalna nadmetanja tačnije zanimljivije je za igru više nego kad postoji 100 država koje slabo ko ume da formuliše kako treba
 

Međutim onda ratovi totalno gube svoju svrhu, ratovaćete ali ne za teritoriju zar ne? ko je onda pobednik? Mislim to možda čak i nije toliki problem jer bi se lako smislile svrhe ratova na drugi način

**Comment by frop1k** [comment]
Ovako, slažem se sa dosta toga što je rečeno ovde, od obe strane.

Kako rešiti te probleme:

- Pravimo zvaničnu mapu, koja ide u zaseban kanal na hog discordu.
- Odluke o claimovima donosimo samo uz konsenzus, ako njega ne bude, teritorija neka bude označena kao osporena.
- Treba utvrditi pravila o claimovima, tipa, radijus oko gradova koji može da se claima na geopol mapi. Da ne bude da ljudi claimaju zemlju na koju nemaju pravo.
- Mislim da je mnogo lakše novim, i mladim igračima da razumeju kako šta funkcioniše, jer je u pitanju mapa sveta, koju je i neko od 10 godina video bar 1000 puta i razume suštinu.

Ja se dobrovoljno javljam da pravim mapu, bar jednom nedeljno, vrv češće ako bude potrebe. I bez svadja, kako kaže staff, tako će i biti, što se mene tiče.

**Comment by PiweeX** [comment]
daću primer na ovo što sam pisao u predhodnom tekstu

Earthmc nema statičke claimove koji samo stoje, bukvalno ima milion claimova i provincija u svakoj državi, ovo je bolje jer je server decentralizovaniji tačnije bolje raspoređen ali da li je onda dobar? Nije, nije jer ko će imati motiv da igra ukoliko oće da živi lupam u Turskoj a tamo milijardu claimova u kojima igra 10 ljudi koji ni sami ne znaju što su tu i koji im je motiv igre


tako da, hajde da brendiramo države, to je bio moj predlog i pre ovog podservera pre godinu dana ali Miksa i još neki ljudi koji su stručniji tačnije koji su igrali na takvim serverima su rekli da bi to bilo preloše, svakako nebitno je jer se to lako ispravi tako što se uzmu najveće države

**Comment by dzelat** [comment]
Nije problem imati mapu, nas ovdje brine najvise to kako ce se drzave siriti uzet cu za primjer ccg znamo kako se sirila i kako je zavrsila, zavrsila je na cjelom sredozemlju. Za takve mape potrebno je oformiti cijelu komisiju kako bi se to održavalo obako kako treba a ne da se samo ucrtava po necijim hirovima. Zato ako dodje do toga da se uvede zelio bih biti taj clan komisije i aktivno ucestvovati u svemu. I jednom sedmicno da se održi sastanak komisije lrije ucrtavanja. 


**Ali želim napomenuti da sam jasno za to da je bez karte bolje**

**Comment by VukIcrnogorskii** [comment]
Ima jedna stvar, kada dođe war komanda i neko deklariše rat, da uzmemo za primjer Mongoliju, Mongoliji CIJELI Zlajin claim se briše. I šta će on onda, do tada vjerovatno nije ni izašao iz onog duga bez kraja, a mora opet da claimuje cijelu državu jer mu je neko declerao rat.
Zato postoje političke mape koje jasnl govore ko je đe i šta se tu radi. Kada stigne war komanda biće bolji rp jer manje nacije koje hoće nezavisnost će se buniti i praviti mreže u državi kako bi oborile vlast i promijenile ideologiju, dobile nezavisnost ili nešto drugo. Zato smatram da je politička mapa dobra opcija za jedan uspješni RolePlay server.
Ako već imamo mogućnosti i dobrovoljce zašto to i da ne iskoristimo, pa jel da.
Takođe kad se razvije roleplay, pravi roleplay kada su claimani gradovi pojedinačno veće su šanse kao što si i px rekao za sukobe (a ne samo napuštanje zemlje) pa će biti i više unutrašnje nestabilnosti, prevlasti, građanskih ratova, više novopečenih sila i tako dalje. Sve u svemu sve ovo pokreće u stvari politička, a ne dinamo mapa

**Comment by VukIcrnogorskii** [comment]
> Nije problem imati mapu, nas ovdje brine najvise to kako ce se drzave siriti uzet cu za primjer ccg znamo kako se sirila i kako je zavrsila, zavrsila je na cijelom sredozemlju. Za takve mape potrebno je oformiti cijelu komisiju kako bi se to održavalo obako kako treba a ne da se samo ucrtava po necijim hirovima. Zato ako dodje do toga da se uvede zelio bih biti taj clan komisije i aktivno ucestvovati u svemu. I jednom sedmicno da se održi sastanak komisije lrije ucrtavanja.
> 
> **Ali želim napomenuti da sam jasno za to da je bez karte bolje**

Kao što rekoh za ovaj primjer, a ima i drugih država u sličnoj situaciji, po navedenim pobudama u carevini sve je jasno bilo raspoređeno i u svim oblastima ste bar jedan grad mogli nać.
A tragično je završila prvi put samo iz moje dobre  volje da dam ljudima šansu da igraju kad se mene i mojim prijateljima već nije igralo poslije onog što smo preživjeli. 
Da napomenem, organizacija je ključ svega!

**Comment by PiweeX** [comment]
uglavnom nadam se da ćemo doći do rešenja zajedničkim predlozima, čućemo ovih dana i šta ostali igrači misle

iskreno ne znam šta više da mislim, dosta je komplikovano i šta god da uradimo na kraju neće valjati u nekom pogledu, treba naći neki kompromis ali ujedno i način na koji bi server najbolje funkcionisao

ono za brending država je sjajno po igru, imali bi dosta više igrača pogotovo kad krene mainnet faza

**Comment by Featherica** [comment]
Poštovani,

mapa nije laka da se pravi, @dzelat i meni je trebalo duže vreme. Nemam sliku sa HogMaps servera, tamo je bilo stotine tiketa. Jednog dana dođe neko kaže "Hej moja teritorija je pogrešno nacrtana, ne može to tako!" on očigledno nije razumeo pojam da mi ne izagravamo robote. Mi crtamo mapu ali ne možemo biti 100% tačni jer opet nismo roboti. Kada bi uveli političku mapu mi minimalno moramo svaki dan da je menjamo, jer danas postoji npr. Ruska Federacija sledećeg dana izbrisana je i kupili su je npr. Turci. Koliko god mi updatovali nikad neće biti updejtana.

Srdačan Pozdrav!

**Comment by buducidzelat** [comment]
> slažem se sa obojicom, obe opcije su mač sa dve oštrice
> 
> donekle razumem na koji način StoneWorks funkcioniše ali me zanima na koji način si mislio da mi to odradimo?
> 
> npr. uzmimo zemlju kao što je Mongolija, ta zemlja je predobro organizovana i početa da se gradi ali setite se dok je bila raspodeljena na gradove tačnije dok je svaki vođa grada u Mongoliji imao svoj claim, claim pod svojim vlasništvom, došlo je do svađe i Lizard se odvojio od Zlaje, to su situacije u kojima dželati dobiju nervne slomove jer ko će te gluposti da trpi..
> 
> E sad, kad Zlaji pripada čitav claim u Mongoliji tu ipak postoji neki red, nema više svađa i cepljenja, ako neko hoće da napusti jer se posvađao sa nekim iz države on se jednostavno preseli u drugu državu, preseli se jer ne može da proglasi nezavisnost jer tu ipak stoji claim
> 
> moj predlog je onda da se u 1 momentu od trenutnih većih država poput Bardonije, Japana, Engleske, Britanije itd formiraju statične države koje se neće pomerati i onda, nebitno je ko im je vođa u datom momentu jer jednom će biti jedan jednom drugi a igrači će ostati isti ili će dolaziti novi i biće priliv starih
> 
> ovo bi bilo dobro iz razloga što onda dobijamo nešto što se zove vezivanje za nešto, isto kao što se neko veže za Partizan ili Zvezdu, tako bi i recimo igrači Hoga za određene države, ideologije, ljude u njima itd a sve radi zabave.. Sve to utiče na to da Hog zadrži bukvalno svakog igrača koji igra, jer evo neće živeti u državi od 8godišnjaka koji se posvađao sa nekim i izbrisao claim, srušio sve i popljuvao server već u da se tako izrazim brendiranoj državi kao npr CCG koju predhodno nije statički formirao server već osoba koja je sposobna za tako nešto da osmisli napravi i vodi državu mesecima. To je pozitivno i zbog toga što bi se onda vrlo lako organizovali eventi u pojedinačnim državama, zamislite da Engleska ima 50 membera od tih da uzmemo da je minimum 20 aktivno dnevno i da rade na zajedničkim projektima u Engleskoj, a onda kad je recimo rat svih 50 državljana dođu i tako puta još 10 velikih država, mnogo utiče na brending i na to prepiranje i stalna nadmetanja tačnije zanimljivije je za igru više nego kad postoji 100 država koje slabo ko ume da formuliše kako treba
> 
> Međutim onda ratovi totalno gube svoju svrhu, ratovaćete ali ne za teritoriju zar ne? ko je onda pobednik? Mislim to možda čak i nije toliki problem jer bi se lako smislile svrhe ratova na drugi način

Mozes se naprimer nakon rata organizovati sastanak izmedju vladar i na tom sastanku agresor ako je osvojio neke delove teritorije moze ih zahtevati od pobedjene drzave.Naravno dzelati ili neko iz staffa bi morao tu teritoriju preneti njima ako me razumete.

**Comment by buducidzelat** [comment]
> > > slažem se sa obojicom, obe opcije su mač sa dve oštrice
> > > donekle razumem na koji način StoneWorks funkcioniše ali me zanima na koji način si mislio da mi to odradimo?
> > > npr. uzmimo zemlju kao što je Mongolija, ta zemlja je predobro organizovana i početa da se gradi ali setite se dok je bila raspodeljena na gradove tačnije dok je svaki vođa grada u Mongoliji imao svoj claim, claim pod svojim vlasništvom, došlo je do svađe i Lizard se odvojio od Zlaje, to su situacije u kojima dželati dobiju nervne slomove jer ko će te gluposti da trpi..
> > > E sad, kad Zlaji pripada čitav claim u Mongoliji tu ipak postoji neki red, nema više svađa i cepljenja, ako neko hoće da napusti jer se posvađao sa nekim iz države on se jednostavno preseli u drugu državu, preseli se jer ne može da proglasi nezavisnost jer tu ipak stoji claim
> > > moj predlog je onda da se u 1 momentu od trenutnih većih država poput Bardonije, Japana, Engleske, Britanije itd formiraju statične države koje se neće pomerati i onda, nebitno je ko im je vođa u datom momentu jer jednom će biti jedan jednom drugi a igrači će ostati isti ili će dolaziti novi i biće priliv starih
> > > ovo bi bilo dobro iz razloga što onda dobijamo nešto što se zove vezivanje za nešto, isto kao što se neko veže za Partizan ili Zvezdu, tako bi i recimo igrači Hoga za određene države, ideologije, ljude u njima itd a sve radi zabave.. Sve to utiče na to da Hog zadrži bukvalno svakog igrača koji igra, jer evo neće živeti u državi od 8godišnjaka koji se posvađao sa nekim i izbrisao claim, srušio sve i popljuvao server već u da se tako izrazim brendiranoj državi kao npr CCG koju predhodno nije statički formirao server već osoba koja je sposobna za tako nešto da osmisli napravi i vodi državu mesecima. To je pozitivno i zbog toga što bi se onda vrlo lako organizovali eventi u pojedinačnim državama, zamislite da Engleska ima 50 membera od tih da uzmemo da je minimum 20 aktivno dnevno i da rade na zajedničkim projektima u Engleskoj, a onda kad je recimo rat svih 50 državljana dođu i tako puta još 10 velikih država, mnogo utiče na brending i na to prepiranje i stalna nadmetanja tačnije zanimljivije je za igru više nego kad postoji 100 država koje slabo ko ume da formuliše kako treba
> > > Međutim onda ratovi totalno gube svoju svrhu, ratovaćete ali ne za teritoriju zar ne? ko je onda pobednik? Mislim to možda čak i nije toliki problem jer bi se lako smislile svrhe ratova na drugi način
> > 
> > 
> > Mozes se naprimer nakon rata organizovati sastanak izmedju vladar i na tom sastanku agresor ako je osvojio neke delove teritorije moze ih zahtevati od pobedjene drzave.Naravno dzelati ili neko iz staffa bi morao tu teritoriju preneti njima ako me razumete.
> 
> Još se ne zna tačno kako bi koncept trebao izgledati ratova, ali sigurno neće ako pobediš neku državu da bude eto samo sam ih poklao, verovatno ćeš dobiti teritoriju te države.

dao sam predlog iznad

**Comment by konfix** [comment]
> Još se ne zna tačno kako bi koncept trebao izgledati ratova, ali sigurno neće ako pobediš neku državu da bude eto samo sam ih poklao, verovatno ćeš dobiti teritoriju te države.

Koncept ratovanja je odavno odrađen, na nama je samo da odlučimo na koji način će da funkcioniše ceo taj sistem. Dosta je komplikovano ali sigurno neće biti moguće da se tako lako uništi jedna država. 

Nakon rata svaka teritorija koja je napadnuta dobija štit koji im daje dovoljno vremena da se obnove, ratovanje svakako neće moći da se desi iznenadno već postoji vreme koje omogućava i napadaču i napadnutoj teritoriji da okupe sve svoje članove i da ih pripreme za rat.

Teritorije mogu (ali i ne moraju) da se gube, možemo da dodamo i opciju da se nakon pobeđenog rata dobije neka nagrada (bukvalno bilo šta) ili da se čak opljačka novac iz banke gubitničke teritorije. Da bi se osvojila neka teritorija napadač treba da zauzme claim na neko duže vreme i da ga odbrani (nešto kao KoTH) a ako u tome bude uspešan taj chunk se unclaimuje i postaje dostupan bilo kome.

Svakako, mislim da je najbolje da se međusobno dogovorite vi kao igrači, meni lično je malo glupo da se u ratu ne gube teritorije.
Možemo i da stavimo da je potrebna obostrana saglasnost da bi rat uopšte i počeo

**Comment by JedemJaja** [comment]
> Valjalo bi da se vrati karta svijeta, ipak je rp a ne factions server, s time ne samo što bi svijet izgledao urednije nego bi bilo i državama mnogo lakše da komuniciraju, sarađujuz prave saveze(ekonomske i vojne)... Politička mapa svijeta je veliki faktor na rp serverima i ne bi trebalo da je zanemarujemo!

Ne

**Comment by akipaki293** [comment]
Glupo da se vrati, ja imam dosta claimova svuda a verujem i drugi

**Comment by vukstrale** [comment]
Nikako, gubim onda ilegalni trust u samarkandu

**Comment by buducidzelat** [comment]
> > Još se ne zna tačno kako bi koncept trebao izgledati ratova, ali sigurno neće ako pobediš neku državu da bude eto samo sam ih poklao, verovatno ćeš dobiti teritoriju te države.
> 
> Koncept ratovanja je odavno odrađen, na nama je samo da odlučimo na koji način će da funkcioniše ceo taj sistem. Dosta je komplikovano ali sigurno neće biti moguće da se tako lako uništi jedna država.
> 
> Nakon rata svaka teritorija koja je napadnuta dobija štit koji im daje dovoljno vremena da se obnove, ratovanje svakako neće moći da se desi iznenadno već postoji vreme koje omogućava i napadaču i napadnutoj teritoriji da okupe sve svoje članove i da ih pripreme za rat.
> 
> Teritorije mogu (ali i ne moraju) da se gube, možemo da dodamo i opciju da se nakon pobeđenog rata dobije neka nagrada (bukvalno bilo šta) ili da se čak opljačka novac iz banke gubitničke teritorije. Da bi se osvojila neka teritorija napadač treba da zauzme claim na neko duže vreme i da ga odbrani (nešto kao KoTH) a ako u tome bude uspešan taj chunk se unclaimuje i postaje dostupan bilo kome.
> 
> Svakako, mislim da je najbolje da se međusobno dogovorite vi kao igrači, meni lično je malo glupo da se u ratu ne gube teritorije. Možemo i da stavimo da je potrebna obostrana saglasnost da bi rat uopšte i počeo

dao sam predlog gore voleo bih da ga pogledate ti i px

**Comment by NemanjaRusija** [comment]
Spaho je upravu što se tiče političke mape, na serveru će doći djeca koja ne znaju sistem rada i princip servera i claimati gdje god hoće i zamisli da se staff se svađa sa djetetom čija je teritorija i kako funkcioniše. I PiweeeX nadam se da se dobro sjeća Afrike i problema sa teritorijom i klejmanjem.

**Comment by NemanjaRusija** [comment]
> Sada kada je velik priliv novih igrača mislim da je to neizvedivo, treba uzeti u obzir da ima dosta igrača koji jos nemaju 14 godina i teško je objasniti kako to funkcionise. Mapa se svkako nije poštovala i UN je bio pun tiketa. Uskoro je opet tu live mapa gdje ćemo vidjeti sve klejmove (3D) i mislim da će još jedna karta u ovom slučaju politička biti potpuno nepotrebna.

Spaho je upravu što se tiče političke mape, na serveru će doći djeca koja ne znaju sistem rada i princip servera i claimati gdje god hoće i zamisli da se staff se svađa sa djetetom čija je teritorija i kako funkcioniše. I PiweeeX nadam se da se dobro sjećaš Afrike i problema sa teritorijom i klejmanjem.

**Comment by JaSamIgor** [comment]
Ako se napravi tim igrača koji želi da prati claimove na dynmapi, kao i da se uvedu neke mjere za uzimanje teritorije na političkoj karti, mislim da bi bila **dobra ideja ponovo uvesti političku kartu**.

**Comment by buducidzelat** [comment]
> Ako se napravi tim igrača koji želi da prati claimove na političkoj karti i dynmapi, kao i da se uvedu neke mjere za uzimanje teritorije na političkoj karti, mislim da bi bila **dobra ideja ponovo uvesti političku kartu**.

ili na primer da taj tim prati dynmap i preko njega uredjuje politicku kartu.

**Comment by akipaki293** [comment]
Za zatvaranje

**Comment by PiweeX** [comment]
Vraćena je, zatvaram issue
