### ISSUE TITLE
Da li Galileo i Igor treba da se leče

### ISSUE THREAD

**Issue by BaatarovaKrv** [PiweeX/HogRealms#52]
Jedan brat izbačen iz Mongolije pa pošao sa likom koga nema na serveru vec 2 meseca, došao da leči komolekse, a drugi slao poruke mržnje o galileo, eo sad mu liže stopala ima foot fetiš, država mu u raspadu nema dva aktivna igrača, kaže da je najjača država a ima 6 ulica sve ukupno u državi

**Comment by buducidzelat** [comment]
dobro je legendo

**Comment by Ratko7** [comment]
Mute

**Comment by NemanjaRusija** [comment]
> Jedan brat izbačen iz Mongolije pa pošao sa likom koga nema na serveru vec 2 meseca, došao da leči komolekse, a drugi slao poruke mržnje o galileo, eo sad mu liže stopala ima foot fetiš, država mu u raspadu nema dva aktivna igrača, kaže da je najjača država a ima 6 ulica sve ukupno u državi

Moram da reagujem na ovo jer ako ne bih pukao bi. Engleska je u odličnom stanju stvarno ne znam šta ti misliš, a ti si zajedno sa svojim drugom zlajom gradio preko buildmoda dok bio, a mi smo gradili kao svaka normalna država na serveru. A što tiče igrača šta si bolji od nas ništa, uđeš ti, zlaja i faris a i helena u 3 mjeseca možda i griješim a bogami i ti. Kome igor ulizije noge galileu? Ne bih rekao. I kakvih šest ulica nisi ni bio u engleskoj dok se gradila ovih sedmica. A ti si gradio mongoliju pomoću buildmoda isto kao i zlaja. 

Srdačan pozdrav 

Nemanja_Rusija

**Comment by konfix** [comment]
zasto otvaras issue za ovo

**Comment by NemanjaRusija** [comment]
> zasto otvaras issue za ovo

Misli da je github bog pa da on sve može riješiti

**Comment by BaatarovaKrv** [comment]
> zasto otvaras issue za ovo

Jer me galileo mutao bez razloga i okacio mene u novosti u un-u, a i sami ste odlucili da se za sve glasa ovde

**Comment by buducidzelat** [comment]
> > Jedan brat izbačen iz Mongolije pa pošao sa likom koga nema na serveru vec 2 meseca, došao da leči komolekse, a drugi slao poruke mržnje o galileo, eo sad mu liže stopala ima foot fetiš, država mu u raspadu nema dva aktivna igrača, kaže da je najjača država a ima 6 ulica sve ukupno u državi
> 
> Moram da reagujem na ovo. Engleska je u odličnom stanju stvarno ne znam kako je ti zamišljaš, a ti si zajedno sa svojim drugom zlajom gradio preko buildmoda, a mi smo gradili kao svaka normalna država na serveru. A što tiče igrača šta si bolji od nas ništa, uđeš ti, zlaja i faris a i helena u 3 mjeseca možda i griješim a bogami i ti. Kome igor ulizije noge galileu? Ne bih rekao. I kakvih šest ulica nisi ni bio u engleskoj dok se gradila ovih sedmica. A ti si gradio mongoliju pomoću buildmoda isto kao i zlaja.
> 
> Srdačan pozdrav
> 
> Nemanja_Rusija

Nemanja_Brčko*

**Comment by JaSamIgor** [comment]
> Jedan brat izbačen iz Mongolije pa pošao sa likom koga nema na serveru vec 2 meseca, došao da leči komolekse, a drugi slao poruke mržnje o galileo, eo sad mu liže stopala ima foot fetiš, država mu u raspadu nema dva aktivna igrača, kaže da je najjača država a ima 6 ulica sve ukupno u državi

Čuo sam kuće u Samarkandu još nisu popunjene?
Sam si sebi sjebao šansu da postaneš dželat ali eto samo pokazuje kakve igrače Mongolija ima ako ih ima

**Comment by JaSamIgor** [comment]
Sve u svemu mongol momenat ☕
