### ISSUE TITLE
Galileo za HS

### ISSUE THREAD

**Issue by buducidzelat** [PiweeX/HogRealms#53]
Ovaj deckic se najvise trudi od svih dzelata(izuzev tome da nema.zivota nego visi na hogu sa Zlajom 24/7) ja kao pojedinac mislim da bi trebali da ga nagradite jednim HS-om zato sto Why not
Glasanje ispod

Srdacno njegov naslednik

**Comment by BaatarovaKrv** [comment]
Nedo Bog nikome, taj deckic samo sjebava server iznutra i zavađuje ljude između sebe..
Zato je ceo san na hogu, jer nema svoj zivot

**Comment by buducidzelat** [comment]
> Nedo Bog nikome, taj deckic samo sjebava server iznutra i zavađuje ljude između sebe.. Zato je ceo san na hogu, jer nema svoj zivot

idi kradi bakar bolje ti je

**Comment by markeccc998** [comment]
> Nedo Bog nikome, taj deckic samo sjebava server iznutra i zavađuje ljude između sebe.. Zato je ceo san na hogu, jer nema svoj zivot

Ne seri

**Comment by DzingisKan** [comment]
> Ovaj deckic se najvise trudi od svih dzelata(izuzev tome da nema.zivota nego visi na hogu sa Zlajom 24/7) ja kao pojedinac mislim da bi trebali da ga nagradite jednim HS-om zato sto Why not Glasanje ispod
> 
> Srdacno njegov naslednik

Znam da lažeš jer mene na serveru nema lok

**Comment by buducidzelat** [comment]
> 

ne lazem sinoc si se klao sa zenom

**Comment by dzelat** [comment]
> Nedo Bog nikome, taj deckic samo sjebava server iznutra i zavađuje ljude između sebe.. Zato je ceo san na hogu, jer nema svoj zivot

to ti tajo dzingis prica

**Comment by Ratko7** [comment]
> Nedo Bog nikome, taj deckic samo sjebava server iznutra i zavađuje ljude između sebe.. Zato je ceo san na hogu, jer nema svoj zivot

Ljubomora ubija
