### ISSUE TITLE
Izmena Farminga

### ISSUE THREAD

**Issue by djonmla** [PiweeX/HogRealms#54]
Predlazem da se namesti da traktor moze da se puni _SAMO_ sa **coalom** i **charcoalom**
Onda nakon toga da se cena psenice poveca jer je potrebna "investicija" za coal.
Ovo bi napravilo ogromnu potraznju za ugljem sto bi motivisalo **rudare** da krenu u kopanje. Zbog velikog broja rudara, **enchanteri** bi imali posla preko glave sa pravljenjem novih krampova.
**Builderi** bi isto imali puno posla oko izgradnje novih farmi.
**Drvosece** bi morale da cepaju mnogo drveta da bi pravili charcoal.

64 Coala moze da dodaje 25% u traktor, a 64 CharCoala mogu da dodaju 15% (jer je poprilicno lako da se napravi)

Uglavnom ovaj mali update bi poprilicno poboljsao ekonomiju i motivisao ljude da vise rade na serveru.

Glasajte 👍 ako ste za ovo.
Glasajte 👎 ako ste protiv.

**Comment by BaatarovaKrv** [comment]
Cena wheata na laputi definitivno treba da se poveća slažem se

**Comment by djokca09** [comment]
Wheat 16kom- 70$

**Comment by dimitrije231** [comment]
Wheat-20=60

**Comment by HyperTwo29394** [comment]
Brate lijepo mi je da punim traktor sa sjemenkama :/

**Comment by Darislaw** [comment]
> 

Previse je op, i nema smisla

**Comment by Coplek** [comment]
lijepo ali nema smisla, jer npr samim tim se aktivira trgovina ugljem prakticki je bespotreban jer ispec nesto mozemo bambusom, a ugalj je beskorisan prakticki

**Comment by dzelat** [comment]
Slažem se mislim da je jako lako uzeti novac sada, dođe nov igrač, krene da peca i za 2-3 dana ima 150k i glupo je. Ovako bi se možda i cijene na laputi koliko toliko normalizovale.
_podržavam_

**Comment by Coplek** [comment]
@PiweeX  mogao bi prihvatiti ovo stoji tu odavno

**Comment by PiweeX** [comment]
> @PiweeX mogao bi prihvatiti ovo stoji tu odavno

radili smo na tome i smanjili cenu riba ali glasali smo skoro i da treba pojednačiti cenu riba i pšenice mada još ćemo videti, u suštini jedino šta bi trebalo još iz ovog glasanja je da se doda da se traktor može puniti samo coalom

**Comment by PiweeX** [comment]
> > @PiweeX mogao bi prihvatiti ovo stoji tu odavno
> 
> radili smo na tome i smanjili cenu riba ali glasali smo skoro i da treba pojednačiti cenu riba i pšenice mada još ćemo videti, u suštini jedino šta bi trebalo još iz ovog glasanja je da se doda da se traktor može puniti samo coalom

upravo sam rešio ovo i traktori će se od sutra posle restarta moći puniti samo sledećim stavkama

 'COAL':
  material: 'COAL'
  fuel-amount: 2
 'CHARCOAL':
  material: 'CHARCOAL'
  fuel-amount: 2
 'COAL_BLOCK':
  material: 'COAL_BLOCK'
  fuel-amount: 18
 'COAL_ORE':
  material: 'COAL_ORE'
  fuel-amount: 1
  
  
  uživajte! i izvinjavam se što je ovoliko potrajalo, izgubio se predlog
