### ISSUE TITLE
Da se poveća cena wheata i riba na laputi

### ISSUE THREAD

**Issue by BaatarovaKrv** [PiweeX/HogRealms#55]
Na prvi predlog xDjonmle

**Comment by frop1k** [comment]
ne, radi malo kao i mi ostali pa ces zaraditi nema nista bez rada

**Comment by PiweeX** [comment]
radim server konstantno već godinu dana i ne mogu da stignem da igram gotovo uopšte pa ne mogu da pričam o tome kakva je ekonomija skroz dok ne igram ali mislim da je idealno da na serveru sve bude teže pa samim tim i ekonomija, to stvara čar igri, ako hoćeš OP Factions onda igraj to ali ovo je nekako po meni bar zanimljivije


trebalo bi samo dodati možda još načina zarade u budućnosti ali možda i ne jer će tako podstaći trgovinu međ igračima

**Comment by akipaki293** [comment]
> radim server konstantno već godinu dana i ne mogu da stignem da igram gotovo uopšte pa ne mogu da pričam o tome kakva je ekonomija skroz dok ne igram ali mislim da je idealno da na serveru sve bude teže pa samim tim i ekonomija, to stvara čar igri, ako hoćeš OP Factions onda igraj to ali ovo je nekako po meni bar zanimljivije
> 
> trebalo bi samo dodati možda još načina zarade u budućnosti ali možda i ne jer će tako podstaći trgovinu međ igračima

Ako dodajes jos nacina nemoj Gold jer pojedinci kao sto su Zlaja imaju preko 20 puna double chesta gold blokova i to mi je par ljudi potvrdilo, dodaj drvoseču da ljudi cepaju drva za jos nesto a ne samo za gradnju i carcoal, wheat bi bilo lepo povecati do nekih 40-50$, ja sam juce zaradio preko 333k na katani koja ne istice i itema iz nether i end perka dok px nije sklonio iz mvpa, mnogo njih me optuzuje da sam p2w jer sam preko 1m zaradio sa mvpom, nije istina. Imao sam 900k jer sam prodavao stvari, iz wheata sam dobio minumum 200k, a iz riba jedno 300k, a 400k sto sam prodavao iteme iz nether i end perka, perkovi su bili dostupni na 3 dana sto nije pre op gledajuci sta se sve dobija, ja da sam htek abjuzati perkove nasao bih nacin, al sto bih rizikovao ban...

**Comment by PiweeX** [comment]
Što se tiče ovoga odavno je otvoreno ali je od tad i razmišljanjano o tome i o ekonomiji preciznije, upravo smo to rešili tačnije igrači kroz black shop i određene reforme

![unknown-7](https://user-images.githubusercontent.com/33425430/196843183-3862b45e-7741-44a9-97a6-fad3c3fcd358.png)



Uživajte! 🦩
