### ISSUE TITLE
Da se omoguci craftovanje diamond armora

### ISSUE THREAD

**Issue by frop1k** [PiweeX/HogRealms#56]
S tim da bude jako skupo ili tesko, neka bude jedan set vredan $1 000 000 al nek bude moguce da se crafta.

Takodje, neka bude kao sto je sad samo ako otkljucas reward, al da moze da se crafta ne da dobijes 1 set i tjt.

**Comment by PiweeX** [comment]
Razumem ali ako bi stavili da nakon što se otključa dozvola za kraftanje na rewardovima ona bi bi svako mogao svakom da krafa i samim tim rewardovi nebi imali smisla


što se tiče zašto je kraftovanje onemogućeno tu ima više uloga, kako nebi smorilo a i server mora da ima određenu dozu težine kako bi se igra više poštovala jer kad se pomučiš za nešto više ćeš igrati, ovde je praksa pokazala da je server zbog toga aktivan i posle godinu dana od otvaranja, i eto sad i da svi imaju sve otključano u ovom momentu godinu dana nakon otvaranja oni su se mesecima mučili i igrali za te armore, hoće li napustiti server jer ih je smorilo ili će ostati i igrati jer su se vezali emotivno i u svakom smislu za server? pa hoće



al svakako da bi bilo dobro da se dobija nekako drugačije, da ne bude samo na rewards mada i ovo je ok ali nije 100% ideal

**Comment by akipaki293** [comment]
> Razumem ali ako bi stavili da nakon što se otključa dozvola za kraftanje na rewardovima ona bi bi svako mogao svakom da krafa i samim tim rewardovi nebi imali smisla
> 
> što se tiče zašto je kraftovanje onemogućeno tu ima više uloga, kako nebi smorilo a i server mora da ima određenu dozu težine kako bi se igra više poštovala jer kad se pomučiš za nešto više ćeš igrati, ovde je praksa pokazala da je server zbog toga aktivan i posle godinu dana od otvaranja, i eto sad i da svi imaju sve otključano u ovom momentu godinu dana nakon otvaranja oni su se mesecima mučili i igrali za te armore, hoće li napustiti server jer ih je smorilo ili će ostati i igrati jer su se vezali emotivno i u svakom smislu za server? pa hoće
> 
> al svakako da bi bilo dobro da se dobija nekako drugačije, da ne bude samo na rewards mada i ovo je ok ali nije 100% ideal

Ja prvi svaki put kad se iznerviram i kad puknem odem na "pauzu", ali se uvek vratim jer volim da igram na serveru i nemam na kom drugom. Sto se tice oklopa za kraftovanje 88% ljudi bi odma smorilo ali 22% nebi, ja sam u beti odma cim sam skupio dmda napravio 2 pika i 1 set oklopa, imao sam prot 3 i unb 2, a jedan pik fort drugi silk, a pik iz mvpa sam izgubio ili je nestao, armor sam maxo i upgrade na netherite tek kada sam usao u UKA sto nije bilo tako davno i evo idalje igram, nestao mi je silk pik dok sam kopao bikone jer ima pl za anvile od iron blokova sto je po meni glupo...

**Comment by Darislaw** [comment]
> S tim da bude jako skupo ili tesko, neka bude jedan set vredan $1 000 000 al nek bude moguce da se crafta.
> 
> Takodje, neka bude kao sto je sad samo ako otkljucas reward, al da moze da se crafta ne da dobijes 1 set i tjt.

Inflacija je sad trenutno velika, ako je bio neko pametan da to provali, evo npr imamo veoma bogate igrace na serveru i one manje bogate a oba ne znaju sta ce s novcem, a jos i ta suma novca od 1 milion$. Pa server bi propao druze, stonks na dole i novac bi bio nebitan bukvalno
