### ISSUE TITLE
Da se skloni Austro Ugarska

### ISSUE THREAD

**Issue by Galilejo** [PiweeX/HogRealms#58]
Austo Ugarska monarhija nije aktivna vec duzi vremenski period pa zbog toga bi bilo u redu da se taj claim makne. i oslobodi teritorij...

**Comment by PiweeX** [comment]
Ja sam duže vreme predlagao da se sačeka da se vidi šta će da bude i da li će se obnoviti jer je ipak praistorijska država i bukvalno druga ili treća država kad su krenule da se formiraju u ALFA verziji

ali nemam pojma, pametno bi bilo kad bi se neko javio da je preuzme, ipak je to ogromna teritorija i jako dobro osmišljena država, msm da se ne briše

**Comment by akipaki293** [comment]
> Ja sam duže vreme predlagao da se sačeka da se vidi šta će da bude i da li će se obnoviti jer je ipak praistorijska država i bukvalno druga ili treća država kad su krenule da se formiraju u ALFA verziji
> 
> ali nemam pojma, pametno bi bilo kad bi se neko javio da je preuzme, ipak je to ogromna teritorija i jako dobro osmišljena država, msm da se ne briše

Vidi, luka to nikom nebi dao, ja kad sam otisao iz japana ja sam ga pitao da on i ja vodimo, on je odbio, jedino da nadjes nekog ko to zna voditi i kome će luka dati, ali jedno vreme sam i bio u AUMu i lepo je sve osmišljeno i da su ljudi tamo aktivni imali bi jedan od najboljih rpa

**Comment by Coplek** [comment]
Bio sam ministar prometa u AUM, brutalan rp, sve u svemu trebalo bi maknuti taj claim pod uslovom da luka ima neaktivnost vecu od 2mj

**Comment by PiweeX** [comment]
Sklonjena odavno čini mi se
