### ISSUE TITLE
Banovanje Rakta

### ISSUE THREAD

**Issue by buducidzelat** [PiweeX/HogRealms#59]
Trazim da se ponovi glasanje o banovanju igraca i abjuzera pod imenom Ratko/Srbenda1389/Thunder dozivotno

Srdacno MarePlebexx

volim zlaju

**Comment by T1GAR** [comment]
Vec se glasalo. Ovaj github je samo mjesto gdje određeni ljudi izjašnjavaju svoj "ego" nista drugo... Postoje dvije strane "pro-Zlaja" koji ce glasat za sto god Zlaja objavi, a ostali su koji ce vecinski glasat protiv toga. Gdje je tu uopce pravednost? Ovo uopce nije mjesto za ovakve teme...

**Comment by T1GAR** [comment]
Ovake stvari bi trebali rješavati admini servera a ne igrači. Gdje je tu logika? Ovdje može doc bilo tko i samo glasat da se netko bana bez da uopce zna sto je taj igrac radio ili slicno. Ciste gluposti. A i necu pocet o tome kako je vecina glasanju ovdje pod utjecajem onih o kojima se i radi.

**Comment by T1GAR** [comment]
![Screenshot_20220619_062257](https://user-images.githubusercontent.com/107375896/174465804-fe56cfa3-610f-4f74-906e-6f472a61089d.jpg)
![Screenshot_20220619_062240](https://user-images.githubusercontent.com/107375896/174465806-68fba9b2-4109-43f9-914e-3eff739c2a38.jpg)
![Screenshot_20220619_062206](https://user-images.githubusercontent.com/107375896/174465807-4a26a4b2-49d8-4a2f-bfd5-1819bc84f762.jpg)

A i jedni od dokaza kako se to radi. Nisu jedini primjeri ima ih još. Treba naoraviti neka pravila cemu se ovdje može glasati a o cemu je. Ideje kao sto su dodavanje macaka i opce ideje za sama događanja na serveru su dobre stvari, a sve ostalo sto se tice individualnih igraca i gluposti koje se pisu su posao staff tima.

**Comment by T1GAR** [comment]
![unknown-2](https://user-images.githubusercontent.com/107375896/174466172-cbf61969-a7ca-4940-aa30-e2cf9cb37b4f.png)

O ovome nemam nista za rec. Namjera je jasna uz trenutnu situaciju na serveru.

**Comment by akipaki293** [comment]
> ![unknown-2](https://user-images.githubusercontent.com/107375896/174466172-cbf61969-a7ca-4940-aa30-e2cf9cb37b4f.png)
> 
> O ovome nemam nista za rec. Namjera je jasna uz trenutnu situaciju na serveru.

Github, i px je sam rekao da otvaramo issues ono sto mi mislimo da je potrebno, npr ja sam otvorio issues za moju državu da bih mogao da stavljam novosti iz nje, ovo za bananje igrača je glupo, ali ono što je galileo otvorio za AUM nije.

**Comment by T1GAR** [comment]
Upravo to.

**Comment by Coplek** [comment]
Srbenda nije najbolji igrac dapace nije nikakav uzor, ali ako je lik toliko para bacio na server, ako je toliko puta cekao unban/unhag/unmute to pokazuje da mu je stalo do servera njegovo ponasanje se regulira na nacin da dobije mute/hag ne mora nuzno dobiti ban, trenutno smo maknuli sve njegove abusane stvari i nema razloga za perma ban, sutra mozemo otvoriti glasanje da se ti banujes  nabavim ljude i izglasam oko banova je posao staff teama, i ovakav vid je neposten ne slazem se sa srbendom i ne branim ga, ali niti se slazem da ga treba perma ban px je najbolje opisao na proslom issue, grupa ljudi ce se skupit i glasat ce za jer ih jedan kontrolira

**Comment by konfix** [comment]
> Vec se glasalo. Ovaj github je samo mjesto gdje određeni ljudi izjašnjavaju svoj "ego" nista drugo... Postoje dvije strane "pro-Zlaja" koji ce glasat za sto god Zlaja objavi, a ostali su koji ce vecinski glasat protiv toga. Gdje je tu uopce pravednost? Ovo uopce nije mjesto za ovakve teme...

Nije tačno, ovi "ostali" su tu da glasaju za bilo šta što im se kaže na discordima drugih država. Mogu da nabrojim nekoliko ljudi ovde koji teraju druge da glasaju za bilo šta što njima ide u korist.

**Comment by konfix** [comment]
> Ovake stvari bi trebali rješavati admini servera a ne igrači. Gdje je tu logika? Ovdje može doc bilo tko i samo glasat da se netko bana bez da uopce zna sto je taj igrac radio ili slicno. Ciste gluposti. A i necu pocet o tome kako je vecina glasanju ovdje pod utjecajem onih o kojima se i radi.

da, problem je što se bunite za bilo šta što ti isti admini urade.

**Comment by T1GAR** [comment]
> > Ovake stvari bi trebali rješavati admini servera a ne igrači. Gdje je tu logika? Ovdje može doc bilo tko i samo glasat da se netko bana bez da uopce zna sto je taj igrac radio ili slicno. Ciste gluposti. A i necu pocet o tome kako je vecina glasanju ovdje pod utjecajem onih o kojima se i radi.
> 
> da, problem je što se bunite za bilo šta što ti isti admini urade.

Ne govori u ime svih molim te. Problem admina je to da ne mogu podnjet nikakav hate ili kritiku ocito.

**Comment by T1GAR** [comment]
> > Vec se glasalo. Ovaj github je samo mjesto gdje određeni ljudi izjašnjavaju svoj "ego" nista drugo... Postoje dvije strane "pro-Zlaja" koji ce glasat za sto god Zlaja objavi, a ostali su koji ce vecinski glasat protiv toga. Gdje je tu uopce pravednost? Ovo uopce nije mjesto za ovakve teme...
> 
> Nije tačno, ovi "ostali" su tu da glasaju za bilo šta što im se kaže na discordima drugih država. Mogu da nabrojim nekoliko ljudi ovde koji teraju druge da glasaju za bilo šta što njima ide u korist.

Pa ajde mi onda objasni kako je ovo pravedno? Malo citaj druge stvari

**Comment by Ratko7** [comment]
Pozdrav momak,gde žuriš nije se ni onaj ugasio issue oćete i ovde da izgubite issue kako vidim

**Comment by VukIcrnogorskii** [comment]
> Vec se glasalo. Ovaj github je samo mjesto gdje određeni ljudi izjašnjavaju svoj "ego" nista drugo... Postoje dvije strane "pro-Zlaja" koji ce glasat za sto god Zlaja objavi, a ostali su koji ce vecinski glasat protiv toga. Gdje je tu uopce pravednost? Ovo uopce nije mjesto za ovakve teme...

Mozes izdvojit i anti-carski glasaci, dje pojedinci ne zele bolji server samo kako bi probali naprkostit meni, jer sam ja ili neko iz moje drxave nesto dobro predlozio.
U ovom slucaju sta god da se predlozi ti glasaci ce glasat prtiv, upravo iz njihove mrznje i zadovoljavanja sopstvenog ega.
Sto se tiče banovanja igrača preko githuba, to je najveća glupost koja može da se radi, jer rijetko kad ovakve stvari mogu da budu pošteno izglasane, a takođe ovo je opcija koju admini moraju da riješe, a ne đeca kojoj se neko ne sviđa pa ne znaju šta da rade pa kače ljude po githubu.

**Comment by T1GAR** [comment]
> 

Druge stvari se mogu rijesit uz suradnju igraca i staff tima na githubu, ali bananje i takve stvari su jednostavno neprihvatljive.

**Comment by T1GAR** [comment]
> > Vec se glasalo. Ovaj github je samo mjesto gdje određeni ljudi izjašnjavaju svoj "ego" nista drugo... Postoje dvije strane "pro-Zlaja" koji ce glasat za sto god Zlaja objavi, a ostali su koji ce vecinski glasat protiv toga. Gdje je tu uopce pravednost? Ovo uopce nije mjesto za ovakve teme...
> 
> Mozes izdvojit i anti-carski glasaci, dje pojedinci ne zele bolji server samo kako bi probali naprkostit meni, jer sam ja ili neko iz moje drxave nesto dobro predlozio. U ovom slucaju sta god da se predlozi ti glasaci ce glasat prtiv, upravo iz njihove mrznje i zadovoljavanja sopstvenog ega. Sto se tiče banovanja igrača preko githuba, to je najveća glupost koja može da se radi, jer rijetko kad ovakve stvari mogu da budu pošteno izglasane, a takođe ovo je opcija koju admini moraju da riješe, a ne đeca kojoj se neko ne sviđa pa ne znaju šta da rade pa kače ljude po githubu.

Druge stvari se mogu rijesit uz suradnju igraca i staff tima na githubu, ali bananje i takve stvari su jednostavno neprihvatljive.

**Comment by IamJoseMourinho** [comment]
> Vec se glasalo. Ovaj github je samo mjesto gdje određeni ljudi izjašnjavaju svoj "ego" nista drugo... Postoje dvije strane "pro-Zlaja" koji ce glasat za sto god Zlaja objavi, a ostali su koji ce vecinski glasat protiv toga. Gdje je tu uopce pravednost? Ovo uopce nije mjesto za ovakve teme...

To sa stranama isti kurac ko sa Vucicem i penzionerima

**Comment by buducidzelat** [comment]
> > ![unknown-2](https://user-images.githubusercontent.com/107375896/174466172-cbf61969-a7ca-4940-aa30-e2cf9cb37b4f.png)
> > O ovome nemam nista za rec. Namjera je jasna uz trenutnu situaciju na serveru.
> 
> Github, i px je sam rekao da otvaramo issues ono sto mi mislimo da je potrebno, npr ja sam otvorio issues za moju državu da bih mogao da stavljam novosti iz nje, ovo za bananje igrača je glupo, ali ono što je galileo otvorio za AUM nije.



> ![unknown-2](https://user-images.githubusercontent.com/107375896/174466172-cbf61969-a7ca-4940-aa30-e2cf9cb37b4f.png)
> 
> O ovome nemam nista za rec. Namjera je jasna uz trenutnu situaciju na serveru.

nkntm  sta je lose u tome sto je objasnio nekome kako glasa AHAHAHHA

**Comment by T1GAR** [comment]
> > > ![unknown-2](https://user-images.githubusercontent.com/107375896/174466172-cbf61969-a7ca-4940-aa30-e2cf9cb37b4f.png)
> > > O ovome nemam nista za rec. Namjera je jasna uz trenutnu situaciju na serveru.
> > 
> > 
> > Github, i px je sam rekao da otvaramo issues ono sto mi mislimo da je potrebno, npr ja sam otvorio issues za moju državu da bih mogao da stavljam novosti iz nje, ovo za bananje igrača je glupo, ali ono što je galileo otvorio za AUM nije.
> 
> > ![unknown-2](https://user-images.githubusercontent.com/107375896/174466172-cbf61969-a7ca-4940-aa30-e2cf9cb37b4f.png)
> > O ovome nemam nista za rec. Namjera je jasna uz trenutnu situaciju na serveru.
> 
> nkntm sta je lose u tome sto je objasnio nekome kako glasa AHAHAHHA

Ocito ne shvacas najmeru te recenice u trenutnome stanju na serveru. Logicno je. Khm "jeste glasali protiv Ratka". I i sam dobro znas koliko se mrze. Naravno tvoj komentar opet stoji ali logika vuce na drugu stvar.
