### ISSUE TITLE
ruše server. Tehnička Zaštita Servera (DDOS Protekcija)

### ISSUE THREAD

**Issue by PiweeX** [PiweeX/HogRealms#6]
Nakon podešavanja igre za telefon server je dobio nekoliko DDOS napada te je postao nestabilan

**Velocity je vraćen na istu mašinu kao i ostali serveri, serverov IP trenutno nije bezbedan**

Sledeći korak jeste da se ponovo podesi **TCPShield** nakon čega će Kinez pokušati da odradi sledeću šemu

> JAVA IGRAČ -  TCPShield - Velocity - Podserveri (Mašina 1 - ovaj IP se ne vidi zbog TCP-a)
> > > 
> Bedrock Igrač - Geyser (Mašina 2 - ovaj IP se vidi)

  

_Do 7h jutru igrači koji su online će moći da igraju međutim ko tek ulazi neće moći jer mu IP neće biti prikazan_

Sutra posle podne kreće prvi test, Kinez će rekodirati čitav Geyser kako bi uspeli u ovoj nameri

**Comment by PiweeX** [comment]
TCP je ipak podešen bez gašenja IP-a do jutra, trenutno niko ne može da bekenduje IP ali isto tako igrači sa telefona ne mogu da igraju dok se plugin ne rekodira i dok sve ne bude završeno


` JAVA igrači mogu da igraju bez problema`

**Comment by PiweeX** [comment]
odjava u 01:48

radovi nastavljaju sutra posle podne!

server je bezbedan.

**Comment by PiweeX** [comment]
Objava sa discorda iz pxtype od pre par dana kako bi vam bilo jasnije zbog čega se ovo radi:



Neko život provede rešavajući svetske probleme, neko dižući porodicu, neko u Manastiru.. medjutim postoji next level

osoba koja sedi kući i na internetu ispoljava svoje komplekse rušeći tuđi rad.

Da, server je srušen par dana posle moje objave da ko sruši server dobija 350 htokena u igri, ovo je nešto što sam želeo i što se inače radi u blockchain i sličnim projektima gde developeri tih projekata žele da provere da li je sve ok na mreži i ukoliko neko uspe da uhakuje ili provali grešku na njihovom radu budu plaćeni

medjutim ovde je stvar da postoje zavidni ljudi koji gledaju kako nekom da napakoste

da, neko se bavi time da plati streeser tipa 15$ i onda ruši uspesne servere verovatno jer je ranije bio glup da napravi slican ili bilo kakav uspeh

imamo sreće da u zajednici imamo mnogo pametnih ljudi pa i našeg developera kineza koji je pre mesec ipo zamislio kako će rešiti taj problem ddosa ukoliko se desi, u suštini problem se dešava zato što nemamo zaštitu a zaštitu nemamo jer kada bi postojala onda igra na telefonima nebi bila moguća, tu su defektaši pronašli rupu i iskoristlil da ruše server preko ddosera.

Uz to od kako je server srušen u roku od 15 minuta je ispisan plan kako će problem biti rešen, i hoće ako sve dobro prodje, verujem da hoce medjutim bice naporno gledati kako server bude padao u narednih par sati a verovatno i dana i uvek to kad se nesto lose desava sa tehnicke strane servera se desi onda kad je najudarnije za igru pa još sklopi par najbitnijih dana, četvrtak petak subota nedelja..

**Comment by PiweeX** [comment]
Mapa i port za Bedrock verziju za igrače sa telefona isključeni sa Cloudflarea, Kinez će odraditi to kroz proxy kako se IP adresa ni tu nebi videla što će dodatno povećati sigurnost servera

**Comment by PiweeX** [comment]
![unknown](https://user-images.githubusercontent.com/33425430/172867289-82c0494b-3794-4152-b738-f5e6db6e5fc8.png)

**Comment by buducidzelat** [comment]
no hejt al msm da ovo niko ne cita xd
![Screenshot_2061](https://user-images.githubusercontent.com/107114906/172869078-086d1af8-a6c4-44c1-b8b8-525ad1921d41.png)

**Comment by dzelat** [comment]
> no hejt al msm da ovo niko ne cita xd
> ![Screenshot_2061](https://user-images.githubusercontent.com/107114906/172869078-086d1af8-a6c4-44c1-b8b8-525ad1921d41.png)
> 

**_citam ja~~lol~~_**

**Comment by PiweeX** [comment]
CPU Velocity-a povecan sa 600 na 1000 i memorija sa 3 na 5 GB

zašto?

iako je ddos zaštita sa TCPShieldom nameštena, TCP se može izbeći jer i on funkcioniše kao Cloudflare, kao proxy server samo bolje od Cloudflare-a naravno

neko ko se bolje razume u računalne mreže može da otkrije IP, može da iskoristi tako što će ostalim igračima dati IP koji će svako moći da ddosa

međutim, baš zbog toga, povećan je ram i cpu kako bi kvalitet konekcije i uopšte izdržljivost tog servera koji drži sve podservere bio bolji.

**Comment by PiweeX** [comment]
Planiramo da dodamo dodatnu ddos zaštitu u naredna 2 meseca, pored toga planirano je prebacivanje sa Hetzner mašine na OVH jer ima mnogo bolji ddos sistem, nismo računali da će iko ddosati server, tačnije mislili smo da će sve biti mnogo teže da se otkrije i sruši i da se uz to niko time više ne bavi.

**Comment by PiweeX** [comment]
što se tiče radova, zbog životnih problema i obaveza smo ih odložili za ovo veče i upravo ćemo krenuti da sređujemo šemu od gore

**Comment by buducidzelat** [comment]
> > no hejt al msm da ovo niko ne cita xd
> > ![Screenshot_2061](https://user-images.githubusercontent.com/107114906/172869078-086d1af8-a6c4-44c1-b8b8-525ad1921d41.png)
> 
> **_citam ja~lol~_**

evo poceo sam i ja xd
![Screenshot_2061](https://user-images.githubusercontent.com/107114906/172935683-a96c3e8b-8b67-49b3-b24e-fd4c2de687b4.png)

**Comment by PiweeX** [comment]
10:25 radovi se nastavljaju

**Comment by PiweeX** [comment]
Napravljen je poseban Geyser podserver na drugoj mašini koju skladiste poseduje

**Comment by PiweeX** [comment]
11:26 radovi su obustavljeni na 2h

Server je namešten na panel međutim brojčani IP u igri ne radi, ovo može biti do toga što je ranije već negde podešavan isti port na istoj mašini (2) i zbog toga ne funkcioniše, takođe može biti do toga što port nije otvoren direktno na mašini, kad se radovi nastave prvo ćemo probati da migriramo ovaj server na local skladište node koji inače drži panel jer tu nikada nije otvaran sličan port

Što se tiče tehničke strane Kinez je odradio sve potrebno, još samo da se otvori dobar port na 19132

Radovi su pauzirani na naredna 2h zbog hitnih obaveza


Server je restartovan samo jednom dok je oko 15ak ljudi bilo online, restart je najavljivan 20 minuta pre.

**Comment by PiweeX** [comment]
13:38 radovi nastavljaju za 1h

**Comment by PiweeX** [comment]
Nakon što je server pomeren na skladište VPS tačnije Contabo server nije mogao lepo da se starta kao i prošli put
 
Posle 1h ćemo probati da izvadimo daemona logove pa da proverimo da li fejluje neka skripta

**Comment by PiweeX** [comment]
server je vraćen na HOG OBLAK 2 mašinu 

Port 19132 na UDP će biti otvoren uskoro na HOG OBLAK 2 node

TCPShieldov plugin ima support za Geyser, onda ćemo dodati IP od glavnog servera koji se nalazi na HOG OBLAK 1 u whitelist

što se tiče toga što server ne prepoznaje da je startovan ili da se startuje to je jer ne koristi egg specifičan za go a server u pozadini ustvari radi

**Comment by PiweeX** [comment]
trenutno pored porta moramo ponovo da restartujemo proxy tačnije sve sa Hogovih servera će kikovati na 30 sekundi

verovatno ćemo zbog ovoga odraditi restart tek u 00 ili čekati sutra posle standardnog jutarnjeg

**Comment by PiweeX** [comment]
22:41 - imaćemo problem sa otvaranjem porta, nalog na kom nam OBLAK 2 stoji je lockan i ne može se unlock u ovom momentu i ko zna kad će moći, videćemo šta ćemo moći da uradimo povodom toga sutra

što se tiče restarta, čekamo jutro jer trenutno nema potrebe pošto svakako port ne radi

**Comment by PiweeX** [comment]
6:55 port otvoren, hvala Neonu

**Comment by PiweeX** [comment]
Čekamo da Pterodactyl uradi sledeći realse kako bi popravio bag što se tiče Oracle VMova kako bi server mogao da se startuje bez bagova na panelu

(https://github.com/pterodactyl/panel/issues/3999)

trenutno čekamo, kad ovo bude rešeno, igrači sa telefona će ponovo moći da igraju bez problema

**Comment by PiweeX** [comment]
![Screenshot_2022-06-11-22-51-48-139_com mojang minecraftpe](https://user-images.githubusercontent.com/33425430/173204594-4eff9dc8-6335-45e2-9856-ed3aa6ca1cea.jpg)

Test server na Bedrocku radi, nema veze što na panelu prikazuje da se starta svo vreme

![Screenshot_2022-06-11-22-56-59-643_com android chrome](https://user-images.githubusercontent.com/33425430/173204628-d2d2fdd0-354a-4f3c-ac6c-9beaf668a618.jpg)


Sutra bi svi radovi oko ovoga trebali biti gotovi nakon čega će igrači sa telefona ponovo moći da uđu i igraju ukoliko uspe

22:58 odjava

**Comment by PiweeX** [comment]
Bedrock user with ip: /178.921.112.73 has disconnected for reason Outdated Bedrock client! This server supports the following Bedrock versions: 1.19.0


Trenutna verzija za bedrock je 1.19 što nije kompatibilno sa ostalim podserverima i Velocity-em uopšte, rešiće se

**Comment by PiweeX** [comment]
Radimo još neka testiranja i skinuli smo Minecraft BEDROCK za 1.19.0 nakon čega je server ipak pokrenut na 1.18.2 a otkriveno je u konzoli da cela šema donekle radi

Regardless of the server or what plugins it has installed, you can join it with Geyser (as long as the server supports the latest vanilla (unmodified) Minecraft version).

ovo znači da će nam trebati standalone za 1.18x nakon čega ćemo probati na istom brojčanom IP-u, ukoliko sve bude perfektno radilo spojićemo na pe.hogrealms.com domenu kao i ranije i igrači sa telefona će ponovo moći da igraju

**Comment by PiweeX** [comment]
11:29 sinoć smo došli do zaključka da ovo neće moći da funkcioniše na taj način sve dok se deo plugina ne rekodira

Kinez će početi da menja stvari u kodu i da shvata šta je do čega od srede, dakle igrači sa telefona će moći da uđu kroz nekoliko dana

**Comment by PiweeX** [comment]
Ne samo to, zbog floodgate koji je povezan sa Geyserom komande koje već neko vreme ne rade poput /lands delete i sličnih će proraditi nakon što ovo bude gotovo, odmah posle toga 3D mapa će taman biti učitana i otvorićemo port za nju

**Comment by KriptoEtnoRomAleksa** [comment]
Ja mislim da trebamo dodati burek kao hranu

**Comment by akipaki293** [comment]
.

**Comment by PiweeX** [comment]
Radovi se nastavljaju u ovu subotu!

**Comment by PiweeX** [comment]
radovi su nezvanično trebali da se dogode u četvrtak ali je došlo do neplaniranih obaveza

**očekuje se da će do nedelje igra sa telefona biti ponovo moguća**

**Comment by PiweeX** [comment]
![IMG_20220616_180605](https://user-images.githubusercontent.com/33425430/174116258-30c68abc-33bb-4809-9064-179fd98141d6.jpg)
![IMG_20220616_180615](https://user-images.githubusercontent.com/33425430/174116262-1bfb7261-7cff-467e-bb36-df0b98957047.jpg)
![IMG_20220616_180644](https://user-images.githubusercontent.com/33425430/174116268-9d76fa05-9516-4a51-b531-8b51530dcb29.jpg)
![IMG_20220616_180659](https://user-images.githubusercontent.com/33425430/174116273-881914d7-dfe9-4a8b-bcc5-b7b2ef8ee2de.jpg)
![IMG_20220616_180710](https://user-images.githubusercontent.com/33425430/174116274-18c9b2c6-a81e-4714-827e-85301926f79b.jpg)
![IMG_20220616_180727](https://user-images.githubusercontent.com/33425430/174116277-5404db4e-8450-472d-9f8a-fbcd6636b173.jpg)
![IMG_20220616_180742](https://user-images.githubusercontent.com/33425430/174116279-54dca73b-e761-438b-ac28-28e36aed0cae.jpg)

**Comment by PiweeX** [comment]
Slike od gore su replike TikToka od pre skoro 3 dana:

https://vm.tiktok.com/ZMNFUt1CL/?k=1



Objavili smo da dajemo 750 hokena u vrednosti u Bitcoinu osobi koja uspe da sruši server, mnogo njih se javilo ali za sad niko nije uspeo i server je imao 99.99% uptime-a u poslednjih nedelju dana.

Potencijalno možda neko uspe da bekenda IP kad se bedrock ponovo omogući, čak šta više vrlo je lako ali svakako ukoliko se desi da neko ruši server zeznuće se jer će srušiti samo bedrock proxy, džabe bačene pare maltene jer je glavna stvar na javi.

**Comment by PiweeX** [comment]
Tokom subote se nisu odvili radovi jer nismo uspeli da se uskladimo s vremenom, zato će sutra sve biti rešeno ukoliko uspemo da završimo šta smo zamislili

**Comment by PiweeX** [comment]
Radovi na ddos protekciji za igru za telefon se nastavljaju upravo

**Comment by PiweeX** [comment]
[Pterodactyl Daemon]: Finished pulling Docker container image
standard_init_linux.go:228: exec user process caused: exec format error
container@pterodactyl~ Server marked as offline...

**Comment by PiweeX** [comment]
17:17

{"success":true,"data":{"gameId":"MCPE","name":"A Minecraft Server","description":"A Minecraft Server","unknownId":"503","version":{"name":"1.18.30"},"players":{"online":"0","max":"20"},"type":"pe","cleanDescription":"A Minecraft Server"}}

**Comment by PiweeX** [comment]
test spigot server koji je napravljen malo pre radi, treba biti na 1.18.2 pa da se proba konekcija

**Comment by PiweeX** [comment]
![download](https://user-images.githubusercontent.com/33425430/175780278-e75fd45e-dcac-43b0-ae1a-bf07ac089b28.png)

[15:27:47] [Server thread/ERROR]: [TCPShield] TCPShield not loading because ProtocolLib is not installed. Either use Paper to enable native compatibility or install ProtocolLib.

**Comment by PiweeX** [comment]
[15:30:14] [Netty Epoll Server IO #3/WARN]: [TCPShield] Debug : unknown[unknown/x] was disconnected because no proxy info was received and only-allow-proxy-connections is enabled. Raw payload = "x"

**Comment by PiweeX** [comment]
Plugin će morati malo da se menja iz koda jer ulaženje ne radi kako treba na način koji smo hteli

**Comment by PiweeX** [comment]
Kinez nije stigao sinoć tako da će uskoro rekodirati plugin na standalone verziji, nadamo se najboljem!

Ako ovo uspe da se reši vote i mapa će odmah proraditi 🗿

**Comment by PiweeX** [comment]
aplikacija mape je rešena pre vremena, postoji poseban issue za nju tako da su napisani koraci koji su poduzeti ali uglavnom otvoren je reverse proxy te je dodat na cf i sad sve radi

**Comment by PiweeX** [comment]
napomena da ne radi svima, proradiće svakome kroz par sati iako je cache obrisan ne radi svima

**Comment by PiweeX** [comment]
![Screenshot_2022-07-10-23-50-22-821_com android chrome](https://user-images.githubusercontent.com/33425430/178163286-3708b011-e581-4b9d-806c-1706f5469aa9.jpg)


Test server za podešavanje ddos protekcije na gejser serveru koji je odvojen od mašine 1 spamuje error verovatno već danima, server stopiran neko vreme

**Comment by PiweeX** [comment]
Problem da se proxy server zbog panel restart baga restartuje po 50 puta jutru i treba mu do 8

**Comment by PiweeX** [comment]
Test server za nameštanje geysera tačnije crossplaya stopiran, biće kupljen OVH tako da sa ddosom nećemo imati problema


![download](https://user-images.githubusercontent.com/33425430/188639831-3cbaa56c-7fee-406a-ba34-b3054f02fad2.png)

**Comment by PiweeX** [comment]
I dalje ruše, sa 5 strana tačno sam izbrojao otprilike. Neću pisati sve strane ali eto ovih dana i ddosuju i sa streserom ulaze 10k puta na Decentraland pokušavaju pa sjebu discord čet i zbaguju konzolu pa ulaze na naloge pa to rešimo a onda opet pa domaći pa strani pa opet domaćih nekoliko i sve tako, retardirani ljudi šta ćeš sve ovo nam stvara velike gubitke igrača ali svakako mi to rešimo lako ali oni problem u glavi nikad

**Comment by PiweeX** [comment]
Zapretio sam tužbom uz sve dokaze koje smo prikupili prikupljamo ih još, ljudi i dalje ruše server (ZeVs, Dimitrije Dosić iz Bosne) a tvrde da to ne rade iako iznuđuju ljude za da im kupe njihovu ddos protekciju ili hosting nakon što sruše server, ove osobe sam identifikovao takođe i skontao da su oni upravo rušili ekonomiju servera ovih dana ulaskom direktnim na Decentraland podserver, znamo po tome što je server botovan tačnije pokušavaju da ubace 100k botova svakodnevno a nakon što je to sa nalozima fixano počeli su da ddosuju i ruše server

uglavnom sprema im se tužba a mi smo u procesu dodatne zaštite i optimizacije celog Hog Realmsa, CPU na skoro svim podserverima je sveden na MINIMUM na ispod 1% kad nema nikoga, takođe kroz core sređen je anti ddos dodatni koji nije tako dobar ali može da posluži, pored toga anti bot je usavršen do 120k konekcija po sekundi tako da server sa te strane NEĆE imati problema sem možda gušenja Discord četa na kratko.

botove će od sad AUTOMATSKI blacklistovati na Hogu a nama će logovati podatke o osobi koja to radi

trenutno smo takođe u procesu vraćanja proxy servera Hoga na BUNGEECORD umesto Velocity kako bi proxy koji povezuje sve podservere takođe bio bezbedan

**Comment by PiweeX** [comment]
Poruka iz zaključanog čet kanala od malo pre

Obaveštenje!

Moram da vas obavestim sve da već punih mesec dana traju napadi na Hog, prvo ulaze na naloge onda botuju onda ddosuju, postalo je neizdrživo, ddosuju osobe sa Angor earth servera koji se otvorio kao TOTALNA kopija Hoga samo što mi imamo 60 igrača a oni za 3 meseca rada napravili 4 reseta mape

mi smo gledali na bilo koji način da rešimo problem, na sve moguće načine smo se trudili, prebacili na bungeecord sa velocity sistema i delimično smo rešili bot napade kroz novi core koji sprečava napade do 120k botova po sekundi, osoba je indetifikovana (Dimitrije Dosić iz Bosne) i imamo sve njegove podatke tako da će u Januaru dobiti tužbu za šta ga čeka 3 godine zatvora minimum zbog ucene servera koje je rušio da pređu na njegov host i da kupe njegovu ddos zaštitu


Danas takođe ceo dan traju napadi ali bilo je minimalno padova servera i povećanja pinga, prošli mesec su nam ceo bandwitch prepunili i morali smo da isključimo TCPShield pa su sad dodatno jebali vratili smo TCP ali on nije dovoljan jer dečko sa cardovanim i nelegalnim mašinama ne prestaje da obara naš sistem, u roku od par dana ćemo nabaviti novu ddos zaštitu i odraditi promenu IPa kako bi se ddos sprečio totalno a u Januaru idemo u tužilaštvo jer su ovo iste osobe koje ruše Hog već mesecima i koje su totalno bolesne i opsednute time

proces ću kačiti na github ali i na dozuhoga povremeno, tamo možete pratiti razvoj situacije a do tad niko neće moći da igra na serveru jer ne želimo da server pada svakih 2h, razumite da je nama najteže sad jer mi smo upravo zbog ovoga morali da odvojimo silne pare iz budžeta servera kako bi se sve rešilo i to nije humano, svakako izaćićemo iz ovoga kao pobednici i server će raditi nesmetano i dok traje testnet kao i do sad

**Comment by PiweeX** [comment]
> Poruka iz zaključanog čet kanala od malo pre
> 
> Obaveštenje!
> 
> Moram da vas obavestim sve da već punih mesec dana traju napadi na Hog, prvo ulaze na naloge onda botuju onda ddosuju, postalo je neizdrživo, ddosuju osobe sa Angor earth servera koji se otvorio kao TOTALNA kopija Hoga samo što mi imamo 60 igrača a oni za 3 meseca rada napravili 4 reseta mape
> 
> mi smo gledali na bilo koji način da rešimo problem, na sve moguće načine smo se trudili, prebacili na bungeecord sa velocity sistema i delimično smo rešili bot napade kroz novi core koji sprečava napade do 120k botova po sekundi, osoba je indetifikovana (Dimitrije Dosić iz Bosne) i imamo sve njegove podatke tako da će u Januaru dobiti tužbu za šta ga čeka 3 godine zatvora minimum zbog ucene servera koje je rušio da pređu na njegov host i da kupe njegovu ddos zaštitu
> 
> Danas takođe ceo dan traju napadi ali bilo je minimalno padova servera i povećanja pinga, prošli mesec su nam ceo bandwitch prepunili i morali smo da isključimo TCPShield pa su sad dodatno jebali vratili smo TCP ali on nije dovoljan jer dečko sa cardovanim i nelegalnim mašinama ne prestaje da obara naš sistem, u roku od par dana ćemo nabaviti novu ddos zaštitu i odraditi promenu IPa kako bi se ddos sprečio totalno a u Januaru idemo u tužilaštvo jer su ovo iste osobe koje ruše Hog već mesecima i koje su totalno bolesne i opsednute time
> 
> proces ću kačiti na github ali i na dozuhoga povremeno, tamo možete pratiti razvoj situacije a do tad niko neće moći da igra na serveru jer ne želimo da server pada svakih 2h, razumite da je nama najteže sad jer mi smo upravo zbog ovoga morali da odvojimo silne pare iz budžeta servera kako bi se sve rešilo i to nije humano, svakako izaćićemo iz ovoga kao pobednici i server će raditi nesmetano i dok traje testnet kao i do sad

već je nabavljena ddos zaštita nije bitno koja i uglavnom plaćamo je po satu po svakom igraču, za sad nema problema ali očekuje se nestabilnost još neko vreme dok ne zamenimo IP tako da su i dalje mogući padovi ali mnogo je bolje makar za sad tako deluje

**Comment by PiweeX** [comment]
Svi podserveri na Hogu već danima imaju problem sa konekcijom zbog firewalla, zbog toga mnogi igrači ne mogu da uđu na server jer im samo pininguje kad se konektuju na zvanični IP. Ovo je posledica DDos napada na Hogov server,

dok se ovaj problem rešava mi sa manjim brojem prisutnih igrača tokom dana radimo neka testiranja i otklanjanje bagova, takođe dosta je optimizovan server i mnogo je manja šansa da neko pravi lag mašine, da ddosuje itd.

Svakako ustaše sa Atlasa imaju privatan IP koji smo nabavili za novu mašinu, ustaše su ustaše, oni će da ruše kao što su radili poslednjih 12 meseci a mi ćemo da gradimo. Veliki pozdrav za njih

**Comment by PiweeX** [comment]
SkyBlock je vraćen Djovaniju nakon obezbeđivanja naloga, pored toga na lobby-u više ne mogu da otvaraju trapdoorove

lobby je takođe sređen u poslednje vreme oko NPC-eva što je bio problem i oko logina tako da za sad nema načina za pravljenje problema preko njega

Ovih dana ću videti sa Bognarom o tome kako napreduje BedWars, stopirali smo rad na njemu zbog svih napada na server pa bi trebalo da se vratimo na to što pre jer nije ostalo još puno da bi sve bilo završeno ali je potrebno posvetiti sigurno 5 neprekidnih dana

Što se tiče mašine, mi moramo da nabavimo još 1 mašinu jer ustaše sa Atlasa su bekendale i novi IP, to nije jeftino da se nabavi imajući u vidu šta smo sve finansirali kako bi sprečili DDos i bot napade ali izguraćemo to do kraja Februara a na skladište discordu sam obećao još 3 mašine za besplatan mint koje ćemo finansirati u inat osobama koje ddosuju servere i onda im traže da pređu na njihov hosting kako bi prestale.

**Comment by PiweeX** [comment]
UHC je skoro gotov ali imamo problem da igrači ne mogu da uđu sa 1.7 verzije jer je lobby na 1.19.3..

pokušavao sam oko sat vremena da ovo sve rešim, backupovao više puta, kontaktirao support ali nije moguće jer se valjda blokira konekcija jer je na 1.19.3 generacija sveta drugačija, ipak iako nemamo ni bedrock na tom svetu i iako je dosta iznad 00 nije radilo, pokušavao sam i da dodam datapack koji bi omogućio konekciju ali nije moguće. Čak sam vratio i na 1.17.1 verziju gde je generacija sveta normalna, obrisao stari lobby i onda je imalo samo još veće errore

Kako će se ovo rešiti ne znam.. na 1.18 verziji je radilo normalno a na 1.18 je isto drugačija struktura sveta ispod 00. Sačekaću još neko vreme da se updatea ViaVersion pa ću probati, bukvalno ne možemo UHC koji smo hteli

**Comment by PiweeX** [comment]
Na svim podserverima na skladištu su odrađeni updateovi, novi backupovi i optimizacije

pored toga zbog konstantnih napada radimo i bezbedonosne mere, svi bot tokeni tačnije botovi će se prebaciti na moj drugi nalog jer je ovako rizično

**Comment by PiweeX** [comment]
Pre par dana na VPSu koji drži skladište promenjena je root šifra, odrađeni su viši stepeni bezbednosti jer stalno dobijamo napade i na taj način kroz discord bot tokene i druge metode da ne spominjem


Istina je da nam je DDos stvorio ne samo velike finansijske gubitke i probleme već i gubljenje mnogih igrača, zato sam i najavio da će mainnet početi ranije od uobičajenog, u Aprilu umesto u Maju i da ako Bog da uspećemo u tome


Krajem Februara bi trebalo da nabavimo još 1 mašinu kojoj ovaj put dosmanlije neće moći da pronađu privatan IP, to nam stvara još dodatni trošak na mesečnom nivou ali sam najavio i još 3 mašine koje će se deliti besplatno na skladište discordu tačnije koje će omogućavati novim serverima da se hostuju potpuno besplatno jer i mi sami znamo kako je nama bilo teško hostovati sve servere ranije. Podsetiću da smo u prošloj godini podelili mnogo besplatnih servera, u 2023. ćemo još više. Mustafa može da duva kurac

**Comment by PiweeX** [comment]
Sinoć se desio upad na moj nalog od strane dosmanlija sa Atlas Balkan servera. Ukupno su bili 10 miunta na nalogu, celu noć smo gledali logove i šteta je napravljena samo na laputi i black shopu, cela laputa je bila srušena i onemogućili su plugin za inventare preko su i za rollback ali su glupi pa je na fawe ostalo, tako da sve je vraćeno sem black shopa kog nikako nismo mogli da vratimo, uglavnom iako je pronađena alternativa za laputu a i imali smo 2 backupa stare svakako smo uspeli da vratimo ovu tako da nova neće biti.

**Comment by PiweeX** [comment]
Što se tiče ovog upada, dosmanlije su jer više ne mogu da zaustave rast servera koji su do sad usporavali došli i ušli na nalog preko IP-a kog smo promenili pre 1 mesec na Hetzneru, kako su ušli? direktno na IP i port Decentralanda, kako to? bungeeguard ne radi na spigot serverima tako da je to rešeno jer smo vratili pufferfish, inače je pufferfish izbačen pre par meseci jer je stvarao errore u konzoli.

**Comment by PiweeX** [comment]
Rešeno u potpunosti uskoro uprkos pretnjama da će ddos opet krenuti

**Comment by PiweeX** [comment]
Uskoro Hog neće moći da se ruši od dosmanlijskog ološa. Spremite se

**Comment by PiweeX** [comment]
Pošto je najavljena promena mašine na storijima pre nekoliko dana to se trenutno sprovodi kao što i treba

danas smo ponovo reaktivirali i tako popravili VPS za skladiste.net

sutra bi trebalo platiti dug za predhodnu mašinu a onda je otkazati i nabaviti potpuno novu, sve to će koštati dosta ali uspećemo da izguramo do kraja.

**Comment by PiweeX** [comment]
HR | 2k18 Radio

HR | SMP (obrisano)

HR | 2k18 Radio obrisano

HS | Licenses Base obrisano a nepotrebno

MNB | skladiste Support obrisano

HR | JavaStore Radio obrisano i nepotrebno

HR | DevMod obrisano i nepotrebno

HS | tradingflow. obrisano i nepotrebno

HS | tradingflow Radio obrisano i nepotreebno

HR | BTE obrisano i nepotrebno

HR | Liga Naroda obrisano

HR | Liga Naroda Support obrisano

HS | JavaStore Core obrisano

HS | Java Store obrisano




HR | Hogline. i HR | Decentraland (ostalo al su tokeni resetovani i glavni botovi su prebaceni na drugo)

**Comment by PiweeX** [comment]
Ovaj issue je otvoren početkom Juna prošle godine. Od tad, do duše i puno ranije ali od tad traju intezivni napadi na HogRealms i na mene kao i na moju porodicu


traju od osoba koje su mislile da mogu da za 20 dana budu bolji od Hoga pa pošto im to nije uspelo svoj neuspeh vide u nama. Meni ih je žao i prosto mesecima smo vodili borbu sa takvim osobama, dobijao sam pretnje smrću, maltretiranje putem sms poruka, otkrivanje mojih ličnih podataka i ostalog

Ja sam totalno nebitna osoba na Hogu, server je stvoren sa ciljem da igrači kontrolišu sve i u tome smo uspeli. Eto djonmla radi svoj SkyBlock podserver, drowned od 2018. platforme tačnije mini igre, partneri sa BuildTheEarthBalkan balkanske buildere i prosto ja sam tu nebitna osoba u smislu da sam ja samo kreirao Minecraft na Balkanu community pre negde više od 5 godina i registrovao udruženje građana kao neprofitnu organizaciju M N B.


Ja od Hoga ne jedem hleb, niti bilo koji server može da se pohvali svojom zaradom. Ja kao i neke porodice koje rade u Hogo kompaniji žive od svog rada i mi radimo softverska rešenja. Ipak dobijao sam pretnje smrću, pretnje da će me prebiti, da samo što nisu došli u moj grad itd.. Evo ja sam otkrio svoju adresu i čekam ih, ne mrzim nikog i ne vidim razlog da mene neko mrzi, ipak mene možete mrzeti ali ne mešajte druge ljude u to, dakle familiju.

**Comment by PiweeX** [comment]
^ procitajte predhodnu objavu VRLO je bitna za dalji rad servera

**Comment by PiweeX** [comment]
Uz male poteškoće koje su trajale osposobljen je ceo Lands plugin tako da sad svi igrači mogu da koriste /lands spawn i ostale komande. Neki su iskoristili da kradu ali su dobili banove, takođe sad je ostalo da osposobimo teksturu i aplikaciju mape i server je tada da kažemo ponovo stabilan posle nekoliko meseci.


Takođe pošto sam prebacio sve bot tokene na svoj drugi discord nalog, tačnije pobrisali smo apsolutno sve botove a onda ih napravili ponovo na mom drugom nalogu gde su inače kao backup i neki važni serveri sa Decentralanda od igrača poput npr. za RP kartu staru, RP ligu itd

Uz to gledam da osposobim i db za banove i muteove tako da rade globalno na celom Hogu. Sitna promena je takođe da sam isključio obaveštenja u četu jer je npr slalo da ljudi mogu da počaste sebe i doniraju preko sajta a monetizacija preko Hoga je isključena još pre par meseci

**Comment by PiweeX** [comment]
Pošto smo rešili DDos problem Issue ću zatvoriti sada uoči tačno 9 meseci od otvaranja istog.

Kada radite nešto što je ispravno morate biti spremni da budete napadani od najvećeg ološa koji postoji. Mi smo kroz to prošli i ja sam lično osetio na svojoj koži kad te svi izdaju, svi oni kojima si pomagao i sa kojima si bio dobar.

Kao što znamo nova mašina je stigla i iako ima još par ključnih stvari da se podešava suština je da je DDos problem rešen i da server više neće biti napadan od strane ološa sa te strane da čim se oporavi od predhodnog dođe novi napad i onda sruši server.



Moram da se pohvalim i da je danas uspešno podnet zahtev za osnivanje Hogove firme, tačnije ovo je širenje Hogo Studios kompanije koja već postoji u UK-u samo za Srbiju baš kao što smo i zamislili. Može se naći pod imenom Software Engineering HOGO STUDIOS Lazarevac u apr-u
