### ISSUE TITLE
Zmajeva Kugla.

### ISSUE THREAD

**Issue by Attack36** [PiweeX/HogRealms#60]
Prvu stvar koji svatko čuje kad uđe na decentraland. I uz to, prva pomisao svih je uvijek ili "Koji je ovo vrag?" ili "Zašto je idalje tu ovaj vrag?"

Mislim da se treba maknuti taj zvuk jer ide na živce, ne dodaje iskustvu i nema veze sa serverom.

**Comment by akipaki293** [comment]
> Prvu stvar koji svatko čuje kad uđe na decentraland. I uz to, prva pomisao svih je uvijek ili "Koji je ovo vrag?" ili "Zašto je idalje tu ovaj vrag?"
> 
> Mislim da se treba maknuti taj zvuk jer ide na živce, ne dodaje iskustvu i nema veze sa serverom.

To možda ide na živce ali je dobar dodatak, dok traje ako ti smeta smanjis mc i kraj

**Comment by Darislaw** [comment]
> > Prvu stvar koji svatko čuje kad uđe na decentraland. I uz to, prva pomisao svih je uvijek ili "Koji je ovo vrag?" ili "Zašto je idalje tu ovaj vrag?"
> > Mislim da se treba maknuti taj zvuk jer ide na živce, ne dodaje iskustvu i nema veze sa serverom.
> 
> To možda ide na živce ali je dobar dodatak, dok traje ako ti smeta smanjis mc i kraj, ne vidim razlog za sklanjanje

Ti ne vidis, ali vise nas vidi, taj dodatak je suvisan i nepotreban, ja sam za da se skloni

**Comment by akipaki293** [comment]
> > > Prvu stvar koji svatko čuje kad uđe na decentraland. I uz to, prva pomisao svih je uvijek ili "Koji je ovo vrag?" ili "Zašto je idalje tu ovaj vrag?"
> > > Mislim da se treba maknuti taj zvuk jer ide na živce, ne dodaje iskustvu i nema veze sa serverom.
> > 
> > 
> > To možda ide na živce ali je dobar dodatak, dok traje ako ti smeta smanjis mc i kraj, ne vidim razlog za sklanjanje
> 
> Ti ne vidis, ali vise nas vidi, taj dodatak je suvisan i nepotreban, ja sam za da se skloni

Zmajeva kugla je tu od bete i lep je dodatak, to je kao prica sta se prvo desilo na rpu i treba da ostane

**Comment by JedemJaja** [comment]
> Prvu stvar koji svatko čuje kad uđe na decentraland. I uz to, prva pomisao svih je uvijek ili "Koji je ovo vrag?" ili "Zašto je idalje tu ovaj vrag?"
> 
> Mislim da se treba maknuti taj zvuk jer ide na živce, ne dodaje iskustvu i nema veze sa serverom.

Nek se zmajeva kugla makne

**Comment by markeccc998** [comment]
Neee

**Comment by PiweeX** [comment]
Zmajeva kugla nema neke veze sa serverom preterano ali je dodata jer nismo uspeli da nađemo sličnu priču o postanku sveta, msm to je ipak zamišljeno mesto, server je stvoren u tom vremenu

al ne znam šta bi slično moglo da se stavi.. ako imate neki predlog

**Comment by ZlajaCelendzGej** [comment]
nebi trebalo da se makne ali da postoji opcija da se iskljuci jer i meni ide na zivce

**Comment by Darislaw** [comment]
> Zmajeva kugla nema neke veze sa serverom preterano ali je dodata jer nismo uspeli da nađemo sličnu priču o postanku sveta, msm to je ipak zamišljeno mesto, server je stvoren u tom vremenu
> 
> al ne znam šta bi slično moglo da se stavi.. ako imate neki predlog

Evo ovk ja nisam za da se prica makne nek ostane, ali audio da se makne to je to sto nama igracima smeta, nek ostane prica npr na spawnu negde, nek se nadje drugi nacin, a ne preko audia koji traje par minuta

**Comment by PiweeX** [comment]
Ovo je rešeno ali nek ostane otvoren issue jer će biti promena u glasu USKORO

od profesionalnog voice aktera
