### ISSUE TITLE
Ukidanje glasanja za banove i ostale stvari koje se vezu za pojedine igrace na githubu

### ISSUE THREAD

**Issue by T1GAR** [PiweeX/HogRealms#61]
Bananje i ostale stvari koje se ticu pojedinih igraca su problem admina. Ovo glasanje nije pravedno sa apsolutno niti jedne strane. Treba biti ukinuto i nevazece, a admini trebaju postavit "hard" no mercy pravila i ako se prekrše ide određena kazna(koja nije uvijek ban) bez pitanja.

**Comment by konfix** [comment]
slažem se

**Comment by Pandzaaa** [comment]
slazem se!

**Comment by vukstrale** [comment]
Ostavite glasanje, ali neka samo dželati mogu da ga pokrenu što se tiče bana.
-Vuk_TheGreat

**Comment by dzelat** [comment]
Apsolutno se slazem da se takve stvari ovdje ne bi trebalo odlucivati. Ukoliko staff ne moze donijeti odluku onda neka se napisu pravila po kojima ce se kaznjavati ne mora biti kazna napisana u dan ali barem da znamo sto je za ban sto za jail...

**Comment by T1GAR** [comment]
> Ostavite glasanje, ali neka samo dželati mogu da ga pokrenu što se tiče bana. -Vuk_TheGreat

Ne to je ista stvar kao i ovo. Posao stafa je posao stafa a ne da random ljudi glasaju.

**Comment by T1GAR** [comment]
> Apsolutno se slazem da se takve stvari ovdje ne bi trebalo odlucivati. Ukoliko staff ne moze donijeti odluku onda neka se napisu pravila po kojima ce se kaznjavati ne mora biti kazna napisana u dan ali barem da znamo sto je za ban sto za jail...

Upravo to...

**Comment by PiweeX** [comment]
Rešeno
