### ISSUE TITLE
Kapibare na Decentralandu

### ISSUE THREAD

**Issue by JedemJaja** [PiweeX/HogRealms#62]
Bilo bi kul kad bi piwex dodao mod s kapibarama na server jer ih se moze jahati, stavljati cestove na njih, a i jer su hot.

**Comment by akipaki293** [comment]
Nemas modove na server samo plugini

**Comment by Coplek** [comment]
slazem se custom model kapibara, i divlja svinja da budemo hog rideri

**Comment by Coplek** [comment]
Kapibare bi bile jako dobre zbog ekonomije, hrane, i prijevoza, zamisli nabavis kapibaru, nek se hrane grozdjem i onda napravis kao ono za sargarepu i prase napravis to za kapibaru sa grozdjem il orahom npr sta vec jedu, i onda nazoves kapibaru lamborghini

**Comment by akipaki293** [comment]
Sta ja onda da radim sa konjima? Ako to se doda neka dobijes samo ti i razmnozavas i prodajes za velike pare, jer onda konji nemaju smisla.

**Comment by markeccc998** [comment]
Koji kurac sranje teško šta imaš jahatj jebene svinje ko crnac

**Comment by Coplek** [comment]
To nisu svinje i one su lijepe kapibare su dobre za zoloski, ratovanje icicu u napad na kapibarama ima neko nesto protiv i ne ne samo ja nego se random spawnuju rijetko

**Comment by NemanjaRusija** [comment]
Druže šta će nam to na serveru, bolje ptice dodati a ne ta sranja.

**Comment by Coplek** [comment]
e da i ptice treba
ali i kapibare
i sokola

**Comment by markeccc998** [comment]
> To nisu svinje i one su lijepe kapibare su dobre za zoloski, ratovanje icicu u napad na kapibarama ima neko nesto protiv i ne ne samo ja nego se random spawnuju rijetko

Kome treba jebeni zoološki vrt da gledaš životinje.i sta ce ti za rat imaš konje sta imaš jahati dijete od dobra i svinje

**Comment by markeccc998** [comment]
Dabra*

**Comment by NemanjaRusija** [comment]
> e da i ptice treba ali i kapibare i sokola

Šta će nam prasad po serveru to mi nije jasno

**Comment by 3Ragnar3** [comment]
kapibare nece biti brze kao konji one ce biti dosta sporije

**Comment by Coplek** [comment]
Da, takodjer bas su funny tkd kapibare su vrijedne ubacivanja i imaju pravo glasa ne diskriminirajte ih i prekinite bit rasisti nisu svinje nego su kapibare

**Comment by akipaki293** [comment]
> > To nisu svinje i one su lijepe kapibare su dobre za zoloski, ratovanje icicu u napad na kapibarama ima neko nesto protiv i ne ne samo ja nego se random spawnuju rijetko
> 
> Kome treba jebeni zoološki vrt da gledaš životinje.i sta ce ti za rat imaš konje sta imaš jahati dijete od dobra i svinje

Ja cu praviti zoo vrt

**Comment by NemanjaRusija** [comment]
> Da, takodjer bas su funny tkd kapibare su vrijedne ubacivanja i imaju pravo glasa ne diskriminirajte ih i prekinite bit rasisti nisu svinje nego su kapibare

DOSTA!

**Comment by Lenna672** [comment]
> > Da, takodjer bas su funny tkd kapibare su vrijedne ubacivanja i imaju pravo glasa ne diskriminirajte ih i prekinite bit rasisti nisu svinje nego su kapibare
> 
> DOSTA!

plz :(

**Comment by NemanjaRusija** [comment]
> > > Da, takodjer bas su funny tkd kapibare su vrijedne ubacivanja i imaju pravo glasa ne diskriminirajte ih i prekinite bit rasisti nisu svinje nego su kapibare
> > 
> > 
> > DOSTA!
> 
> plz :(

SIKTER!

**Comment by Darislaw** [comment]
> Bilo bi kul kad bi piwex dodao mod s kapibarama na server jer ih se moze jahati, stavljati cestove na njih, a i jer su hot.

Kolko igracima dosadno jbt, umesto da predlozis nesto korisno i normalno za promenu ti predlozis kapibare... necu nista da kazem ti sam shvati kakvo razmisljanje imas

**Comment by JedemJaja** [comment]
> Sta ja onda da radim sa konjima? Ako to se doda neka dobijes samo ti i razmnozavas i prodajes za velike pare, jer onda konji nemaju smisla.

Pa onda ti deri po konjima, nekim drzavama bi dobro dosle manje, sporije zivotinje koje bi bas zbog toga bile jeftinije

**Comment by JedemJaja** [comment]
> Koji kurac sranje teško šta imaš jahatj jebene svinje ko crnac

HOOOGG RIDDERR

**Comment by JedemJaja** [comment]
> Druže šta će nam to na serveru, bolje ptice dodati a ne ta sranja.

Da, slazem se, ali ptice nemaju neku veliku funkciju. Kapibare bi mogli jahati i na njih stavljati cestove

**Comment by JedemJaja** [comment]
> > To nisu svinje i one su lijepe kapibare su dobre za zoloski, ratovanje icicu u napad na kapibarama ima neko nesto protiv i ne ne samo ja nego se random spawnuju rijetko
> 
> Kome treba jebeni zoološki vrt da gledaš životinje.i sta ce ti za rat imaš konje sta imaš jahati dijete od dobra i svinje

Kapibare su jeftinije ratno prijevozno sredstvo.

**Comment by JedemJaja** [comment]
> Dabra*

Dabra nemres jahat

**Comment by JedemJaja** [comment]
> > > To nisu svinje i one su lijepe kapibare su dobre za zoloski, ratovanje icicu u napad na kapibarama ima neko nesto protiv i ne ne samo ja nego se random spawnuju rijetko
> > 
> > 
> > Kome treba jebeni zoološki vrt da gledaš životinje.i sta ce ti za rat imaš konje sta imaš jahati dijete od dobra i svinje
> 
> Ja cu praviti zoo vrt

Onda lajkaj

**Comment by JedemJaja** [comment]
> kapibare nece biti brze kao konji one ce biti dosta sporije

I zato ce ih bit jeftinije za nabaviti

**Comment by JedemJaja** [comment]
> > > > Da, takodjer bas su funny tkd kapibare su vrijedne ubacivanja i imaju pravo glasa ne diskriminirajte ih i prekinite bit rasisti nisu svinje nego su kapibare
> > > 
> > > 
> > > DOSTA!
> > 
> > 
> > plz :(
> 
> SIKTER!

Sikter ti mama

**Comment by JedemJaja** [comment]
Glup sam ko kurac, misclicko sam

**Comment by PiweeX** [comment]
da bi se mod ubacio server mora da bude na forge

a sad ako je server na forge, server je na 1.8 i starijim verzijama gde bi igrači morali da skidaju modove po svakom ulasku što je više za neki privatan server nego za server ovog obima kao Decentraland podserver

što se tiče tih životinja mogu se ubaciti sa modelima, ali takvi modeli koštaju itekako puno da bi smo izdvojili novac iz budžeta za samo tako sitnu stvar, nekako mi nema smisla, nalazila bi se u 1 biomu i eto.

Ovako će uskoro doći biom update za pustinjske predele i za celokupnu vodu, biće više velikih riba i čudovišta al kao custom rađene teksture gde će biti sigurno recimo pustinjskih ptica onih sa ultre i kamila (trebalo bi, već je testirano i ok je u većini slučajeva ali implementacija sa dev servera na glavni nije prošla dobro nikako te su se i nage pomešale sa njima i eo)

**Comment by PiweeX** [comment]
Kapibare smo ubacili na SMP podserver a uskoro na Decentraland dolaze mobovi koji će zameniti obične što nam je i plan predhodnih godinu dana

**Comment by PiweeX** [comment]
Ovaj issue smo držali mesecima jer sam hteo da kad odradimo modele koje smo želeli pred mainnet to i objavimo ovde tako da ću uskoro objaviti nove modele koje imamo

**Comment by PiweeX** [comment]
15 novih mobova mesečno na Borbe za Laputu podserveru 

(https://github.com/PiweeX/HogRealms/issues/485)


obaveštavam vas da je ovaj issue pri kraju svoje realizacije, već mesecima radimo na izdvajanju sredstava za Minecraft na Balkanu udruženje od kog bi mogli da napravimo puno mobova i tekstura za Borbe za Laputu specifično. Evo sad je došlo vreme

više o tome sam napisao u issueu koji je gore označen


trebam napomenuti i ovde da ovaj issue nismo zatvarali mesecima upravo kako bi jednom završili ovako nešto, i da napokon realizacija kreće i to ne u bilo kom procesu već u proizvodnji do 15 mobova mesečno.
