### ISSUE TITLE
- Brewery Plugin - Da se doda brewery plugin mozemo pravit alkohol i trade-at se po svijetu i to bi bio novi nacin ekonomije -HogRealms-

### ISSUE THREAD

**Issue by darixonn** [PiweeX/HogRealms#66]
Brewery Plugin je plugin koji nam dopustava da pravimo bilo koju vrstu alkohola npr. Vino,Viski,Rakia,Gin itd..
![Brewery](https://user-images.githubusercontent.com/75794558/174502070-499c217b-c028-4d6d-a3c2-5a56dff6dbd8.png)
.

**Comment by darixonn** [comment]
Glasajte 'Like' 'Dislike'

**Comment by Coplek** [comment]
TOOO JA SAM ZAGOREC HOCU GEMIŠT

**Comment by darixonn** [comment]
Post ce trajati 24 h  zbrojit ce se glasovi i odlucit cemo sa piweeexom o novim dodavanjima na server!

**Comment by darixonn** [comment]
> GEMIŠT

ima i tog!!!
nebrini

**Comment by Darislaw** [comment]
> Brewery Plugin je plugin koji nam dopustava da pravimo bilo koju vrstu alkohola npr. Vino,Viski,Rakia,Gin itd.. ![Brewery](https://user-images.githubusercontent.com/75794558/174502070-499c217b-c028-4d6d-a3c2-5a56dff6dbd8.png) .

Napokon nesto lepo za predloziti i korisno, ja sam za

**Comment by konfix** [comment]
plugin koji predlažeš nije imao novi update od prošle godine, ne podržava zvanično 1.18.2 (base verziju servera), a ni 1.19 koja će biti glavna verzija u budućnosti. Može da se nađe sličan ili da mi sami odradimo nešto tako, ali to ne mogu da garantujem

**Comment by darixonn** [comment]
> plugin koji predlažeš nije imao novi update od prošle godine, ne podržava zvanično 1.18.2 (base verziju servera), a ni 1.19 koja će biti glavna verzija u budućnosti. Može da se nađe sličan ili da mi sami odradimo nešto tako, ali to ne mogu da garantujem

ima 3 plugin-a licno testirano od mene radi na 1.18.2

**Comment by akipaki293** [comment]
> > Brewery Plugin je plugin koji nam dopustava da pravimo bilo koju vrstu alkohola npr. Vino,Viski,Rakia,Gin itd.. ![Brewery](https://github.com/assets/75794558/499c217b-c028-4d6d-a3c2-5a56dff6dbd8) .
> 
> Napokon nesto lepo za predloziti i korisno, ja sam za

Rekao bih da je ovo prvi put da se ovaj gospodin slaze za nesto

**Comment by darixonn** [comment]
@PiweeX  ovo je po prilicno izglasano moze li se sada napraviti odluka.

**Comment by PiweeX** [comment]
Bilo je više issue-a o ovome i Attack se bacio na posao, biće gotovo ubrzo imam informacije o tome
