### ISSUE TITLE
Lidl

### ISSUE THREAD

**Issue by Savohog** [PiweeX/HogRealms#67]
Mogli bi ste dodat neke stvari u shop koje se ne mogu dobiti npr ink sac od hobotnice blaze rod za napitke i to ender pearl (da kosta negdje oko 10k 2 komada) i te stvari.

**Comment by Darislaw** [comment]
Slazem se sa predlogom ali ne u potpunosti, ja sam protiv end pearla, i dalje ne mogu da shvatim kako vi igraci mozete da trazite neke stvari ds budu u shop a pritom da kostaju mnogo novca u razlici s ostalim stvarima, kao npr prosli put sto trazio valjda fropik, ne secam se, ceo obican dmd set za 1 milion.. Bolje da ni ne budu uvedeni u shop takve stvari, besmisleno je a i velika ce tek biti inflacija i novac nece imati smisla.. a kolko vidim ni sad nije bas nesto bolja situacija sto se tice novca. Ali vidim bolju buducnost malo po malo.

**Comment by akipaki293** [comment]
> Slazem se sa predlogom ali ne u potpunosti, ja sam protiv end pearla, i dalje ne mogu da shvatim kako vi igraci mozete da trazite neke stvari ds budu u shop a pritom da kostaju mnogo novca u razlici s ostalim stvarima, kao npr prosli put sto trazio valjda fropik, ne secam se, ceo obican dmd set za 1 milion.. Bolje da ni ne budu uvedeni u shop takve stvari, besmisleno je a i velika ce tek biti inflacija i novac nece imati smisla.. a kolko vidim ni sad nije bas nesto bolja situacija sto se tice novca. Ali vidim bolju buducnost malo po malo.

Po tom fropikovom jedan deo kosta 250k, sada jedan full set sa mendingom kosta 250k,i to ima smisla, necu da prodam oklop sa mendingom za npr 100k kad mending vredi vise od 50k... Sto we tiče lapute to za perle je dobro ali da se doda oko 8k 2/3, da se dodaju stvari koje ne mogu ovako a potrebne su...

**Comment by Coplek** [comment]
ne perle su skroz bespotrebne, zalite se da srw nije rp, a hocete perle, dalje sta ce ti buraz moj perle da se po mapi portas, pvpas se s nekim da se perlas, kakvog smisla onda imaju zidine, da se perlas preko zidina, nemoj molim te, perle se nece ubacivat, a sto se tice blaze roda isto ne, nego blaze powder, za potione

**Comment by akipaki293** [comment]
> ne perle su skroz bespotrebne, zalite se da srw nije rp, a hocete perle, dalje sta ce ti buraz moj perle da se po mapi portas, pvpas se s nekim da se perlas, kakvog smisla onda imaju zidine, da se perlas preko zidina, nemoj molim te, perle se nece ubacivat, a sto se tice blaze roda isto ne, nego blaze powder, za potione

Powder da, ja sam imao perle sam skupljao i po laputi trazio one skrivene sajnove i sve potrosio haha

**Comment by PiweeX** [comment]
![unknown-7](https://user-images.githubusercontent.com/33425430/196843447-454d1e4d-5d71-4e9e-b2d8-34438cbf8404.png)

![unknown-8](https://user-images.githubusercontent.com/33425430/196843460-92c016e5-8e34-4519-ab5d-578322c6e9ed.png)

Hvala Djovaniju i Djomli na zalaganju, ovih dana su pravili reforme u ekonomiji i ujedno poboljšanju igre za sve igrače kroz crni market, ovo će biti veoma dobro vremenom a uskoro će biti i pušteno tako da će igrači već do kraja meseca Oktobra mislim moći da pristupe tom zatvorenom marketu ispod zemlje koji će imati questove i koji će dići gameplay na viši nivo
