### ISSUE TITLE
HogRealms na verzijama od 1.7 do 1.18X

### ISSUE THREAD

**Issue by PiweeX** [PiweeX/HogRealms#69]
Povodom UHC kupa na pola decenije Hoga server mora da se prebaci na više verzija, ovo znači da će se na lobby moći ući sa svih verzija od 1.7 verzije do 1.18.2 i ujedno će svaki podserver imati svoju verziju na kojoj je

**Comment by PiweeX** [comment]
PRIMER 1 

Lobby preko Velocity na verzijama od 1.17 do 1.18.2

Decentraland na verziji 1.18.2

SMP na verziji 1.19

a UHC na verziji 1.8


igrač koji želi da igra SMP neće ući na 1.18.2 već na 1.19, ujedno proxy tj preko lobija će mu raditi i na 1.18.2 i na 1.19 a na podservere na koje bude ulazio će ući verzijom na kojoj su ti podserveri dostupni

**Comment by dzelat** [comment]
kad možemo očekivati decentraland na 1.19 znam koliko je tu posla i koliko je to trajalo kada smo prelazili na 1.18. Da li je to uopšte u planu?

**Comment by konfix** [comment]
> kad možemo očekivati decentraland na 1.19 znam koliko je tu posla i koliko je to trajalo kada smo prelazili na 1.18. Da li je to uopšte u planu?

tesko je da se server u ovakvom stanju sad prebaci na 1.19 tako lako i brzo, moze eventualno viaversion ali rekao bih ne nista vise od toga
