### ISSUE TITLE
Nations

### ISSUE THREAD

**Issue by Galilejo** [PiweeX/HogRealms#7]
Bilo bi dobro da se uvede nations opcija u lands, na taj nacin bi mogli i praviti gradove i oblasti, te bi jedan claim mogao pokrivati jednu državu sve bi bilo mnogo organizovanije nego sto je sada.

**Comment by akipaki293** [comment]
Ovo treba

**Comment by buducidzelat** [comment]
> 

pokusano vec jednom ali neuspesno

**Comment by PiweeX** [comment]
ovo je bilo u planu, uvodi se uskoro kao test na server. Inače je bilo i u ranoj beti pa je komanda uklonjena skroz zbog toga što nije bilo razlike između lands claima i nations pa je Gothia predložio da se nacije skroz izbrišu jer su bile preskupe

videćemo, ovo nas očekuje uskoro i možda i bude rešenje za političke karte

**Comment by PiweeX** [comment]
Rešeno
