### ISSUE TITLE
o Pay To Win-u!

### ISSUE THREAD

**Issue by PiweeX** [PiweeX/HogRealms#72]
Evo malo vremena da pored Abuse teme obradim još jednu temu koja se neretko vrti i koju svi vole a to je A pX a Ti UzImAš PaRe kAkO tE nIjE sRaMoTa

sve što sam ikada radio radio sam pošteno

nikada nisam radio sa namerom da steknem materijalno dobro za sebe i lične interese preko noći, iako mi se nudilo i to dosta puta preko Hoga a pogotovo u zadnje 2 3 godine.

u svakom radu postoje greške, ne možemo imati idealan sistem, najveći uređeni sistemi kroz istoriju su imali svoje padove i rušili su se

svako ko je na Hogu od ranijih godina a ima vas puno jer imamo jak community koji ostaje uz server, zna kako smo radili do sad i zna da radimo na Hogu totalnih 5 godina da bi tek sad došli na ovaj nivo, tačnije od 2020. je server počeo da dobija svoj oblik a 2019. da se formira kad su uvedene veće reforme, 2018. je bilo priča o tome i dosta, dosta rada....

Dakle, ovo su godine rada i truda, reformi, padova, stresa i ponovnog padanja, neko je morao tu da se žrtvuje dosta, i ja i par nas u timu. Podsetiću vas podatka da 9 od 10 startupova propadne, ovo je priča koja je pokrenuta dok smo bili 6 razred pre bukvalno sad će 5 godina u Julu. Odmah u početku smo ušli jako i sa nekom klinačkom namerom da budemo najbolji u tome, ali naravno onako rekli smo to čisto eto klinački, ne sa znanjem da će ovo doći na ove razine, to sam video tek negde 2018. i 2019.

žao mi je što ranije nije pokrenut Github iako je bila namera ali se odužilo pa da vidite kolko se radilo samo u poslednjih 6 meseci, nego eto sad je sve skoro i uređeno i gotovo sa tehničke strane pa nema puno toga da vidite..

DA PREĐEM NA TEMU (PX PREĐI NA TEMU)

**Kako to ljudi vide**

Neko je kupio rank ili unban sa web shopa servera, PX UZIMA MASNE PARE I MANIPULIŠE DECU!

**Kako je zapravo**

Troškovi servera da bi bio bolji više od 1300 evra godišnje i preko 60 evra mesečno (uzmemo samo mašinu i još neke sitnice) Gde je tu nečiji višesatni rad, cimanje, stres svakoga dana?

shvatite da ovo radim ni za pare ni volonterski već zato što volim i zato što imamo cilj koji smo zamislili i pre 5 godina i cilj koji nije materijalan ili ličan.

Isto tako morate shvatiti da nije potrebno prodati 1000 rankova da bi postali bogati, dovoljno je da prodate 30 rankova po 20$ i vi ste u abnormalnom X

tu dolazimo do teme drugih defektaških servera koje vode kompleksaši, ukoliko pratite dozahoga na Instagramu tu ironično kačim storije gde prozivam te servere i jednostavno slike primera gde se ljudi mogu uveriti na koji način ti serveri funkcionišu.. Rećiću samo po 10 kanala za donacije, eto dovoljno, ali su dovoljno lukavi da znaju da otvore velik server i da stvore hype pa da zbrišu nakon 2 meseca kad im troškovi postanu ne isplativi i kad im niko ne igra jer je server bullshit. Naprave nekoliko takvih sezona pa izračunajte, AL NE KONTAŠ PX to je CoMeBaCk na ScEnU

**MARŠ U PIČKU MATERINU!**

E sad tema, znači slažem se da na shopu nije bilo dobrih stvari za eto recimo jedan RP server do kraja ali je totalno svaka stavka legit i sa razlogom dodata, isti perkovi se prodaju na Hypixelu i većim serverima za 5e pa tu niko ne pravi pitanje oko toga al problem je kad PX iz Srbije deci proda rank od 20e E kukala vam majka luda

u suštini, build mod, build mod je predstavljen kao da su igrači imali kreativ, to uopšte nije creative mod već su neki dovoljno glupi da ni to ne shvataju ali dobro, pisao sam o tome pa ne mogu više. (AlienCraft, MineRealms) i drugi domaći serveri su imali ISTI princip, cilj build moda je bio da svaka država ima svog buildera a da server stekne dobar novac od toga a ujedno države budu prejako izgrađene. Build mod je ukinut pre 4 5 meseci jer su mnogi pogrešno shvatili i više ne postoji u obliku da se kupi niti koristi

DAKLE BUILD MOD NIJE KREATIV, BLOKIRA SVE RADNJE IZ KREATIVA SEM BUILDANJA, ZATO SE I ZOVE BUILD MOD, KONTAŠ KAO BUILD PA MOD A USTVARI NIJE KREATIV NEGO BUILD MOD A ZAPRAVO BUILD MOD KAO MOD, STEVO POZDRAVLJA TE MAMA!

unban, šta je problem sa unbanom????? Najveći serveri deru pare na unban opciji na storeovima, tu nema ništa loše, ako dobiješ ban a stalo ti je do servera jer ti tu igra društvo ili sl, plati unban pa da vidimo dal ćeš opet da praviš probleme.

rank, ovo je glupo komentarisati

**Comment by PiweeX** [comment]
CIlj Hoga kao servera i projekta je da stvori nešto dobro za osobe koje igraju, dobro mesto za zabavu chill i druženje pre svega

da sam hteo, mogao sam da napravim server gde govorim Majnkreft umesto majnkraft server (NEĆU DA IMENUJEM, ne imenuj ljubi te mama) i da uzimam pare a ujedno znate šta je najjače kod tih osoba! što nemaju trunke stida te kad bi otvorio takav server, zamislite, kad se ugasi uopšte ne moram da se javljam ljudima što se žale da su potrošili masne pare na rankove, ne moram, napravi se drugi discord i gura se nova sezona uz NajjAčI CoMeBaCk na BAlK0nu koji će opet trajati 3 meseca!

Kolko dobra stvar! Zamisli, govoriš majnkreft server i skemuješ ljude! Pa ima li boljeg!


moja adresa je javno dostupna svakome ko je kupio rank a i ovako, dakle nemam od čega da se krijem, Hog ima firmu, plaća porez, nikome nije ostao dužan i igrači koji su kupili bilo šta imaju tu stvar uz punih 5 godina uptimea, ne jebena 2 meseca i onda ComEbAcK NA sCEnU UUZ Novu SeZoNu na mom MajnKreFT SERVERU!

**Comment by PiweeX** [comment]
izvinite, zaboravite sve što sam rekao

predomisio sam se! Kupite rank na mom MajNkreFt serveru! IP je (ne imenuj, neću).xyz

**Comment by PiweeX** [comment]
![download](https://user-images.githubusercontent.com/33425430/174902807-24d9d5b8-e815-41f1-8854-643435415d2d.png)

ma, bre, oni deru pare od rankova i manipulišu!


Šalu na stranu, bogatstvo se meri time koliko ste ljudi usrećili, 80% toga nam se svodi na nove društveno korisne projekte

tužno je što će i posle ovog celog posta neki govoriti o nekakvom Pay to Winu,

pomenuo bih samo da smo mi konačno u ovoj mogućnosti i još možda 2 servera na Balkanu, verovatno jer niko od ovih scammy defekt servera nebi imao karakter da drži server tokom 5 godina propasti igre na Balkanu a da je predhodno igra bila najviše igrana u regionu, ne samo karakter, niko nebi želeo jer nikog nije briga za igrača kao čoveka već ih boli da ne kažem šta

**Comment by PiweeX** [comment]
i da hoću da pomenem, mi to radimo.

Što se neko drugi nije setio da pokreće nešto pametno u sklopu svog game servera? Pa nije

**Comment by akipaki293** [comment]
Jer ljudi nemaju para 😂 ja sad mogu krenem na aternosu i uporno da ne zatvaram i da se trudim da vidim kako ce biti za 5 godina

**Comment by Coplek** [comment]
također zelite roleplay? sto bi bilo kad bi uveli da onaj koji umre dobije 5 sati haga, dodamo pravila PG-radnja nemoguca u rl kaznjava se RPS- ponasanje igraca ko da mu niko nista ne moze- kaznjava se RK- ubistvo iz osvete kaznjava se FEARP- nemas strah za svoj zivot kaznjava se zelite roleplay najmanji je problem kaznjavat za to i napravit pravi roleplay roleplay je server zbog ratova izmedju drzava, rl mape, ekonomije itd, ali vi se zalite na rp servera zbog rankova i tih stvari, svatko tko zeli pravi hard roleplay, eto otvorite issue i izglasajte da srw bude hard rp, al onda se nemojte zalit kad vas budemo kaznjavali za krsenje rp pravila

**Comment by PiweeX** [comment]
Evo da napomenem da će shop uskoro biti u potpunosti ugašen, pre oko mesec dva smo prihvatili eulu u potpunosti jer je bilo nekih propusta ali sad se shop skroz gasi i neće biti opcije da igrači doniraju novac u communty jer ne želimo da jedan pojedinac kao persona dobija specijalan status među igračima ako je recimo top donator a što se moglo videti da se vole hvaliti i pokazivati moć

Više neće biti rankova za kupovinu, nemate zašta da me prozivate. Možete samo da me uhvatite za kurac, svojim mozgom sam razvio preko 20 patenata plugina preko kojih dižemo MC i game servere na viši nivo, ne želim da dobijam novac za koji će neko sujetan reći kako pljačkam nekoga ako se odlučio da kupi rank..

P.S osobama koje su do sad kupile rankove imaće svoj rank na 3 godine na tom nicku baš kao što je i pisalo pre njihove kupovine, neko na godinu a neko na 3 u zavisnosti kako je menjano ranije

**Comment by PiweeX** [comment]
> 

zbog ove objave nekoliko ljudi se javilo za kupovinu rankova dok se shop u potpunosti ne ugasi

kao korak ka ovom gašenju dodato je obaveštenje u promo četu te je obavest za UN invite zajdeno premešteno sa tom obavešću u taj kanal

pored toga na laputi na Decentralandu je uklonjena slika koja promoviše kupovinu rankova, dakle zmaj.ymll fajl obrisan

**Comment by PiweeX** [comment]
> > 
> 
> zbog ove objave nekoliko ljudi se javilo za kupovinu rankova dok se shop u potpunosti ne ugasi
> 
> kao korak ka ovom gašenju dodato je obaveštenje u promo četu te je obavest za UN invite zajdeno premešteno sa tom obavešću u taj kanal
> 
> pored toga na laputi na Decentralandu je uklonjena slika koja promoviše kupovinu rankova, dakle zmaj.ymll fajl obrisan

ovo će biti malo komplikovaniji proces jer će igračima koji su ranije kupili rank trebati da se prvobitno urede rankovi, u suštini mogao bi biti ugašen do sredine sledećeg meseca maksimalno do kraja

**Comment by PiweeX** [comment]
još 1 korak ka gašenju shopa, glavni plugin za shop koji je integrisan Crafting Store upravo obrisan i neće ga biti od ujutru

**Comment by PiweeX** [comment]
![Screenshot_2022-10-20-04-20-14-933_com brave browser](https://user-images.githubusercontent.com/33425430/196840887-aa517571-aa58-4ce4-8057-72def8e42a18.jpg)

20ti Oktobar je i kao što je i najavljeno shop je ugašen, igrom slučaja juče smo podešavali TCPShield zbog ddosova konstantnih u zadnja 2 3 dana pa smo uklonili usput i recordove na cf koji drže shop, žao mi je sad što nismo slikali ali svakako imali smo slike od ranije landing page-a

Više zvanično ne postoji način da kupite rank, perk ili bilo šta drugo zašta smo bili prozivani, hejteri mogu da ga dućkaju što bi reko davinči

U narednom periodu ćemo rešiti stvar sa rankovima tako da osobe koje su kupile ranije i koje ga imaju 3 ili 1 godinu (kako ko) budu zadovoljne a da paralelno postoji način da i obični igrači dobiju rank free.

**Comment by PiweeX** [comment]
Želeo bih takođe da se zahvalim svima koji su ikada kupili nešto sa shopa ili donirali novac na bilo koji način, vi ste doprineli da se ovaj community izgradi, više puta sam pisao gde novac od donacija ide, da mi unapređujemo server i da nam donacije ne poklapaju ni deo ukupnih troškova na mesečnom nivou koje smo plaćali te smo na kraju odlučili da svi rankovi idu u humanitarne svrhe tačnije novac od rankova ali ipak smo ugasili u potpunosti tu mogućnost na celom Hogovom Realmsu jer smatramo da nema potrebe za tim a da nas paralelno neko proziva, mi smo razvili svoje plugine kroz Hog koji vrede puno više od bilo kog ranka i ne moram nikome da se dokazujem gde bi novac išao i kolko smo uzeli novca od rankova i prozivke da je p2w itd.. Uživajte, mi imamo svoje izvore prihoda kroz patente koje smo razvili i vrlo rado pomoću njih izdvajamo veliki novac za troškove i nadogradnje a uskoro i dovođenje youtubera

Pozdrav i opet kažem hvala svima, na kraju naravno niko nije oštećen i svi koji su kupili imaće do isteka svog roka od 3 ili 1 godine

Podsetiću da ko je kupio rank 2017. imao je tokom svih 5 godina, to nigde niste mogli videti ali eto kanceri su kanceri i zbog njih smo i ugasili shop, hvala još jednom svima i toliko od mene u ovom polju
