### ISSUE TITLE
Minigames

### ISSUE THREAD

**Issue by PiweeX** [PiweeX/HogRealms#73]
.

**Comment by PiweeX** [comment]
![download](https://user-images.githubusercontent.com/33425430/175698699-a0f3b4c6-16e3-447d-aadb-b3ab19b72e48.png)

started a larger project

**Comment by PiweeX** [comment]
![unknown](https://user-images.githubusercontent.com/33425430/177883113-d6526d7e-db4c-4405-a56e-246de1adf772.png)


It'il all be over in time!

**Comment by frop1k** [comment]
Sto ovo vamo kacis

**Comment by PiweeX** [comment]
![download](https://user-images.githubusercontent.com/33425430/178058982-53ac7580-9386-42e9-894a-34bec2e05bb6.png)

bedwars map

**Comment by PiweeX** [comment]
![download](https://user-images.githubusercontent.com/33425430/178060554-50a47c47-5995-46a4-b160-8ec7c5095dd6.png)


grass removed

**Comment by PiweeX** [comment]
![11](https://user-images.githubusercontent.com/33425430/178070162-29a89011-f527-4580-b846-f5f523ef3423.png)

**Comment by PiweeX** [comment]
![2](https://user-images.githubusercontent.com/33425430/178070182-e0e05a8d-76cb-4e35-ab02-b6b50252ce3e.png)

**Comment by PiweeX** [comment]
![3](https://user-images.githubusercontent.com/33425430/178070197-edf2a64a-a383-4825-a53f-b72db9523166.png)

**Comment by PiweeX** [comment]
![1 (2)](https://user-images.githubusercontent.com/33425430/178070220-50b157f6-1965-414e-9514-6785ae51b840.png)

**Comment by PiweeX** [comment]
![77](https://user-images.githubusercontent.com/33425430/178070244-7f67f07a-7ed9-4e2f-a8e2-7083b87537ff.png)

**Comment by PiweeX** [comment]
![66](https://user-images.githubusercontent.com/33425430/178070260-7175c87d-86b2-4133-8456-95ab5da12676.png)

**Comment by PiweeX** [comment]
![55](https://user-images.githubusercontent.com/33425430/178070279-d459a99f-04c6-4747-8bfd-30cf41c0e16c.png)

**Comment by PiweeX** [comment]
![download](https://user-images.githubusercontent.com/33425430/178070546-43e5f394-a79c-4aff-a070-ebc999c7522c.png)

**Comment by PiweeX** [comment]
![download](https://user-images.githubusercontent.com/33425430/178070694-1b7c02ac-db87-4374-bec4-56b7c1a6b99c.png)

**Comment by PiweeX** [comment]
![download](https://user-images.githubusercontent.com/33425430/178071019-6c3bfed6-3064-4581-93e9-75a77e51e1e1.png)


parkour *progress*

**Comment by PiweeX** [comment]
![download](https://user-images.githubusercontent.com/33425430/178071500-e1599682-3daf-4c2a-a643-ea0d7231c74a.png)

**Comment by PiweeX** [comment]
![download](https://user-images.githubusercontent.com/33425430/178071524-50bc2a06-3cc1-4924-a2e4-72674cc9d42a.png)

**Comment by PiweeX** [comment]
Ovo nam je jedna od prvih većih saradnji, zatvaram ovaj issue jer je davno gotova jer je bila jednokratna saradnja 👍🏻
