### ISSUE TITLE
NOVI IGRAČI ODLAZE

### ISSUE THREAD

**Issue by PiweeX** [PiweeX/HogRealms#74]
Od kako je javan Decentraland otvoren sve trigeruju novi igrači koji govore da je server shit i da ne znaju da izađu sa spawna, igraju, ne znaju o čemu se radi na serveru itd..

2018. smo imali isti problem dok je SMP bio javan, zaista je tužno da određen broj ljudi provede godine radeći na serveru i onda dođe neko i popljuje to samo zato što ne zna kako se igra..

dakle, kad se uđe na server, prvo na lobiju (hubu) ljudi kad uđu budu izgubljeni, nakon što sam ovo uvideo odlučio sam da sklonim ostale gedžete iz inventara i da ostavim samo KOMPAS (a da, pre je bio nether star, sad je još jasnije uz kompas), nakon što ni ovo nije palilo dodao sam svetleće NPCeve, nakon što ni ovo nije upalilo dodao sam NPC koji šeta levo desno i na kom piše da treba da se klikne KOMPAS, uz to stavljen je i dosta lepo urađen hologram na kom piše kako ući na podserver u bukvalno 2 reči

zatim, uđu na Decentraland, tu imaju prvo tutorial koji ih baci sa lapute u vodu a onda na vrh lapute gde im piše 1 HOLOGRAM u 3 REDA sa OZNAKAMA i sa EMOJIIMA, piše im parafraziraću 1. Uđi na discord 2. Pridruži se nekoj od država 3. Skini aplikaciju I TO JE TO, BIĆE IM JASNO SVE! Pored toga na lobiju imaju objašnjenje u kompasu za svaki podserver i za svaku igru, onda dodao sam i znak na kome piše da kucaju /tutoriali, a da i tutoriale smo snimili, a da i custom komandu dodali PA ŠTA VIŠE DA URADIMO?

ili npr. uđe na server i na lobiju otvori kompas pa piše na instagram kako ne može da uđe jer piše da je privatno a video SMP podserver

bitno je napomenuti da ovo nema veze sa godištem, nevezano je, bitno je samo da ogroman % igrača server gubi samo zato što ljudi ne shvate početak, ovo me toliko trigeruje da počnem da im jebem pokoljenja.

želim da čujem vaše mišljenje kako da rešimo ovaj problem? Greota

**Comment by PiweeX** [comment]
![jedna dosta stara gradjevina na hogu](https://user-images.githubusercontent.com/33425430/175320452-c482aad5-a4bd-4cb8-a3ea-69214b9bf7c7.png)

![11](https://user-images.githubusercontent.com/33425430/175320477-5dbcf2ca-67d8-47f0-ad35-4d812434904b.png)

**Comment by akipaki293** [comment]
Px, nema spasa novim igračima, jedino kad udju da im 5 minuta pise kako sta i gde na ekranu, i ako je moguce nekako samo novim IP-evima to da se namesti

**Comment by konfix** [comment]
Spawn je previse zbunjujuc, treba da napravis 10 kruga da bi pogodio rupu odakle mozes da izadjes. Bilo bi idealno za ove nove koji ne znaju gde se nalaze da se malo promeni spawn

**Comment by akipaki293** [comment]
Napisano ovo, na svakih 2h ce se ostavljat u promo, kad tad u chatu i preko MHN Novosti



Za nove

Ujedinjene Nacije - discord gde prijavljujete nestanak stvari, krađu, grif... Mesto gde se nalazi i zakon Hog Decentralanda https://discord.gg/Hqtkzx24gR

MHN Community 

Community koji obuhvata Hogo Psihijatriju, Hogo Novine, MHN Evente, Hog Političku Mapu. 
https://discord.gg/hjWYwFcG5g

Kako započeti? 

1. Pogledati /tutoriali
2. Naći sebi odgovarajuću državu na Discord-u u kanalu #promo  /discord
3. Skinuti HogRealms aplikaciju, live mapu sveta na Play Prodavnici

Koraci za pravljenje države:

1. Naći Mesto za državu
2. Napraviti discord za nju
3. Napisati ustav
4. Claimati i zabavljati se

Najvažnije komande:

/la (laputa, gde ljudi prodaju stvari) 
/la sell cena (item se drži u ruci. Stavljate iteme na laputu) 
/land create (napraviti land) 
/land claim (claimati chunk) 
/land trust ime default (ubaciš nekoga u tvoj land) 
/land claim radius broj (claimas veći broj chunkova) 
/spawn (odlazis na spawn) 

Kako zaraditi? 

Prodavanjem stvari na laputi
Prodavanjem ribe i wheata na spawnu 

Dobre države:

Mongolija:
https://discord.gg/47vHapur6h
Engleska: https://discord.gg/vcnFpUZfQf
Pacifički Diktat:
https://discord.gg/sYbHsXHg

**Comment by PiweeX** [comment]
Kako bi se ovo rešilo u poslednjih nekoliko nedelja Knedla radi nove tutoriale po starim skriptama koje će kroz vizuelni identitet kroz par minuta jednog klipa brzo predstaviti novim igračima sve o Hogu

**Comment by PiweeX** [comment]
Takođe na lobby se upravo dodaju hologrami iznad svakog podservera

![download](https://user-images.githubusercontent.com/33425430/189479785-0ef2440e-89cd-419f-a528-6cbe39749639.png)

**Comment by PiweeX** [comment]
![download](https://user-images.githubusercontent.com/33425430/189480105-f4d8c036-ac18-4f19-a6d4-1135c3610dd2.png)

3 servera napisana ostala 3 će biti ubrzo

**Comment by PiweeX** [comment]
- "&8(&fDesni Klik!&8)"

preuredjeno na kompasu

**Comment by PiweeX** [comment]
Nemanja upravo na lobiju piše tutoriale za ostale podservere

**Comment by PiweeX** [comment]
Lobby (Početak):

Ako ste novi na serveru moraćete se registrovat komanda je /register (šifra) (šifra)

Posle registrovanja morat ćete se loginovat /login (šifra)

Ako ste zaboravili šifru obratite se PiweeeX-u ili Djovaniju

Da uđete u na Hogov podserver Decentrland idi kompas i nađete ili nađete Iron Golema

Imate još podservera kao što je HogSMP, Build Škola i Platforme

**Comment by PiweeX** [comment]
![download](https://user-images.githubusercontent.com/33425430/189527822-925aec0a-992a-4472-8697-1d39fc9197f5.png)

**Comment by PiweeX** [comment]
> Lobby (Početak):
> 
> Ako ste novi na serveru moraćete se registrovat komanda je /register (šifra) (šifra)
> 
> Posle registrovanja morat ćete se loginovat /login (šifra)
> 
> Ako ste zaboravili šifru obratite se PiweeeX-u ili Djovaniju
> 
> Da uđete u na Hogov podserver Decentrland idi kompas i nađete ili nađete Iron Golema
> 
> Imate još podservera kao što je HogSMP, Build Škola i Platforme

Dodati još neke sitnice i objaviti u sobi čet dok se ne nađe rešenje

Za nove igrače ostali podserveri i kako da igrate na njima Takođe nešto i o MNB (MINECRAFT NA BALKANU):

- Platforme

Platforme su nastale od SMP igrača Bognara i Arqvia. Da bi ste igrali platforme morate na lobbyu naći platforme i ući. Platforme su zanimljive jer imaju mini igre, Možete dobiti kitove kada votate za hog. Naravno imaju eventi na Platformama, pratite kanal event i možete svojiti vrijedne nagrade. Da stvorite komunikaciju sa igračima platformama uđite na discord server: 

- Hog SMP 

Hog SMP je privatan server za Hog yutubere. Server je napravljen 2017 godine. Svake godine reset. Ima 6 godina od stvaranja servera i 6 sezona na novoj verziji. Na smpu ima 20-18 igrača. Da igrate na SMP-u prijavite se na ig @hogsmp. Trenutni vlasnik tog podservera se traži, prije je bio Zlaja_Chellange. Najbolja sezona je 2018 godine. Na ovom SMP-u igrači stvaraju kreativnost, zabavu, maštu.... 

- Build Škola

Ako niste vješti sa buildom ili hoćete da poboljšate znjaje ovo je odlično mjesto za vas. Ovaj server je napravljen da bi se pomoglo igračima što se tiče builda. Ovu zajednicu vodi Leooon. Da se prijavite za Build Školu morate ući na discord server: https://discord.gg/7Aj7HXRMEu 

- MNB 

Ovu zajednicu vodi JaSamIgor on pravi vijesti hoga i za cijelu zajednicu MNB-a. Zašto je ovaj zajednica nastala? Da bi Minecraft na Balkanu dobio kvalitetne vijesti i da bi igrače zainteresovali. Ovo je dobra stvar da bi pomoglo zajednici i zato što ne dostaju kvalitetne vijesti Hogu i zajednici MNB-a. Da se informišete i da pratite ovu zajednicu uđite na ovaj discord server: https://discord.gg/sJjusgbERv

**Comment by PiweeX** [comment]
- "&8(&fDesni Klik&8)"

**Comment by PiweeX** [comment]
![download](https://user-images.githubusercontent.com/33425430/189529304-933e9a08-db5b-4f2f-8944-3be632e21b5d.png)


finalno, stavljena je bela boja za glavni tekst a Levi Klik na hologramima je stavljen tekst u sivu, mnogo lepše izgleda, takođe bilo je previsoko jer je &f bio name a sad je Levi Klik sklonjeno iz holograma NPCa i stavljeno kao name, sad je idealno i jako lepo izgleda vizuelno kad se uđe na hub, ovo će dosta pomoći da ostali podserveri budu dosta traženiji i da bude jasnije o čemu se radi na njima

**Comment by PiweeX** [comment]
Sledeće što je ostalo na lobiju jeste da se u kompas dodaju podserveri za UHC i platforme, build škola je već odavno dodata još kad smo spajali sve podservere na Realms

**Comment by PiweeX** [comment]
Takođe treba staviti da vreme uvek bude dan jer se po noći slabo vidi

**Comment by PiweeX** [comment]
Redovni backup lobija napravljen posle 7 dana ( na panelu )

**Comment by NemanjaRusija** [comment]
Puno izdanje koje sam pisao da olakšam igračima

**Za nove igrače Hoga komande su:**

**_Lobby (Početak):_**

Ako ste novi na serveru moraćete se registrovat komanda je /register (šifra) (šifra)

Posle registrovanja morat ćete se loginovat /login (šifra)

**_Da izabere zemlju ili da napravite pogledajte ove komande:_**

Ako nećete da napravite svoju državu idite u kanal #🌿promo i izaberite državu koju god hoćete

Ako niste na discord serveru od hoga ukucajte /discord

Ako želite da napravite državu idite /lands create (ime države)

Da trustate nekog komanda je /lands trust (ime igrača) default 

Ako hoćete da napustite idite /lands leave 

Da izbiršete teritoriju /lands delate confirm

Klejmovi moraju da se plate pa da dodate novac ukucajte /lands deposit (suma novca)

Da novac skinete sa klejma ukucajte /lands withdraw

**_Kako pare zaraditi na Hogu?_**

Ako hoćete da zaradite pare morate prodavati wheat i ribe na laputi.

Komanda za laputu je /spawn

Možete neke stvari da stavite na laputi komanda za to je /lap sell i cena (morate taj item držati u ruci)

**_Neke sitnice još:_**

Možete glasati putem komande /vote možete osvojiti neke vredne nagrade.

Da bi vidjeli koliko sati igrate ukucajte /playtime

Da dobijete nagrade ukucajte /rewards

**UHC** se održava svakog petka u 21h i verzija je 1.7.10. UHC kup je svake godine. Da učestvujete čekate u lobby-u. Kad vam neko od glavnih kaže kao što su Attack36 ili neko od dželata da možete ući ukucajte /server uhc

Da se više informišete za nagrade UHC-a pratite event 

Možete da svoju državu da stavite na mapu discord je: https://discord.gg/GPuUv4FTx8

Ako hoćete da prijavite da vam je neko nešto ukrao ili vređao prijavite na discordu na tom discord serveru se nalaze hogova pravila: 
https://discord.gg/EZ2bEZ7pSS

         **Strogo zabranjeno praviti Alt cc naloge, grifati i abjuzati!!! Ako budete radili te stvari bićete kažnjeni po zakonu Hoga!!!**

**Comment by NemanjaRusija** [comment]
**Za nove igrače ostali podserveri i kako da igrate na njima Takođe nešto i o MNB (MINECRAFT NA BALKANU):**

**_- Platforme_**

Platforme su nastale od SMP igrača Bognara i Arqvia. Da bi ste igrali platforme morate na lobbyu naći platforme i ući. Platforme su zanimljive jer imaju mini igre, Možete dobiti kitove kada votate za hog. Naravno imaju eventi na Platformama, pratite kanal event i možete svojiti vrijedne nagrade. Da stvorite komunikaciju sa igračima platformama uđite na discord server: https://discord.gg/uSjQUwgg

**_- Hog SMP_** 

Hog SMP je privatan server za Hog yutubere. Server je napravljen 2017 godine. Svake godine reset. Ima 6 godina od stvaranja servera i 6 sezona na novoj verziji. Na smpu ima 20-18 igrača. Da igrate na SMP-u prijavite se na ig @hogsmp. Trenutni vlasnik tog podservera se traži, prije je bio Zlaja_Chellange. Najbolja sezona je 2018 godine. Na ovom SMP-u igrači stvaraju kreativnost, zabavu, maštu.... 

**_- Build Škola_**

Ako niste vješti sa buildom ili hoćete da poboljšate znjaje ovo je odlično mjesto za vas. Ovaj server je napravljen da bi se pomoglo igračima što se tiče builda. Ovu zajednicu vodi Leooon. Da se prijavite za Build Školu morate ući na discord server: https://discord.gg/7Aj7HXRMEu 

**_- MNB_** 

Ovu zajednicu vodi JaSamIgor on pravi vijesti hoga i za cijelu zajednicu MNB-a. Zašto je ovaj zajednica nastala? Da bi Minecraft na Balkanu dobio kvalitetne vijesti i da bi igrače zainteresovali. Ovo je dobra stvar da bi pomoglo zajednici i zato što ne dostaju kvalitetne vijesti Hogu i zajednici MNB-a. Da se informišete i da pratite ovu zajednicu uđite na ovaj discord server: https://discord.gg/sJjusgbERv

**Comment by NemanjaRusija** [comment]
![2022-09-11_14 57 36](https://user-images.githubusercontent.com/107151423/189530181-8f613a93-ba6c-4ffd-8566-dbcc8ddb30cf.png)

**LOBBY**

**Comment by NemanjaRusija** [comment]
![2022-09-11_14 54 32](https://user-images.githubusercontent.com/107151423/189530375-096ac2bd-edc6-42bc-8460-20e92f80d117.png)

**PLATFORME**

**Comment by NemanjaRusija** [comment]
![2022-09-11_14 54 21](https://user-images.githubusercontent.com/107151423/189530465-afe5fdc4-5df8-4db4-8ba7-b459cb915f1e.png)

**HogSMP**

**Comment by NemanjaRusija** [comment]
![2022-09-11_14 42 29](https://user-images.githubusercontent.com/107151423/189530544-e15dee97-a5d8-45eb-ba6f-172534072098.png)

**BUILD ŠKOLA**

**Comment by NemanjaRusija** [comment]
![2022-09-11_14 54 45](https://user-images.githubusercontent.com/107151423/189530631-946f1397-70d1-4b39-84aa-2d3941fc47c9.png)

**UHC KUP**

**Comment by NemanjaRusija2** [comment]
**- MNB** 

Ovu zajednicu vodi JaSamIgor on pravi vijesti hoga i za cijelu zajednicu MNB-a. Zašto je ovaj zajednica nastala? Da bi Minecraft na Balkanu dobio kvalitetne vijesti i da bi igrače zainteresovali. Ovo je dobra stvar da bi pomoglo zajednici i zato što ne dostaju kvalitetne vijesti Hogu i zajednici MNB-a. Da se informišete i da pratite ovu zajednicu uđite na ovaj discord server: https://discord.gg/sJjusgbERv

**Comment by NemanjaRusija2** [comment]
Naravno moja odgovornost je da pokažem igračima kako da počnu ali problem je najviše lobby. Pa sam odlučio da napravim za podsevere uz njih je naravno MNB koji će pomoći Minecraft zajednici na balkanu. Pa sam zato i napisao nešto o tome. Px će naći način da sve te poruku tj. opustva za nove igrače stavi negdje pošto mali broj ljudi gleda pin poruku. Nadam se da će se u budućnosti rešiti taj problem

**Comment by NemanjaRusija2** [comment]
Pišem sa drugog acc jer šifru ne znam lol

**Comment by NemanjaRusija2** [comment]
Nismo mi problem nego se novi igrači ne znaju snaći. Ne krivim ja njih nego takav je problem. Prije na hogu nije bilo lobbya nego samo je bio Decentraland. Sad su svi hogovi serveri spojeni. Na hogu se menjalo više puta lobby zbog ovog problema. Danas je px stavljao holograme ispod svakog NPC-a. Pokušati ću nešto preko vikenda da smislim i da napišem još nešto.

**Comment by PiweeX** [comment]
SkyBlock koji Djonmla predstavlja Hogovim igračima u Martu ilo Februaru 2023. će dosta pomoći ovom problemu da se suzbije jer ljudi ne razumeju šta je Decentraland ni kad uđu i igraju

**Comment by PiweeX** [comment]
Finansiran je plugin za bannere za 1.19.3 tako da je sad mnogo jasnije osobama koje prve put uđu na Decentraland kako se igra tj. šta treba da urade prvo kroz 3 prosta koraka

**Comment by PiweeX** [comment]
rešen problem
