### ISSUE TITLE
PITANJE JE?

### ISSUE THREAD

**Issue by Zav1637** [PiweeX/HogRealms#78]
kada ce se zlaja vratiti za admina?

#ZlajaNatragZaAdmina

**Comment by dzelat** [comment]
> kada ce se zlaja vratiti za admina?
> 
> #ZlajaNatragZaAdmina

kad se ispune njegovi uslovi

**Comment by konfix** [comment]
Pitanje je, ne issue. I ne treba da otvaras 2 puta za gluposti, bice zatvoreno svakako

**Comment by PiweeX** [comment]
Nikad
