### ISSUE TITLE
Brisanje claim-a

### ISSUE THREAD

**Issue by hungryslayer** [PiweeX/HogRealms#79]
Postoji claim od x: -10057 y:5757  do x:-10056 y:5741 koji je napravljen pre 2 meseca i ima dvoje ljudi u njemu,u blizini nema nijedan drugi claim osim od mene i mog druga,smeta nam za razvoj pa pravim ovaj vote za brisanje istog.

**Comment by T1GAR** [comment]
Isto ima claim u Bardoniji preciznije:
![image](https://user-images.githubusercontent.com/107375896/175395836-bcf39464-e05c-43e7-bdda-1da417033d2a.png)

taj igrac je neaktivan a tamo se nalazi dosta stvari koje bi nam poslužile. 
Bio je dio Bardonije ako se pita za dokaze sve imamo tako da nebi trebalo biti problema sa micanjem claima.

**Comment by PiweeX** [comment]
Ovo je rešeno ja mislim do sad 🥲
