### ISSUE TITLE
Ustav 

### ISSUE THREAD

**Issue by akipaki293** [PiweeX/HogRealms#8]
Da drzava mora imati ustav i drzavljani da ga postuju. Npr kao kod vuka u ccg sto se desilo da Herobrajn oce da se odcepi a u ustavu pise da ne moze i da dzelati kaznjavaju drzavljana preko ustava države u kojoj je prekrsio i pravilima servera.

**Comment by dzelat** [comment]
Da to sam poceo pisat u zakoniku

**Comment by akipaki293** [comment]
Primetio sam :)

**Comment by akipaki293** [comment]
> Da to sam poceo pisat u zakoniku

Da zatvorim ovo?
