### ISSUE TITLE
Dokle?

### ISSUE THREAD

**Issue by Zav1637** [PiweeX/HogRealms#80]
Hyper bas si uporan sa svojom ekipom da dobijem ban al to nije bitno.... 
Nacin na koji se biraju dzelati je besmislen a jedan od njih koji prica da ce biti dzelat ima dosije cak i ban ali to nema veze znate nije to bitno mislim izgubio sam zelju igranja na serveru kad vidim ko je kandidat za dzelata i njegovo ponasanje. Cujem da je vuk novi staff i to clan medije sa ne aktivnim kanalom cak nije ni na hogsmp.

**Comment by akipaki293** [comment]
Brate stvarno preterujes, do sad sam bio protiv tvog bana ali sad se premisljam, ako zelis da ne dobijes ban unormalizuj se malo. To sto ne igra na smpu ne znaci da ne moze biti media

**Comment by konfix** [comment]
https://www.youtube.com/watch?v=pTYZF5g59t8

**Comment by dzelat** [comment]
> Hyper bas si uporan sa svojom ekipom da dobijem ban al to nije bitno.... Nacin na koji se biraju dzelati je besmislen a jedan od njih koji prica da ce biti dzelat ima dosije cak i ban ali to nema veze znate nije to bitno mislim izgubio sam zelju igranja na serveru kad vidim ko je kandidat za dzelata i njegovo ponasanje. Cujem da je vuk novi staff i to clan medije sa ne aktivnim kanalom cak nije ni na hogsmp.

sta pricas ti?

**Comment by dzelat** [comment]
Obuydaj se

**Comment by akipaki293** [comment]
> Obuydaj se

Brt to je njegovo misljenje, ovo je napravljeno da ljudi imaju prava da rade i pricaju svoja misljenja a ako dzelati i ovo kontrolisu smisao ce da badne u vodu

**Comment by dzelat** [comment]
> > Obuydaj se
> 
> Brt to je njegovo misljenje, ovo je napravljeno da ljudi imaju prava da rade i pricaju svoja misljenja a ako dzelati i ovo kontrolisu smisao ce da badne u vodu

i ja ovdje iznosim moje misljenje, procitaj sta si mu ti napiso... ima covjek lud da je papir

**Comment by NemanjaRusija** [comment]
> Hyper bas si uporan sa svojom ekipom da dobijem ban al to nije bitno.... Nacin na koji se biraju dzelati je besmislen a jedan od njih koji prica da ce biti dzelat ima dosije cak i ban ali to nema veze znate nije to bitno mislim izgubio sam zelju igranja na serveru kad vidim ko je kandidat za dzelata i njegovo ponasanje. Cujem da je vuk novi staff i to clan medije sa ne aktivnim kanalom cak nije ni na hogsmp.

O cemu ti?

**Comment by akipaki293** [comment]
> > > Obuydaj se
> > 
> > 
> > Brt to je njegovo misljenje, ovo je napravljeno da ljudi imaju prava da rade i pricaju svoja misljenja a ako dzelati i ovo kontrolisu smisao ce da badne u vodu
> 
> i ja ovdje iznosim moje misljenje, procitaj sta si mu ti napiso... ima covjek lud da je papir

Bolje mi ko i u rl da cutim i da ne govorim nista jer svima smetaju moja misljenja i moje ideje isto bukv isto kao u rl, a dosao sam na hog da se lepo druzim i provedem

**Comment by Zav1637** [comment]
i ja sam doso na hog da se opustim i zabavim ali zbog POJEDINACA to nije moguce jer dzelati nista ne preduzimaju dok oni ovo rade sve....

**Comment by konfix** [comment]
☕

**Comment by dzelat** [comment]
> i ja sam doso na hog da se opustim i zabavim ali zbog POJEDINACA to nije moguce jer dzelati nista ne preduzimaju dok oni ovo rade sve

> i ja sam doso na hog da se opustim i zabavim ali zbog POJEDINACA to nije moguce jer dzelati nista ne preduzimaju dok oni ovo rade sve....

ne kontam, kad dodje lik protiv koga  je pola servera i krene da mi prica da li neko nesto radi ili ne radi...
