### ISSUE TITLE
Da se uvede traktor koji može da ore ili sprava koja ore

### ISSUE THREAD

**Issue by NemanjaRusija** [PiweeX/HogRealms#81]
Mislim da bi bila dobra ideja da se uvede da traktor može i da ore ili dio traktora koji ore. To bi pomoglo igračima da naprave velike farme. Mislim da bi bilo logično da njegova cijena bude velika.

**Comment by konfix** [comment]
mislim da ovo nije moguce da se izvede

**Comment by NemanjaRusija** [comment]
> mislim da ovo nije moguce da se izvede

steta

**Comment by Coplek** [comment]
moguce, je ali dosta tesko, mozda ako se stavi kao za place seeds, da bude da se izore zemlja, msm da bi moglo
samo treba malo prouciti skriptu traktora

**Comment by PiweeX** [comment]
Moguće je ali ne želimo to pošto nije baš dobro, jeste da bi olakšalo ali bi i udosadilo igru
