### ISSUE TITLE
EVO ZA SVE!

### ISSUE THREAD

**Issue by Zav1637** [PiweeX/HogRealms#82]
Posto vidim da ste toliko uporni da me napadate evo spaho,konfix,px,coplek,djovani evo posto da im NE BIH SMETAO mute me na 

5782 MESECA MUTE EVO MOZE?

**Comment by NemanjaRusija** [comment]
> Posto vidim da ste toliko uporni da me napadate evo spaho,konfix,px,coplek,djovani evo posto da im NE BIH SMETAO mute me na
> 
> 5782 MESECA MUTE EVO MOZE?

Ti si kid
