### ISSUE TITLE
#ZlajaNatragZaAdmina

### ISSUE THREAD

**Issue by JedemJaja** [PiweeX/HogRealms#84]
Otkad nema zlaje toksicnost je prevrsila svaku mjeru, igraci mi doslovno prijete samo zato sto vodim drzavu. Kad je Zlaja bio tu isti takvi igraci bili su muteani i hagovani.

**Comment by Ratko7** [comment]
Ne

**Comment by NemanjaRusija** [comment]
#ne

**Comment by dzelat** [comment]
mislim da se tocno vidi ko ovo piše, zlajo sto altove pravis

**Comment by NemanjaRusija** [comment]
> mislim da se tocno vidi ko ovo piše, zlajo sto altove pravis

Hahaha

**Comment by JedemJaja** [comment]
> mislim da se tocno vidi ko ovo piše, zlajo sto altove pravis

Nije zlaja vec vjerni igrac kojem je stalo do dobrobiti starijih i novih igraca

**Comment by JaSamIgor** [comment]
> > mislim da se tocno vidi ko ovo piše, zlajo sto altove pravis
> 
> Nije zlaja vec vjerni igrac kojem je stalo do dobrobiti starijih i novih igraca

Moze nick u minecraftu ako nije problem?

**Comment by JedemJaja** [comment]
> > > mislim da se tocno vidi ko ovo piše, zlajo sto altove pravis
> > 
> > 
> > Nije zlaja vec vjerni igrac kojem je stalo do dobrobiti starijih i novih igraca
> 
> Moze nick u minecraftu ako nije problem?

Quandale_Dingle420
Disc: Stef14#0372

**Comment by dzelat** [comment]
> > > > mislim da se tocno vidi ko ovo piše, zlajo sto altove pravis
> > > 
> > > 
> > > Nije zlaja vec vjerni igrac kojem je stalo do dobrobiti starijih i novih igraca
> > 
> > Moze nick u minecraftu ako nije problem?
> 
> Quandale_Dingle420
> Disc: Stef14#0372

Nikad ovaj na srv uso nije

**Comment by DrogiraniGremlin** [comment]
> Otkad nema zlaje toksicnost je prevrsila svaku mjeru, igraci mi doslovno prijete samo zato sto vodim drzavu. Kad je Zlaja bio tu isti takvi igraci bili su muteani i hagovani.

nemoj zlajo

**Comment by Coplek** [comment]
Igraci ti mogu prijetit sto vodis drzavu, zasto nebi jel roleplay server je, zalite se da nema roleplay-a? zalite, hocete rp pravila mozda, kao sto su pg, rps, fearrp itd?, i cekaj malo daj dokaze za tu toksicnost, pa ce dobit mute, jesi vidio un dosije, ne vidis ga, al mute-am igrace... informiraj se onda pisi
