### ISSUE TITLE
Predlog za rank "Dzelat"

### ISSUE THREAD

**Issue by Darislaw** [PiweeX/HogRealms#85]
Malo je bilo raspravke u "odmer snaga na decentrelandu" oko ranka "Dzelat" gde se meni i par igracima nije dopao njihov nacin funkcionisanja, tako da sam par dana razmisljao kako da lepo to svedem u jedan text i otvorim nov issue posebno za to, i sta smatram da bi bilo u potpunosti fer po svakog i gde niko ne gubi nista. INC sta je to sto sto ja sad zelim da predlazem? 

-Pivex kaze da neki mi ispadamo kao hejteri koji pljujemo dzelate koji rade svoj posao odlicno i napomenuo je kao da gledamo sve lose kod njih sto cini 1% a ovo ostalo dobro 99% da se pravimo da ne vidimo. 
 Ne, ja sve vidim dobro sto ce tice njihovog posla, ali dokle god postoji ta mogucnost da zloupotrebljavaju njihov rank, cak i da to ne rade i dokle im se nudi ta mogucnost kolko god posteni bili, nije fer jednostavno. Ja to smatram Admin-igracom, a to ne bi trebalo da postoji ni u jednoj RP igrici, ni serveru. 

- Nije zanimljivo biti malo op a ipak igrac si, zar ne? 
- Ne trazim mnogo, svesto sad trazim je da njima bude dozvoljeno da koriste 2 accaunta. JEDAN na koji ce biti full obicni igraci (RP).
- A DRUGI na koji ce ulaziti kao staff, (odnosno dzelat) sa full komandama, ali i ne da bude igrac. 
- 
To je to, ja mislim da je ovo sasvim fer i korektno, jer je glupo biti istovremeno i igrac i rank sa op komandama... 

Za dzelate: Ako sebe smatras da si dobar i posten dzelat onda glasaj ZA moj predlog, a ako glasas PROTIV ja cu to smatrati (a i drugi bi trebali) da si ti igrac kome je zabavno biti Staff sa RP mogucnostima, umesto da budes pravi Staff.  

Sad neka svi odluce glasanjem, i nemojte shvatiti ovo bilo kakvim vredjanjem, cak i da moj predlog ne prodje necu se ljutiti. Pozdrav.

**Comment by Darislaw** [comment]
Vase predloge slobodne upisujte, pa ce pivex za zavrsnu odluku odluciti kako i sta

**Comment by Amidza0** [comment]
Iskreno bolje bi bilo da se napravi da imaju komande kao: duty on i duty off i kad su na duznosti tojest kada resavaju probleme da su im sve komande omogucene,
a kada nisu na duznosti ili duty off da im nije dotupna ni jedna komanda sem duty on i sve komande koje imaju obicni igraci ili da imaju neki kupljen ili zasluzen rank kao lord ili king pa onda da imaju komande kao   king ili neki drugi rank

**Comment by konfix** [comment]
> Iskreno bolje bi bilo da se napravi da imaju komande kao: duty on i duty off i kad su na duznosti tojest kada resavaju probleme da su im sve komande omogucene, a kada nisu na duznosti ili duty off da im nije dotupna ni jedna komanda sem duty on i sve one komande koje imaju obicni igraci ili da imaju neki kupljen ili zasluzen rank kao lord ili king pa onda da imaju komande kao king ili neki drugi rank

ovo moze vrlo lako da se izvede, samo napravimo komandu koja bi im skinula rank i vratila po potrebi, svidja mi se ideja

**Comment by dzelat** [comment]
Svidja mi se prijedlog

**Comment by Darislaw** [comment]
> > Iskreno bolje bi bilo da se napravi da imaju komande kao: duty on i duty off i kad su na duznosti tojest kada resavaju probleme da su im sve komande omogucene, a kada nisu na duznosti ili duty off da im nije dotupna ni jedna komanda sem duty on i sve one komande koje imaju obicni igraci ili da imaju neki kupljen ili zasluzen rank kao lord ili king pa onda da imaju komande kao king ili neki drugi rank
> 
> ovo moze vrlo lako da se izvede, samo napravimo komandu koja bi im skinula rank i vratila po potrebi, svidja mi se ideja

I meni se isto svidja ideja, ali nije to to jednostavno, bolje je imati full staffa a ne staff sa rp mogucnostima, pa to nigde nema druze...

**Comment by Darislaw** [comment]
> Iskreno bolje bi bilo da se napravi da imaju komande kao: duty on i duty off i kad su na duznosti tojest kada resavaju probleme da su im sve komande omogucene, a kada nisu na duznosti ili duty off da im nije dotupna ni jedna komanda sem duty on i sve one komande koje imaju obicni igraci ili da imaju neki kupljen ili zasluzen rank kao lord ili king pa onda da imaju komande kao king ili neki drugi rank

Jeste zanimljivo, ali to ne menja nista, kad malo bolje pogledas, to je i dalje isto, dzelat i dalje ima mogucnosti RP-a kao staff, a toga nema nigde..

**Comment by konfix** [comment]
> > Iskreno bolje bi bilo da se napravi da imaju komande kao: duty on i duty off i kad su na duznosti tojest kada resavaju probleme da su im sve komande omogucene, a kada nisu na duznosti ili duty off da im nije dotupna ni jedna komanda sem duty on i sve one komande koje imaju obicni igraci ili da imaju neki kupljen ili zasluzen rank kao lord ili king pa onda da imaju komande kao king ili neki drugi rank
> 
> Jeste zanimljivo, ali to ne menja nista, kad malo bolje pogledas, to je i dalje isto, dzelat i dalje ima mogucnosti RP-a kao staff, a toga nema nigde..

na velikoj vecini servera je igranje dozvoljeno staffu (nebitno da li se radi o survivalu, skyblocku ili bilo kojoj vrsti servera). Jedini nacin da se ovo spreci je da se uvede pravilo da osoblje nema pravo da igra kao i svi ostali, sto opet ne bi bilo fer. Svakako, protiv pravila je da se abjuza pozicija i lako moze da se proveri ko i sta radi u svakom trenutku, tako da mislim da to i nije neki problem. Ko hoce da abjuza nadje nacin, lako je ostaviti iteme u chest i pokupiti ih posle na drugom nalogu :)

**Comment by Darislaw** [comment]
> > > Iskreno bolje bi bilo da se napravi da imaju komande kao: duty on i duty off i kad su na duznosti tojest kada resavaju probleme da su im sve komande omogucene, a kada nisu na duznosti ili duty off da im nije dotupna ni jedna komanda sem duty on i sve one komande koje imaju obicni igraci ili da imaju neki kupljen ili zasluzen rank kao lord ili king pa onda da imaju komande kao king ili neki drugi rank
> > 
> > 
> > Jeste zanimljivo, ali to ne menja nista, kad malo bolje pogledas, to je i dalje isto, dzelat i dalje ima mogucnosti RP-a kao staff, a toga nema nigde..
> 
> na velikoj vecini servera je igranje dozvoljeno staffu (nebitno da li se radi o survivalu, skyblocku ili bilo kojoj vrsti servera). Jedini nacin da se ovo spreci je da se uvede pravilo da osoblje nema pravo da igra kao i svi ostali, sto opet ne bi bilo fer. Svakako, protiv pravila je da se abjuza pozicija i lako moze da se proveri ko i sta radi u svakom trenutku, tako da mislim da to i nije neki problem. Ko hoce da abjuza nadje nacin, lako je ostaviti iteme u chest i pokupiti ih posle na drugom nalogu :)

Kako god druze, ne kazem da ni ti nisi u pravu, ali onda jednostavno je imati samo full staffa, bez RP-a onda.

**Comment by JaSamIgor** [comment]
> Malo je bilo raspravke u "odmer snaga na decentrelandu" oko ranka "Dzelat" gde se meni i par igracima nije dopao njihov nacin funkcionisanja, tako da sam par dana razmisljao kako da lepo to svedem u jedan text i otvorim nov issue posebno za to, i sta smatram da bi bilo u potpunosti fer po svakog i gde niko ne gubi nista. INC sta je to sto sto ja sad zelim da predlazem?
> 
> -Pivex kaze da neki mi ispadamo kao hejteri koji pljujemo dzelate koji rade svoj posao odlicno i napomenuo je kao da gledamo sve lose kod njih sto cini 1% a ovo ostalo dobro 99% da se pravimo da ne vidimo. Ne, ja sve vidim dobro sto ce tice njihovog posla, ali dokle god postoji ta mogucnost da zloupotrebljavaju njihov rank, cak i da to ne rade i dokle im se nudi ta mogucnost kolko god posteni bili, nije fer jednostavno. Ja to smatram Admin-igracom, a to ne bi trebalo da postoji ni u jednoj RP igrici, ni serveru.
> 
> * Nije zanimljivo biti malo op a ipak igrac si, zar ne?
> * Ne trazim mnogo, svesto sad trazim je da njima bude dozvoljeno da koriste 2 accaunta. JEDAN na koji ce biti full obicni igraci (RP).
> * A DRUGI na koji ce ulaziti kao staff, (odnosno dzelat) sa full komandama, ali i ne da bude igrac.
> 
> To je to, ja mislim da je ovo sasvim fer i korektno, jer je glupo biti istovremeno i igrac i rank sa op komandama...
> 
> Za dzelate: Ako sebe smatras da si dobar i posten dzelat onda glasaj ZA moj predlog, a ako glasas PROTIV ja cu to smatrati (a i drugi bi trebali) da si ti igrac kome je zabavno biti Staff sa RP mogucnostima, umesto da budes pravi Staff.
> 
> Sad neka svi odluce glasanjem, i nemojte shvatiti ovo bilo kakvim vredjanjem, cak i da moj predlog ne prodje necu se ljutiti. Pozdrav.

Podržavam.

**Comment by akipaki293** [comment]
Ne znam zašto bi ljude smarali sa 2 acc-a kad su potrebni uvek, a ti dok promenis acc dok uđeš više ti nisu potrebni, najbolje da se uvede komanda koja im skida rank, jer nebi bilo fer prema njima da ne smeju rpat ako su dželati

**Comment by Coplek** [comment]
E SAD CEMO OVAKO PRICATI. AKO MI DZELATI ABUSAMO?, DAJTE DOKAZ, KAKO MI TO ISKORISTAVAMO SVOJU POZICIJU DZELATA, TAKO STO MUTE-AM IGRACE KOJI PISU DRUGIMA INVALIDI, I JEBU SI MAME, ILI TAKO STO ULAZIM U GMSP, ILI CREATIVE KAD TREBA NEKOM POMOC, ILI TAKO STO RESAVAMO TICKETE, ILI TAKO STO VAM VRACAMO STVARI KAD DOBIJEMO DOKAZE DA SU STVARNO NESTALE, JEL NEKI STAFF TO RADI, OSIM OVOG, JEL?, JEL BI TI BIO BOLJI DZELAT, AJDE UDJI NA NEKI AMERICKI SRW ISTOG TIPA, PA NJIMA RECI DA NAPRAVE TO STO SI NABROJAO, PRIJATLEJU MOJ OD NAS 3 NITKO NIJE DOBIO DZELATA TAKO STO JE MOLIO OKOLO, NEGO TAKO STO JE ZASLUZIO ILI BIO PREPORUCEN OD DRUGOG DZELATA, ZNACI PX JE SAM DOBIO POVJERENJE U NAS
OPET, TVRDNJA JE ARGUMENTIRANO OBORENA LOCK.

**Comment by Darislaw** [comment]
> E SAD CEMO OVAKO PRICATI. AKO MI DZELATI ABUSAMO?, DAJTE DOKAZ, KAKO MI TO ISKORISTAVAMO SVOJU POZICIJU DZELATA, TAKO STO MUTE-AM IGRACE KOJI PISU DRUGIMA INVALIDI, I JEBU SI MAME, ILI TAKO STO ULAZIM U GMSP, ILI CREATIVE KAD TREBA NEKOM POMOC, ILI TAKO STO RESAVAMO TICKETE, ILI TAKO STO VAM VRACAMO STVARI KAD DOBIJEMO DOKAZE DA SU STVARNO NESTALE, JEL NEKI STAFF TO RADI, OSIM OVOG, JEL?, JEL BI TI BIO BOLJI DZELAT, AJDE UDJI NA NEKI AMERICKI SRW ISTOG TIPA, PA NJIMA RECI DA NAPRAVE TO STO SI NABROJAO, PRIJATLEJU MOJ OD NAS 3 NITKO NIJE DOBIO DZELATA TAKO STO JE MOLIO OKOLO, NEGO TAKO STO JE ZASLUZIO ILI BIO PREPORUCEN OD DRUGOG DZELATA, ZNACI PX JE SAM DOBIO POVJERENJE U NAS OPET, TVRDNJA JE ARGUMENTIRANO OBORENA LOCK.

Da li si ti uopste procitao sta sam ja gore napisao? Boli mene kurac kolko god da je dzelat posten, retardirano je imati staffa sa takvim komandama koje moze svojevoljno da iskoriscava kad god zeli. A istovremeno je i igrac, pozdrav

**Comment by Darislaw** [comment]
Neka se lepo donese odluka da bude dzelat full staff bez RP-a, bemu mater.

**Comment by Coplek** [comment]
Znaci hoces reci da ja nemam pravo igrati?, samo zato sto pomazem drugim igracima Permisije staffa imamo sad samo mi dzelati, i ajde daj dokaze za sta svojevoljno iskoristavamo iskoristavamo za ono sto se mora, ako netko zapne, ako netko ima problem itd sve sam ti napisao, znaci ti hoces reci da sam ja robot koji nema pravo na igru na serveru, ja mozda jesam dio tog servera ali sam isti kao i ti, zajebem li ja dobit cu vecu kaznu nego ti, tkd nemoj izmisljat gluposti, abusam li dobit cu ban.. daj mi sve dokaze a ne da mi tu pricas gluposti, dalje konkursises se za dzelata nije ti dzelat role kao na pijaci da se konkursises to se dobija s povjerenjem, zato ti i kazem nema nitko osim nas dzelata px-a i konfixa permisije

**Comment by Coplek** [comment]
Upravo iz tog razloga sto si ti rekao ne primamo nove dzelate koji se prijavljuju na githubu kao ti i ostali, tocno si naveo sve razloge zasto ne treba biti dzelat netko u kog se nema povjerenja

**Comment by ConeBe** [comment]
Opet neka svađa oko Dželata?

**Comment by Darislaw** [comment]
> Znaci hoces reci da ja nemam pravo igrati?, samo zato sto pomazem drugim igracima Permisije staffa imamo sad samo mi dzelati, i ajde daj dokaze za sta svojevoljno iskoristavamo iskoristavamo za ono sto se mora, ako netko zapne, ako netko ima problem itd sve sam ti napisao, znaci ti hoces reci da sam ja robot koji nema pravo na igru na serveru, ja mozda jesam dio tog servera ali sam isti kao i ti, zajebem li ja dobit cu vecu kaznu nego ti, tkd nemoj izmisljat gluposti, abusam li dobit cu ban.. daj mi sve dokaze a ne da mi tu pricas gluposti, dalje konkursises se za dzelata nije ti dzelat role kao na pijaci da se konkursises to se dobija s povjerenjem, zato ti i kazem nema nitko osim nas dzelata px-a i konfixa permisije

Tako je, ja kazem da dzelat ne bi trebalo imati pravo na RP, vidis kako si lepo shvatio, i nemoj da ga duzis, rekao sam zasto i nisam rekao "samo zato sto pomazes drugim igracima". Sve sam lepo naveo a ti ponovo isto ponavljas, i opet cu ti reci. Boli nas igrace kurac kolko ste vi posteni, ja necu da mi se staff-igrac

**Comment by akipaki293** [comment]
> > Znaci hoces reci da ja nemam pravo igrati?, samo zato sto pomazem drugim igracima Permisije staffa imamo sad samo mi dzelati, i ajde daj dokaze za sta svojevoljno iskoristavamo iskoristavamo za ono sto se mora, ako netko zapne, ako netko ima problem itd sve sam ti napisao, znaci ti hoces reci da sam ja robot koji nema pravo na igru na serveru, ja mozda jesam dio tog servera ali sam isti kao i ti, zajebem li ja dobit cu vecu kaznu nego ti, tkd nemoj izmisljat gluposti, abusam li dobit cu ban.. daj mi sve dokaze a ne da mi tu pricas gluposti, dalje konkursises se za dzelata nije ti dzelat role kao na pijaci da se konkursises to se dobija s povjerenjem, zato ti i kazem nema nitko osim nas dzelata px-a i konfixa permisije
> 
> Tako je, ja kazem da dzelat ne bi trebalo imati pravo na RP, vidis kako si lepo shvatio, i nemoj da ga duzis, rekao sam zasto i nisam rekao "samo zato sto pomazes drugim igracima". Sve sam lepo naveo a ti ponovo isto ponavljas, i opet cu ti reci. Boli nas igrace kurac kolko ste vi posteni, ja necu da mi se staff-igrac

zabole i nas sta sve za vas kojima smeta sto dzelati koji vise ni nemaju nikakvu ulogu su i igraci

**Comment by Darislaw** [comment]
Ja sam predlozio: 1. ili full dzelat ili se odjavi od dzelata.
2. Dva accaunta, jedan na koji ces full staff a jedan za full RP, a vama se ni to ne svidja? A to vase je lose izbalansirano sto vi zelite, zato se ja protivim tome, i niko nece da me ubedi da nisam u pravu.

**Comment by akipaki293** [comment]
> Ja sam predlozio: 1. ili full dzelat ili se odjavi od dzelata. 2. Dva accaunta, jedan na koji ces full staff a jedan za full RP, a vama se ni to ne svidja? A to vase je lose izbalansirano sto vi zelite, zato se ja protivim tome, i niko nece da me ubedi da nisam u pravu.

ne mora niko da te ubedi jer niko ljude ne moze naterati da ne rpaju ili da imaju 2 acca samo zato sto su dzelati to sto ti govoris za njih je glupo a i ovako sad dzelatima upravljaju drugi ljudi i ne vidim zasto je ovo otvorene jer ovo nece biti usvojeno

**Comment by akipaki293** [comment]
> > Iskreno bolje bi bilo da se napravi da imaju komande kao: duty on i duty off i kad su na duznosti tojest kada resavaju probleme da su im sve komande omogucene, a kada nisu na duznosti ili duty off da im nije dotupna ni jedna komanda sem duty on i sve one komande koje imaju obicni igraci ili da imaju neki kupljen ili zasluzen rank kao lord ili king pa onda da imaju komande kao king ili neki drugi rank
> 
> ovo moze vrlo lako da se izvede, samo napravimo komandu koja bi im skinula rank i vratila po potrebi, svidja mi se ideja

lakse je ovo izvesti nego naterati ljude da prave altove

**Comment by Coplek** [comment]
> Ja sam predlozio: 1. ili full dzelat ili se odjavi od dzelata. 2. Dva accaunta, jedan na koji ces full staff a jedan za full RP, a vama se ni to ne svidja? A to vase je lose izbalansirano sto vi zelite, zato se ja protivim tome, i niko nece da me ubedi da nisam u pravu.

Umm a tko kaze da je meni bitno tvoje misljenje, ja dzelata nisam trazio ja sam njega dobio i zasto bi onda bio full dzelat ako dzelat nije preko konkursa, znaci ja ne biram hocu li bit dzelat dzelat se dobija ako dobijes respect
Sto ti neces dobiti

**Comment by PiweeX** [comment]
Rešeno
