### ISSUE TITLE
Neverujem....

### ISSUE THREAD

**Issue by Zav1637** [PiweeX/HogRealms#86]
Da je tu Zlaja kao pre svi bi ovi koji su zasluzili da budu u hga i mute vec od kad bili ali sada nisu vec jadnog igraca zav-a napadaju i hyperova druzina isto
Iskreno ajmo svi da je zlaja radio jako dobro svoj posao....

**Comment by JedemJaja** [comment]
Slazem se #ZlajaNatragZaAdmina

**Comment by NemanjaRusija** [comment]
> Da je tu Zlaja kao pre svi bi ovi koji su zasluzili da budu u hga i mute vec od kad bili ali sada nisu vec jadnog igraca zav-a napadaju i hyperova druzina isto Iskreno ajmo svi da je zlaja radio jako dobro svoj posao....

Otvaraš github zbog ovakvih stvari? Ovaj github služi za neki prijedlog a be zbog neslaganja sa hyperom i ostalim igračima. Kad ne bi otvarao issue zbog gluposti i ne petljeao se niskim možda bi se i popravio i to bi vjerovatno ostali igrači primjetili ili dželati. Velike su šanse da dobiješ mute zbog ovakvih gluposti. Zato bolje smiri se i gledaj svoj posao i namješaj se nigdje.

**Comment by NemanjaRusija** [comment]
> Slazem se #ZlajaNatragZaAdmina

Neće se vratiti hoće da ostane Kan u mongoliji. Shvati to više jednom

**Comment by dzelat** [comment]
Meni ovo izgleda kao da zlaja iskoristava igrace za propagandu, i tebi i tom Hyperu sam rekao da cete dobiti mute na barem 3 mjeseca ako ne prestanete, i da kriv sam sto nisam ucinio na samom pocetku nego sam pokusavao da smirim tu savdju

**Comment by dzelat** [comment]
> Slazem se #ZlajaNatragZaAdmina

#ne

**Comment by konfix** [comment]
realnost je da zlaja nije admin i da ti treba zabraniti da koristis github

**Comment by NemanjaRusija** [comment]
> Slazem se #ZlajaNatragZaAdmina

Verujem da si zlaja

**Comment by DrogiraniGremlin** [comment]
> Slazem se #ZlajaNatragZaAdmina

desi zlajo nisam te prepoznao

**Comment by Coplek** [comment]
Zav o moralu ti pricati ne mozes imas srece sto te nisam u hag strpao kad si lazno svjedocio svom liku da je izgubio pare, i netherite stvari, provjerim nije imao nista onda kaze pa nije bio netherite chestplate nego diamond, opet nije imao, pitam koliko para ti nestalo kaze 7k, ajde pametni moj Zave, daj 1 dokaz za igraca kog treba ban, i ban cemo ga, pljujete nemate ni argument, ni dokaz, nit ste upuceni

**Comment by PiweeX** [comment]
Rešeno
