### ISSUE TITLE
Resavanje baga sto se tice claima (da moze da se udje u vise claimova, a ne samo 1)

### ISSUE THREAD

**Issue by DrogiraniGremlin** [PiweeX/HogRealms#87]
Dakle proteklih 10 dana ne mogu da udjem u claim koji pripada ccg-u, kad god se posalje inv kaze da imam previse claimova ,a imam samo 1, Vukopolj, molio bih da se ovo resi sto brze jer se ovaj bag desava vec 10 dana i ocu da budem u celoj drzavi, a ne samo u 1 gradu nase drzave

ili da se napravi nova vrsta claima koja obuhvata drzavu celu ili da se resi ovo

**Comment by T1GAR** [comment]
Da isto imam problema sa claimovima. pokusavam ga izbrisat i nece kaže da ima neki internal error

**Comment by akipaki293** [comment]
> Dakle proteklih 10 dana ne mogu da udjem u claim koji pripada ccg-u, kad god se posalje inv kaze da imam previse claimova ,a imam samo 1, Vukopolj, molio bih da se ovo resi sto brze jer se ovaj bag desava vec 10 dana i ocu da budem u celoj drzavi, a ne samo u 1 gradu nase drzave
> 
> ili da se napravi nova vrsta claima koja obuhvata drzavu celu ili da se resi ovo

Claimovi su zbagani već duže vreme, ako sam dobro primetio od prebacivanja na novu mašinu i perioda ddosa su počeli bugovi, PX gleda prvo da reši ulaženje na Telefon na server pa će posle da reši claimove (tako je on rekao). Sa obzirom da server ima dosta tehničkih problema, to mora da se reši do mainneta, tako da će biti rešeno u što kraćem periodu

**Comment by konfix** [comment]
> > Dakle proteklih 10 dana ne mogu da udjem u claim koji pripada ccg-u, kad god se posalje inv kaze da imam previse claimova ,a imam samo 1, Vukopolj, molio bih da se ovo resi sto brze jer se ovaj bag desava vec 10 dana i ocu da budem u celoj drzavi, a ne samo u 1 gradu nase drzave
> > ili da se napravi nova vrsta claima koja obuhvata drzavu celu ili da se resi ovo
> 
> Claimovi su zbagani već duže vreme, ako sam dobro primetio od prebacivanja na novu mašinu i perioda ddosa su počeli bugovi, PX gleda prvo da reši ulaženje na Telefon na server pa će posle da reši claimove (tako je on rekao). Sa obzirom da server ima dosta tehničkih problema, to mora da se reši do mainneta, tako da će biti rešeno u što kraćem periodu

ja garantujem za ovog decka

**Comment by PiweeX** [comment]
Što se tiče ovoga odavno je moguće na predlog

**Comment by PiweeX** [comment]
Dakle, radi, može se u više claimova 😄
