### ISSUE TITLE
o Zlaji!

### ISSUE THREAD

**Issue by PiweeX** [PiweeX/HogRealms#90]
Hoću da i ovim postom zaključim priču o nekoj temi, sad sam stigao da napišem šta mislim o svemu ovome

Zlaji su pre oko 2 meseca oduzete sve permisije na serveru, jedno vreme je imao OP a jedno vreme samo ovako komande kao dželati i to.

ovo nije prvi put da mu se oduzimaju, i sa SMP i na hog discordu, jednostavno ne može da iskorišćava pogodnosti koje ima iz 1 razloga za neku totalno levu stvar, ja mogu da prećutim nekoliko puta kad vidim al nije ok da se to ponavlja

i kad se desi nekoliko puta, ne napišem ništa jer ne želim da ulazim u dalje rasprave jer tu realno nema kraja, samo oduzmem perme, isto je bilo i sa Blackom ranije, znači ne oduzmem zato što mi se ćefnulo tako taj dan već zato što nesvesno ili svesno abjuzuju ili loše rade taj deo posla, iskorišćavaju komande ili ih loše koriste već duže vreme a ne samo taj 1 put..

dakle, njemu su pre 2 meseca oduzete komande iz igre, iz razloga što je viđen da koristi world edit, tad mu je oduzet OP (to je radio nesvesno jer je mislio da ide uz build mod), zatim su mu oduzete i ostale perme kao i ban sa discorda (jer u MC nije radio ni dželatima već je moralo sa Discorda iz konzole) dakle, oduzeta mu konzola sa discorda kako nebi koristio, posle toga rekao je da će mu trebati samo kako bi nešto radio (ne sećam se šta ugl konzola mu je vraćena) da vraćena mu je ali je dogovor bio da ne koristi za banove jer on ban, mute, jail itd nema jer to ima dželat, ne i admin.

2 meseca posle toga banovao je nekoliko igrača iz konzole, to su bili neki uticajniji igrači pa su svi igrači skočili da ga vređaju kako je abjuzer, pedofil, ovakav onakav. Baš iz tog razloga hitri potezi nisu dobri, problem tu je što se napravi pometnja kad ti banuješ nekoliko igrača odjednom sa razlogom iz užitka, prvo u četu se vidi i novi igrači to vide, bezveze je malo da postoji odlično urađen  server i onda dođe neko i banuje nekoliko igrača pa svi skoče na njega da ga vređaju pa mjutuje i njih.

dakle, čak i da su svi oni do jednog zaslužili ban što verujem da jesu tokom svojih dosijea sa servera, 1 osoba koja je zadužena za kažnjavanje ne sme tako da postupa, jednostavno je ne dopustivo

potom, oduzeta mu je konzola totalno i onda se desila sva ova zbrka. Ja ne vidim problem, šta je problem da dželati kažnjavaju a ne on, zašto Zlaja kao admin mora da glumi dželate?

on uopšte nije imao loše namere za server ali prosto tako se ne može raditi, uz to posao brend menadžera, admina i slično je da unapređuje i menadžuje serverom, ne da kažnjava i to skroz suprotno kako dželati rade

e sad što se tiče toga kakvi su dželati, tačnije kakva im je istorija, dosije kako on kaže, ako postoji neki dokaz iznesite i ne mora da se izglasa na githubu, biće im oduzeto momentalno, al i da postoji nešto što su uradili pre 6 meseci ne moramo da se hvatamo za to šta su radili ranije već šta danas dobro rade za zajednicu.

da, mi želimo savršen sistem na serveru ali ne na način da banujemo i postupamo hitro, ni 1 radikalni potez ne valja nizašta kamoli za game server

hoću da napomenem da nemam ništa protiv zlaje i da je on puno uradio za hog da bi ga spominjao u negativnom kontekstu, jednostavno su se desile određene nesuglasice u mišljenjima i tako se desilo kako se desilo, to je normalno.

Ni ja ni black ni niko od ljudi što su napravili server ne koristi permisije, server je upravo iz ovih i sličnih problema zamišljen tako da bude narodski, kao što su najveći blockchain projekti i defi sistemi.

ali evo, sad je vraćen i Github, tu zaista ne vidim problem zašto se Zlaja ukoliko već ne želi da bude brend menadžer u priči ne prijavi za dželata kad želi da očisti server,

dakle ako ga igrači žele, napraviće se javno glasanje i na tom glasanju će svako izneti zašto on treba d se vrati, šta bi uveo u server i slično. ukoliko Zlaja pobedi uopšte ne vidim i 1 razlog zašto nebi dobio dozvole, isti taj narod ga je izabrao i isti taj narod će ga smeniti ukoliko bude radio nešto protiv volje većine, to NE treba da ima veze sa PXom kao osobom

e sad, neko će reći da određena grupa loših igrača tera ljude da glasaju, napomenuću opet da ukoliko neko primeti to odmah prijavi i dobiće novčanu nadoknadu a ta osoba će dobiti kaznu.

e sad neko će reći i da Zlaja nema većinu iz razloga što je većina igrača toksično, jeste ali nikad loše ne može da preovlada dobro, u kom smislu, pa u smislu da ukoliko neko zaista mrzi Zlaju od tih loših igrača, on će glasati za sve protiv njega, ali njegov glas se neće važiti ukoliko nije izneo zašto to misli što misli i neke potencijalne dokaze i konstruktivne argumente

Svakako mislim da je Github uvod u neku demokratiju na serveru, mislim to je idealan sistem zar ne, da se postupa 100% shodno volji ljudi

**Comment by PsihoKing** [comment]
Sta covek naprica.

**Comment by DzingisKan** [comment]
Sutra ide moj odgovor, lep pozdrav! Pratite Hogo kanal

**Comment by PiweeX** [comment]
hoću samo još da dodam na ovo gore


niko ne može protiv volje naroda


i da, ja poštujem svakoga ko radi na Hogu a pogotovo Zlaju ali po ovom pitanju sam se izjasnio i to je moj stav, ako mislite da možete protiv volje naroda onda je to velika greška i server se vraća na ono staro

ako mislite da Zlaja treba da ima dozvole, nek se napravi glasanje, ako Zlaja dobije volju naoda i napravi nešto loše i pravi konstantno nešto loše sa tim dozvolama, nek se napravi glasanje da mu se oduzmu

to važi i za neku X osobu, ne samo za Zlaju, Čopleka i Djovanija

I to je to, nema nikakve matematike i nema potrebe za razapinjanjem PiweeXa ili nekoga, to je to


opet da kažem da lažiranje glasova nije dopustivo, kao i teranje ili bilo kakvo nagovaranje igrača da glasaju za neku stvar, nema nametanja volje, jedino pravilo



Server nije ni moj ni Kinezov ni Blekov Konfixov već od svih igrača! Ukoliko igrači izglasaju nešto to će i biti, 1 dželat ne radi shodno volji naroda? Obara se i na mesto njega dolazi drugi, tako da se ponovi 2 puta i videćete koliko će dželata da pravi probleme, pa neće praviti jer će prvo pored skidanja ranka i biti javno osramoćeni ili šta god.

**Comment by NemanjaRusija** [comment]
Da se zna da ne zlaja muto mene galilea i dedsea ne znam koji je razlog

**Comment by PiweeX** [comment]
![download](https://user-images.githubusercontent.com/33425430/175791464-299182df-a987-4b10-8a0e-3ac496554244.png)

**autokratija**

ovo su 97% game servera na Balkanu, Hogovi, tj. ekipa gde sam bio i ja su 2017. otvorili HogRealms iz razloga što su trpeli nepravdu od strane admina i prijatelja admina a da bili protivnička fekcija na jednom od tada najvećih public YT servera na Balkanu, otvorili su ga pod Nidinim sloganom Svi smo isti (jbg ne mogu da nađem sliku, ima je psiho)

HOG ne želi da bude pod autokratijom nekoliko admina, tad je zamišljeno a sada je i u potpunosti realizovano.


samo ko je igrao na domaćim MC serverima i ko igra trenutno zna kakvi debili vode te servere, zato se i ja ironično sprdam na njihov račun, to je puno sujete i mutnih radnji, kažnjavanja iz besa, ličnih kompleksa i frustracija

konačno je na Balkan uveden ovakav sistem za game servere, i to baš Minecraft server prvo, inače i na stranim serverima gotovo da ne postoji ovo ali postoji na DEFI projektima



ljudi su kvarljiva roba, stoga ne može se zamisliti sistem nekog projekta gde postoji 1 OWNER, 1 HEAD ADMIN, 2 ADMINA, 3 MODERATORA i 2 HELPERA i 8 ljudi kontroliše server od 2k ljudi! a ne mora se zamisliti ustvari, dođite na domaće Majnkreft servere kako oni kažu

jednostavno, i meni se smučilo koji sam ranije igrao na takvim mestima, niko više ne želi to, vreme je za napredak

**Comment by akipaki293** [comment]
Ma bre aki za dzelata :sweat_smile:

**Comment by akipaki293** [comment]
> ![download](https://user-images.githubusercontent.com/33425430/175791464-299182df-a987-4b10-8a0e-3ac496554244.png)
> 
> **autokratija**
> 
> ovo su 97% game servera na Balkanu, Hogovi, tj. ekipa gde sam bio i ja su 2017. otvorili HogRealms iz razloga što su trpeli nepravdu od strane admina i prijatelja admina a da bili protivnička fekcija na jednom od tada najvećih public YT servera na Balkanu, otvorili su ga pod Nidinim sloganom Svi smo isti (jbg ne mogu da nađem sliku, ima je psiho)
> 
> HOG ne želi da bude pod autokratijom nekoliko admina, tad je zamišljeno a sada je i u potpunosti realizovano.
> 
> samo ko je igrao na domaćim MC serverima i ko igra trenutno zna kakvi debili vode te servere, zato se i ja ironično sprdam na njihov račun, to je puno sujete i mutnih radnji, kažnjavanja iz besa, ličnih kompleksa i frustracija
> 
> konačno je na Balkan uveden ovakav sistem za game servere, i to baš Minecraft server prvo, inače i na stranim serverima gotovo da ne postoji ovo ali postoji na DEFI projektima
> 
> ljudi su kvarljiva roba, stoga ne može se zamisliti sistem nekog projekta gde postoji 1 OWNER, 1 HEAD ADMIN, 2 ADMINA, 3 MODERATORA i 2 HELPERA i 8 ljudi kontroliše server od 2k ljudi! a ne mora se zamisliti ustvari, dođite na domaće Majnkreft servere kako oni kažu
> 
> jednostavno, i meni se smučilo koji sam ranije igrao na takvim mestima, niko više ne želi to, vreme je za napredak

Ispisa se čovek, aj sad da smiris živce kod Akija na Hogo Psihijatriju :)

**Comment by PiweeX** [comment]
svi dođu da se opuste na server, nije im bitno da li Zlaja ili Goran kažnjavaju

ono što je bitno jeste da te osobe budu izabrane od strane naroda i da u svakom momentu ti igrači mogu da ih smene ukoliko većina vidi da to ide beztraga, inače jedan od većih razloga što game serveri propadaju je taj što se admini među sobom posvađaju i poizvade oči jedni drugima.


Reče da se odpuste dželati i da se adminima vrate komande, pa ne može, admini jasno imaju šta rade na serveru, zašto su tu i na koji način doprinose


ako hoćeš da budeš dželat nek zajednica to odluči a ne da se igramo igre da ideš na gringose i da povlačiš igrače da igraju tamo, ovo ovako ne vodi nikud jer se opet maši poenta pored tolike slobode igrača da kontrolišu server ljudi se opet obaziru na to šta je PX uradio i kome je skinuo dozvole

**Comment by akipaki293** [comment]
> svi dođu da se opuste na server, nije im bitno da li Zlaja ili Goran kažnjavaju
> 
> ono što je bitno jeste da te osobe budu izabrane od strane naroda i da u svakom momentu ti igrači mogu da ih smene ukoliko većina vidi da to ide beztraga, inače jedan od većih razloga što game serveri propadaju je taj što se admini među sobom posvađaju i poizvade oči jedni drugima.
> 
> Reče da se odpuste dželati i da se adminima vrate komande, pa ne može, admini jasno imaju šta rade na serveru, zašto su tu i na koji način doprinose
> 
> ako hoćeš da budeš dželat nek zajednica to odluči a ne da se igramo igre da ideš na gringose i da povlačiš igrače da igraju tamo, ovo ovako ne vodi nikud jer se opet maši poenta pored tolike slobode igrača da kontrolišu server ljudi se opet obaziru na to šta je PX uradio i kome je skinuo dozvole
> 
> isto tako, ako hoćeš da se ovi dželati odpuste otvori issue, iznesi dokaze i argumente i to je to..

Ja uskoro otvaram issues za dzelata (ne brinite se necu za sebe haha)

**Comment by dzelat** [comment]
WORLD EDIT UZ BUILD MOD HAHAHAHAHAHAHAHAAHHHHHHHHHHHHHHAHAHAHHHHHHHHHHAHAHAHAAAAAAAHHA

**Comment by ratkomraleu** [comment]
tipican abjuzer koji okrivljuje druge ljude za abjuz

**Comment by dzelat** [comment]
> Sta covek naprica.

psiho ja koliko se sjecam i ti si ga pljuvao?

**Comment by NemanjaRusija** [comment]
> WORLD EDIT UZ BUILD MOD HAHAHAHAHAHAHAHAAHHHHHHHHHHHHHHAHAHAHHHHHHHHHHAHAHAHAAAAAAAHHA

Sad sve ima smisla

**Comment by NemanjaRusija** [comment]
> svi dođu da se opuste na server, nije im bitno da li Zlaja ili Goran kažnjavaju
> 
> ono što je bitno jeste da te osobe budu izabrane od strane naroda i da u svakom momentu ti igrači mogu da ih smene ukoliko većina vidi da to ide beztraga, inače jedan od većih razloga što game serveri propadaju je taj što se admini među sobom posvađaju i poizvade oči jedni drugima.
> 
> Reče da se odpuste dželati i da se adminima vrate komande, pa ne može, admini jasno imaju šta rade na serveru, zašto su tu i na koji način doprinose
> 
> ako hoćeš da budeš dželat nek zajednica to odluči a ne da se igramo igre da ideš na gringose i da povlačiš igrače da igraju tamo, ovo ovako ne vodi nikud jer se opet maši poenta pored tolike slobode igrača da kontrolišu server ljudi se opet obaziru na to šta je PX uradio i kome je skinuo dozvole
> 
> isto tako, ako hoćeš da se ovi dželati odpuste otvori issue, iznesi dokaze i argumente i to je to..

A ko je sad goran

**Comment by dzelat** [comment]
> svi dođu da se opuste na server, nije im bitno da li Zlaja ili Goran kažnjavaju
> 
> ono što je bitno jeste da te osobe budu izabrane od strane naroda i da u svakom momentu ti igrači mogu da ih smene ukoliko većina vidi da to ide beztraga, inače jedan od većih razloga što game serveri propadaju je taj što se admini među sobom posvađaju i poizvade oči jedni drugima.
> 
> Reče da se odpuste dželati i da se adminima vrate komande, pa ne može, admini jasno imaju šta rade na serveru, zašto su tu i na koji način doprinose
> 
> ako hoćeš da budeš dželat nek zajednica to odluči a ne da se igramo igre da ideš na gringose i da povlačiš igrače da igraju tamo, ovo ovako ne vodi nikud jer se opet maši poenta pored tolike slobode igrača da kontrolišu server ljudi se opet obaziru na to šta je PX uradio i kome je skinuo dozvole
> 
> isto tako, ako hoćeš da se ovi dželati odpuste otvori issue, iznesi dokaze i argumente i to je to..

Zlaja zavrsio politicke nauke...pozicioner

**Comment by konfix** [comment]
> hoću samo još da dodam na ovo gore
> 
> niko ne može protiv volje naroda
> 
> i da, ja poštujem svakoga ko radi na Hogu a pogotovo Zlaju ali po ovom pitanju sam se izjasnio i to je moj stav, ako mislite da možete protiv volje naroda onda je to velika greška i server se vraća na ono staro
> 
> ako mislite da Zlaja treba da ima dozvole, nek se napravi glasanje, ako Zlaja dobije volju naoda i napravi nešto loše i pravi konstantno nešto loše sa tim dozvolama, nek se napravi glasanje da mu se oduzmu
> 
> to važi i za neku X osobu, ne samo za Zlaju, Čopleka i Djovanija
> 
> I to je to, nema nikakve matematike i nema potrebe za razapinjanjem PiweeXa ili nekoga, to je to
> 
> opet da kažem da lažiranje glasova nije dopustivo, kao i teranje ili bilo kakvo nagovaranje igrača da glasaju za neku stvar, nema nametanja volje, jedino pravilo
> 
> Server nije ni moj ni Kinezov ni Blekov Konfixov već od svih igrača! Ukoliko igrači izglasaju nešto to će i biti, 1 dželat ne radi shodno volji naroda? Obara se i na mesto njega dolazi drugi, tako da se ponovi 2 puta i videćete koliko će dželata da pravi probleme, pa neće praviti jer će prvo pored skidanja ranka i biti javno osramoćeni ili šta god.

laz, server je moj

**Comment by Coplek** [comment]
![Screenshot_61](https://user-images.githubusercontent.com/83037533/175821042-a1e17562-4135-44ba-80b8-91f5a496cef0.png)
