### ISSUE TITLE
Unban Appeal | Thundeerrr

### ISSUE THREAD

**Issue by ratkomraleu** [PiweeX/HogRealms#91]
Pozdrav svim igračima HogRealms servera! Unban appeal pišem zato što bivši tvz admin Zlaja Challenge (džingis kan) nije još uvek izneo dokaze protiv mene kad mi je dao ban! Molim sve igrače koji imaju dokaz da sam Abjuzao a da nisam prethodno kažnjen za to da iznesu dokaze, ako bude dokaza protiv mene a da nemam argument protiv toga čekam normalan unban (za dva meseca) . Ukoliko ne bude dokaza protiv mene i pobedim na Unban Appeal ovaj proces mog unbana treba da prođe pozitivnim ishodom za mene i ceo narod Bardonije koji je osuđen za svakakve gluposti za koje nisu krive! Ovaj Issue traje nedelju dana  tako da igrači Izjasnite se! (Dokazalo se kakav je zlaja zapravo i svako ko je trčao za njim , nadam se da žali zbog te odluke :)  )

**Comment by DzingisKan** [comment]
ovo je tvoj treci acc na GitHubu kojeg imas, isto tako si i na glasanjima koristia sve te acc

**Comment by NemanjaRusija** [comment]
> ovo je tvoj treci acc na GitHubu kojeg imas, isto tako si i na glasanjima koristia sve te acc

Imaš i ti

**Comment by ratkomraleu** [comment]
> ovo je tvoj treci acc na GitHubu kojeg imas, isto tako si i na glasanjima koristia sve te acc

Ne, imam dva naloga. Ratko7 (telefon, zaboravio sam sifru a mrzi me rrati) i ovaj

**Comment by DzingisKan** [comment]
> > ovo je tvoj treci acc na GitHubu kojeg imas, isto tako si i na glasanjima koristia sve te acc
> 
> Imaš i ti

neman ja nijedan osim ovog, ne trebaju meni altovi

**Comment by NemanjaRusija** [comment]
> ovo je tvoj treci acc na GitHubu kojeg imas, isto tako si i na glasanjima koristia sve te acc

I kad se skinu ti njegovi alt accountovi opet si izgubio

**Comment by ratkomraleu** [comment]
> ovo je tvoj treci acc na GitHubu kojeg imas, isto tako si i na glasanjima koristia sve te acc

A iskreno mislim da si se ti dokazao , izdajice jedna kako te nije stid da kačiš na hogo kanalu onakve gluposti, ali ništa drugo od takve debilane od čoveka nisam očekivao

**Comment by ratkomraleu** [comment]
> ovo je tvoj treci acc na GitHubu kojeg imas, isto tako si i na glasanjima koristia sve te acc

idi na gringose pozicioneru jedan

**Comment by dzelat** [comment]
zlaja tamo admin zato je otisao

**Comment by akipaki293** [comment]
> Pozdrav svim igračima HogRealms servera! Unban appeal pišem zato što bivši tvz admin Zlaja Challenge (džingis kan) nije još uvek izneo dokaze protiv mene kad mi je dao ban! Molim sve igrače koji imaju dokaz da sam Abjuzao a da nisam prethodno kažnjen za to da iznesu dokaze, ako bude dokaza protiv mene a da nemam argument protiv toga čekam normalan unban (za dva meseca) . Ukoliko ne bude dokaza protiv mene i pobedim na Unban Appeal ovaj proces mog unbana treba da prođe pozitivnim ishodom za mene i ceo narod Bardonije koji je osuđen za svakakve gluposti za koje nisu krive! Ovaj Issue traje nedelju dana tako da igrači Izjasnite se! (Dokazalo se kakav je zlaja zapravo i svako ko je trčao za njim , nadam se da žali zbog te odluke :) )

I"m neutralan

**Comment by R1derPN** [comment]
Dobio si ban od 150 dana ako mi se ne cini radi vredjanja admina i svakakvih stvari.

**Comment by Pandzaaa** [comment]
> Dobio si ban od 150 dana ako mi se ne cini radi vredjanja admina i svakakvih stvari.

koje to svakakve stvari, ajde kazi nam kad si takav majstor.. proof hocemo

**Comment by ratkomraleu** [comment]
> Pozdrav svim igračima HogRealms servera! Unban appeal pišem zato što bivši tvz admin Zlaja Challenge (džingis kan) nije još uvek izneo dokaze protiv mene kad mi je dao ban! Molim sve igrače koji imaju dokaz da sam Abjuzao a da nisam prethodno kažnjen za to da iznesu dokaze, ako bude dokaza protiv mene a da nemam argument protiv toga čekam normalan unban (za dva meseca) . Ukoliko ne bude dokaza protiv mene i pobedim na Unban Appeal ovaj proces mog unbana treba da prođe pozitivnim ishodom za mene i ceo narod Bardonije koji je osuđen za svakakve gluposti za koje nisu krive! Ovaj Issue traje nedelju dana tako da igrači Izjasnite se! (Dokazalo se kakav je zlaja zapravo i svako ko je trčao za njim , nadam se da žali zbog te odluke :) )

Inace bivsi admin zlaja je mene optuzio za abjuz a on je koristio world edit!

**Comment by ratkomraleu** [comment]
i nije kaznjen za to

**Comment by Coplek** [comment]
Ovako, ja osobno nemam nista protiv srbende, al nit ga volim, njegovo ponasanje itd mi se ne svidja i to je moje misljenje, ali sto se tice lika, ako je dobio ban za abuse, a stvari su spaljene ili nitko od vas znaci od 30-50 igraca nitko do sad nije poslao ni 1 dokaz zasto bi ga trebalo ban, a niti valjani argument, nema jednostavan razlog zasto da ga drzimo na banu, ako psuje, mozemo ga mute, a i nije glup da se ne popravi, realno smatram da je ratko naucio sto je trebao.
Da, ja sam za unban

**Comment by Coplek** [comment]
Dalje, ako je srbenda banovan onda mora biti izlaja kolko je dobrog napravio, sam px je izjavio da je abusao, nesvjesno, ali je napravio abuse, sve u svemu ne moze se jednom igracu oprastati, dok se drugom ne oprasta

**Comment by PiweeX** [comment]
Rešeno
