### ISSUE TITLE
O Zlaji (komentar klasičnog igrača HogRealmsa)

### ISSUE THREAD

**Issue by dzelat** [PiweeX/HogRealms#92]
Na HogRealms sam došao relativno nedavno, 18. Decembra 2021. godine. Nakon samo dva dana igre sam shvatio ko je Zlaja, a sve je pocelo porukama igrača i pitanjem da li je Zlaja popio lekove. Nisam tražio objašnjenje igrača jer se odgovor na pitanja sam nametnuo. Zlaja pošten fin a ko bi rekao da je zaporavo veći abjuzer nego srbenda. Prije svega kako izgleda živjeti u Mongoliji, ulaskom u Mongoliju dobijate sve privilegije, dobijate sve najbolje i imate sve što poželite. Nakon što više ne trebate Zlaji ili mu jednostavno zasmetate jer niste istomišljenici on vas protjera o tamo i krene da vas pljuje kako god može. Pa evo Lizard, Lizard je Mongoliju vodio i dok je on bio tamo Zlaja nije radio sve što je htio ali to je njemu smetalo i kao izgovor zašto je Lizard izbačen bilo je neplaćanje poreza kojeg uopće nije bilo i nepoštovanje rp-a. 

**Build Mod**
Hvali se gradovima koje je gradio u kreativu a pritom je taj build mod i abjuzao jer je mislio da uz njega dobija i WorldEdit. Naravno kad je viđen i prijavljen njegov izgovor je bio "nisam znao". 

Kako je uopšte dobio OP-a tako što je došao kod piwexa u dm i rekao mu kako ne zna da vodi server kao što to sada govori javno svima. Sada taj Zlaja odvlači igrače na neki server koji će propasti kroz koji mjesec zašto zato što je sada tao admin. NE osporavam ono što je on uradio za server ali znamo šta je  uradio protiv istog. Ovime je dokazao da je govno dok px samo šutio i opraštao, danas dolazi ovdje sa alt nalozima i piše #ZlajaNatragZaAdmina a znamo da u stvarnosti 90% servera nema lijepo mišljenje o njemu. 
Sada on hoće da igrači SMPa koji ni ne znaju šta mi na Realmsu radimo budu vlasnici Realmsa. To je samo jedna od njegovih suludih ideja. 

Za ovo što je jučer uradio dobija se ban na discordu ali naravno... 

https://www.youtube.com/watch?v=j_SP3S2Ovow

**Comment by JedemJaja** [comment]
Moj rođendan je 18. Decembra 🥰

**Comment by ratkomraleu** [comment]
Px i da mu sve dokažeš protiv zlaje, on jednostavno neće njega banovati zato što je takav . A onu decu od 12 godina sto nisu nikakva konkurencija hogu banuje doživotno sa servera sa razlogom da su kopija hoga (ne kažem da su gringosi konkurencija jer kao server veoma im je los community )

**Comment by DzingisKan** [comment]
Lizard je gradia u Mongoliji i napravia je 3 stvari, a roleplay nije poštova. I izbačen je jer nije roleplaya. I to nije bit istomišljenik nego je to bit dio roleplaya ili ga ometat ko šta je on. Ima više razloga zašto je on izbačen iz Mongolije ne samo porez i roleplay.

Buildmodom građeni su gradovi, buildmod sam dobio od piweeexa tako da ne vidim šta je tu abjuz jer je bia i na marketu. World edit ima sam na jedan dan i to sam sagradia zidove Novgoroda i to je jedino napravljeno s tim build modom. Moga sam vadit koji god item sam tia i pogodi šta, nisam. Tako da ne zovi me abjuzerom jer sve te privilegije koje sam ima koristia sam da poboljšam server na šta bi osoba koja je napisala komentar iznad ovog mog to iskoristila da lepo napuni chestove i proda stvari.

Ja sam OPa dobia jer sam na SMPu krv da dok ti nisi bia na serveru uopce. PiweeeX je tia zajednicu youtubera na serveru koji je bia kao sada Realms. Tamo smo black i ja banali sve, našli seed za sezonu, otvorili Hogo kanal, doveli 10 youtubera i došlo je do te mjere da ama baš niko nije treba imat ni mute ni ban komande jer tamo toksicnosti nema. 

Ja altove nemam to sam vec davno reka, ako cu nesto rec rec cu ti u facu, i koliko vidim onaj #ZlajaNatragZaAdmina pisali su Aki, Zav i Knedla koji su vec prije bili na GitHubu tkd to je dovoljan dokaz. Zato odi brani ratka i njih i pokazi sta radis

**Comment by dzelat** [comment]
> Lizard je gradia u Mongoliji i napravia je 3 stvari, a roleplay nije poštova. I izbačen je jer nije roleplaya. I to nije bit istomišljenik nego je to bit dio roleplaya ili ga ometat ko šta je on. Ima više razloga zašto je on izbačen iz Mongolije ne samo porez i roleplay.
> 
> Buildmodom građeni su gradovi, buildmod sam dobio od piweeexa tako da ne vidim šta je tu abjuz jer je bia i na marketu. World edit ima sam na jedan dan i to sam sagradia zidove Novgoroda i to je jedino napravljeno s tim build modom. Moga sam vadit koji god item sam tia i pogodi šta, nisam. Tako da ne zovi me abjuzerom jer sve te privilegije koje sam ima koristia sam da poboljšam server na šta bi osoba koja je napisala komentar iznad ovog mog to iskoristila da lepo napuni chestove i proda stvari.
> 
> Ja sam OPa dobia jer sam na SMPu krv da dok ti nisi bia na serveru uopce. PiweeeX je tia zajednicu youtubera na serveru koji je bia kao sada Realms. Tamo smo black i ja banali sve, našli seed za sezonu, otvorili Hogo kanal, doveli 10 youtubera i došlo je do te mjere da ama baš niko nije treba imat ni mute ni ban komande jer tamo toksicnosti nema. 
> 
> Ja altove nemam to sam vec davno reka, ako cu nesto rec rec cu ti u facu, i koliko vidim onaj #ZlajaNatragZaAdmina pisali su Aki, Zav i Knedla koji su vec prije bili na GitHubu tkd to je dovoljan dokaz. Zato odi brani ratka i njih i pokazi sta radis


》
Nasmijah se fino ti ne pravis razliku izmedju SMPa i vecih zajednica kao sto je Realms

**Comment by ratkomraleu** [comment]
> Lizard je gradia u Mongoliji i napravia je 3 stvari, a roleplay nije poštova. I izbačen je jer nije roleplaya. I to nije bit istomišljenik nego je to bit dio roleplaya ili ga ometat ko šta je on. Ima više razloga zašto je on izbačen iz Mongolije ne samo porez i roleplay.
> 
> Buildmodom građeni su gradovi, buildmod sam dobio od piweeexa tako da ne vidim šta je tu abjuz jer je bia i na marketu. World edit ima sam na jedan dan i to sam sagradia zidove Novgoroda i to je jedino napravljeno s tim build modom. Moga sam vadit koji god item sam tia i pogodi šta, nisam. Tako da ne zovi me abjuzerom jer sve te privilegije koje sam ima koristia sam da poboljšam server na šta bi osoba koja je napisala komentar iznad ovog mog to iskoristila da lepo napuni chestove i proda stvari.
> 
> Ja sam OPa dobia jer sam na SMPu krv da dok ti nisi bia na serveru uopce. PiweeeX je tia zajednicu youtubera na serveru koji je bia kao sada Realms. Tamo smo black i ja banali sve, našli seed za sezonu, otvorili Hogo kanal, doveli 10 youtubera i došlo je do te mjere da ama baš niko nije treba imat ni mute ni ban komande jer tamo toksicnosti nema.
> 
> Ja altove nemam to sam vec davno reka, ako cu nesto rec rec cu ti u facu, i koliko vidim onaj #ZlajaNatragZaAdmina pisali su Aki, Zav i Knedla koji su vec prije bili na GitHubu tkd to je dovoljan dokaz. Zato odi brani ratka i njih i pokazi sta radis

ti si dokazao svoje sa onom objavom na hogo kanalu

**Comment by dzelat** [comment]
dokazao da je govno, dobio poziciju pa sad reklamira a reklamira ko federalna

**Comment by DzingisKan** [comment]
> dokazao da je govno, dobio poziciju pa sad reklamira a reklamira ko federalna

ja govno? ajde reci mi šta si napravia za server?

**Comment by dzelat** [comment]
> > dokazao da je govno, dobio poziciju pa sad reklamira a reklamira ko federalna
> 
> ja govno? ajde reci mi šta si napravia za server?

nisam ništa, al si ti jos uvijek govno

**Comment by dzelat** [comment]
Ne moram nista napravit za srv da bih rekao da si govno

**Comment by DzingisKan** [comment]
> > > dokazao da je govno, dobio poziciju pa sad reklamira a reklamira ko federalna
> > 
> > 
> > ja govno? ajde reci mi šta si napravia za server?
> 
> nisam ništa, al si ti jos uvijek govno

jesan li govno jer tražin piweeexa da privilegije da ljudima koji su gradili SMP prije decentralanda?

**Comment by ratkomraleu** [comment]
> > > > dokazao da je govno, dobio poziciju pa sad reklamira a reklamira ko federalna
> > > 
> > > 
> > > ja govno? ajde reci mi šta si napravia za server?
> > 
> > 
> > nisam ništa, al si ti jos uvijek govno
> 
> jesan li govno jer tražin piweeexa da privilegije da ljudima koji su gradili SMP prije decentralanda?

jesi

**Comment by ratkomraleu** [comment]
kratko i jasno

**Comment by dzelat** [comment]
> > > > dokazao da je govno, dobio poziciju pa sad reklamira a reklamira ko federalna
> > > 
> > > 
> > > ja govno? ajde reci mi šta si napravia za server?
> > 
> > 
> > nisam ništa, al si ti jos uvijek govno
> 
> jesan li govno jer tražin piweeexa da privilegije da ljudima koji su gradili SMP prije decentralanda?

jesi, govno si za ovo sto si juce uradio

**Comment by dzelat** [comment]
samo si to dokazao

**Comment by DzingisKan** [comment]
> > > > > dokazao da je govno, dobio poziciju pa sad reklamira a reklamira ko federalna
> > > > 
> > > > 
> > > > ja govno? ajde reci mi šta si napravia za server?
> > > 
> > > 
> > > nisam ništa, al si ti jos uvijek govno
> > 
> > 
> > jesan li govno jer tražin piweeexa da privilegije da ljudima koji su gradili SMP prije decentralanda?
> 
> jesi

onda je problem u tebi. Jer nisam ja bia taj koji je reka sinoc na SMPu amo preuzet realms. ja sam mislia da mi zele oduzet poziciju na SMPu al na kraju su trazili da dignemo server na novi nivo, i onda su ljudi kao MrKnedla i PsihoKing ispostavili ideju da SMP preuzme Realms i ja sam reka da i ja zelim podrzat. I tako su svi ostali iz SMPa, Helena, Bognar, Strale.... Svi su rekli da su za. Ono sinoc nisam ja, ono sinoc je cijeli SMP

**Comment by dzelat** [comment]
> > > > > > dokazao da je govno, dobio poziciju pa sad reklamira a reklamira ko federalna
> > > > > 
> > > > > 
> > > > > ja govno? ajde reci mi šta si napravia za server?
> > > > 
> > > > 
> > > > nisam ništa, al si ti jos uvijek govno
> > > 
> > > 
> > > jesan li govno jer tražin piweeexa da privilegije da ljudima koji su gradili SMP prije decentralanda?
> > 
> > 
> > jesi
> 
> onda je problem u tebi. Jer nisam ja bia taj koji je reka sinoc na SMPu amo preuzet realms. ja sam mislia da mi zele oduzet poziciju na SMPu al na kraju su trazili da dignemo server na novi nivo, i onda su ljudi kao MrKnedla i PsihoKing ispostavili ideju da SMP preuzme Realms i ja sam reka da i ja zelim podrzat. I tako su svi ostali iz SMPa, Helena, Bognar, Strale.... Svi su rekli da su za. Ono sinoc nisam ja, ono sinoc je cijeli SMP

Da i niko sa SMP ne zna ni sta mi na Realmsu radimo, ajde ti znas jer igras ali sta zna Bognar o Realmsu nek mi nabroji dvije drzave

**Comment by ratkomraleu** [comment]
uštogljeni youtuberi sa 50 subscribera misle da će im biti dopušteno uraditi tako nešto na realmsu, grdno se varate onda

**Comment by DzingisKan** [comment]
> > > > > > > dokazao da je govno, dobio poziciju pa sad reklamira a reklamira ko federalna
> > > > > > 
> > > > > > 
> > > > > > ja govno? ajde reci mi šta si napravia za server?
> > > > > 
> > > > > 
> > > > > nisam ništa, al si ti jos uvijek govno
> > > > 
> > > > 
> > > > jesan li govno jer tražin piweeexa da privilegije da ljudima koji su gradili SMP prije decentralanda?
> > > 
> > > 
> > > jesi
> > 
> > 
> > onda je problem u tebi. Jer nisam ja bia taj koji je reka sinoc na SMPu amo preuzet realms. ja sam mislia da mi zele oduzet poziciju na SMPu al na kraju su trazili da dignemo server na novi nivo, i onda su ljudi kao MrKnedla i PsihoKing ispostavili ideju da SMP preuzme Realms i ja sam reka da i ja zelim podrzat. I tako su svi ostali iz SMPa, Helena, Bognar, Strale.... Svi su rekli da su za. Ono sinoc nisam ja, ono sinoc je cijeli SMP
> 
> Da i niko sa SMP ne zna ni sta mi na Realmsu radimo, ajde ti znas jer igras ali sta zna Bognar o Realmsu nek mi nabroji dvije drzave

Knedla vodi pacifik, Sarac vodi sovjete, Bognar je u Mongoliji odavno, ja vodim Mongoliju, Psiho je na SMPu aktivan al ima i pristup Realmsu. To su sve ljudi koji su stvorili ovaj server. A ne piweeex, piweeex je sam niko i nista bez tih ljudi koje vi ne vidite

**Comment by dzelat** [comment]
![image](https://user-images.githubusercontent.com/107082292/175814032-c30be228-b8fb-492d-9867-a6f0a60d5163.png)

**Comment by DzingisKan** [comment]
> > uštogljeni youtuberi sa 50 subscribera misle da će im biti dopušteno uraditi tako nešto na realmsu, grdno se varate onda
> 
> od svih ljudi koji su sinoc bili samo Knedla i ja smo youtuberi, svi ostali su igraci iz prve sezone Hoga.

prva sezona znaci dok je Hog bia factions dok je pola vas koji sad pisete na githubu imali fazon 7-8 godina

**Comment by dzelat** [comment]
> > > > > > > > dokazao da je govno, dobio poziciju pa sad reklamira a reklamira ko federalna
> > > > > > > 
> > > > > > > 
> > > > > > > ja govno? ajde reci mi šta si napravia za server?
> > > > > > 
> > > > > > 
> > > > > > nisam ništa, al si ti jos uvijek govno
> > > > > 
> > > > > 
> > > > > jesan li govno jer tražin piweeexa da privilegije da ljudima koji su gradili SMP prije decentralanda?
> > > > 
> > > > 
> > > > jesi
> > > 
> > > 
> > > onda je problem u tebi. Jer nisam ja bia taj koji je reka sinoc na SMPu amo preuzet realms. ja sam mislia da mi zele oduzet poziciju na SMPu al na kraju su trazili da dignemo server na novi nivo, i onda su ljudi kao MrKnedla i PsihoKing ispostavili ideju da SMP preuzme Realms i ja sam reka da i ja zelim podrzat. I tako su svi ostali iz SMPa, Helena, Bognar, Strale.... Svi su rekli da su za. Ono sinoc nisam ja, ono sinoc je cijeli SMP
> > 
> > 
> > Da i niko sa SMP ne zna ni sta mi na Realmsu radimo, ajde ti znas jer igras ali sta zna Bognar o Realmsu nek mi nabroji dvije drzave
> 
> Knedla vodi pacifik, Sarac vodi sovjete, Bognar je u Mongoliji odavno, ja vodim Mongoliju, Psiho je na SMPu aktivan al ima i pristup Realmsu. To su sve ljudi koji su stvorili ovaj server. A ne piweeex, piweeex je sam niko i nista bez tih ljudi koje vi ne vidite

Sarac igrao davno dosao opet igrao 20 dana i otisao, Knedla jedini igra ti si otisao a ako vec radis za ovaj server dobrovoljno ne vidim razlog da postavljas uvjete

**Comment by dzelat** [comment]
Zasto igraci odlaze, evo odgovor odlazim i ja, ako si nesto uradio za server nisi bog ni otac ni duh sveti i ja da sam PX nikad sebi en bih dozvolio da mi neko postavlja uslove na vlastitom serveru...ne svijda ti se idi

**Comment by DzingisKan** [comment]
> > > > > > > > > dokazao da je govno, dobio poziciju pa sad reklamira a reklamira ko federalna
> > > > > > > > 
> > > > > > > > 
> > > > > > > > ja govno? ajde reci mi šta si napravia za server?
> > > > > > > 
> > > > > > > 
> > > > > > > nisam ništa, al si ti jos uvijek govno
> > > > > > 
> > > > > > 
> > > > > > jesan li govno jer tražin piweeexa da privilegije da ljudima koji su gradili SMP prije decentralanda?
> > > > > 
> > > > > 
> > > > > jesi
> > > > 
> > > > 
> > > > onda je problem u tebi. Jer nisam ja bia taj koji je reka sinoc na SMPu amo preuzet realms. ja sam mislia da mi zele oduzet poziciju na SMPu al na kraju su trazili da dignemo server na novi nivo, i onda su ljudi kao MrKnedla i PsihoKing ispostavili ideju da SMP preuzme Realms i ja sam reka da i ja zelim podrzat. I tako su svi ostali iz SMPa, Helena, Bognar, Strale.... Svi su rekli da su za. Ono sinoc nisam ja, ono sinoc je cijeli SMP
> > > 
> > > 
> > > Da i niko sa SMP ne zna ni sta mi na Realmsu radimo, ajde ti znas jer igras ali sta zna Bognar o Realmsu nek mi nabroji dvije drzave
> > 
> > 
> > Knedla vodi pacifik, Sarac vodi sovjete, Bognar je u Mongoliji odavno, ja vodim Mongoliju, Psiho je na SMPu aktivan al ima i pristup Realmsu. To su sve ljudi koji su stvorili ovaj server. A ne piweeex, piweeex je sam niko i nista bez tih ljudi koje vi ne vidite
> 
> Sarac igrao davno dosao opet igrao 20 dana i otisao, Knedla jedini igra ti si otisao a ako vec radis za ovaj server dobrovoljno ne vidim razlog da postavljas uvjete

znaci i Sarac i Knedla i ja smo igrali dovoljno dugo da vidimo server.  Ja radim za ovaj server bez da sam iti kune dobio. Ali vise ono sta radim ne vredi jer se to jednostanvo ne ispunjava. 
Ja idem protiv toksicnosti a vi mi se protivite.

**Comment by dzelat** [comment]
> > > > > > > > > > dokazao da je govno, dobio poziciju pa sad reklamira a reklamira ko federalna
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > ja govno? ajde reci mi šta si napravia za server?
> > > > > > > > 
> > > > > > > > 
> > > > > > > > nisam ništa, al si ti jos uvijek govno
> > > > > > > 
> > > > > > > 
> > > > > > > jesan li govno jer tražin piweeexa da privilegije da ljudima koji su gradili SMP prije decentralanda?
> > > > > > 
> > > > > > 
> > > > > > jesi
> > > > > 
> > > > > 
> > > > > onda je problem u tebi. Jer nisam ja bia taj koji je reka sinoc na SMPu amo preuzet realms. ja sam mislia da mi zele oduzet poziciju na SMPu al na kraju su trazili da dignemo server na novi nivo, i onda su ljudi kao MrKnedla i PsihoKing ispostavili ideju da SMP preuzme Realms i ja sam reka da i ja zelim podrzat. I tako su svi ostali iz SMPa, Helena, Bognar, Strale.... Svi su rekli da su za. Ono sinoc nisam ja, ono sinoc je cijeli SMP
> > > > 
> > > > 
> > > > Da i niko sa SMP ne zna ni sta mi na Realmsu radimo, ajde ti znas jer igras ali sta zna Bognar o Realmsu nek mi nabroji dvije drzave
> > > 
> > > 
> > > Knedla vodi pacifik, Sarac vodi sovjete, Bognar je u Mongoliji odavno, ja vodim Mongoliju, Psiho je na SMPu aktivan al ima i pristup Realmsu. To su sve ljudi koji su stvorili ovaj server. A ne piweeex, piweeex je sam niko i nista bez tih ljudi koje vi ne vidite
> > 
> > 
> > Sarac igrao davno dosao opet igrao 20 dana i otisao, Knedla jedini igra ti si otisao a ako vec radis za ovaj server dobrovoljno ne vidim razlog da postavljas uvjete
> 
> znaci i Sarac i Knedla i ja smo igrali dovoljno dugo da vidimo server. Ja radim za ovaj server bez da sam iti kune dobio. Ali vise ono sta radim ne vredi jer se to jednostanvo ne ispunjava. Ja idem protiv toksicnosti a vi mi se protivite.

izvinite presveti ne bude se ponovilo vise

**Comment by konfix** [comment]
👀
