### ISSUE TITLE
DAO Sistem na Hogu!

### ISSUE THREAD

**Issue by PiweeX** [PiweeX/HogRealms#94]
Pošto se nekoliko ljudi koji nisu učestvovali u dvosatnoj diskusiji u Konfixovom issueu na https://github.com/PiweeX/HogRealms/issues/93 javilo i počelo da se žali da im se ne sviđa to što sad SMP igrači odlučuju o celom Hogu potrudiću se da iznesem šta je tačno izglasano i zašto

Diskusija je trajala par sati, od jutra se dogovaramo na SMPu

Ukratko, pokušavali smo da dođemo do rešenja za sve što nas muči danima, stvar je u tome da kad je Github otvoren, tu je dostupna totalna sloboda da svako može otvoriti Issue i doneti neku odluku o serveru na osnovu samo glasova igrača,

Najveći problem tu je što u tom slučaju toksični igrači mogu da plaćaju i teraju osobe da glasaju za njih, nevezano za to koje je njihovo mišljenje

Kad imate server od 2000 ljudi i od tih 2000 jedna osoba može da napravi grupicu drugara od 40 njih da glasaju za ili protiv nečega nevezano šta misli o toj temi već samo na osnovu toga šta ima protiv osobe koja je sa suprotne strane onda je to jako loše jer postoji pritisak da nešto loše bude uvedeno samo na osnovu toga da je neko platio glasove

Na ugled najvećih blockchain projekata, doneta je odluka da server umesto VIP ranka prijatelji Hoga ima DAO rank, blockchain projekti funkcionišu na princip da grupa holdera sa najviše tokena ima DAO opciju, na osnovu toga oni imaju pravo na zajedničke diskusije i odluke oko servera, ispred njih je developer

Dakle ovako bi server funkcionisao

Igrač - da predlog na gitu - DAO - razmatraju - developer - učini ukoliko je moguće

SMP stranka će biti prva zato što na SMPu igraju najozbiljnije osobe i to već 5 godina zaredom, posle nje kako bi se balansiralo biće još stranaka kako bi DAO sistem bio još bolji, ovo znači da će developeri raditi po tome kakve je DAO predloge doneo preko igrača, ovo će skroz smanjiti korupciju u smislu da igrači neće moći da teraju ikoga da glasa za nešto, glasovi će se naravno važiti ali samo kao jedan deo, ni 1 predlog neće biti usvojen dok se ne obavi diskusija o njemu i dok developeri ne vide da li je moguće, kao što je bio slučaj ovih dana, neko napravi issue da se neko banuje, isti taj lik smara igrače da glasaju i na osnovu toga to 100% mora biti doneto nevezano da li je dobro i loše, e tu je bio problem.

DAO će privremeno raditi kao grupa od manjeg broja igrača do 20 njih na SMPu, videćemo kako to bude funkcionisalo pa se u 1 momentu bude povećavalo jer što da ne

**Comment by Cetnik1918** [comment]
95% se slazem, ali ipak je logicno ono sto je konfix rekao da je github sranje i da svako moze dobiti sta hoce i da admini trebaju sami da procene

**Comment by Cetnik1918** [comment]
I ja cu biti DAO od sutra tkd moze

**Comment by dzelat** [comment]
odosmo u kurac dragi moji drage moje

**Comment by NemanjaRusija** [comment]
> odosmo u kurac dragi moji drage moje

Slažem se

**Comment by Ratko7** [comment]
I tako je autokratija uvedena na server.

**Comment by konfix** [comment]
> I tako je autokratija uvedena na server.

server ne moze da funkcionise bez toga

**Comment by Skleper5** [comment]
> > I tako je autokratija uvedena na server.
> 
> server ne moze da funkcionise bez toga

Moze koliko god nisam voleo zlaju ali on može da vrati hog da funkcioniše i ako je jedan od njegovih zahteva da me banuju neka ptihvaticu jer bez njega server je propao ljudi rade šta hoće

**Comment by akipaki293** [comment]
I tako Aki ode na odmor na Novi Zeland bez interneta i struje da odmori moždane ćelije

nevezano za ovo gore, dželati ako sam dobro skontao neće imati nikakvu svrhu, DAO ce uglavnom biti ljudi koji podržavaju i slušaju Zlaju kao sto je Helena itd. Ako dodajete a vidim da ste dodali dodajte par ozbiljnih ljudi sa servera kao DAO koji neće slušati svaku Zlajinu reč, kao sto su Čoplek, Đovani i Galileo, i kao što je Galileo rekao negde da je UN njegova ideja a da je Zlaja jer je bio PXev miljenik dobio vrhovnog sudiju, dok je gala dobio ništa a on je dao ideju za UN...

**Comment by dzelat** [comment]
> > > I tako je autokratija uvedena na server.
> > 
> > 
> > server ne moze da funkcionise bez toga
> 
> Moze koliko god nisam voleo zlaju ali on može da vrati hog da funkcioniše i ako je jedan od njegovih zahteva da me banuju neka ptihvaticu jer bez njega server je propao ljudi rade šta hoće

zaves ce on da ne kazem sto

**Comment by Coplek** [comment]
Totalno se slazem sa tim DAO, moze bit kao advokat u sudu, ali ne kao sudija, dalje zlaja ne moze donositi zakon ne moze, dzelat sad vise ni nema svrhe zapravo ima mi smo marionete trenutno, i moramo raditi po odlukama onoga tko nas vodi, da ako bude tako ja cu i dalje radit po svom nahodjenju
![Screenshot_61](https://user-images.githubusercontent.com/83037533/175824034-595d4343-8af6-4154-bd05-09a913a73dbc.png)
Tu sam sve objasnio

Zlaja je osvojio Laputu cestitam

**Comment by Coplek** [comment]
I prakticki kolko sam shvatio dzelati vise ne postoje..?
![Screenshot_62](https://user-images.githubusercontent.com/83037533/175824264-4cce655c-0ab9-466f-abdc-ea2b07e58bd6.png)

**Comment by akipaki293** [comment]
Tačno tako
sve je tačno

**Comment by akipaki293** [comment]
> I prakticki kolko sam shvatio dzelati vise ne postoje..? ![Screenshot_62](https://user-images.githubusercontent.com/83037533/175824264-4cce655c-0ab9-466f-abdc-ea2b07e58bd6.png)

Ja da sam na vasem mestu gledao bih da ostanem da ranku dzelatu a ako se ne resi to da dzelati nemaju svrhu i da neko kontrolise nad njima ja bih otiso jer ako sam dzelat px mi moze naredjivati a ne neka stranka, btw ja sam na hogu od 2018 pokusavao se prijaviti i stojao na discordu i pratio na ytu...

**Comment by PiweeX** [comment]
ne znam jeste glupi ili da

DAO ne utice na dzelate, utice u malom broju slucajeva samo ako neko napravi issue protiv nekog za poseban ban

**Comment by PiweeX** [comment]
> I tako je autokratija uvedena na server.

ne nije uvedena autokratija već više nećeš moći da sa svojom ekipom izglasavaš loše stvari za server koje su samo tebi u korist, već će 50 igrača koji su godinama na serveru i koji samo žele dobro serveru da diskutuju o predlozima koje igrači daju

nigde nema veće slobode nego na hogu

**Comment by PiweeX** [comment]
zatvoriću ovaj issue i mogu reći samo da mi je drago što smo uveli ovaj sistem
