### ISSUE TITLE
Psiho glavni baja.

### ISSUE THREAD

**Issue by PsihoKing** [PiweeX/HogRealms#95]
E vako cisto da opomenem da sledecih 7 dana sam ja glavni na serveru.
Sto bi znacilo da ce bit rigorozne mere da cu davat banove na sve sta ucinite protiv pravila server.
I banovi se nece moci skinuti posto ne zelim da neki mentol udje posle 10 dana i napravi opet isti problem na serveru.
Hvala na razumevanju.
 PS: Px pusi pisu he he he.

**Comment by dzelat** [comment]
Prisegnite!

**Comment by frop1k** [comment]
Prisegnite!

**Comment by VukIcrnogorskii** [comment]
> E vako cisto da opomenem da sledecih 7 dana sam ja glavni na serveru. Sto bi znacilo da ce bit rigorozne mere da cu davat banove na sve sta ucinite protiv pravila server. I banovi se nece moci skinuti posto ne zelim da neki mentol udje posle 10 dana i napravi opet isti problem na serveru. Hvala na razumevanju. PS: Px pusi pisu he he he.

Opaaaaaaaaaaaaa, da ne vracamo staru gardu???

**Comment by muvstp** [comment]
Bruh
