### ISSUE TITLE
DAO Sistem

### ISSUE THREAD

**Issue by buducidzelat** [PiweeX/HogRealms#96]
ja kao stari igrac hogrealmsa i propali trovo strimer i jutjuber mislim da je sistem koji ste izmislili veliko sranje i ne vidim razlog zasto da mene igraci hogsmpa koriste kao lutku ako se neko normalan kao je ne moze pridruziti zbog idiota od vlasnika cije ime ne zelim da spomenem.I jos se zalim na to sto ste mi obrisali vip kanal jebem li vam semenku u picku

**Comment by NemanjaRusija** [comment]
> ja kao stari igrac hogrealmsa i propali trovo strimer i jutjuber mislim da je sistem koji ste izmislili veliko sranje i ne vidim razlog zasto da mene igraci hogsmpa koriste kao lutku ako se neko normalan kao je ne moze pridruziti zbog idiota od vlasnika cije ime ne zelim da spomenem.I jos se zalim na to sto ste mi obrisali vip kanal jebem li vam semenku u picku

Meni je važno da se vip kanal vrati

**Comment by buducidzelat** [comment]
> NemanjaRusija

slazemse

**Comment by Lenna672** [comment]
Vip kanal postoji samo ga vi ne vidite

**Comment by DzingisKan** [comment]
> Vip kanal postoji samo ga vi ne vidite

Znaju da je u Svrhu DAO kanala. Oni oce zaseban kanal za sebe. 


Stavit ce se predlog da vam se otvori kanal

**Comment by NemanjaRusija** [comment]
> Vip kanal postoji samo ga vi ne vidite

Gospođo ja imam media role i znam da je vip soba ustvari sad DAO soba

**Comment by NemanjaRusija** [comment]
> > Vip kanal postoji samo ga vi ne vidite
> 
> Znaju da je u Svrhu DAO kanala. Oni oce zaseban kanal za sebe.
> 
> Stavit ce se predlog da vam se otvori kanal

mi hocemo da se soba vip vrati a ne da se pravi opet

**Comment by Lenna672** [comment]
> > > Vip kanal postoji samo ga vi ne vidite
> > 
> > Gospođo ja imam media role i znam da je vip soba ustvari sad DAO soba
> 
> ![Screenshot_20220628_114333.jpg](https://user-images.githubusercontent.com/107657688/176148209-0b33e961-24cd-4dd1-b761-7012e71effe0.jpg)

evo vam gospodine 🌼

**Comment by NemanjaRusija** [comment]
> > > Vip kanal postoji samo ga vi ne vidite
> > 
> > 
> > Gospođo ja imam media role i znam da je vip soba ustvari sad DAO soba
> 
> ![Screenshot_20220628_114333.jpg](https://user-images.githubusercontent.com/107657688/176148209-0b33e961-24cd-4dd1-b761-7012e71effe0.jpg)

to je sad za DAO

**Comment by Lenna672** [comment]
> > > > Vip kanal postoji samo ga vi ne vidite
> > > 
> > > 
> > > Gospođo ja imam media role i znam da je vip soba ustvari sad DAO soba
> > 
> > ![Screenshot_20220628_114333.jpg](https://user-images.githubusercontent.com/107657688/176148209-0b33e961-24cd-4dd1-b761-7012e71effe0.jpg)
> 
> to je sad za DAO
> 

znam gospodine

**Comment by NemanjaRusija** [comment]
> > Al ga mi ne vidimo jer je sad za DAO
> 
> hehe pa to je drugi problem



> > > > > Vip kanal postoji samo ga vi ne vidite
> > > > 
> > > > 
> > > > Gospođo ja imam media role i znam da je vip soba ustvari sad DAO soba
> > > 
> > > 
> > > ![Screenshot_20220628_114333.jpg](https://user-images.githubusercontent.com/107657688/176148209-0b33e961-24cd-4dd1-b761-7012e71effe0.jpg)
> > 
> > 
> > to je sad za DAO
> 
> znam gospodine

Pa ne razumijem šta se miješaš ako znaš

**Comment by akipaki293** [comment]
> > > > Al ga mi ne vidimo jer je sad za DAO
> > > 
> > > 
> > > hehe pa to je drugi problem
> > 
> > 
> > > > > > > Vip kanal postoji samo ga vi ne vidite
> > > > > > 
> > > > > > 
> > > > > > Gospođo ja imam media role i znam da je vip soba ustvari sad DAO soba
> > > > > 
> > > > > 
> > > > > ![Screenshot_20220628_114333.jpg](https://user-images.githubusercontent.com/107657688/176148209-0b33e961-24cd-4dd1-b761-7012e71effe0.jpg)
> > > > 
> > > > 
> > > > to je sad za DAO
> > > 
> > > 
> > > znam gospodine
> > 
> > 
> > Pa ne razumijem šta se miješaš ako znaš
> 
> pa jer postoji, al glasali smo da vam se mozda vrati

Zeno sto bi nam uopste bio oduzet kad jednostavno za dao napravite novi kanal koj ce mi rank donator ako nemam vip chat mrs u pm

**Comment by Lenna672** [comment]
> > > > > Al ga mi ne vidimo jer je sad za DAO
> > > > 
> > > > 
> > > > hehe pa to je drugi problem
> > > 
> > > 
> > > > > > > > Vip kanal postoji samo ga vi ne vidite
> > > > > > > 
> > > > > > > 
> > > > > > > Gospođo ja imam media role i znam da je vip soba ustvari sad DAO soba
> > > > > > 
> > > > > > 
> > > > > > ![Screenshot_20220628_114333.jpg](https://user-images.githubusercontent.com/107657688/176148209-0b33e961-24cd-4dd1-b761-7012e71effe0.jpg)
> > > > > 
> > > > > 
> > > > > to je sad za DAO
> > > > 
> > > > 
> > > > znam gospodine
> > > 
> > > 
> > > Pa ne razumijem šta se miješaš ako znaš
> > 
> > pa jer postoji, al glasali smo da vam se mozda vrati
> 
> Zeno sto bi nam uopste bio oduzet kad jednostavno za dao napravite novi kanal koj ce mi rank donator ako nemam vip chat mrs u pm 

budite fino ako ga uopce zelite nazad

**Comment by NemanjaRusija** [comment]
> > > > > > Al ga mi ne vidimo jer je sad za DAO
> > > > > 
> > > > > 
> > > > > hehe pa to je drugi problem
> > > > 
> > > > 
> > > > > > > > > Vip kanal postoji samo ga vi ne vidite
> > > > > > > > 
> > > > > > > > 
> > > > > > > > Gospođo ja imam media role i znam da je vip soba ustvari sad DAO soba
> > > > > > > 
> > > > > > > 
> > > > > > > ![Screenshot_20220628_114333.jpg](https://user-images.githubusercontent.com/107657688/176148209-0b33e961-24cd-4dd1-b761-7012e71effe0.jpg)
> > > > > > 
> > > > > > 
> > > > > > to je sad za DAO
> > > > > 
> > > > > 
> > > > > znam gospodine
> > > > 
> > > > 
> > > > Pa ne razumijem šta se miješaš ako znaš
> > > 
> > > 
> > > pa jer postoji, al glasali smo da vam se mozda vrati
> > 
> > 
> > Zeno sto bi nam uopste bio oduzet kad jednostavno za dao napravite novi kanal koj ce mi rank donator ako nemam vip chat mrs u pm
> 
> budite fino ako ga uopce zelite nazad

Vau sad si DAO pa misliš da si neko

**Comment by Lenna672** [comment]
> > > > > > > Al ga mi ne vidimo jer je sad za DAO
> > > > > > 
> > > > > > 
> > > > > > hehe pa to je drugi problem
> > > > > 
> > > > > 
> > > > > > > > > > Vip kanal postoji samo ga vi ne vidite
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > Gospođo ja imam media role i znam da je vip soba ustvari sad DAO soba
> > > > > > > > 
> > > > > > > > 
> > > > > > > > ![Screenshot_20220628_114333.jpg](https://user-images.githubusercontent.com/107657688/176148209-0b33e961-24cd-4dd1-b761-7012e71effe0.jpg)
> > > > > > > 
> > > > > > > 
> > > > > > > to je sad za DAO
> > > > > > 
> > > > > > 
> > > > > > znam gospodine
> > > > > 
> > > > > 
> > > > > Pa ne razumijem šta se miješaš ako znaš
> > > > 
> > > > 
> > > > pa jer postoji, al glasali smo da vam se mozda vrati
> > > 
> > > 
> > > Zeno sto bi nam uopste bio oduzet kad jednostavno za dao napravite novi kanal koj ce mi rank donator ako nemam vip chat mrs u pm
> > 
> > budite fino ako ga uopce zelite nazad
> 
> Vau sad si DAO pa misliš da si neko

Ne jer vam ne prijetim vec dajem savjet jer vam svaki glas vrijedi iskreno

**Comment by KriptoEtnoRomAleksa** [comment]
Ja mislim da Zlaju za kaznu treba nabiti na kolac.

**Comment by konfix** [comment]
da sam ja vlasnik sve bih vas banovao 👍

**Comment by ratkomraleu** [comment]
Ja sam vas upozorio, a ovo je samo početak :)

**Comment by ratkomraleu** [comment]
i ja bi dao, ne bi bio nečija marioneta svakako :)

**Comment by DzingisKan** [comment]
> i ja bi dao, ne bi bio nečija marioneta svakako :)

Kako se planiras zaposlit u real life ako neces radis posao po proceduri koju ti zada šef

**Comment by Coplek** [comment]
> > i ja bi dao, ne bi bio nečija marioneta svakako :)
> 
> Kako se planiras zaposlit u real life ako neces radis posao po proceduri koju ti zada šef

ti mi neces biti sef sigurno

**Comment by VukIcrnogorskii** [comment]
> > i ja bi dao, ne bi bio nečija marioneta svakako :)
> 
> Kako se planiras zaposlit u real life ako neces radis posao po proceduri koju ti zada šef

Najbitnije je biti svoj covjek i postovat sebe za pocetak. Ukoliko njegov moral kvari taj "sef" nece tu radit nego ce nac drugu posao
