### ISSUE TITLE
Novi dzelat(ja)

### ISSUE THREAD

**Issue by Siu804** [PiweeX/HogRealms#97]
Mislim da bi bilo vreme da dodje novi dzelat nakon sto su otisli Coplek i Galileo...Sada su potrebni zato sto ne moze da pokrije sve jedan dzelat...Mislim da bi bio odlican za ovu ulogu sa obzirom koliko ulazem u server i pomazem igracima...O ovome sam vec razgovarao sa px i galileom(kada je bio dzelat)...Pokusavam da budem Jos bolji uzimam savete od ostalih dzelata i uspevam u tome...Zelim da prinesem serveru nekako a ovo bi bilo stvarno odlican nacin za to...Nadam se da Cu postati jer vec od početka igre kad sam poceo da igram se trudim za dzelata

**Comment by bogoljub1234** [comment]
Ne, brinite se px ce odabrati kad ce mu zatrebati

**Comment by Siu804** [comment]
> 

Ne brini,vec sam pitao px-a odgovorio je da napisem ovde pa da ce zajednica odluciti

**Comment by bogoljub1234** [comment]
Ne trebate se sada svađat

**Comment by DzingisKan** [comment]
koji je vas nick u discordu i igri?

**Comment by bogoljub1234** [comment]
Vec me znas

**Comment by DzingisKan** [comment]
> Vec me znas

mislim na Siu koji je otvorio GitHub

**Comment by Siu804** [comment]
> игри

Moje discord ime je Red🔱 a nick u MC mi je ThePredrag

**Comment by Siu804** [comment]
DzingisKan rekao sam sad ime ne znam dal si video

**Comment by bogoljub1234** [comment]
Koliko vas glasa uopce?

**Comment by aaaaaaaaaaaaaadddddddddddddddaaaaaaaa** [comment]
Ja bih voleo da budem dzelat zato sto sam dugo na hogu pomazem igracim i sklapam prijateljstva i dobre odnose,o ovome sam vec pricao sa px-om i mislim da sam odlican kandidat za to zato sto se mnogo trudim i zato sto volim da pomazem
nadam se da nisam zakasnio
-miki_triske2010

**Comment by bogoljub1234** [comment]
Aj se smirite px bira

**Comment by bogoljub1234** [comment]
Znaci oko 1

**Comment by bogoljub1234** [comment]
10

**Comment by Lenna672** [comment]
> Znaci oko 1

Ima nas vise od 10

**Comment by bogoljub1234** [comment]
Ako bog da mozda budem ja

Al kao i inace pomoc cu serveru koliko mogu
Briga me za pare itd

**Comment by DzingisKan** [comment]
bogoljub daj nick u disc i nick u igri

**Comment by DzingisKan** [comment]
4 glasa su dovoljna da se izglasa, oko 10ak ljudi glasa

**Comment by akipaki293** [comment]
> 4 glasa su dovoljna da se izglasa, oko 10ak ljudi glasa

Da se i ja prijavim. Za dzelata 🤣🤣🤣

**Comment by NemanjaRusija** [comment]
> bogoljub daj nick u disc i nick u igri

Zlajo znaš mene i znam da si me blokirao mogu li  ija da učestvujem da se i ja glasam za dželata

**Comment by Lenna672** [comment]
> > bogoljub daj nick u disc i nick u igri
> 
> Zlajo znaš mene i znam da si me blokirao mogu li i ja da učestvujem da se i ja glasam za dželata 

posalji dc i mc ime
