### ISSUE TITLE
Rankovi

### ISSUE THREAD

**Issue by PiweeX** [PiweeX/HogRealms#99]
Ovih dana desetine ljudi je kupilo rankove sa shopa kao i druge stvari,

imam neku potrebu da dodamo još stvari za te rankove ali da ujedno ne bude previše stvari koje bi obične igrače činilo bezvrednijima već neke fun opcije poput /hat

Imate li ideje šta bi moglo da se doda potencijalno?

**Comment by R1derPN** [comment]
Mobove poput peta drugim recima Kapibare.

**Comment by R1derPN** [comment]
Ili vec Piweex oces dodat dodaj Casove .

**Comment by buducidzelat** [comment]
> Ovih dana desetine ljudi je kupilo rankove sa shopa kao i druge stvari,
> 
> imam neku potrebu da dodamo još stvari za te rankove ali da ujedno ne bude previše stvari koje bi obične igrače činilo bezvrednijima već neke fun opcije poput /hat
> 
> Imate li ideje šta bi moglo da se doda potencijalno?

sedlo za jahanje kornjaci

**Comment by DzingisKan** [comment]
> > Ovih dana desetine ljudi je kupilo rankove sa shopa kao i druge stvari,
> > imam neku potrebu da dodamo još stvari za te rankove ali da ujedno ne bude previše stvari koje bi obične igrače činilo bezvrednijima već neke fun opcije poput /hat
> > Imate li ideje šta bi moglo da se doda potencijalno?
> 
> sedlo za jahanje kornjaci

nismo Jack Sparrow da jašemo kornjače

**Comment by buducidzelat** [comment]
> > > Ovih dana desetine ljudi je kupilo rankove sa shopa kao i druge stvari,
> > > imam neku potrebu da dodamo još stvari za te rankove ali da ujedno ne bude previše stvari koje bi obične igrače činilo bezvrednijima već neke fun opcije poput /hat
> > > Imate li ideje šta bi moglo da se doda potencijalno?
> > 
> > 
> > sedlo za jahanje kornjaci
> 
> nismo Jack Sparrow da jašemo kornjače

A ZASTO DA NE?

**Comment by KriptoEtnoRomAleksa** [comment]
Evo ovako,px ja ti preporucujem da dodas neki rank ispod hero ranka da ljudi koji hocu nesot da kupe ali da necu da potrose pare nprm.Onda dodaj jači rank od kinga nprm god rank gde se dobijaju dodatno vozilo ili nesto drugo umesto busilice i jos drugih stvari.Kao taj nprm rank moze da ima neki custom item ili neku premium komandu isto i da se dobiju dodatno neke gluposti jos.Ako ces dodati te male rankove onda stavi cene 2,50 evra od imena nprm (hogo rank,itd) za taj veci rank koji bi kostao nprm 25-30 evra nazovi (god,imperator,itd) uz taj rank dodas dodatno vozilo custom oruzije neko dodas komande neke pare nprm 60k ili htokeni a za bonus dodas nprm custom item po izboru ili neku trecu glupost.

**Comment by Cetnik1918** [comment]
Bonus para  od npr rank kosta 20.00 e onda dobijes 20k ing
